.TH "__iar_u32" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__iar_u32
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cmsis_iccarm\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBv\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint32_t v"


.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
