.TH "source/AccountManager.h" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/AccountManager.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBUsers\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDATA_BASE_MAX\fP   100"
.br
.ti -1c
.RI "#define \fBID_SIZE\fP   8"
.br
.ti -1c
.RI "#define \fBPIN_SIZE_MAX\fP   6"
.br
.ti -1c
.RI "#define \fBMASTER_ID\fP   12345678"
.br
.ti -1c
.RI "#define \fBMASTER_PIN\fP   12345"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBUsers\fP \fBUser\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit_data_base\fP ()"
.br
.ti -1c
.RI "bool \fBid_check\fP (uint32_t ID_buffered)"
.br
.ti -1c
.RI "\fBUser\fP \fBuser_search\fP (uint32_t ID_to_search)"
.br
.ti -1c
.RI "bool \fBadd_to_data_base\fP (\fBUser\fP admin_user, uint32_t ID_u, uint32_t PIN_u, bool admin_u)"
.br
.ti -1c
.RI "bool \fBdelete_from_data_base\fP (\fBUser\fP admin_user, uint32_t ID_u)"
.br
.ti -1c
.RI "bool \fBedit_PIN\fP (uint32_t user_to_change, uint32_t PIN_u)"
.br
.ti -1c
.RI "void \fBunblock_user\fP (\fBUser\fP u)"
.br
.ti -1c
.RI "bool \fBis_blocked\fP (\fBUser\fP u)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DATA_BASE_MAX   100"

.SS "#define ID_SIZE   8"

.SS "#define MASTER_ID   12345678"

.SS "#define MASTER_PIN   12345"

.SS "#define PIN_SIZE_MAX   6"

.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBUsers\fP  \fBUser\fP"

.SH "Function Documentation"
.PP 
.SS "bool add_to_data_base (\fBUser\fP admin_user, uint32_t ID_u, uint32_t PIN_u, bool admin_u)"

.SS "bool delete_from_data_base (\fBUser\fP admin_user, uint32_t ID_u)"

.SS "bool edit_PIN (uint32_t user_to_change, uint32_t PIN_u)"

.SS "bool id_check (uint32_t ID_buffered)"

.SS "void init_data_base ()"

.SS "bool is_blocked (\fBUser\fP u)"

.SS "void unblock_user (\fBUser\fP u)"

.SS "\fBUser\fP user_search (uint32_t ID_to_search)"

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
