.TH "ADC_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_Type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MK64F12\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSC1\fP [2]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCFG1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCFG2\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBR\fP [2]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCV1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCV2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSC2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSC3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOFS\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPG\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMG\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCLPD\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCLPS\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCLP4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCLP3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCLP2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCLP1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCLP0\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_0\fP [4]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCLMD\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCLMS\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCLM4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCLM3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCLM2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCLM1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCLM0\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
ADC - Register Layout Typedef 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
