.TH "AIPS_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AIPS_Type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MK64F12\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMPRA\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_0\fP [28]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPACRA\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPACRB\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPACRC\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPACRD\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_1\fP [16]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPACRE\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPACRF\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPACRG\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPACRH\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPACRI\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPACRJ\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPACRK\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPACRL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPACRM\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPACRN\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPACRO\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPACRP\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_2\fP [16]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPACRU\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
AIPS - Register Layout Typedef 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
