.TH "source/App.c" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/App.c \- Application functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'DRV_Display\&.h'\fP
.br
\fC#include 'DRV_LEDs\&.h'\fP
.br
\fC#include 'DRV_Encoder\&.h'\fP
.br
\fC#include 'DRV_Board\&.h'\fP
.br
\fC#include 'DRV_Timers\&.h'\fP
.br
\fC#include 'DRV_Reader\&.h'\fP
.br
\fC#include 'NumberEditor\&.h'\fP
.br
\fC#include 'AccountManager\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBID_LENGTH\fP   8"
.br
.ti -1c
.RI "#define \fBPIN_LENGTH\fP   5"
.br
.ti -1c
.RI "#define \fBERROR_TIME_MS\fP   2500"
.br
.ti -1c
.RI "#define \fBWARNING_TIME_MS\fP   2500"
.br
.ti -1c
.RI "#define \fBLATCH_TIME_MS\fP   5000"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBmenuEvent_t\fP { \fBEVENT_ENC_LEFT\fP = ENC_LEFT, \fBEVENT_ENC_RIGHT\fP = ENC_RIGHT, \fBEVENT_ENC_CLICK\fP = ENC_CLICK, \fBEVENT_NONE\fP = ENC_NONE, \fBEVENT_CARD\fP }"
.br
.ti -1c
.RI "enum \fBmenuState_t\fP { \fBSTATE_MAIN\fP, \fBSTATE_ID\fP, \fBSTATE_PIN\fP, \fBSTATE_EDIT\fP, \fBSTATE_ADMIN\fP, \fBSTATE_BRIGHTNESS\fP, \fBSTATE_SPEED\fP }"
.br
.ti -1c
.RI "enum \fBmenuItem_t\fP { \fBITEM_ID\fP, \fBITEM_EDIT\fP, \fBITEM_BRIGHTNESS\fP, \fBITEM_SPEED\fP, \fBNUM_ITEMS\fP }"
.br
.ti -1c
.RI "enum { \fBLED_LATCH\fP, \fBLED_ERROR\fP, \fBLED_WARNING\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBApp_Init\fP (void)"
.br
.ti -1c
.RI "void \fBApp_Run\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Application functions\&. 


.PP
\fBAuthor:\fP
.RS 4
Nicolás Magliola 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define ERROR_TIME_MS   2500"

.SS "#define ID_LENGTH   8"

.SS "#define LATCH_TIME_MS   5000"

.SS "#define PIN_LENGTH   5"

.SS "#define WARNING_TIME_MS   2500"

.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILED_LATCH \fP\fP
.TP
\fB\fILED_ERROR \fP\fP
.TP
\fB\fILED_WARNING \fP\fP
.SS "enum \fBmenuEvent_t\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIEVENT_ENC_LEFT \fP\fP
.TP
\fB\fIEVENT_ENC_RIGHT \fP\fP
.TP
\fB\fIEVENT_ENC_CLICK \fP\fP
.TP
\fB\fIEVENT_NONE \fP\fP
.TP
\fB\fIEVENT_CARD \fP\fP
.SS "enum \fBmenuItem_t\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIITEM_ID \fP\fP
.TP
\fB\fIITEM_EDIT \fP\fP
.TP
\fB\fIITEM_BRIGHTNESS \fP\fP
.TP
\fB\fIITEM_SPEED \fP\fP
.TP
\fB\fINUM_ITEMS \fP\fP
.SS "enum \fBmenuState_t\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISTATE_MAIN \fP\fP
.TP
\fB\fISTATE_ID \fP\fP
.TP
\fB\fISTATE_PIN \fP\fP
.TP
\fB\fISTATE_EDIT \fP\fP
.TP
\fB\fISTATE_ADMIN \fP\fP
.TP
\fB\fISTATE_BRIGHTNESS \fP\fP
.TP
\fB\fISTATE_SPEED \fP\fP
.SH "Function Documentation"
.PP 
.SS "void App_Init (void)"

.SS "void App_Run (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
