.TH "APSR_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
APSR_Type \- Union type to access the Application Program Status Register (APSR)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <core_armv8mbl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:28"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fBw\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:16"
.br
.ti -1c
.RI "   uint32_t \fBGE\fP:4"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:7"
.br
.ti -1c
.RI "   uint32_t \fBQ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:16"
.br
.ti -1c
.RI "   uint32_t \fBGE\fP:4"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:7"
.br
.ti -1c
.RI "   uint32_t \fBQ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Union type to access the Application Program Status Register (APSR)\&. 
.SH "Field Documentation"
.PP 
.SS "uint32_t _reserved0"
bit: 0\&.\&.27 Reserved
.PP
bit: 0\&.\&.15 Reserved 
.SS "uint32_t _reserved1"
bit: 20\&.\&.26 Reserved 
.SS "struct { \&.\&.\&. }   b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }   b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }   b"
Structure used for bit access 
.SS "uint32_t C"
bit: 29 Carry condition code flag 
.SS "uint32_t GE"
bit: 16\&.\&.19 Greater than or Equal flags 
.SS "uint32_t N"
bit: 31 Negative condition code flag 
.SS "uint32_t Q"
bit: 27 Saturation condition flag 
.SS "uint32_t V"
bit: 28 Overflow condition code flag 
.SS "uint32_t w"
Type used for word access 
.SS "uint32_t Z"
bit: 30 Zero condition code flag 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
