.TH "arm_dct4_instance_q31" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arm_dct4_instance_q31 \- Instance structure for the Q31 DCT4/IDCT4 function\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arm_math\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBN\fP"
.br
.ti -1c
.RI "uint16_t \fBNby2\fP"
.br
.ti -1c
.RI "\fBq31_t\fP \fBnormalize\fP"
.br
.ti -1c
.RI "\fBq31_t\fP * \fBpTwiddle\fP"
.br
.ti -1c
.RI "\fBq31_t\fP * \fBpCosFactor\fP"
.br
.ti -1c
.RI "\fBarm_rfft_instance_q31\fP * \fBpRfft\fP"
.br
.ti -1c
.RI "\fBarm_cfft_radix4_instance_q31\fP * \fBpCfft\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Instance structure for the Q31 DCT4/IDCT4 function\&. 
.SH "Field Documentation"
.PP 
.SS "uint16_t N"
length of the DCT4\&. 
.SS "uint16_t Nby2"
half of the length of the DCT4\&. 
.SS "\fBq31_t\fP normalize"
normalizing factor\&. 
.SS "\fBarm_cfft_radix4_instance_q31\fP* pCfft"
points to the complex FFT instance\&. 
.SS "\fBq31_t\fP* pCosFactor"
points to the cosFactor table\&. 
.SS "\fBarm_rfft_instance_q31\fP* pRfft"
points to the real FFT instance\&. 
.SS "\fBq31_t\fP* pTwiddle"
points to the twiddle factor table\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
