.TH "arm_cfft_radix2_instance_f32" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arm_cfft_radix2_instance_f32 \- Instance structure for the floating-point CFFT/CIFFT function\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arm_math\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBfftLen\fP"
.br
.ti -1c
.RI "uint8_t \fBifftFlag\fP"
.br
.ti -1c
.RI "uint8_t \fBbitReverseFlag\fP"
.br
.ti -1c
.RI "\fBfloat32_t\fP * \fBpTwiddle\fP"
.br
.ti -1c
.RI "uint16_t * \fBpBitRevTable\fP"
.br
.ti -1c
.RI "uint16_t \fBtwidCoefModifier\fP"
.br
.ti -1c
.RI "uint16_t \fBbitRevFactor\fP"
.br
.ti -1c
.RI "\fBfloat32_t\fP \fBonebyfftLen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Instance structure for the floating-point CFFT/CIFFT function\&. 
.SH "Field Documentation"
.PP 
.SS "uint8_t bitReverseFlag"
flag that enables (bitReverseFlag=1) or disables (bitReverseFlag=0) bit reversal of output\&. 
.SS "uint16_t bitRevFactor"
bit reversal modifier that supports different size FFTs with the same bit reversal table\&. 
.SS "uint16_t fftLen"
length of the FFT\&. 
.SS "uint8_t ifftFlag"
flag that selects forward (ifftFlag=0) or inverse (ifftFlag=1) transform\&. 
.SS "\fBfloat32_t\fP onebyfftLen"
value of 1/fftLen\&. 
.SS "uint16_t* pBitRevTable"
points to the bit reversal table\&. 
.SS "\fBfloat32_t\fP* pTwiddle"
points to the Twiddle factor table\&. 
.SS "uint16_t twidCoefModifier"
twiddle coefficient modifier that supports different size FFTs with the same twiddle factor table\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
