.TH "arm_fir_sparse_instance_q31" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arm_fir_sparse_instance_q31 \- Instance structure for the Q31 sparse FIR filter\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arm_math\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBnumTaps\fP"
.br
.ti -1c
.RI "uint16_t \fBstateIndex\fP"
.br
.ti -1c
.RI "\fBq31_t\fP * \fBpState\fP"
.br
.ti -1c
.RI "\fBq31_t\fP * \fBpCoeffs\fP"
.br
.ti -1c
.RI "uint16_t \fBmaxDelay\fP"
.br
.ti -1c
.RI "int32_t * \fBpTapDelay\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Instance structure for the Q31 sparse FIR filter\&. 
.SH "Field Documentation"
.PP 
.SS "uint16_t maxDelay"
maximum offset specified by the pTapDelay array\&. 
.SS "uint16_t numTaps"
number of coefficients in the filter\&. 
.SS "\fBq31_t\fP* pCoeffs"
points to the coefficient array\&. The array is of length numTaps\&. 
.SS "\fBq31_t\fP* pState"
points to the state buffer array\&. The array is of length maxDelay+blockSize-1\&. 
.SS "int32_t* pTapDelay"
points to the array of delay values\&. The array is of length numTaps\&. 
.SS "uint16_t stateIndex"
state buffer index\&. Points to the oldest sample in the state buffer\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
