.TH "arm_iir_lattice_instance_q15" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arm_iir_lattice_instance_q15 \- Instance structure for the Q15 IIR lattice filter\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arm_math\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBnumStages\fP"
.br
.ti -1c
.RI "\fBq15_t\fP * \fBpState\fP"
.br
.ti -1c
.RI "\fBq15_t\fP * \fBpkCoeffs\fP"
.br
.ti -1c
.RI "\fBq15_t\fP * \fBpvCoeffs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Instance structure for the Q15 IIR lattice filter\&. 
.SH "Field Documentation"
.PP 
.SS "uint16_t numStages"
number of stages in the filter\&. 
.SS "\fBq15_t\fP* pkCoeffs"
points to the reflection coefficient array\&. The array is of length numStages\&. 
.SS "\fBq15_t\fP* pState"
points to the state variable array\&. The array is of length numStages+blockSize\&. 
.SS "\fBq15_t\fP* pvCoeffs"
points to the ladder coefficient array\&. The array is of length numStages+1\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
