.TH "ARM_MPU_Region_t" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARM_MPU_Region_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mpu_armv7\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBRBAR\fP"
.br
.RI "The region base address register value (RBAR) "
.ti -1c
.RI "uint32_t \fBRASR\fP"
.br
.RI "The region attribute and size register value (RASR) \fBMPU_RASR\fP\&. "
.ti -1c
.RI "uint32_t \fBRLAR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct for a single MPU Region 
.SH "Field Documentation"
.PP 
.SS "uint32_t RASR"

.PP
The region attribute and size register value (RASR) \fBMPU_RASR\fP\&. 
.SS "uint32_t RBAR"

.PP
The region base address register value (RBAR) Region Base Address Register value 
.SS "uint32_t RLAR"
Region Limit Address Register value 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
