.TH "arm_rfft_instance_f32" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arm_rfft_instance_f32 \- Instance structure for the floating-point RFFT/RIFFT function\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arm_math\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBfftLenReal\fP"
.br
.ti -1c
.RI "uint16_t \fBfftLenBy2\fP"
.br
.ti -1c
.RI "uint8_t \fBifftFlagR\fP"
.br
.ti -1c
.RI "uint8_t \fBbitReverseFlagR\fP"
.br
.ti -1c
.RI "uint32_t \fBtwidCoefRModifier\fP"
.br
.ti -1c
.RI "\fBfloat32_t\fP * \fBpTwiddleAReal\fP"
.br
.ti -1c
.RI "\fBfloat32_t\fP * \fBpTwiddleBReal\fP"
.br
.ti -1c
.RI "\fBarm_cfft_radix4_instance_f32\fP * \fBpCfft\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Instance structure for the floating-point RFFT/RIFFT function\&. 
.SH "Field Documentation"
.PP 
.SS "uint8_t bitReverseFlagR"
flag that enables (bitReverseFlagR=1) or disables (bitReverseFlagR=0) bit reversal of output\&. 
.SS "uint16_t fftLenBy2"
length of the complex FFT\&. 
.SS "uint32_t fftLenReal"
length of the real FFT\&. 
.SS "uint8_t ifftFlagR"
flag that selects forward (ifftFlagR=0) or inverse (ifftFlagR=1) transform\&. 
.SS "\fBarm_cfft_radix4_instance_f32\fP* pCfft"
points to the complex FFT instance\&. 
.SS "\fBfloat32_t\fP* pTwiddleAReal"
points to the real twiddle factor table\&. 
.SS "\fBfloat32_t\fP* pTwiddleBReal"
points to the imag twiddle factor table\&. 
.SS "uint32_t twidCoefRModifier"
twiddle coefficient modifier that supports different size FFTs with the same twiddle factor table\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
