.TH "arm_cfft_instance_q31" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arm_cfft_instance_q31 \- Instance structure for the fixed-point CFFT/CIFFT function\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arm_math\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBfftLen\fP"
.br
.ti -1c
.RI "const \fBq31_t\fP * \fBpTwiddle\fP"
.br
.ti -1c
.RI "const uint16_t * \fBpBitRevTable\fP"
.br
.ti -1c
.RI "uint16_t \fBbitRevLength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Instance structure for the fixed-point CFFT/CIFFT function\&. 
.SH "Field Documentation"
.PP 
.SS "uint16_t bitRevLength"
bit reversal table length\&. 
.SS "uint16_t fftLen"
length of the FFT\&. 
.SS "const uint16_t* pBitRevTable"
points to the bit reversal table\&. 
.SS "const \fBq31_t\fP* pTwiddle"
points to the Twiddle factor table\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
