.TH "arm_fir_interpolate_instance_q31" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arm_fir_interpolate_instance_q31 \- Instance structure for the Q31 FIR interpolator\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arm_math\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBL\fP"
.br
.ti -1c
.RI "uint16_t \fBphaseLength\fP"
.br
.ti -1c
.RI "\fBq31_t\fP * \fBpCoeffs\fP"
.br
.ti -1c
.RI "\fBq31_t\fP * \fBpState\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Instance structure for the Q31 FIR interpolator\&. 
.SH "Field Documentation"
.PP 
.SS "uint8_t L"
upsample factor\&. 
.SS "\fBq31_t\fP* pCoeffs"
points to the coefficient array\&. The array is of length L*phaseLength\&. 
.SS "uint16_t phaseLength"
length of each polyphase filter component\&. 
.SS "\fBq31_t\fP* pState"
points to the state variable array\&. The array is of length blockSize+phaseLength-1\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
