.TH "BilinearInterpolate" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BilinearInterpolate
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "CMSIS_INLINE \fB__STATIC_INLINE\fP \fBfloat32_t\fP \fBarm_bilinear_interp_f32\fP (const \fBarm_bilinear_interp_instance_f32\fP *S, \fBfloat32_t\fP X, \fBfloat32_t\fP Y)"
.br
.RI "Floating-point bilinear interpolation\&. "
.ti -1c
.RI "CMSIS_INLINE \fB__STATIC_INLINE\fP \fBq31_t\fP \fBarm_bilinear_interp_q31\fP (\fBarm_bilinear_interp_instance_q31\fP *S, \fBq31_t\fP X, \fBq31_t\fP Y)"
.br
.RI "Q31 bilinear interpolation\&. "
.ti -1c
.RI "CMSIS_INLINE \fB__STATIC_INLINE\fP \fBq15_t\fP \fBarm_bilinear_interp_q15\fP (\fBarm_bilinear_interp_instance_q15\fP *S, \fBq31_t\fP X, \fBq31_t\fP Y)"
.br
.RI "Q15 bilinear interpolation\&. "
.ti -1c
.RI "CMSIS_INLINE \fB__STATIC_INLINE\fP \fBq7_t\fP \fBarm_bilinear_interp_q7\fP (\fBarm_bilinear_interp_instance_q7\fP *S, \fBq31_t\fP X, \fBq31_t\fP Y)"
.br
.RI "Q7 bilinear interpolation\&. "
.in -1c
.SH "Detailed Description"
.PP 
Bilinear interpolation is an extension of linear interpolation applied to a two dimensional grid\&. The underlying function \fCf(x, y)\fP is sampled on a regular grid and the interpolation process determines values between the grid points\&. Bilinear interpolation is equivalent to two step linear interpolation, first in the x-dimension and then in the y-dimension\&. Bilinear interpolation is often used in image processing to rescale images\&. The CMSIS DSP library provides bilinear interpolation functions for Q7, Q15, Q31, and floating-point data types\&.
.PP
\fBAlgorithm\fP 
.PP
\fB\fP
.RS 4
The instance structure used by the bilinear interpolation functions describes a two dimensional data table\&. For floating-point, the instance structure is defined as: 
.PP
.nf

  typedef struct
  {
    uint16_t numRows;
    uint16_t numCols;
    float32_t *pData;
} \fBarm_bilinear_interp_instance_f32\fP;
.fi
.PP
.RE
.PP
\fB\fP
.RS 4
where \fCnumRows\fP specifies the number of rows in the table; \fCnumCols\fP specifies the number of columns in the table; and \fCpData\fP points to an array of size \fCnumRows*numCols\fP values\&. The data table \fCpTable\fP is organized in row order and the supplied data values fall on integer indexes\&. That is, table element (x,y) is located at \fCpTable[x + y*numCols]\fP where x and y are integers\&.
.RE
.PP
\fB\fP
.RS 4
Let \fC(x, y)\fP specify the desired interpolation point\&. Then define: 
.PP
.nf

    XF = floor(x)
    YF = floor(y)
.fi
.PP
 
.RE
.PP
\fB\fP
.RS 4
The interpolated output point is computed as: 
.PP
.nf

 f(x, y) = f(XF, YF) * (1-(x-XF)) * (1-(y-YF))
          + f(XF+1, YF) * (x-XF)*(1-(y-YF))
          + f(XF, YF+1) * (1-(x-XF))*(y-YF)
          + f(XF+1, YF+1) * (x-XF)*(y-YF)
.fi
.PP
 Note that the coordinates (x, y) contain integer and fractional components\&. The integer components specify which portion of the table to use while the fractional components control the interpolation processor\&.
.RE
.PP
\fB\fP
.RS 4
if (x,y) are outside of the table boundary, Bilinear interpolation returns zero output\&. 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "CMSIS_INLINE \fB__STATIC_INLINE\fP \fBfloat32_t\fP arm_bilinear_interp_f32 (const \fBarm_bilinear_interp_instance_f32\fP * S, \fBfloat32_t\fP X, \fBfloat32_t\fP Y)"

.PP
Floating-point bilinear interpolation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIS\fP points to an instance of the interpolation structure\&. 
.br
\fIX\fP interpolation coordinate\&. 
.br
\fIY\fP interpolation coordinate\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
out interpolated value\&. 
.RE
.PP

.SS "CMSIS_INLINE \fB__STATIC_INLINE\fP \fBq15_t\fP arm_bilinear_interp_q15 (\fBarm_bilinear_interp_instance_q15\fP * S, \fBq31_t\fP X, \fBq31_t\fP Y)"

.PP
Q15 bilinear interpolation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIS\fP points to an instance of the interpolation structure\&. 
.br
\fIX\fP interpolation coordinate in 12\&.20 format\&. 
.br
\fIY\fP interpolation coordinate in 12\&.20 format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
out interpolated value\&. 
.RE
.PP

.SS "CMSIS_INLINE \fB__STATIC_INLINE\fP \fBq31_t\fP arm_bilinear_interp_q31 (\fBarm_bilinear_interp_instance_q31\fP * S, \fBq31_t\fP X, \fBq31_t\fP Y)"

.PP
Q31 bilinear interpolation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIS\fP points to an instance of the interpolation structure\&. 
.br
\fIX\fP interpolation coordinate in 12\&.20 format\&. 
.br
\fIY\fP interpolation coordinate in 12\&.20 format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
out interpolated value\&. 
.RE
.PP

.SS "CMSIS_INLINE \fB__STATIC_INLINE\fP \fBq7_t\fP arm_bilinear_interp_q7 (\fBarm_bilinear_interp_instance_q7\fP * S, \fBq31_t\fP X, \fBq31_t\fP Y)"

.PP
Q7 bilinear interpolation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIS\fP points to an instance of the interpolation structure\&. 
.br
\fIX\fP interpolation coordinate in 12\&.20 format\&. 
.br
\fIY\fP interpolation coordinate in 12\&.20 format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
out interpolated value\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
