.TH "Bit_Field_Generic_Macros" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bit_Field_Generic_Macros
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNXP_VAL2FLD\fP(field,  value)   (((value) << (field ## _SHIFT)) & (field ## _MASK))"
.br
.RI "Mask and left-shift a bit field value for use in a register bit range\&. "
.ti -1c
.RI "#define \fBNXP_FLD2VAL\fP(field,  value)   (((value) & (field ## _MASK)) >> (field ## _SHIFT))"
.br
.RI "Mask and right-shift a register value to extract a bit field value\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define NXP_FLD2VAL(field, value)   (((value) & (field ## _MASK)) >> (field ## _SHIFT))"

.PP
Mask and right-shift a register value to extract a bit field value\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of the register\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Masked and shifted bit field value\&. 
.RE
.PP

.SS "#define NXP_VAL2FLD(field, value)   (((value) << (field ## _SHIFT)) & (field ## _MASK))"

.PP
Mask and left-shift a bit field value for use in a register bit range\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of the bit field\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Masked and shifted value\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
