.TH "CAN_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CAN_Type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MK64F12\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCTRL1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTIMER\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_0\fP [4]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRXMGMASK\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRX14MASK\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRX15MASK\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBECR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBESR1\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_1\fP [4]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBIMASK1\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_2\fP [4]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBIFLAG1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCTRL2\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBESR2\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_3\fP [8]"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBCRCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRXFGMASK\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBRXFIR\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_4\fP [48]"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBCS\fP"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBID\fP"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBWORD0\fP"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBWORD1\fP"
.br
.ti -1c
.RI "} \fBMB\fP [16]"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_5\fP [1792]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRXIMR\fP [16]"
.br
.in -1c
.SH "Detailed Description"
.PP 
CAN - Register Layout Typedef 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
