.TH "CAU_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CAU_Type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MK64F12\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__O\fP uint32_t \fBDIRECT\fP [16]"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_0\fP [2048]"
.br
.ti -1c
.RI "\fB__O\fP uint32_t \fBLDR_CASR\fP"
.br
.ti -1c
.RI "\fB__O\fP uint32_t \fBLDR_CAA\fP"
.br
.ti -1c
.RI "\fB__O\fP uint32_t \fBLDR_CA\fP [9]"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_1\fP [20]"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBSTR_CASR\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBSTR_CAA\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBSTR_CA\fP [9]"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_2\fP [20]"
.br
.ti -1c
.RI "\fB__O\fP uint32_t \fBADR_CASR\fP"
.br
.ti -1c
.RI "\fB__O\fP uint32_t \fBADR_CAA\fP"
.br
.ti -1c
.RI "\fB__O\fP uint32_t \fBADR_CA\fP [9]"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_3\fP [20]"
.br
.ti -1c
.RI "\fB__O\fP uint32_t \fBRADR_CASR\fP"
.br
.ti -1c
.RI "\fB__O\fP uint32_t \fBRADR_CAA\fP"
.br
.ti -1c
.RI "\fB__O\fP uint32_t \fBRADR_CA\fP [9]"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_4\fP [84]"
.br
.ti -1c
.RI "\fB__O\fP uint32_t \fBXOR_CASR\fP"
.br
.ti -1c
.RI "\fB__O\fP uint32_t \fBXOR_CAA\fP"
.br
.ti -1c
.RI "\fB__O\fP uint32_t \fBXOR_CA\fP [9]"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_5\fP [20]"
.br
.ti -1c
.RI "\fB__O\fP uint32_t \fBROTL_CASR\fP"
.br
.ti -1c
.RI "\fB__O\fP uint32_t \fBROTL_CAA\fP"
.br
.ti -1c
.RI "\fB__O\fP uint32_t \fBROTL_CA\fP [9]"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_6\fP [276]"
.br
.ti -1c
.RI "\fB__O\fP uint32_t \fBAESC_CASR\fP"
.br
.ti -1c
.RI "\fB__O\fP uint32_t \fBAESC_CAA\fP"
.br
.ti -1c
.RI "\fB__O\fP uint32_t \fBAESC_CA\fP [9]"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_7\fP [20]"
.br
.ti -1c
.RI "\fB__O\fP uint32_t \fBAESIC_CASR\fP"
.br
.ti -1c
.RI "\fB__O\fP uint32_t \fBAESIC_CAA\fP"
.br
.ti -1c
.RI "\fB__O\fP uint32_t \fBAESIC_CA\fP [9]"
.br
.in -1c
.SH "Detailed Description"
.PP 
CAU - Register Layout Typedef 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
