.TH "clarke" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
clarke
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "CMSIS_INLINE \fB__STATIC_INLINE\fP void \fBarm_clarke_f32\fP (\fBfloat32_t\fP Ia, \fBfloat32_t\fP Ib, \fBfloat32_t\fP *pIalpha, \fBfloat32_t\fP *pIbeta)"
.br
.RI "Floating-point Clarke transform\&. "
.ti -1c
.RI "CMSIS_INLINE \fB__STATIC_INLINE\fP void \fBarm_clarke_q31\fP (\fBq31_t\fP Ia, \fBq31_t\fP Ib, \fBq31_t\fP *pIalpha, \fBq31_t\fP *pIbeta)"
.br
.RI "Clarke transform for Q31 version\&. "
.in -1c
.SH "Detailed Description"
.PP 
Forward Clarke transform converts the instantaneous stator phases into a two-coordinate time invariant vector\&. Generally the Clarke transform uses three-phase currents \fCIa, Ib and Ic\fP to calculate currents in the two-phase orthogonal stator axis \fCIalpha\fP and \fCIbeta\fP\&. When \fCIalpha\fP is superposed with \fCIa\fP as shown in the figure below Stator current space vector and its components in (a,b)\&. and \fCIa + Ib + Ic = 0\fP, in this condition \fCIalpha\fP and \fCIbeta\fP can be calculated using only \fCIa\fP and \fCIb\fP\&.
.PP
The function operates on a single sample of data and each call to the function returns the processed output\&. The library provides separate functions for Q31 and floating-point data types\&. 
.PP
\fBAlgorithm\fP
.RS 4
 where \fCIa\fP and \fCIb\fP are the instantaneous stator phases and \fCpIalpha\fP and \fCpIbeta\fP are the two coordinates of time invariant vector\&. 
.RE
.PP
\fBFixed-Point Behavior\fP
.RS 4
Care must be taken when using the Q31 version of the Clarke transform\&. In particular, the overflow and saturation behavior of the accumulator used must be considered\&. Refer to the function specific documentation below for usage guidelines\&. 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "CMSIS_INLINE \fB__STATIC_INLINE\fP void arm_clarke_f32 (\fBfloat32_t\fP Ia, \fBfloat32_t\fP Ib, \fBfloat32_t\fP * pIalpha, \fBfloat32_t\fP * pIbeta)"

.PP
Floating-point Clarke transform\&. 
.PP
\fBParameters:\fP
.RS 4
\fIIa\fP input three-phase coordinate \fCa\fP 
.br
\fIIb\fP input three-phase coordinate \fCb\fP 
.br
\fIpIalpha\fP points to output two-phase orthogonal vector axis alpha 
.br
\fIpIbeta\fP points to output two-phase orthogonal vector axis beta 
.RE
.PP

.SS "CMSIS_INLINE \fB__STATIC_INLINE\fP void arm_clarke_q31 (\fBq31_t\fP Ia, \fBq31_t\fP Ib, \fBq31_t\fP * pIalpha, \fBq31_t\fP * pIbeta)"

.PP
Clarke transform for Q31 version\&. 
.PP
\fBParameters:\fP
.RS 4
\fIIa\fP input three-phase coordinate \fCa\fP 
.br
\fIIb\fP input three-phase coordinate \fCb\fP 
.br
\fIpIalpha\fP points to output two-phase orthogonal vector axis alpha 
.br
\fIpIbeta\fP points to output two-phase orthogonal vector axis beta
.RE
.PP
\fBScaling and Overflow Behavior:\fP 
.PP
\fB\fP
.RS 4
The function is implemented using an internal 32-bit accumulator\&. The accumulator maintains 1\&.31 format by truncating lower 31 bits of the intermediate multiplication in 2\&.62 format\&. There is saturation on the addition, hence there is no risk of overflow\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
