.TH "CMP_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMP_Type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MK64F12\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint8_t \fBCR0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBCR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBFPR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBSCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBDACCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBMUXCR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
CMP - Register Layout Typedef 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
