.TH "CMSIS_SCnSCB" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_SCnSCB \- Type definitions for the System Control and ID Register not in the SCB\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBSCnSCB_Type\fP"
.br
.RI "Structure type to access the System Control and ID Register not in the SCB\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Msk\fP   (0xFUL /*<< SCnSCB_ICTR_INTLINESNUM_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Msk\fP   (0xFUL /*<< SCnSCB_ICTR_INTLINESNUM_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISOOFP_Pos\fP   9U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISOOFP_Msk\fP   (1UL << SCnSCB_ACTLR_DISOOFP_Pos)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISFPCA_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISFPCA_Msk\fP   (1UL << SCnSCB_ACTLR_DISFPCA_Pos)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISFOLD_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISFOLD_Msk\fP   (1UL << SCnSCB_ACTLR_DISFOLD_Pos)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISDEFWBUF_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISDEFWBUF_Msk\fP   (1UL << SCnSCB_ACTLR_DISDEFWBUF_Pos)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISMCYCINT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISMCYCINT_Msk\fP   (1UL /*<< SCnSCB_ACTLR_DISMCYCINT_Pos*/)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Type definitions for the System Control and ID Register not in the SCB\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define SCnSCB_ACTLR_DISDEFWBUF_Msk   (1UL << SCnSCB_ACTLR_DISDEFWBUF_Pos)"
ACTLR: DISDEFWBUF Mask 
.SS "#define SCnSCB_ACTLR_DISDEFWBUF_Pos   1U"
ACTLR: DISDEFWBUF Position 
.SS "#define SCnSCB_ACTLR_DISFOLD_Msk   (1UL << SCnSCB_ACTLR_DISFOLD_Pos)"
ACTLR: DISFOLD Mask 
.SS "#define SCnSCB_ACTLR_DISFOLD_Pos   2U"
ACTLR: DISFOLD Position 
.SS "#define SCnSCB_ACTLR_DISFPCA_Msk   (1UL << SCnSCB_ACTLR_DISFPCA_Pos)"
ACTLR: DISFPCA Mask 
.SS "#define SCnSCB_ACTLR_DISFPCA_Pos   8U"
ACTLR: DISFPCA Position 
.SS "#define SCnSCB_ACTLR_DISMCYCINT_Msk   (1UL /*<< SCnSCB_ACTLR_DISMCYCINT_Pos*/)"
ACTLR: DISMCYCINT Mask 
.SS "#define SCnSCB_ACTLR_DISMCYCINT_Pos   0U"
ACTLR: DISMCYCINT Position 
.SS "#define SCnSCB_ACTLR_DISOOFP_Msk   (1UL << SCnSCB_ACTLR_DISOOFP_Pos)"
ACTLR: DISOOFP Mask 
.SS "#define SCnSCB_ACTLR_DISOOFP_Pos   9U"
ACTLR: DISOOFP Position 
.SS "#define SCnSCB_ICTR_INTLINESNUM_Msk   (0xFUL /*<< SCnSCB_ICTR_INTLINESNUM_Pos*/)"
ICTR: INTLINESNUM Mask 
.SS "#define SCnSCB_ICTR_INTLINESNUM_Msk   (0xFUL /*<< SCnSCB_ICTR_INTLINESNUM_Pos*/)"
ICTR: INTLINESNUM Mask 
.SS "#define SCnSCB_ICTR_INTLINESNUM_Pos   0U"
ICTR: INTLINESNUM Position 
.SS "#define SCnSCB_ICTR_INTLINESNUM_Pos   0U"
ICTR: INTLINESNUM Position 
.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
