.TH "CMSIS_Core_SAUFunctions" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_Core_SAUFunctions \- Functions that configure the SAU\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Functions that configure the SAU\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
