.TH "CMSIS_NVIC" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_NVIC \- Type definitions for the NVIC Registers\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBNVIC_Type\fP"
.br
.RI "Structure type to access the Nested Vectored Interrupt Controller (NVIC)\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNVIC_STIR_INTID_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBNVIC_STIR_INTID_Msk\fP   (0x1FFUL /*<< NVIC_STIR_INTID_Pos*/)"
.br
.ti -1c
.RI "#define \fBNVIC_STIR_INTID_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBNVIC_STIR_INTID_Msk\fP   (0x1FFUL /*<< NVIC_STIR_INTID_Pos*/)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Type definitions for the NVIC Registers\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define NVIC_STIR_INTID_Msk   (0x1FFUL /*<< NVIC_STIR_INTID_Pos*/)"
STIR: INTLINESNUM Mask 
.SS "#define NVIC_STIR_INTID_Msk   (0x1FFUL /*<< NVIC_STIR_INTID_Pos*/)"
STIR: INTLINESNUM Mask 
.SS "#define NVIC_STIR_INTID_Pos   0U"
STIR: INTLINESNUM Position 
.SS "#define NVIC_STIR_INTID_Pos   0U"
STIR: INTLINESNUM Position 
.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
