.TH "SDK/CMSIS/cmsis_compiler.h" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDK/CMSIS/cmsis_compiler.h \- CMSIS compiler generic header file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SH "Detailed Description"
.PP 
CMSIS compiler generic header file\&. 


.PP
\fBVersion:\fP
.RS 4
V5\&.0\&.4 
.RE
.PP
\fBDate:\fP
.RS 4
10\&. January 2018 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
