.TH "CMSIS_Core_FunctionInterface" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_Core_FunctionInterface
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBCMSIS Core Register Access Functions\fP"
.br
.ti -1c
.RI "\fBNVIC Functions\fP"
.br
.RI "Functions that manage interrupts and exceptions via the NVIC\&. "
.ti -1c
.RI "\fBFPU Functions\fP"
.br
.RI "Function that provides FPU type\&. "
.ti -1c
.RI "\fBSAU Functions\fP"
.br
.RI "Functions that configure the SAU\&. "
.ti -1c
.RI "\fBSysTick Functions\fP"
.br
.RI "Functions that configure the System\&. "
.ti -1c
.RI "\fBITM Functions\fP"
.br
.RI "Functions that access the ITM debug interface\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
