.TH "CMSIS_core_bitfield" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_core_bitfield \- Macros for use with bit field definitions (xxx_Pos, xxx_Msk)\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_VAL2FLD\fP(field,  value)   (((uint32_t)(value) << field ## _Pos) & field ## _Msk)"
.br
.RI "Mask and shift a bit field value for use in a register bit range\&. "
.ti -1c
.RI "#define \fB_FLD2VAL\fP(field,  value)   (((uint32_t)(value) & field ## _Msk) >> field ## _Pos)"
.br
.RI "Mask and shift a register value to extract a bit filed value\&. "
.ti -1c
.RI "#define \fB_VAL2FLD\fP(field,  value)   (((uint32_t)(value) << field ## _Pos) & field ## _Msk)"
.br
.RI "Mask and shift a bit field value for use in a register bit range\&. "
.ti -1c
.RI "#define \fB_FLD2VAL\fP(field,  value)   (((uint32_t)(value) & field ## _Msk) >> field ## _Pos)"
.br
.RI "Mask and shift a register value to extract a bit filed value\&. "
.ti -1c
.RI "#define \fB_VAL2FLD\fP(field,  value)   (((uint32_t)(value) << field ## _Pos) & field ## _Msk)"
.br
.RI "Mask and shift a bit field value for use in a register bit range\&. "
.ti -1c
.RI "#define \fB_FLD2VAL\fP(field,  value)   (((uint32_t)(value) & field ## _Msk) >> field ## _Pos)"
.br
.RI "Mask and shift a register value to extract a bit filed value\&. "
.in -1c
.SH "Detailed Description"
.PP 
Macros for use with bit field definitions (xxx_Pos, xxx_Msk)\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define _FLD2VAL(field, value)   (((uint32_t)(value) & field ## _Msk) >> field ## _Pos)"

.PP
Mask and shift a register value to extract a bit filed value\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of register\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Masked and shifted bit field value\&. 
.RE
.PP

.SS "#define _FLD2VAL(field, value)   (((uint32_t)(value) & field ## _Msk) >> field ## _Pos)"

.PP
Mask and shift a register value to extract a bit filed value\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of register\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Masked and shifted bit field value\&. 
.RE
.PP

.SS "#define _FLD2VAL(field, value)   (((uint32_t)(value) & field ## _Msk) >> field ## _Pos)"

.PP
Mask and shift a register value to extract a bit filed value\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of register\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Masked and shifted bit field value\&. 
.RE
.PP

.SS "#define _VAL2FLD(field, value)   (((uint32_t)(value) << field ## _Pos) & field ## _Msk)"

.PP
Mask and shift a bit field value for use in a register bit range\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of the bit field\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Masked and shifted value\&. 
.RE
.PP

.SS "#define _VAL2FLD(field, value)   (((uint32_t)(value) << field ## _Pos) & field ## _Msk)"

.PP
Mask and shift a bit field value for use in a register bit range\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of the bit field\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Masked and shifted value\&. 
.RE
.PP

.SS "#define _VAL2FLD(field, value)   (((uint32_t)(value) << field ## _Pos) & field ## _Msk)"

.PP
Mask and shift a bit field value for use in a register bit range\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of the bit field\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Masked and shifted value\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
