.TH "CMSIS_Core_RegAccFunctions" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_Core_RegAccFunctions
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__STATIC_INLINE\fP uint32_t \fB__get_CONTROL\fP (void)"
.br
.RI "Enable IRQ Interrupts\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP void \fB__set_CONTROL\fP (uint32_t control)"
.br
.RI "Set Control Register\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP uint32_t \fB__get_IPSR\fP (void)"
.br
.RI "Get IPSR Register\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP uint32_t \fB__get_APSR\fP (void)"
.br
.RI "Get APSR Register\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP uint32_t \fB__get_xPSR\fP (void)"
.br
.RI "Get xPSR Register\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP uint32_t \fB__get_PSP\fP (void)"
.br
.RI "Get Process Stack Pointer\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP void \fB__set_PSP\fP (uint32_t topOfProcStack)"
.br
.RI "Set Process Stack Pointer\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP uint32_t \fB__get_MSP\fP (void)"
.br
.RI "Get Main Stack Pointer\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP void \fB__set_MSP\fP (uint32_t topOfMainStack)"
.br
.RI "Set Main Stack Pointer\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP uint32_t \fB__get_PRIMASK\fP (void)"
.br
.RI "Get Priority Mask\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP void \fB__set_PRIMASK\fP (uint32_t priMask)"
.br
.RI "Set Priority Mask\&. "
.ti -1c
.RI "\fB__STATIC_FORCEINLINE\fP void \fB__enable_irq\fP (void)"
.br
.RI "Enable IRQ Interrupts\&. "
.ti -1c
.RI "\fB__STATIC_FORCEINLINE\fP void \fB__disable_irq\fP (void)"
.br
.RI "Disable IRQ Interrupts\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "\fB__STATIC_FORCEINLINE\fP void __disable_irq (void)"

.PP
Disable IRQ Interrupts\&. Disables IRQ interrupts by setting the I-bit in the CPSR\&. Can only be executed in Privileged modes\&. 
.SS "\fB__STATIC_FORCEINLINE\fP void __enable_irq (void)"

.PP
Enable IRQ Interrupts\&. Enables IRQ interrupts by clearing the I-bit in the CPSR\&. Can only be executed in Privileged modes\&. 
.SS "\fB__STATIC_FORCEINLINE\fP uint32_t __get_APSR (void)"

.PP
Get APSR Register\&. Returns the content of the APSR Register\&. 
.PP
\fBReturns:\fP
.RS 4
APSR Register value 
.RE
.PP

.SS "\fB__STATIC_FORCEINLINE\fP uint32_t __get_CONTROL (void)"

.PP
Enable IRQ Interrupts\&. Get Control Register\&.
.PP
Enables IRQ interrupts by clearing the I-bit in the CPSR\&. Can only be executed in Privileged modes\&. Disable IRQ Interrupts
.PP
Disables IRQ interrupts by setting the I-bit in the CPSR\&. Can only be executed in Privileged modes\&. Get Control Register
.PP
Returns the content of the Control Register\&. 
.PP
\fBReturns:\fP
.RS 4
Control Register value
.RE
.PP
Returns the content of the Control Register\&. 
.PP
\fBReturns:\fP
.RS 4
Control Register value 
.RE
.PP

.SS "\fB__STATIC_FORCEINLINE\fP uint32_t __get_IPSR (void)"

.PP
Get IPSR Register\&. Returns the content of the IPSR Register\&. 
.PP
\fBReturns:\fP
.RS 4
IPSR Register value 
.RE
.PP

.SS "\fB__STATIC_FORCEINLINE\fP uint32_t __get_MSP (void)"

.PP
Get Main Stack Pointer\&. Returns the current value of the Main Stack Pointer (MSP)\&. 
.PP
\fBReturns:\fP
.RS 4
MSP Register value 
.RE
.PP

.SS "\fB__STATIC_FORCEINLINE\fP uint32_t __get_PRIMASK (void)"

.PP
Get Priority Mask\&. Returns the current state of the priority mask bit from the Priority Mask Register\&. 
.PP
\fBReturns:\fP
.RS 4
Priority Mask value 
.RE
.PP

.SS "\fB__STATIC_FORCEINLINE\fP uint32_t __get_PSP (void)"

.PP
Get Process Stack Pointer\&. Returns the current value of the Process Stack Pointer (PSP)\&. 
.PP
\fBReturns:\fP
.RS 4
PSP Register value 
.RE
.PP

.SS "\fB__STATIC_FORCEINLINE\fP uint32_t __get_xPSR (void)"

.PP
Get xPSR Register\&. Returns the content of the xPSR Register\&. 
.PP
\fBReturns:\fP
.RS 4
xPSR Register value 
.RE
.PP

.SS "\fB__STATIC_FORCEINLINE\fP void __set_CONTROL (uint32_t control)"

.PP
Set Control Register\&. Writes the given value to the Control Register\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcontrol\fP Control Register value to set 
.RE
.PP

.SS "\fB__STATIC_FORCEINLINE\fP void __set_MSP (uint32_t topOfMainStack)"

.PP
Set Main Stack Pointer\&. Assigns the given value to the Main Stack Pointer (MSP)\&. 
.PP
\fBParameters:\fP
.RS 4
\fItopOfMainStack\fP Main Stack Pointer value to set 
.RE
.PP

.SS "\fB__STATIC_FORCEINLINE\fP void __set_PRIMASK (uint32_t priMask)"

.PP
Set Priority Mask\&. Assigns the given value to the Priority Mask Register\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpriMask\fP Priority Mask 
.RE
.PP

.SS "\fB__STATIC_FORCEINLINE\fP void __set_PSP (uint32_t topOfProcStack)"

.PP
Set Process Stack Pointer\&. Assigns the given value to the Process Stack Pointer (PSP)\&. 
.PP
\fBParameters:\fP
.RS 4
\fItopOfProcStack\fP Process Stack Pointer value to set 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
