.TH "CMSIS_SCB" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_SCB \- Type definitions for the System Control Block Registers\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBSCB_Type\fP"
.br
.RI "Structure type to access the System Control Block (SCB)\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSCB_CPUID_IMPLEMENTER_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_IMPLEMENTER_Msk\fP   (0xFFUL << SCB_CPUID_IMPLEMENTER_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_VARIANT_Pos\fP   20U"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_VARIANT_Msk\fP   (0xFUL << SCB_CPUID_VARIANT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_ARCHITECTURE_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_ARCHITECTURE_Msk\fP   (0xFUL << SCB_CPUID_ARCHITECTURE_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_PARTNO_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_PARTNO_Msk\fP   (0xFFFUL << SCB_CPUID_PARTNO_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_REVISION_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_REVISION_Msk\fP   (0xFUL /*<< SCB_CPUID_REVISION_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDNMISET_Pos\fP   31U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDNMISET_Msk\fP   (1UL << SCB_ICSR_PENDNMISET_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDNMICLR_Pos\fP   30U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDNMICLR_Msk\fP   (1UL << SCB_ICSR_PENDNMICLR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSVSET_Pos\fP   28U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSVSET_Msk\fP   (1UL << SCB_ICSR_PENDSVSET_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSVCLR_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSVCLR_Msk\fP   (1UL << SCB_ICSR_PENDSVCLR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSTSET_Pos\fP   26U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSTSET_Msk\fP   (1UL << SCB_ICSR_PENDSTSET_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSTCLR_Pos\fP   25U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSTCLR_Msk\fP   (1UL << SCB_ICSR_PENDSTCLR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_STTNS_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_STTNS_Msk\fP   (1UL << SCB_ICSR_STTNS_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_ISRPREEMPT_Pos\fP   23U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_ISRPREEMPT_Msk\fP   (1UL << SCB_ICSR_ISRPREEMPT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_ISRPENDING_Pos\fP   22U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_ISRPENDING_Msk\fP   (1UL << SCB_ICSR_ISRPENDING_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_VECTPENDING_Pos\fP   12U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_VECTPENDING_Msk\fP   (0x1FFUL << SCB_ICSR_VECTPENDING_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_RETTOBASE_Pos\fP   11U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_RETTOBASE_Msk\fP   (1UL << SCB_ICSR_RETTOBASE_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_VECTACTIVE_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_VECTACTIVE_Msk\fP   (0x1FFUL /*<< SCB_ICSR_VECTACTIVE_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTKEY_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTKEY_Msk\fP   (0xFFFFUL << SCB_AIRCR_VECTKEY_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTKEYSTAT_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTKEYSTAT_Msk\fP   (0xFFFFUL << SCB_AIRCR_VECTKEYSTAT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_ENDIANESS_Pos\fP   15U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_ENDIANESS_Msk\fP   (1UL << SCB_AIRCR_ENDIANESS_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_PRIS_Pos\fP   14U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_PRIS_Msk\fP   (1UL << SCB_AIRCR_PRIS_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_BFHFNMINS_Pos\fP   13U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_BFHFNMINS_Msk\fP   (1UL << SCB_AIRCR_BFHFNMINS_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_SYSRESETREQS_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_SYSRESETREQS_Msk\fP   (1UL << SCB_AIRCR_SYSRESETREQS_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_SYSRESETREQ_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_SYSRESETREQ_Msk\fP   (1UL << SCB_AIRCR_SYSRESETREQ_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTCLRACTIVE_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTCLRACTIVE_Msk\fP   (1UL << SCB_AIRCR_VECTCLRACTIVE_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SEVONPEND_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SEVONPEND_Msk\fP   (1UL << SCB_SCR_SEVONPEND_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SLEEPDEEPS_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SLEEPDEEPS_Msk\fP   (1UL << SCB_SCR_SLEEPDEEPS_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SLEEPDEEP_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SLEEPDEEP_Msk\fP   (1UL << SCB_SCR_SLEEPDEEP_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SLEEPONEXIT_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SLEEPONEXIT_Msk\fP   (1UL << SCB_SCR_SLEEPONEXIT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_BP_Pos\fP   18U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_BP_Msk\fP   (1UL << SCB_CCR_BP_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_IC_Pos\fP   17U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_IC_Msk\fP   (1UL << SCB_CCR_IC_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_DC_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_DC_Msk\fP   (1UL << SCB_CCR_DC_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_STKOFHFNMIGN_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_STKOFHFNMIGN_Msk\fP   (1UL << SCB_CCR_STKOFHFNMIGN_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_BFHFNMIGN_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_BFHFNMIGN_Msk\fP   (1UL << SCB_CCR_BFHFNMIGN_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_DIV_0_TRP_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_DIV_0_TRP_Msk\fP   (1UL << SCB_CCR_DIV_0_TRP_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_UNALIGN_TRP_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_UNALIGN_TRP_Msk\fP   (1UL << SCB_CCR_UNALIGN_TRP_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_USERSETMPEND_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_USERSETMPEND_Msk\fP   (1UL << SCB_CCR_USERSETMPEND_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_HARDFAULTPENDED_Pos\fP   21U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_HARDFAULTPENDED_Msk\fP   (1UL << SCB_SHCSR_HARDFAULTPENDED_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SVCALLPENDED_Pos\fP   15U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SVCALLPENDED_Msk\fP   (1UL << SCB_SHCSR_SVCALLPENDED_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SYSTICKACT_Pos\fP   11U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SYSTICKACT_Msk\fP   (1UL << SCB_SHCSR_SYSTICKACT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_PENDSVACT_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_PENDSVACT_Msk\fP   (1UL << SCB_SHCSR_PENDSVACT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SVCALLACT_Pos\fP   7U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SVCALLACT_Msk\fP   (1UL << SCB_SHCSR_SVCALLACT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_NMIACT_Pos\fP   5U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_NMIACT_Msk\fP   (1UL << SCB_SHCSR_NMIACT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_HARDFAULTACT_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_HARDFAULTACT_Msk\fP   (1UL << SCB_SHCSR_HARDFAULTACT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_IMPLEMENTER_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_IMPLEMENTER_Msk\fP   (0xFFUL << SCB_CPUID_IMPLEMENTER_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_VARIANT_Pos\fP   20U"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_VARIANT_Msk\fP   (0xFUL << SCB_CPUID_VARIANT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_ARCHITECTURE_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_ARCHITECTURE_Msk\fP   (0xFUL << SCB_CPUID_ARCHITECTURE_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_PARTNO_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_PARTNO_Msk\fP   (0xFFFUL << SCB_CPUID_PARTNO_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_REVISION_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_REVISION_Msk\fP   (0xFUL /*<< SCB_CPUID_REVISION_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDNMISET_Pos\fP   31U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDNMISET_Msk\fP   (1UL << SCB_ICSR_PENDNMISET_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDNMICLR_Pos\fP   30U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDNMICLR_Msk\fP   (1UL << SCB_ICSR_PENDNMICLR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSVSET_Pos\fP   28U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSVSET_Msk\fP   (1UL << SCB_ICSR_PENDSVSET_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSVCLR_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSVCLR_Msk\fP   (1UL << SCB_ICSR_PENDSVCLR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSTSET_Pos\fP   26U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSTSET_Msk\fP   (1UL << SCB_ICSR_PENDSTSET_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSTCLR_Pos\fP   25U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSTCLR_Msk\fP   (1UL << SCB_ICSR_PENDSTCLR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_STTNS_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_STTNS_Msk\fP   (1UL << SCB_ICSR_STTNS_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_ISRPREEMPT_Pos\fP   23U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_ISRPREEMPT_Msk\fP   (1UL << SCB_ICSR_ISRPREEMPT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_ISRPENDING_Pos\fP   22U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_ISRPENDING_Msk\fP   (1UL << SCB_ICSR_ISRPENDING_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_VECTPENDING_Pos\fP   12U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_VECTPENDING_Msk\fP   (0x1FFUL << SCB_ICSR_VECTPENDING_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_RETTOBASE_Pos\fP   11U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_RETTOBASE_Msk\fP   (1UL << SCB_ICSR_RETTOBASE_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_VECTACTIVE_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_VECTACTIVE_Msk\fP   (0x1FFUL /*<< SCB_ICSR_VECTACTIVE_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_VTOR_TBLOFF_Pos\fP   7U"
.br
.ti -1c
.RI "#define \fBSCB_VTOR_TBLOFF_Msk\fP   (0x1FFFFFFUL << SCB_VTOR_TBLOFF_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTKEY_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTKEY_Msk\fP   (0xFFFFUL << SCB_AIRCR_VECTKEY_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTKEYSTAT_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTKEYSTAT_Msk\fP   (0xFFFFUL << SCB_AIRCR_VECTKEYSTAT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_ENDIANESS_Pos\fP   15U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_ENDIANESS_Msk\fP   (1UL << SCB_AIRCR_ENDIANESS_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_PRIS_Pos\fP   14U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_PRIS_Msk\fP   (1UL << SCB_AIRCR_PRIS_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_BFHFNMINS_Pos\fP   13U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_BFHFNMINS_Msk\fP   (1UL << SCB_AIRCR_BFHFNMINS_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_PRIGROUP_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_PRIGROUP_Msk\fP   (7UL << SCB_AIRCR_PRIGROUP_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_SYSRESETREQS_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_SYSRESETREQS_Msk\fP   (1UL << SCB_AIRCR_SYSRESETREQS_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_SYSRESETREQ_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_SYSRESETREQ_Msk\fP   (1UL << SCB_AIRCR_SYSRESETREQ_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTCLRACTIVE_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTCLRACTIVE_Msk\fP   (1UL << SCB_AIRCR_VECTCLRACTIVE_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SEVONPEND_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SEVONPEND_Msk\fP   (1UL << SCB_SCR_SEVONPEND_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SLEEPDEEPS_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SLEEPDEEPS_Msk\fP   (1UL << SCB_SCR_SLEEPDEEPS_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SLEEPDEEP_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SLEEPDEEP_Msk\fP   (1UL << SCB_SCR_SLEEPDEEP_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SLEEPONEXIT_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SLEEPONEXIT_Msk\fP   (1UL << SCB_SCR_SLEEPONEXIT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_BP_Pos\fP   18U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_BP_Msk\fP   (1UL << SCB_CCR_BP_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_IC_Pos\fP   17U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_IC_Msk\fP   (1UL << SCB_CCR_IC_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_DC_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_DC_Msk\fP   (1UL << SCB_CCR_DC_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_STKOFHFNMIGN_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_STKOFHFNMIGN_Msk\fP   (1UL << SCB_CCR_STKOFHFNMIGN_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_BFHFNMIGN_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_BFHFNMIGN_Msk\fP   (1UL << SCB_CCR_BFHFNMIGN_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_DIV_0_TRP_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_DIV_0_TRP_Msk\fP   (1UL << SCB_CCR_DIV_0_TRP_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_UNALIGN_TRP_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_UNALIGN_TRP_Msk\fP   (1UL << SCB_CCR_UNALIGN_TRP_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_USERSETMPEND_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_USERSETMPEND_Msk\fP   (1UL << SCB_CCR_USERSETMPEND_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_HARDFAULTPENDED_Pos\fP   21U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_HARDFAULTPENDED_Msk\fP   (1UL << SCB_SHCSR_HARDFAULTPENDED_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SECUREFAULTPENDED_Pos\fP   20U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SECUREFAULTPENDED_Msk\fP   (1UL << SCB_SHCSR_SECUREFAULTPENDED_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SECUREFAULTENA_Pos\fP   19U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SECUREFAULTENA_Msk\fP   (1UL << SCB_SHCSR_SECUREFAULTENA_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_USGFAULTENA_Pos\fP   18U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_USGFAULTENA_Msk\fP   (1UL << SCB_SHCSR_USGFAULTENA_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_BUSFAULTENA_Pos\fP   17U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_BUSFAULTENA_Msk\fP   (1UL << SCB_SHCSR_BUSFAULTENA_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_MEMFAULTENA_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_MEMFAULTENA_Msk\fP   (1UL << SCB_SHCSR_MEMFAULTENA_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SVCALLPENDED_Pos\fP   15U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SVCALLPENDED_Msk\fP   (1UL << SCB_SHCSR_SVCALLPENDED_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_BUSFAULTPENDED_Pos\fP   14U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_BUSFAULTPENDED_Msk\fP   (1UL << SCB_SHCSR_BUSFAULTPENDED_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_MEMFAULTPENDED_Pos\fP   13U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_MEMFAULTPENDED_Msk\fP   (1UL << SCB_SHCSR_MEMFAULTPENDED_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_USGFAULTPENDED_Pos\fP   12U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_USGFAULTPENDED_Msk\fP   (1UL << SCB_SHCSR_USGFAULTPENDED_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SYSTICKACT_Pos\fP   11U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SYSTICKACT_Msk\fP   (1UL << SCB_SHCSR_SYSTICKACT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_PENDSVACT_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_PENDSVACT_Msk\fP   (1UL << SCB_SHCSR_PENDSVACT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_MONITORACT_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_MONITORACT_Msk\fP   (1UL << SCB_SHCSR_MONITORACT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SVCALLACT_Pos\fP   7U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SVCALLACT_Msk\fP   (1UL << SCB_SHCSR_SVCALLACT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_NMIACT_Pos\fP   5U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_NMIACT_Msk\fP   (1UL << SCB_SHCSR_NMIACT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SECUREFAULTACT_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SECUREFAULTACT_Msk\fP   (1UL << SCB_SHCSR_SECUREFAULTACT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_USGFAULTACT_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_USGFAULTACT_Msk\fP   (1UL << SCB_SHCSR_USGFAULTACT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_HARDFAULTACT_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_HARDFAULTACT_Msk\fP   (1UL << SCB_SHCSR_HARDFAULTACT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_BUSFAULTACT_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_BUSFAULTACT_Msk\fP   (1UL << SCB_SHCSR_BUSFAULTACT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_MEMFAULTACT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_MEMFAULTACT_Msk\fP   (1UL /*<< SCB_SHCSR_MEMFAULTACT_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_USGFAULTSR_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_USGFAULTSR_Msk\fP   (0xFFFFUL << SCB_CFSR_USGFAULTSR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_BUSFAULTSR_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_BUSFAULTSR_Msk\fP   (0xFFUL << SCB_CFSR_BUSFAULTSR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MEMFAULTSR_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MEMFAULTSR_Msk\fP   (0xFFUL /*<< SCB_CFSR_MEMFAULTSR_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MMARVALID_Pos\fP   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 7U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MMARVALID_Msk\fP   (1UL << SCB_CFSR_MMARVALID_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MLSPERR_Pos\fP   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 5U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MLSPERR_Msk\fP   (1UL << SCB_CFSR_MLSPERR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MSTKERR_Pos\fP   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 4U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MSTKERR_Msk\fP   (1UL << SCB_CFSR_MSTKERR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MUNSTKERR_Pos\fP   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 3U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MUNSTKERR_Msk\fP   (1UL << SCB_CFSR_MUNSTKERR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_DACCVIOL_Pos\fP   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 1U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_DACCVIOL_Msk\fP   (1UL << SCB_CFSR_DACCVIOL_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_IACCVIOL_Pos\fP   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 0U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_IACCVIOL_Msk\fP   (1UL /*<< SCB_CFSR_IACCVIOL_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_BFARVALID_Pos\fP   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 7U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_BFARVALID_Msk\fP   (1UL << SCB_CFSR_BFARVALID_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_LSPERR_Pos\fP   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 5U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_LSPERR_Msk\fP   (1UL << SCB_CFSR_LSPERR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_STKERR_Pos\fP   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 4U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_STKERR_Msk\fP   (1UL << SCB_CFSR_STKERR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_UNSTKERR_Pos\fP   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 3U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_UNSTKERR_Msk\fP   (1UL << SCB_CFSR_UNSTKERR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_IMPRECISERR_Pos\fP   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 2U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_IMPRECISERR_Msk\fP   (1UL << SCB_CFSR_IMPRECISERR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_PRECISERR_Pos\fP   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 1U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_PRECISERR_Msk\fP   (1UL << SCB_CFSR_PRECISERR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_IBUSERR_Pos\fP   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 0U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_IBUSERR_Msk\fP   (1UL << SCB_CFSR_IBUSERR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_DIVBYZERO_Pos\fP   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 9U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_DIVBYZERO_Msk\fP   (1UL << SCB_CFSR_DIVBYZERO_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_UNALIGNED_Pos\fP   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 8U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_UNALIGNED_Msk\fP   (1UL << SCB_CFSR_UNALIGNED_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_STKOF_Pos\fP   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 4U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_STKOF_Msk\fP   (1UL << SCB_CFSR_STKOF_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_NOCP_Pos\fP   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 3U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_NOCP_Msk\fP   (1UL << SCB_CFSR_NOCP_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_INVPC_Pos\fP   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 2U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_INVPC_Msk\fP   (1UL << SCB_CFSR_INVPC_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_INVSTATE_Pos\fP   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 1U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_INVSTATE_Msk\fP   (1UL << SCB_CFSR_INVSTATE_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_UNDEFINSTR_Pos\fP   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 0U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_UNDEFINSTR_Msk\fP   (1UL << SCB_CFSR_UNDEFINSTR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_HFSR_DEBUGEVT_Pos\fP   31U"
.br
.ti -1c
.RI "#define \fBSCB_HFSR_DEBUGEVT_Msk\fP   (1UL << SCB_HFSR_DEBUGEVT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_HFSR_FORCED_Pos\fP   30U"
.br
.ti -1c
.RI "#define \fBSCB_HFSR_FORCED_Msk\fP   (1UL << SCB_HFSR_FORCED_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_HFSR_VECTTBL_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_HFSR_VECTTBL_Msk\fP   (1UL << SCB_HFSR_VECTTBL_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_EXTERNAL_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_EXTERNAL_Msk\fP   (1UL << SCB_DFSR_EXTERNAL_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_VCATCH_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_VCATCH_Msk\fP   (1UL << SCB_DFSR_VCATCH_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_DWTTRAP_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_DWTTRAP_Msk\fP   (1UL << SCB_DFSR_DWTTRAP_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_BKPT_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_BKPT_Msk\fP   (1UL << SCB_DFSR_BKPT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_HALTED_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_HALTED_Msk\fP   (1UL /*<< SCB_DFSR_HALTED_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_NSACR_CP11_Pos\fP   11U"
.br
.ti -1c
.RI "#define \fBSCB_NSACR_CP11_Msk\fP   (1UL << SCB_NSACR_CP11_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_NSACR_CP10_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBSCB_NSACR_CP10_Msk\fP   (1UL << SCB_NSACR_CP10_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_NSACR_CPn_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_NSACR_CPn_Msk\fP   (1UL /*<< SCB_NSACR_CPn_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_CLIDR_LOUU_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBSCB_CLIDR_LOUU_Msk\fP   (7UL << SCB_CLIDR_LOUU_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CLIDR_LOC_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBSCB_CLIDR_LOC_Msk\fP   (7UL << SCB_CLIDR_LOC_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CTR_FORMAT_Pos\fP   29U"
.br
.ti -1c
.RI "#define \fBSCB_CTR_FORMAT_Msk\fP   (7UL << SCB_CTR_FORMAT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CTR_CWG_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBSCB_CTR_CWG_Msk\fP   (0xFUL << SCB_CTR_CWG_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CTR_ERG_Pos\fP   20U"
.br
.ti -1c
.RI "#define \fBSCB_CTR_ERG_Msk\fP   (0xFUL << SCB_CTR_ERG_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CTR_DMINLINE_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBSCB_CTR_DMINLINE_Msk\fP   (0xFUL << SCB_CTR_DMINLINE_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CTR_IMINLINE_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_CTR_IMINLINE_Msk\fP   (0xFUL /*<< SCB_CTR_IMINLINE_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_CCSIDR_WT_Pos\fP   31U"
.br
.ti -1c
.RI "#define \fBSCB_CCSIDR_WT_Msk\fP   (1UL << SCB_CCSIDR_WT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCSIDR_WB_Pos\fP   30U"
.br
.ti -1c
.RI "#define \fBSCB_CCSIDR_WB_Msk\fP   (1UL << SCB_CCSIDR_WB_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCSIDR_RA_Pos\fP   29U"
.br
.ti -1c
.RI "#define \fBSCB_CCSIDR_RA_Msk\fP   (1UL << SCB_CCSIDR_RA_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCSIDR_WA_Pos\fP   28U"
.br
.ti -1c
.RI "#define \fBSCB_CCSIDR_WA_Msk\fP   (1UL << SCB_CCSIDR_WA_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCSIDR_NUMSETS_Pos\fP   13U"
.br
.ti -1c
.RI "#define \fBSCB_CCSIDR_NUMSETS_Msk\fP   (0x7FFFUL << SCB_CCSIDR_NUMSETS_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCSIDR_ASSOCIATIVITY_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBSCB_CCSIDR_ASSOCIATIVITY_Msk\fP   (0x3FFUL << SCB_CCSIDR_ASSOCIATIVITY_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCSIDR_LINESIZE_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_CCSIDR_LINESIZE_Msk\fP   (7UL /*<< SCB_CCSIDR_LINESIZE_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_CSSELR_LEVEL_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_CSSELR_LEVEL_Msk\fP   (7UL << SCB_CSSELR_LEVEL_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CSSELR_IND_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_CSSELR_IND_Msk\fP   (1UL /*<< SCB_CSSELR_IND_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_STIR_INTID_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_STIR_INTID_Msk\fP   (0x1FFUL /*<< SCB_STIR_INTID_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_DCISW_WAY_Pos\fP   30U"
.br
.ti -1c
.RI "#define \fBSCB_DCISW_WAY_Msk\fP   (3UL << SCB_DCISW_WAY_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DCISW_SET_Pos\fP   5U"
.br
.ti -1c
.RI "#define \fBSCB_DCISW_SET_Msk\fP   (0x1FFUL << SCB_DCISW_SET_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DCCSW_WAY_Pos\fP   30U"
.br
.ti -1c
.RI "#define \fBSCB_DCCSW_WAY_Msk\fP   (3UL << SCB_DCCSW_WAY_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DCCSW_SET_Pos\fP   5U"
.br
.ti -1c
.RI "#define \fBSCB_DCCSW_SET_Msk\fP   (0x1FFUL << SCB_DCCSW_SET_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DCCISW_WAY_Pos\fP   30U"
.br
.ti -1c
.RI "#define \fBSCB_DCCISW_WAY_Msk\fP   (3UL << SCB_DCCISW_WAY_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DCCISW_SET_Pos\fP   5U"
.br
.ti -1c
.RI "#define \fBSCB_DCCISW_SET_Msk\fP   (0x1FFUL << SCB_DCCISW_SET_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ITCMCR_SZ_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBSCB_ITCMCR_SZ_Msk\fP   (0xFUL << SCB_ITCMCR_SZ_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ITCMCR_RETEN_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCB_ITCMCR_RETEN_Msk\fP   (1UL << SCB_ITCMCR_RETEN_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ITCMCR_RMW_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_ITCMCR_RMW_Msk\fP   (1UL << SCB_ITCMCR_RMW_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ITCMCR_EN_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_ITCMCR_EN_Msk\fP   (1UL /*<< SCB_ITCMCR_EN_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_DTCMCR_SZ_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBSCB_DTCMCR_SZ_Msk\fP   (0xFUL << SCB_DTCMCR_SZ_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DTCMCR_RETEN_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCB_DTCMCR_RETEN_Msk\fP   (1UL << SCB_DTCMCR_RETEN_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DTCMCR_RMW_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_DTCMCR_RMW_Msk\fP   (1UL << SCB_DTCMCR_RMW_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DTCMCR_EN_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_DTCMCR_EN_Msk\fP   (1UL /*<< SCB_DTCMCR_EN_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_AHBPCR_SZ_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_AHBPCR_SZ_Msk\fP   (7UL << SCB_AHBPCR_SZ_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AHBPCR_EN_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_AHBPCR_EN_Msk\fP   (1UL /*<< SCB_AHBPCR_EN_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_CACR_FORCEWT_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCB_CACR_FORCEWT_Msk\fP   (1UL << SCB_CACR_FORCEWT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CACR_ECCEN_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_CACR_ECCEN_Msk\fP   (1UL << SCB_CACR_ECCEN_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CACR_SIWT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_CACR_SIWT_Msk\fP   (1UL /*<< SCB_CACR_SIWT_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_AHBSCR_INITCOUNT_Pos\fP   11U"
.br
.ti -1c
.RI "#define \fBSCB_AHBSCR_INITCOUNT_Msk\fP   (0x1FUL << SCB_AHBPCR_INITCOUNT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AHBSCR_TPRI_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCB_AHBSCR_TPRI_Msk\fP   (0x1FFUL << SCB_AHBPCR_TPRI_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AHBSCR_CTL_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_AHBSCR_CTL_Msk\fP   (3UL /*<< SCB_AHBPCR_CTL_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_ABFSR_AXIMTYPE_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBSCB_ABFSR_AXIMTYPE_Msk\fP   (3UL << SCB_ABFSR_AXIMTYPE_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ABFSR_EPPB_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBSCB_ABFSR_EPPB_Msk\fP   (1UL << SCB_ABFSR_EPPB_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ABFSR_AXIM_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBSCB_ABFSR_AXIM_Msk\fP   (1UL << SCB_ABFSR_AXIM_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ABFSR_AHBP_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCB_ABFSR_AHBP_Msk\fP   (1UL << SCB_ABFSR_AHBP_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ABFSR_DTCM_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_ABFSR_DTCM_Msk\fP   (1UL << SCB_ABFSR_DTCM_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ABFSR_ITCM_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_ABFSR_ITCM_Msk\fP   (1UL /*<< SCB_ABFSR_ITCM_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_IMPLEMENTER_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_IMPLEMENTER_Msk\fP   (0xFFUL << SCB_CPUID_IMPLEMENTER_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_VARIANT_Pos\fP   20U"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_VARIANT_Msk\fP   (0xFUL << SCB_CPUID_VARIANT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_ARCHITECTURE_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_ARCHITECTURE_Msk\fP   (0xFUL << SCB_CPUID_ARCHITECTURE_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_PARTNO_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_PARTNO_Msk\fP   (0xFFFUL << SCB_CPUID_PARTNO_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_REVISION_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_REVISION_Msk\fP   (0xFUL /*<< SCB_CPUID_REVISION_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_NMIPENDSET_Pos\fP   31U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_NMIPENDSET_Msk\fP   (1UL << SCB_ICSR_NMIPENDSET_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSVSET_Pos\fP   28U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSVSET_Msk\fP   (1UL << SCB_ICSR_PENDSVSET_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSVCLR_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSVCLR_Msk\fP   (1UL << SCB_ICSR_PENDSVCLR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSTSET_Pos\fP   26U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSTSET_Msk\fP   (1UL << SCB_ICSR_PENDSTSET_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSTCLR_Pos\fP   25U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSTCLR_Msk\fP   (1UL << SCB_ICSR_PENDSTCLR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_ISRPREEMPT_Pos\fP   23U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_ISRPREEMPT_Msk\fP   (1UL << SCB_ICSR_ISRPREEMPT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_ISRPENDING_Pos\fP   22U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_ISRPENDING_Msk\fP   (1UL << SCB_ICSR_ISRPENDING_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_VECTPENDING_Pos\fP   12U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_VECTPENDING_Msk\fP   (0x1FFUL << SCB_ICSR_VECTPENDING_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_RETTOBASE_Pos\fP   11U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_RETTOBASE_Msk\fP   (1UL << SCB_ICSR_RETTOBASE_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_VECTACTIVE_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_VECTACTIVE_Msk\fP   (0x1FFUL /*<< SCB_ICSR_VECTACTIVE_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_VTOR_TBLOFF_Pos\fP   7U"
.br
.ti -1c
.RI "#define \fBSCB_VTOR_TBLOFF_Msk\fP   (0x1FFFFFFUL << SCB_VTOR_TBLOFF_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTKEY_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTKEY_Msk\fP   (0xFFFFUL << SCB_AIRCR_VECTKEY_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTKEYSTAT_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTKEYSTAT_Msk\fP   (0xFFFFUL << SCB_AIRCR_VECTKEYSTAT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_ENDIANESS_Pos\fP   15U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_ENDIANESS_Msk\fP   (1UL << SCB_AIRCR_ENDIANESS_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_PRIGROUP_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_PRIGROUP_Msk\fP   (7UL << SCB_AIRCR_PRIGROUP_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_SYSRESETREQ_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_SYSRESETREQ_Msk\fP   (1UL << SCB_AIRCR_SYSRESETREQ_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTCLRACTIVE_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTCLRACTIVE_Msk\fP   (1UL << SCB_AIRCR_VECTCLRACTIVE_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTRESET_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTRESET_Msk\fP   (1UL /*<< SCB_AIRCR_VECTRESET_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SEVONPEND_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SEVONPEND_Msk\fP   (1UL << SCB_SCR_SEVONPEND_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SLEEPDEEP_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SLEEPDEEP_Msk\fP   (1UL << SCB_SCR_SLEEPDEEP_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SLEEPONEXIT_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SLEEPONEXIT_Msk\fP   (1UL << SCB_SCR_SLEEPONEXIT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_STKALIGN_Pos\fP   9U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_STKALIGN_Msk\fP   (1UL << SCB_CCR_STKALIGN_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_BFHFNMIGN_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_BFHFNMIGN_Msk\fP   (1UL << SCB_CCR_BFHFNMIGN_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_DIV_0_TRP_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_DIV_0_TRP_Msk\fP   (1UL << SCB_CCR_DIV_0_TRP_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_UNALIGN_TRP_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_UNALIGN_TRP_Msk\fP   (1UL << SCB_CCR_UNALIGN_TRP_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_USERSETMPEND_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_USERSETMPEND_Msk\fP   (1UL << SCB_CCR_USERSETMPEND_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_NONBASETHRDENA_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_NONBASETHRDENA_Msk\fP   (1UL /*<< SCB_CCR_NONBASETHRDENA_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_USGFAULTENA_Pos\fP   18U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_USGFAULTENA_Msk\fP   (1UL << SCB_SHCSR_USGFAULTENA_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_BUSFAULTENA_Pos\fP   17U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_BUSFAULTENA_Msk\fP   (1UL << SCB_SHCSR_BUSFAULTENA_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_MEMFAULTENA_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_MEMFAULTENA_Msk\fP   (1UL << SCB_SHCSR_MEMFAULTENA_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SVCALLPENDED_Pos\fP   15U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SVCALLPENDED_Msk\fP   (1UL << SCB_SHCSR_SVCALLPENDED_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_BUSFAULTPENDED_Pos\fP   14U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_BUSFAULTPENDED_Msk\fP   (1UL << SCB_SHCSR_BUSFAULTPENDED_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_MEMFAULTPENDED_Pos\fP   13U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_MEMFAULTPENDED_Msk\fP   (1UL << SCB_SHCSR_MEMFAULTPENDED_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_USGFAULTPENDED_Pos\fP   12U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_USGFAULTPENDED_Msk\fP   (1UL << SCB_SHCSR_USGFAULTPENDED_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SYSTICKACT_Pos\fP   11U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SYSTICKACT_Msk\fP   (1UL << SCB_SHCSR_SYSTICKACT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_PENDSVACT_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_PENDSVACT_Msk\fP   (1UL << SCB_SHCSR_PENDSVACT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_MONITORACT_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_MONITORACT_Msk\fP   (1UL << SCB_SHCSR_MONITORACT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SVCALLACT_Pos\fP   7U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SVCALLACT_Msk\fP   (1UL << SCB_SHCSR_SVCALLACT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_USGFAULTACT_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_USGFAULTACT_Msk\fP   (1UL << SCB_SHCSR_USGFAULTACT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_BUSFAULTACT_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_BUSFAULTACT_Msk\fP   (1UL << SCB_SHCSR_BUSFAULTACT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_MEMFAULTACT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_MEMFAULTACT_Msk\fP   (1UL /*<< SCB_SHCSR_MEMFAULTACT_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_USGFAULTSR_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_USGFAULTSR_Msk\fP   (0xFFFFUL << SCB_CFSR_USGFAULTSR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_BUSFAULTSR_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_BUSFAULTSR_Msk\fP   (0xFFUL << SCB_CFSR_BUSFAULTSR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MEMFAULTSR_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MEMFAULTSR_Msk\fP   (0xFFUL /*<< SCB_CFSR_MEMFAULTSR_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MMARVALID_Pos\fP   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 7U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MMARVALID_Msk\fP   (1UL << SCB_CFSR_MMARVALID_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MLSPERR_Pos\fP   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 5U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MLSPERR_Msk\fP   (1UL << SCB_CFSR_MLSPERR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MSTKERR_Pos\fP   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 4U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MSTKERR_Msk\fP   (1UL << SCB_CFSR_MSTKERR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MUNSTKERR_Pos\fP   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 3U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MUNSTKERR_Msk\fP   (1UL << SCB_CFSR_MUNSTKERR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_DACCVIOL_Pos\fP   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 1U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_DACCVIOL_Msk\fP   (1UL << SCB_CFSR_DACCVIOL_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_IACCVIOL_Pos\fP   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 0U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_IACCVIOL_Msk\fP   (1UL /*<< SCB_CFSR_IACCVIOL_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_BFARVALID_Pos\fP   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 7U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_BFARVALID_Msk\fP   (1UL << SCB_CFSR_BFARVALID_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_LSPERR_Pos\fP   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 5U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_LSPERR_Msk\fP   (1UL << SCB_CFSR_LSPERR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_STKERR_Pos\fP   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 4U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_STKERR_Msk\fP   (1UL << SCB_CFSR_STKERR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_UNSTKERR_Pos\fP   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 3U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_UNSTKERR_Msk\fP   (1UL << SCB_CFSR_UNSTKERR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_IMPRECISERR_Pos\fP   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 2U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_IMPRECISERR_Msk\fP   (1UL << SCB_CFSR_IMPRECISERR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_PRECISERR_Pos\fP   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 1U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_PRECISERR_Msk\fP   (1UL << SCB_CFSR_PRECISERR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_IBUSERR_Pos\fP   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 0U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_IBUSERR_Msk\fP   (1UL << SCB_CFSR_IBUSERR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_DIVBYZERO_Pos\fP   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 9U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_DIVBYZERO_Msk\fP   (1UL << SCB_CFSR_DIVBYZERO_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_UNALIGNED_Pos\fP   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 8U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_UNALIGNED_Msk\fP   (1UL << SCB_CFSR_UNALIGNED_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_NOCP_Pos\fP   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 3U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_NOCP_Msk\fP   (1UL << SCB_CFSR_NOCP_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_INVPC_Pos\fP   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 2U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_INVPC_Msk\fP   (1UL << SCB_CFSR_INVPC_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_INVSTATE_Pos\fP   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 1U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_INVSTATE_Msk\fP   (1UL << SCB_CFSR_INVSTATE_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_UNDEFINSTR_Pos\fP   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 0U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_UNDEFINSTR_Msk\fP   (1UL << SCB_CFSR_UNDEFINSTR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_HFSR_DEBUGEVT_Pos\fP   31U"
.br
.ti -1c
.RI "#define \fBSCB_HFSR_DEBUGEVT_Msk\fP   (1UL << SCB_HFSR_DEBUGEVT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_HFSR_FORCED_Pos\fP   30U"
.br
.ti -1c
.RI "#define \fBSCB_HFSR_FORCED_Msk\fP   (1UL << SCB_HFSR_FORCED_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_HFSR_VECTTBL_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_HFSR_VECTTBL_Msk\fP   (1UL << SCB_HFSR_VECTTBL_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_EXTERNAL_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_EXTERNAL_Msk\fP   (1UL << SCB_DFSR_EXTERNAL_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_VCATCH_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_VCATCH_Msk\fP   (1UL << SCB_DFSR_VCATCH_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_DWTTRAP_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_DWTTRAP_Msk\fP   (1UL << SCB_DFSR_DWTTRAP_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_BKPT_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_BKPT_Msk\fP   (1UL << SCB_DFSR_BKPT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_HALTED_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_HALTED_Msk\fP   (1UL /*<< SCB_DFSR_HALTED_Pos*/)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Type definitions for the System Control Block Registers\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define SCB_ABFSR_AHBP_Msk   (1UL << SCB_ABFSR_AHBP_Pos)"
SCB ABFSR: AHBP Mask 
.SS "#define SCB_ABFSR_AHBP_Pos   2U"
SCB ABFSR: AHBP Position 
.SS "#define SCB_ABFSR_AXIM_Msk   (1UL << SCB_ABFSR_AXIM_Pos)"
SCB ABFSR: AXIM Mask 
.SS "#define SCB_ABFSR_AXIM_Pos   3U"
SCB ABFSR: AXIM Position 
.SS "#define SCB_ABFSR_AXIMTYPE_Msk   (3UL << SCB_ABFSR_AXIMTYPE_Pos)"
SCB ABFSR: AXIMTYPE Mask 
.SS "#define SCB_ABFSR_AXIMTYPE_Pos   8U"
SCB ABFSR: AXIMTYPE Position 
.SS "#define SCB_ABFSR_DTCM_Msk   (1UL << SCB_ABFSR_DTCM_Pos)"
SCB ABFSR: DTCM Mask 
.SS "#define SCB_ABFSR_DTCM_Pos   1U"
SCB ABFSR: DTCM Position 
.SS "#define SCB_ABFSR_EPPB_Msk   (1UL << SCB_ABFSR_EPPB_Pos)"
SCB ABFSR: EPPB Mask 
.SS "#define SCB_ABFSR_EPPB_Pos   4U"
SCB ABFSR: EPPB Position 
.SS "#define SCB_ABFSR_ITCM_Msk   (1UL /*<< SCB_ABFSR_ITCM_Pos*/)"
SCB ABFSR: ITCM Mask 
.SS "#define SCB_ABFSR_ITCM_Pos   0U"
SCB ABFSR: ITCM Position 
.SS "#define SCB_AHBPCR_EN_Msk   (1UL /*<< SCB_AHBPCR_EN_Pos*/)"
SCB AHBPCR: EN Mask 
.SS "#define SCB_AHBPCR_EN_Pos   0U"
SCB AHBPCR: EN Position 
.SS "#define SCB_AHBPCR_SZ_Msk   (7UL << SCB_AHBPCR_SZ_Pos)"
SCB AHBPCR: SZ Mask 
.SS "#define SCB_AHBPCR_SZ_Pos   1U"
SCB AHBPCR: SZ Position 
.SS "#define SCB_AHBSCR_CTL_Msk   (3UL /*<< SCB_AHBPCR_CTL_Pos*/)"
SCB AHBSCR: CTL Mask 
.SS "#define SCB_AHBSCR_CTL_Pos   0U"
SCB AHBSCR: CTL Position 
.SS "#define SCB_AHBSCR_INITCOUNT_Msk   (0x1FUL << SCB_AHBPCR_INITCOUNT_Pos)"
SCB AHBSCR: INITCOUNT Mask 
.SS "#define SCB_AHBSCR_INITCOUNT_Pos   11U"
SCB AHBSCR: INITCOUNT Position 
.SS "#define SCB_AHBSCR_TPRI_Msk   (0x1FFUL << SCB_AHBPCR_TPRI_Pos)"
SCB AHBSCR: TPRI Mask 
.SS "#define SCB_AHBSCR_TPRI_Pos   2U"
SCB AHBSCR: TPRI Position 
.SS "#define SCB_AIRCR_BFHFNMINS_Msk   (1UL << SCB_AIRCR_BFHFNMINS_Pos)"
SCB AIRCR: BFHFNMINS Mask 
.SS "#define SCB_AIRCR_BFHFNMINS_Msk   (1UL << SCB_AIRCR_BFHFNMINS_Pos)"
SCB AIRCR: BFHFNMINS Mask 
.SS "#define SCB_AIRCR_BFHFNMINS_Pos   13U"
SCB AIRCR: BFHFNMINS Position 
.SS "#define SCB_AIRCR_BFHFNMINS_Pos   13U"
SCB AIRCR: BFHFNMINS Position 
.SS "#define SCB_AIRCR_ENDIANESS_Msk   (1UL << SCB_AIRCR_ENDIANESS_Pos)"
SCB AIRCR: ENDIANESS Mask 
.SS "#define SCB_AIRCR_ENDIANESS_Msk   (1UL << SCB_AIRCR_ENDIANESS_Pos)"
SCB AIRCR: ENDIANESS Mask 
.SS "#define SCB_AIRCR_ENDIANESS_Msk   (1UL << SCB_AIRCR_ENDIANESS_Pos)"
SCB AIRCR: ENDIANESS Mask 
.SS "#define SCB_AIRCR_ENDIANESS_Pos   15U"
SCB AIRCR: ENDIANESS Position 
.SS "#define SCB_AIRCR_ENDIANESS_Pos   15U"
SCB AIRCR: ENDIANESS Position 
.SS "#define SCB_AIRCR_ENDIANESS_Pos   15U"
SCB AIRCR: ENDIANESS Position 
.SS "#define SCB_AIRCR_PRIGROUP_Msk   (7UL << SCB_AIRCR_PRIGROUP_Pos)"
SCB AIRCR: PRIGROUP Mask 
.SS "#define SCB_AIRCR_PRIGROUP_Msk   (7UL << SCB_AIRCR_PRIGROUP_Pos)"
SCB AIRCR: PRIGROUP Mask 
.SS "#define SCB_AIRCR_PRIGROUP_Pos   8U"
SCB AIRCR: PRIGROUP Position 
.SS "#define SCB_AIRCR_PRIGROUP_Pos   8U"
SCB AIRCR: PRIGROUP Position 
.SS "#define SCB_AIRCR_PRIS_Msk   (1UL << SCB_AIRCR_PRIS_Pos)"
SCB AIRCR: PRIS Mask 
.SS "#define SCB_AIRCR_PRIS_Msk   (1UL << SCB_AIRCR_PRIS_Pos)"
SCB AIRCR: PRIS Mask 
.SS "#define SCB_AIRCR_PRIS_Pos   14U"
SCB AIRCR: PRIS Position 
.SS "#define SCB_AIRCR_PRIS_Pos   14U"
SCB AIRCR: PRIS Position 
.SS "#define SCB_AIRCR_SYSRESETREQ_Msk   (1UL << SCB_AIRCR_SYSRESETREQ_Pos)"
SCB AIRCR: SYSRESETREQ Mask 
.SS "#define SCB_AIRCR_SYSRESETREQ_Msk   (1UL << SCB_AIRCR_SYSRESETREQ_Pos)"
SCB AIRCR: SYSRESETREQ Mask 
.SS "#define SCB_AIRCR_SYSRESETREQ_Msk   (1UL << SCB_AIRCR_SYSRESETREQ_Pos)"
SCB AIRCR: SYSRESETREQ Mask 
.SS "#define SCB_AIRCR_SYSRESETREQ_Pos   2U"
SCB AIRCR: SYSRESETREQ Position 
.SS "#define SCB_AIRCR_SYSRESETREQ_Pos   2U"
SCB AIRCR: SYSRESETREQ Position 
.SS "#define SCB_AIRCR_SYSRESETREQ_Pos   2U"
SCB AIRCR: SYSRESETREQ Position 
.SS "#define SCB_AIRCR_SYSRESETREQS_Msk   (1UL << SCB_AIRCR_SYSRESETREQS_Pos)"
SCB AIRCR: SYSRESETREQS Mask 
.SS "#define SCB_AIRCR_SYSRESETREQS_Msk   (1UL << SCB_AIRCR_SYSRESETREQS_Pos)"
SCB AIRCR: SYSRESETREQS Mask 
.SS "#define SCB_AIRCR_SYSRESETREQS_Pos   3U"
SCB AIRCR: SYSRESETREQS Position 
.SS "#define SCB_AIRCR_SYSRESETREQS_Pos   3U"
SCB AIRCR: SYSRESETREQS Position 
.SS "#define SCB_AIRCR_VECTCLRACTIVE_Msk   (1UL << SCB_AIRCR_VECTCLRACTIVE_Pos)"
SCB AIRCR: VECTCLRACTIVE Mask 
.SS "#define SCB_AIRCR_VECTCLRACTIVE_Msk   (1UL << SCB_AIRCR_VECTCLRACTIVE_Pos)"
SCB AIRCR: VECTCLRACTIVE Mask 
.SS "#define SCB_AIRCR_VECTCLRACTIVE_Msk   (1UL << SCB_AIRCR_VECTCLRACTIVE_Pos)"
SCB AIRCR: VECTCLRACTIVE Mask 
.SS "#define SCB_AIRCR_VECTCLRACTIVE_Pos   1U"
SCB AIRCR: VECTCLRACTIVE Position 
.SS "#define SCB_AIRCR_VECTCLRACTIVE_Pos   1U"
SCB AIRCR: VECTCLRACTIVE Position 
.SS "#define SCB_AIRCR_VECTCLRACTIVE_Pos   1U"
SCB AIRCR: VECTCLRACTIVE Position 
.SS "#define SCB_AIRCR_VECTKEY_Msk   (0xFFFFUL << SCB_AIRCR_VECTKEY_Pos)"
SCB AIRCR: VECTKEY Mask 
.SS "#define SCB_AIRCR_VECTKEY_Msk   (0xFFFFUL << SCB_AIRCR_VECTKEY_Pos)"
SCB AIRCR: VECTKEY Mask 
.SS "#define SCB_AIRCR_VECTKEY_Msk   (0xFFFFUL << SCB_AIRCR_VECTKEY_Pos)"
SCB AIRCR: VECTKEY Mask 
.SS "#define SCB_AIRCR_VECTKEY_Pos   16U"
SCB AIRCR: VECTKEY Position 
.SS "#define SCB_AIRCR_VECTKEY_Pos   16U"
SCB AIRCR: VECTKEY Position 
.SS "#define SCB_AIRCR_VECTKEY_Pos   16U"
SCB AIRCR: VECTKEY Position 
.SS "#define SCB_AIRCR_VECTKEYSTAT_Msk   (0xFFFFUL << SCB_AIRCR_VECTKEYSTAT_Pos)"
SCB AIRCR: VECTKEYSTAT Mask 
.SS "#define SCB_AIRCR_VECTKEYSTAT_Msk   (0xFFFFUL << SCB_AIRCR_VECTKEYSTAT_Pos)"
SCB AIRCR: VECTKEYSTAT Mask 
.SS "#define SCB_AIRCR_VECTKEYSTAT_Msk   (0xFFFFUL << SCB_AIRCR_VECTKEYSTAT_Pos)"
SCB AIRCR: VECTKEYSTAT Mask 
.SS "#define SCB_AIRCR_VECTKEYSTAT_Pos   16U"
SCB AIRCR: VECTKEYSTAT Position 
.SS "#define SCB_AIRCR_VECTKEYSTAT_Pos   16U"
SCB AIRCR: VECTKEYSTAT Position 
.SS "#define SCB_AIRCR_VECTKEYSTAT_Pos   16U"
SCB AIRCR: VECTKEYSTAT Position 
.SS "#define SCB_AIRCR_VECTRESET_Msk   (1UL /*<< SCB_AIRCR_VECTRESET_Pos*/)"
SCB AIRCR: VECTRESET Mask 
.SS "#define SCB_AIRCR_VECTRESET_Pos   0U"
SCB AIRCR: VECTRESET Position 
.SS "#define SCB_CACR_ECCEN_Msk   (1UL << SCB_CACR_ECCEN_Pos)"
SCB CACR: ECCEN Mask 
.SS "#define SCB_CACR_ECCEN_Pos   1U"
SCB CACR: ECCEN Position 
.SS "#define SCB_CACR_FORCEWT_Msk   (1UL << SCB_CACR_FORCEWT_Pos)"
SCB CACR: FORCEWT Mask 
.SS "#define SCB_CACR_FORCEWT_Pos   2U"
SCB CACR: FORCEWT Position 
.SS "#define SCB_CACR_SIWT_Msk   (1UL /*<< SCB_CACR_SIWT_Pos*/)"
SCB CACR: SIWT Mask 
.SS "#define SCB_CACR_SIWT_Pos   0U"
SCB CACR: SIWT Position 
.SS "#define SCB_CCR_BFHFNMIGN_Msk   (1UL << SCB_CCR_BFHFNMIGN_Pos)"
SCB CCR: BFHFNMIGN Mask 
.SS "#define SCB_CCR_BFHFNMIGN_Msk   (1UL << SCB_CCR_BFHFNMIGN_Pos)"
SCB CCR: BFHFNMIGN Mask 
.SS "#define SCB_CCR_BFHFNMIGN_Msk   (1UL << SCB_CCR_BFHFNMIGN_Pos)"
SCB CCR: BFHFNMIGN Mask 
.SS "#define SCB_CCR_BFHFNMIGN_Pos   8U"
SCB CCR: BFHFNMIGN Position 
.SS "#define SCB_CCR_BFHFNMIGN_Pos   8U"
SCB CCR: BFHFNMIGN Position 
.SS "#define SCB_CCR_BFHFNMIGN_Pos   8U"
SCB CCR: BFHFNMIGN Position 
.SS "#define SCB_CCR_BP_Msk   (1UL << SCB_CCR_BP_Pos)"
SCB CCR: BP Mask 
.SS "#define SCB_CCR_BP_Msk   (1UL << SCB_CCR_BP_Pos)"
SCB CCR: BP Mask 
.SS "#define SCB_CCR_BP_Pos   18U"
SCB CCR: BP Position 
.SS "#define SCB_CCR_BP_Pos   18U"
SCB CCR: BP Position 
.SS "#define SCB_CCR_DC_Msk   (1UL << SCB_CCR_DC_Pos)"
SCB CCR: DC Mask 
.SS "#define SCB_CCR_DC_Msk   (1UL << SCB_CCR_DC_Pos)"
SCB CCR: DC Mask 
.SS "#define SCB_CCR_DC_Pos   16U"
SCB CCR: DC Position 
.SS "#define SCB_CCR_DC_Pos   16U"
SCB CCR: DC Position 
.SS "#define SCB_CCR_DIV_0_TRP_Msk   (1UL << SCB_CCR_DIV_0_TRP_Pos)"
SCB CCR: DIV_0_TRP Mask 
.SS "#define SCB_CCR_DIV_0_TRP_Msk   (1UL << SCB_CCR_DIV_0_TRP_Pos)"
SCB CCR: DIV_0_TRP Mask 
.SS "#define SCB_CCR_DIV_0_TRP_Msk   (1UL << SCB_CCR_DIV_0_TRP_Pos)"
SCB CCR: DIV_0_TRP Mask 
.SS "#define SCB_CCR_DIV_0_TRP_Pos   4U"
SCB CCR: DIV_0_TRP Position 
.SS "#define SCB_CCR_DIV_0_TRP_Pos   4U"
SCB CCR: DIV_0_TRP Position 
.SS "#define SCB_CCR_DIV_0_TRP_Pos   4U"
SCB CCR: DIV_0_TRP Position 
.SS "#define SCB_CCR_IC_Msk   (1UL << SCB_CCR_IC_Pos)"
SCB CCR: IC Mask 
.SS "#define SCB_CCR_IC_Msk   (1UL << SCB_CCR_IC_Pos)"
SCB CCR: IC Mask 
.SS "#define SCB_CCR_IC_Pos   17U"
SCB CCR: IC Position 
.SS "#define SCB_CCR_IC_Pos   17U"
SCB CCR: IC Position 
.SS "#define SCB_CCR_NONBASETHRDENA_Msk   (1UL /*<< SCB_CCR_NONBASETHRDENA_Pos*/)"
SCB CCR: NONBASETHRDENA Mask 
.SS "#define SCB_CCR_NONBASETHRDENA_Pos   0U"
SCB CCR: NONBASETHRDENA Position 
.SS "#define SCB_CCR_STKALIGN_Msk   (1UL << SCB_CCR_STKALIGN_Pos)"
SCB CCR: STKALIGN Mask 
.SS "#define SCB_CCR_STKALIGN_Pos   9U"
SCB CCR: STKALIGN Position 
.SS "#define SCB_CCR_STKOFHFNMIGN_Msk   (1UL << SCB_CCR_STKOFHFNMIGN_Pos)"
SCB CCR: STKOFHFNMIGN Mask 
.SS "#define SCB_CCR_STKOFHFNMIGN_Msk   (1UL << SCB_CCR_STKOFHFNMIGN_Pos)"
SCB CCR: STKOFHFNMIGN Mask 
.SS "#define SCB_CCR_STKOFHFNMIGN_Pos   10U"
SCB CCR: STKOFHFNMIGN Position 
.SS "#define SCB_CCR_STKOFHFNMIGN_Pos   10U"
SCB CCR: STKOFHFNMIGN Position 
.SS "#define SCB_CCR_UNALIGN_TRP_Msk   (1UL << SCB_CCR_UNALIGN_TRP_Pos)"
SCB CCR: UNALIGN_TRP Mask 
.SS "#define SCB_CCR_UNALIGN_TRP_Msk   (1UL << SCB_CCR_UNALIGN_TRP_Pos)"
SCB CCR: UNALIGN_TRP Mask 
.SS "#define SCB_CCR_UNALIGN_TRP_Msk   (1UL << SCB_CCR_UNALIGN_TRP_Pos)"
SCB CCR: UNALIGN_TRP Mask 
.SS "#define SCB_CCR_UNALIGN_TRP_Pos   3U"
SCB CCR: UNALIGN_TRP Position 
.SS "#define SCB_CCR_UNALIGN_TRP_Pos   3U"
SCB CCR: UNALIGN_TRP Position 
.SS "#define SCB_CCR_UNALIGN_TRP_Pos   3U"
SCB CCR: UNALIGN_TRP Position 
.SS "#define SCB_CCR_USERSETMPEND_Msk   (1UL << SCB_CCR_USERSETMPEND_Pos)"
SCB CCR: USERSETMPEND Mask 
.SS "#define SCB_CCR_USERSETMPEND_Msk   (1UL << SCB_CCR_USERSETMPEND_Pos)"
SCB CCR: USERSETMPEND Mask 
.SS "#define SCB_CCR_USERSETMPEND_Msk   (1UL << SCB_CCR_USERSETMPEND_Pos)"
SCB CCR: USERSETMPEND Mask 
.SS "#define SCB_CCR_USERSETMPEND_Pos   1U"
SCB CCR: USERSETMPEND Position 
.SS "#define SCB_CCR_USERSETMPEND_Pos   1U"
SCB CCR: USERSETMPEND Position 
.SS "#define SCB_CCR_USERSETMPEND_Pos   1U"
SCB CCR: USERSETMPEND Position 
.SS "#define SCB_CCSIDR_ASSOCIATIVITY_Msk   (0x3FFUL << SCB_CCSIDR_ASSOCIATIVITY_Pos)"
SCB CCSIDR: Associativity Mask 
.SS "#define SCB_CCSIDR_ASSOCIATIVITY_Pos   3U"
SCB CCSIDR: Associativity Position 
.SS "#define SCB_CCSIDR_LINESIZE_Msk   (7UL /*<< SCB_CCSIDR_LINESIZE_Pos*/)"
SCB CCSIDR: LineSize Mask 
.SS "#define SCB_CCSIDR_LINESIZE_Pos   0U"
SCB CCSIDR: LineSize Position 
.SS "#define SCB_CCSIDR_NUMSETS_Msk   (0x7FFFUL << SCB_CCSIDR_NUMSETS_Pos)"
SCB CCSIDR: NumSets Mask 
.SS "#define SCB_CCSIDR_NUMSETS_Pos   13U"
SCB CCSIDR: NumSets Position 
.SS "#define SCB_CCSIDR_RA_Msk   (1UL << SCB_CCSIDR_RA_Pos)"
SCB CCSIDR: RA Mask 
.SS "#define SCB_CCSIDR_RA_Pos   29U"
SCB CCSIDR: RA Position 
.SS "#define SCB_CCSIDR_WA_Msk   (1UL << SCB_CCSIDR_WA_Pos)"
SCB CCSIDR: WA Mask 
.SS "#define SCB_CCSIDR_WA_Pos   28U"
SCB CCSIDR: WA Position 
.SS "#define SCB_CCSIDR_WB_Msk   (1UL << SCB_CCSIDR_WB_Pos)"
SCB CCSIDR: WB Mask 
.SS "#define SCB_CCSIDR_WB_Pos   30U"
SCB CCSIDR: WB Position 
.SS "#define SCB_CCSIDR_WT_Msk   (1UL << SCB_CCSIDR_WT_Pos)"
SCB CCSIDR: WT Mask 
.SS "#define SCB_CCSIDR_WT_Pos   31U"
SCB CCSIDR: WT Position 
.SS "#define SCB_CFSR_BFARVALID_Msk   (1UL << SCB_CFSR_BFARVALID_Pos)"
SCB CFSR (BFSR): BFARVALID Mask 
.SS "#define SCB_CFSR_BFARVALID_Msk   (1UL << SCB_CFSR_BFARVALID_Pos)"
SCB CFSR (BFSR): BFARVALID Mask 
.SS "#define SCB_CFSR_BFARVALID_Pos   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 7U)"
SCB CFSR (BFSR): BFARVALID Position 
.SS "#define SCB_CFSR_BFARVALID_Pos   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 7U)"
SCB CFSR (BFSR): BFARVALID Position 
.SS "#define SCB_CFSR_BUSFAULTSR_Msk   (0xFFUL << SCB_CFSR_BUSFAULTSR_Pos)"
SCB CFSR: Bus Fault Status Register Mask 
.SS "#define SCB_CFSR_BUSFAULTSR_Msk   (0xFFUL << SCB_CFSR_BUSFAULTSR_Pos)"
SCB CFSR: Bus Fault Status Register Mask 
.SS "#define SCB_CFSR_BUSFAULTSR_Pos   8U"
SCB CFSR: Bus Fault Status Register Position 
.SS "#define SCB_CFSR_BUSFAULTSR_Pos   8U"
SCB CFSR: Bus Fault Status Register Position 
.SS "#define SCB_CFSR_DACCVIOL_Msk   (1UL << SCB_CFSR_DACCVIOL_Pos)"
SCB CFSR (MMFSR): DACCVIOL Mask 
.SS "#define SCB_CFSR_DACCVIOL_Msk   (1UL << SCB_CFSR_DACCVIOL_Pos)"
SCB CFSR (MMFSR): DACCVIOL Mask 
.SS "#define SCB_CFSR_DACCVIOL_Pos   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 1U)"
SCB CFSR (MMFSR): DACCVIOL Position 
.SS "#define SCB_CFSR_DACCVIOL_Pos   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 1U)"
SCB CFSR (MMFSR): DACCVIOL Position 
.SS "#define SCB_CFSR_DIVBYZERO_Msk   (1UL << SCB_CFSR_DIVBYZERO_Pos)"
SCB CFSR (UFSR): DIVBYZERO Mask 
.SS "#define SCB_CFSR_DIVBYZERO_Msk   (1UL << SCB_CFSR_DIVBYZERO_Pos)"
SCB CFSR (UFSR): DIVBYZERO Mask 
.SS "#define SCB_CFSR_DIVBYZERO_Pos   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 9U)"
SCB CFSR (UFSR): DIVBYZERO Position 
.SS "#define SCB_CFSR_DIVBYZERO_Pos   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 9U)"
SCB CFSR (UFSR): DIVBYZERO Position 
.SS "#define SCB_CFSR_IACCVIOL_Msk   (1UL /*<< SCB_CFSR_IACCVIOL_Pos*/)"
SCB CFSR (MMFSR): IACCVIOL Mask 
.SS "#define SCB_CFSR_IACCVIOL_Msk   (1UL /*<< SCB_CFSR_IACCVIOL_Pos*/)"
SCB CFSR (MMFSR): IACCVIOL Mask 
.SS "#define SCB_CFSR_IACCVIOL_Pos   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 0U)"
SCB CFSR (MMFSR): IACCVIOL Position 
.SS "#define SCB_CFSR_IACCVIOL_Pos   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 0U)"
SCB CFSR (MMFSR): IACCVIOL Position 
.SS "#define SCB_CFSR_IBUSERR_Msk   (1UL << SCB_CFSR_IBUSERR_Pos)"
SCB CFSR (BFSR): IBUSERR Mask 
.SS "#define SCB_CFSR_IBUSERR_Msk   (1UL << SCB_CFSR_IBUSERR_Pos)"
SCB CFSR (BFSR): IBUSERR Mask 
.SS "#define SCB_CFSR_IBUSERR_Pos   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 0U)"
SCB CFSR (BFSR): IBUSERR Position 
.SS "#define SCB_CFSR_IBUSERR_Pos   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 0U)"
SCB CFSR (BFSR): IBUSERR Position 
.SS "#define SCB_CFSR_IMPRECISERR_Msk   (1UL << SCB_CFSR_IMPRECISERR_Pos)"
SCB CFSR (BFSR): IMPRECISERR Mask 
.SS "#define SCB_CFSR_IMPRECISERR_Msk   (1UL << SCB_CFSR_IMPRECISERR_Pos)"
SCB CFSR (BFSR): IMPRECISERR Mask 
.SS "#define SCB_CFSR_IMPRECISERR_Pos   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 2U)"
SCB CFSR (BFSR): IMPRECISERR Position 
.SS "#define SCB_CFSR_IMPRECISERR_Pos   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 2U)"
SCB CFSR (BFSR): IMPRECISERR Position 
.SS "#define SCB_CFSR_INVPC_Msk   (1UL << SCB_CFSR_INVPC_Pos)"
SCB CFSR (UFSR): INVPC Mask 
.SS "#define SCB_CFSR_INVPC_Msk   (1UL << SCB_CFSR_INVPC_Pos)"
SCB CFSR (UFSR): INVPC Mask 
.SS "#define SCB_CFSR_INVPC_Pos   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 2U)"
SCB CFSR (UFSR): INVPC Position 
.SS "#define SCB_CFSR_INVPC_Pos   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 2U)"
SCB CFSR (UFSR): INVPC Position 
.SS "#define SCB_CFSR_INVSTATE_Msk   (1UL << SCB_CFSR_INVSTATE_Pos)"
SCB CFSR (UFSR): INVSTATE Mask 
.SS "#define SCB_CFSR_INVSTATE_Msk   (1UL << SCB_CFSR_INVSTATE_Pos)"
SCB CFSR (UFSR): INVSTATE Mask 
.SS "#define SCB_CFSR_INVSTATE_Pos   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 1U)"
SCB CFSR (UFSR): INVSTATE Position 
.SS "#define SCB_CFSR_INVSTATE_Pos   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 1U)"
SCB CFSR (UFSR): INVSTATE Position 
.SS "#define SCB_CFSR_LSPERR_Msk   (1UL << SCB_CFSR_LSPERR_Pos)"
SCB CFSR (BFSR): LSPERR Mask 
.SS "#define SCB_CFSR_LSPERR_Msk   (1UL << SCB_CFSR_LSPERR_Pos)"
SCB CFSR (BFSR): LSPERR Mask 
.SS "#define SCB_CFSR_LSPERR_Pos   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 5U)"
SCB CFSR (BFSR): LSPERR Position 
.SS "#define SCB_CFSR_LSPERR_Pos   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 5U)"
SCB CFSR (BFSR): LSPERR Position 
.SS "#define SCB_CFSR_MEMFAULTSR_Msk   (0xFFUL /*<< SCB_CFSR_MEMFAULTSR_Pos*/)"
SCB CFSR: Memory Manage Fault Status Register Mask 
.SS "#define SCB_CFSR_MEMFAULTSR_Msk   (0xFFUL /*<< SCB_CFSR_MEMFAULTSR_Pos*/)"
SCB CFSR: Memory Manage Fault Status Register Mask 
.SS "#define SCB_CFSR_MEMFAULTSR_Pos   0U"
SCB CFSR: Memory Manage Fault Status Register Position 
.SS "#define SCB_CFSR_MEMFAULTSR_Pos   0U"
SCB CFSR: Memory Manage Fault Status Register Position 
.SS "#define SCB_CFSR_MLSPERR_Msk   (1UL << SCB_CFSR_MLSPERR_Pos)"
SCB CFSR (MMFSR): MLSPERR Mask 
.SS "#define SCB_CFSR_MLSPERR_Msk   (1UL << SCB_CFSR_MLSPERR_Pos)"
SCB CFSR (MMFSR): MLSPERR Mask 
.SS "#define SCB_CFSR_MLSPERR_Pos   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 5U)"
SCB CFSR (MMFSR): MLSPERR Position 
.SS "#define SCB_CFSR_MLSPERR_Pos   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 5U)"
SCB CFSR (MMFSR): MLSPERR Position 
.SS "#define SCB_CFSR_MMARVALID_Msk   (1UL << SCB_CFSR_MMARVALID_Pos)"
SCB CFSR (MMFSR): MMARVALID Mask 
.SS "#define SCB_CFSR_MMARVALID_Msk   (1UL << SCB_CFSR_MMARVALID_Pos)"
SCB CFSR (MMFSR): MMARVALID Mask 
.SS "#define SCB_CFSR_MMARVALID_Pos   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 7U)"
SCB CFSR (MMFSR): MMARVALID Position 
.SS "#define SCB_CFSR_MMARVALID_Pos   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 7U)"
SCB CFSR (MMFSR): MMARVALID Position 
.SS "#define SCB_CFSR_MSTKERR_Msk   (1UL << SCB_CFSR_MSTKERR_Pos)"
SCB CFSR (MMFSR): MSTKERR Mask 
.SS "#define SCB_CFSR_MSTKERR_Msk   (1UL << SCB_CFSR_MSTKERR_Pos)"
SCB CFSR (MMFSR): MSTKERR Mask 
.SS "#define SCB_CFSR_MSTKERR_Pos   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 4U)"
SCB CFSR (MMFSR): MSTKERR Position 
.SS "#define SCB_CFSR_MSTKERR_Pos   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 4U)"
SCB CFSR (MMFSR): MSTKERR Position 
.SS "#define SCB_CFSR_MUNSTKERR_Msk   (1UL << SCB_CFSR_MUNSTKERR_Pos)"
SCB CFSR (MMFSR): MUNSTKERR Mask 
.SS "#define SCB_CFSR_MUNSTKERR_Msk   (1UL << SCB_CFSR_MUNSTKERR_Pos)"
SCB CFSR (MMFSR): MUNSTKERR Mask 
.SS "#define SCB_CFSR_MUNSTKERR_Pos   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 3U)"
SCB CFSR (MMFSR): MUNSTKERR Position 
.SS "#define SCB_CFSR_MUNSTKERR_Pos   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 3U)"
SCB CFSR (MMFSR): MUNSTKERR Position 
.SS "#define SCB_CFSR_NOCP_Msk   (1UL << SCB_CFSR_NOCP_Pos)"
SCB CFSR (UFSR): NOCP Mask 
.SS "#define SCB_CFSR_NOCP_Msk   (1UL << SCB_CFSR_NOCP_Pos)"
SCB CFSR (UFSR): NOCP Mask 
.SS "#define SCB_CFSR_NOCP_Pos   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 3U)"
SCB CFSR (UFSR): NOCP Position 
.SS "#define SCB_CFSR_NOCP_Pos   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 3U)"
SCB CFSR (UFSR): NOCP Position 
.SS "#define SCB_CFSR_PRECISERR_Msk   (1UL << SCB_CFSR_PRECISERR_Pos)"
SCB CFSR (BFSR): PRECISERR Mask 
.SS "#define SCB_CFSR_PRECISERR_Msk   (1UL << SCB_CFSR_PRECISERR_Pos)"
SCB CFSR (BFSR): PRECISERR Mask 
.SS "#define SCB_CFSR_PRECISERR_Pos   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 1U)"
SCB CFSR (BFSR): PRECISERR Position 
.SS "#define SCB_CFSR_PRECISERR_Pos   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 1U)"
SCB CFSR (BFSR): PRECISERR Position 
.SS "#define SCB_CFSR_STKERR_Msk   (1UL << SCB_CFSR_STKERR_Pos)"
SCB CFSR (BFSR): STKERR Mask 
.SS "#define SCB_CFSR_STKERR_Msk   (1UL << SCB_CFSR_STKERR_Pos)"
SCB CFSR (BFSR): STKERR Mask 
.SS "#define SCB_CFSR_STKERR_Pos   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 4U)"
SCB CFSR (BFSR): STKERR Position 
.SS "#define SCB_CFSR_STKERR_Pos   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 4U)"
SCB CFSR (BFSR): STKERR Position 
.SS "#define SCB_CFSR_STKOF_Msk   (1UL << SCB_CFSR_STKOF_Pos)"
SCB CFSR (UFSR): STKOF Mask 
.SS "#define SCB_CFSR_STKOF_Pos   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 4U)"
SCB CFSR (UFSR): STKOF Position 
.SS "#define SCB_CFSR_UNALIGNED_Msk   (1UL << SCB_CFSR_UNALIGNED_Pos)"
SCB CFSR (UFSR): UNALIGNED Mask 
.SS "#define SCB_CFSR_UNALIGNED_Msk   (1UL << SCB_CFSR_UNALIGNED_Pos)"
SCB CFSR (UFSR): UNALIGNED Mask 
.SS "#define SCB_CFSR_UNALIGNED_Pos   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 8U)"
SCB CFSR (UFSR): UNALIGNED Position 
.SS "#define SCB_CFSR_UNALIGNED_Pos   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 8U)"
SCB CFSR (UFSR): UNALIGNED Position 
.SS "#define SCB_CFSR_UNDEFINSTR_Msk   (1UL << SCB_CFSR_UNDEFINSTR_Pos)"
SCB CFSR (UFSR): UNDEFINSTR Mask 
.SS "#define SCB_CFSR_UNDEFINSTR_Msk   (1UL << SCB_CFSR_UNDEFINSTR_Pos)"
SCB CFSR (UFSR): UNDEFINSTR Mask 
.SS "#define SCB_CFSR_UNDEFINSTR_Pos   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 0U)"
SCB CFSR (UFSR): UNDEFINSTR Position 
.SS "#define SCB_CFSR_UNDEFINSTR_Pos   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 0U)"
SCB CFSR (UFSR): UNDEFINSTR Position 
.SS "#define SCB_CFSR_UNSTKERR_Msk   (1UL << SCB_CFSR_UNSTKERR_Pos)"
SCB CFSR (BFSR): UNSTKERR Mask 
.SS "#define SCB_CFSR_UNSTKERR_Msk   (1UL << SCB_CFSR_UNSTKERR_Pos)"
SCB CFSR (BFSR): UNSTKERR Mask 
.SS "#define SCB_CFSR_UNSTKERR_Pos   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 3U)"
SCB CFSR (BFSR): UNSTKERR Position 
.SS "#define SCB_CFSR_UNSTKERR_Pos   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 3U)"
SCB CFSR (BFSR): UNSTKERR Position 
.SS "#define SCB_CFSR_USGFAULTSR_Msk   (0xFFFFUL << SCB_CFSR_USGFAULTSR_Pos)"
SCB CFSR: Usage Fault Status Register Mask 
.SS "#define SCB_CFSR_USGFAULTSR_Msk   (0xFFFFUL << SCB_CFSR_USGFAULTSR_Pos)"
SCB CFSR: Usage Fault Status Register Mask 
.SS "#define SCB_CFSR_USGFAULTSR_Pos   16U"
SCB CFSR: Usage Fault Status Register Position 
.SS "#define SCB_CFSR_USGFAULTSR_Pos   16U"
SCB CFSR: Usage Fault Status Register Position 
.SS "#define SCB_CLIDR_LOC_Msk   (7UL << SCB_CLIDR_LOC_Pos)"
SCB CLIDR: LoC Mask 
.SS "#define SCB_CLIDR_LOC_Pos   24U"
SCB CLIDR: LoC Position 
.SS "#define SCB_CLIDR_LOUU_Msk   (7UL << SCB_CLIDR_LOUU_Pos)"
SCB CLIDR: LoUU Mask 
.SS "#define SCB_CLIDR_LOUU_Pos   27U"
SCB CLIDR: LoUU Position 
.SS "#define SCB_CPUID_ARCHITECTURE_Msk   (0xFUL << SCB_CPUID_ARCHITECTURE_Pos)"
SCB CPUID: ARCHITECTURE Mask 
.SS "#define SCB_CPUID_ARCHITECTURE_Msk   (0xFUL << SCB_CPUID_ARCHITECTURE_Pos)"
SCB CPUID: ARCHITECTURE Mask 
.SS "#define SCB_CPUID_ARCHITECTURE_Msk   (0xFUL << SCB_CPUID_ARCHITECTURE_Pos)"
SCB CPUID: ARCHITECTURE Mask 
.SS "#define SCB_CPUID_ARCHITECTURE_Pos   16U"
SCB CPUID: ARCHITECTURE Position 
.SS "#define SCB_CPUID_ARCHITECTURE_Pos   16U"
SCB CPUID: ARCHITECTURE Position 
.SS "#define SCB_CPUID_ARCHITECTURE_Pos   16U"
SCB CPUID: ARCHITECTURE Position 
.SS "#define SCB_CPUID_IMPLEMENTER_Msk   (0xFFUL << SCB_CPUID_IMPLEMENTER_Pos)"
SCB CPUID: IMPLEMENTER Mask 
.SS "#define SCB_CPUID_IMPLEMENTER_Msk   (0xFFUL << SCB_CPUID_IMPLEMENTER_Pos)"
SCB CPUID: IMPLEMENTER Mask 
.SS "#define SCB_CPUID_IMPLEMENTER_Msk   (0xFFUL << SCB_CPUID_IMPLEMENTER_Pos)"
SCB CPUID: IMPLEMENTER Mask 
.SS "#define SCB_CPUID_IMPLEMENTER_Pos   24U"
SCB CPUID: IMPLEMENTER Position 
.SS "#define SCB_CPUID_IMPLEMENTER_Pos   24U"
SCB CPUID: IMPLEMENTER Position 
.SS "#define SCB_CPUID_IMPLEMENTER_Pos   24U"
SCB CPUID: IMPLEMENTER Position 
.SS "#define SCB_CPUID_PARTNO_Msk   (0xFFFUL << SCB_CPUID_PARTNO_Pos)"
SCB CPUID: PARTNO Mask 
.SS "#define SCB_CPUID_PARTNO_Msk   (0xFFFUL << SCB_CPUID_PARTNO_Pos)"
SCB CPUID: PARTNO Mask 
.SS "#define SCB_CPUID_PARTNO_Msk   (0xFFFUL << SCB_CPUID_PARTNO_Pos)"
SCB CPUID: PARTNO Mask 
.SS "#define SCB_CPUID_PARTNO_Pos   4U"
SCB CPUID: PARTNO Position 
.SS "#define SCB_CPUID_PARTNO_Pos   4U"
SCB CPUID: PARTNO Position 
.SS "#define SCB_CPUID_PARTNO_Pos   4U"
SCB CPUID: PARTNO Position 
.SS "#define SCB_CPUID_REVISION_Msk   (0xFUL /*<< SCB_CPUID_REVISION_Pos*/)"
SCB CPUID: REVISION Mask 
.SS "#define SCB_CPUID_REVISION_Msk   (0xFUL /*<< SCB_CPUID_REVISION_Pos*/)"
SCB CPUID: REVISION Mask 
.SS "#define SCB_CPUID_REVISION_Msk   (0xFUL /*<< SCB_CPUID_REVISION_Pos*/)"
SCB CPUID: REVISION Mask 
.SS "#define SCB_CPUID_REVISION_Pos   0U"
SCB CPUID: REVISION Position 
.SS "#define SCB_CPUID_REVISION_Pos   0U"
SCB CPUID: REVISION Position 
.SS "#define SCB_CPUID_REVISION_Pos   0U"
SCB CPUID: REVISION Position 
.SS "#define SCB_CPUID_VARIANT_Msk   (0xFUL << SCB_CPUID_VARIANT_Pos)"
SCB CPUID: VARIANT Mask 
.SS "#define SCB_CPUID_VARIANT_Msk   (0xFUL << SCB_CPUID_VARIANT_Pos)"
SCB CPUID: VARIANT Mask 
.SS "#define SCB_CPUID_VARIANT_Msk   (0xFUL << SCB_CPUID_VARIANT_Pos)"
SCB CPUID: VARIANT Mask 
.SS "#define SCB_CPUID_VARIANT_Pos   20U"
SCB CPUID: VARIANT Position 
.SS "#define SCB_CPUID_VARIANT_Pos   20U"
SCB CPUID: VARIANT Position 
.SS "#define SCB_CPUID_VARIANT_Pos   20U"
SCB CPUID: VARIANT Position 
.SS "#define SCB_CSSELR_IND_Msk   (1UL /*<< SCB_CSSELR_IND_Pos*/)"
SCB CSSELR: InD Mask 
.SS "#define SCB_CSSELR_IND_Pos   0U"
SCB CSSELR: InD Position 
.SS "#define SCB_CSSELR_LEVEL_Msk   (7UL << SCB_CSSELR_LEVEL_Pos)"
SCB CSSELR: Level Mask 
.SS "#define SCB_CSSELR_LEVEL_Pos   1U"
SCB CSSELR: Level Position 
.SS "#define SCB_CTR_CWG_Msk   (0xFUL << SCB_CTR_CWG_Pos)"
SCB CTR: CWG Mask 
.SS "#define SCB_CTR_CWG_Pos   24U"
SCB CTR: CWG Position 
.SS "#define SCB_CTR_DMINLINE_Msk   (0xFUL << SCB_CTR_DMINLINE_Pos)"
SCB CTR: DminLine Mask 
.SS "#define SCB_CTR_DMINLINE_Pos   16U"
SCB CTR: DminLine Position 
.SS "#define SCB_CTR_ERG_Msk   (0xFUL << SCB_CTR_ERG_Pos)"
SCB CTR: ERG Mask 
.SS "#define SCB_CTR_ERG_Pos   20U"
SCB CTR: ERG Position 
.SS "#define SCB_CTR_FORMAT_Msk   (7UL << SCB_CTR_FORMAT_Pos)"
SCB CTR: Format Mask 
.SS "#define SCB_CTR_FORMAT_Pos   29U"
SCB CTR: Format Position 
.SS "#define SCB_CTR_IMINLINE_Msk   (0xFUL /*<< SCB_CTR_IMINLINE_Pos*/)"
SCB CTR: ImInLine Mask 
.SS "#define SCB_CTR_IMINLINE_Pos   0U"
SCB CTR: ImInLine Position 
.SS "#define SCB_DCCISW_SET_Msk   (0x1FFUL << SCB_DCCISW_SET_Pos)"
SCB DCCISW: Set Mask 
.SS "#define SCB_DCCISW_SET_Pos   5U"
SCB DCCISW: Set Position 
.SS "#define SCB_DCCISW_WAY_Msk   (3UL << SCB_DCCISW_WAY_Pos)"
SCB DCCISW: Way Mask 
.SS "#define SCB_DCCISW_WAY_Pos   30U"
SCB DCCISW: Way Position 
.SS "#define SCB_DCCSW_SET_Msk   (0x1FFUL << SCB_DCCSW_SET_Pos)"
SCB DCCSW: Set Mask 
.SS "#define SCB_DCCSW_SET_Pos   5U"
SCB DCCSW: Set Position 
.SS "#define SCB_DCCSW_WAY_Msk   (3UL << SCB_DCCSW_WAY_Pos)"
SCB DCCSW: Way Mask 
.SS "#define SCB_DCCSW_WAY_Pos   30U"
SCB DCCSW: Way Position 
.SS "#define SCB_DCISW_SET_Msk   (0x1FFUL << SCB_DCISW_SET_Pos)"
SCB DCISW: Set Mask 
.SS "#define SCB_DCISW_SET_Pos   5U"
SCB DCISW: Set Position 
.SS "#define SCB_DCISW_WAY_Msk   (3UL << SCB_DCISW_WAY_Pos)"
SCB DCISW: Way Mask 
.SS "#define SCB_DCISW_WAY_Pos   30U"
SCB DCISW: Way Position 
.SS "#define SCB_DFSR_BKPT_Msk   (1UL << SCB_DFSR_BKPT_Pos)"
SCB DFSR: BKPT Mask 
.SS "#define SCB_DFSR_BKPT_Msk   (1UL << SCB_DFSR_BKPT_Pos)"
SCB DFSR: BKPT Mask 
.SS "#define SCB_DFSR_BKPT_Pos   1U"
SCB DFSR: BKPT Position 
.SS "#define SCB_DFSR_BKPT_Pos   1U"
SCB DFSR: BKPT Position 
.SS "#define SCB_DFSR_DWTTRAP_Msk   (1UL << SCB_DFSR_DWTTRAP_Pos)"
SCB DFSR: DWTTRAP Mask 
.SS "#define SCB_DFSR_DWTTRAP_Msk   (1UL << SCB_DFSR_DWTTRAP_Pos)"
SCB DFSR: DWTTRAP Mask 
.SS "#define SCB_DFSR_DWTTRAP_Pos   2U"
SCB DFSR: DWTTRAP Position 
.SS "#define SCB_DFSR_DWTTRAP_Pos   2U"
SCB DFSR: DWTTRAP Position 
.SS "#define SCB_DFSR_EXTERNAL_Msk   (1UL << SCB_DFSR_EXTERNAL_Pos)"
SCB DFSR: EXTERNAL Mask 
.SS "#define SCB_DFSR_EXTERNAL_Msk   (1UL << SCB_DFSR_EXTERNAL_Pos)"
SCB DFSR: EXTERNAL Mask 
.SS "#define SCB_DFSR_EXTERNAL_Pos   4U"
SCB DFSR: EXTERNAL Position 
.SS "#define SCB_DFSR_EXTERNAL_Pos   4U"
SCB DFSR: EXTERNAL Position 
.SS "#define SCB_DFSR_HALTED_Msk   (1UL /*<< SCB_DFSR_HALTED_Pos*/)"
SCB DFSR: HALTED Mask 
.SS "#define SCB_DFSR_HALTED_Msk   (1UL /*<< SCB_DFSR_HALTED_Pos*/)"
SCB DFSR: HALTED Mask 
.SS "#define SCB_DFSR_HALTED_Pos   0U"
SCB DFSR: HALTED Position 
.SS "#define SCB_DFSR_HALTED_Pos   0U"
SCB DFSR: HALTED Position 
.SS "#define SCB_DFSR_VCATCH_Msk   (1UL << SCB_DFSR_VCATCH_Pos)"
SCB DFSR: VCATCH Mask 
.SS "#define SCB_DFSR_VCATCH_Msk   (1UL << SCB_DFSR_VCATCH_Pos)"
SCB DFSR: VCATCH Mask 
.SS "#define SCB_DFSR_VCATCH_Pos   3U"
SCB DFSR: VCATCH Position 
.SS "#define SCB_DFSR_VCATCH_Pos   3U"
SCB DFSR: VCATCH Position 
.SS "#define SCB_DTCMCR_EN_Msk   (1UL /*<< SCB_DTCMCR_EN_Pos*/)"
SCB DTCMCR: EN Mask 
.SS "#define SCB_DTCMCR_EN_Pos   0U"
SCB DTCMCR: EN Position 
.SS "#define SCB_DTCMCR_RETEN_Msk   (1UL << SCB_DTCMCR_RETEN_Pos)"
SCB DTCMCR: RETEN Mask 
.SS "#define SCB_DTCMCR_RETEN_Pos   2U"
SCB DTCMCR: RETEN Position 
.SS "#define SCB_DTCMCR_RMW_Msk   (1UL << SCB_DTCMCR_RMW_Pos)"
SCB DTCMCR: RMW Mask 
.SS "#define SCB_DTCMCR_RMW_Pos   1U"
SCB DTCMCR: RMW Position 
.SS "#define SCB_DTCMCR_SZ_Msk   (0xFUL << SCB_DTCMCR_SZ_Pos)"
SCB DTCMCR: SZ Mask 
.SS "#define SCB_DTCMCR_SZ_Pos   3U"
SCB DTCMCR: SZ Position 
.SS "#define SCB_HFSR_DEBUGEVT_Msk   (1UL << SCB_HFSR_DEBUGEVT_Pos)"
SCB HFSR: DEBUGEVT Mask 
.SS "#define SCB_HFSR_DEBUGEVT_Msk   (1UL << SCB_HFSR_DEBUGEVT_Pos)"
SCB HFSR: DEBUGEVT Mask 
.SS "#define SCB_HFSR_DEBUGEVT_Pos   31U"
SCB HFSR: DEBUGEVT Position 
.SS "#define SCB_HFSR_DEBUGEVT_Pos   31U"
SCB HFSR: DEBUGEVT Position 
.SS "#define SCB_HFSR_FORCED_Msk   (1UL << SCB_HFSR_FORCED_Pos)"
SCB HFSR: FORCED Mask 
.SS "#define SCB_HFSR_FORCED_Msk   (1UL << SCB_HFSR_FORCED_Pos)"
SCB HFSR: FORCED Mask 
.SS "#define SCB_HFSR_FORCED_Pos   30U"
SCB HFSR: FORCED Position 
.SS "#define SCB_HFSR_FORCED_Pos   30U"
SCB HFSR: FORCED Position 
.SS "#define SCB_HFSR_VECTTBL_Msk   (1UL << SCB_HFSR_VECTTBL_Pos)"
SCB HFSR: VECTTBL Mask 
.SS "#define SCB_HFSR_VECTTBL_Msk   (1UL << SCB_HFSR_VECTTBL_Pos)"
SCB HFSR: VECTTBL Mask 
.SS "#define SCB_HFSR_VECTTBL_Pos   1U"
SCB HFSR: VECTTBL Position 
.SS "#define SCB_HFSR_VECTTBL_Pos   1U"
SCB HFSR: VECTTBL Position 
.SS "#define SCB_ICSR_ISRPENDING_Msk   (1UL << SCB_ICSR_ISRPENDING_Pos)"
SCB ICSR: ISRPENDING Mask 
.SS "#define SCB_ICSR_ISRPENDING_Msk   (1UL << SCB_ICSR_ISRPENDING_Pos)"
SCB ICSR: ISRPENDING Mask 
.SS "#define SCB_ICSR_ISRPENDING_Msk   (1UL << SCB_ICSR_ISRPENDING_Pos)"
SCB ICSR: ISRPENDING Mask 
.SS "#define SCB_ICSR_ISRPENDING_Pos   22U"
SCB ICSR: ISRPENDING Position 
.SS "#define SCB_ICSR_ISRPENDING_Pos   22U"
SCB ICSR: ISRPENDING Position 
.SS "#define SCB_ICSR_ISRPENDING_Pos   22U"
SCB ICSR: ISRPENDING Position 
.SS "#define SCB_ICSR_ISRPREEMPT_Msk   (1UL << SCB_ICSR_ISRPREEMPT_Pos)"
SCB ICSR: ISRPREEMPT Mask 
.SS "#define SCB_ICSR_ISRPREEMPT_Msk   (1UL << SCB_ICSR_ISRPREEMPT_Pos)"
SCB ICSR: ISRPREEMPT Mask 
.SS "#define SCB_ICSR_ISRPREEMPT_Msk   (1UL << SCB_ICSR_ISRPREEMPT_Pos)"
SCB ICSR: ISRPREEMPT Mask 
.SS "#define SCB_ICSR_ISRPREEMPT_Pos   23U"
SCB ICSR: ISRPREEMPT Position 
.SS "#define SCB_ICSR_ISRPREEMPT_Pos   23U"
SCB ICSR: ISRPREEMPT Position 
.SS "#define SCB_ICSR_ISRPREEMPT_Pos   23U"
SCB ICSR: ISRPREEMPT Position 
.SS "#define SCB_ICSR_NMIPENDSET_Msk   (1UL << SCB_ICSR_NMIPENDSET_Pos)"
SCB ICSR: NMIPENDSET Mask 
.SS "#define SCB_ICSR_NMIPENDSET_Pos   31U"
SCB ICSR: NMIPENDSET Position 
.SS "#define SCB_ICSR_PENDNMICLR_Msk   (1UL << SCB_ICSR_PENDNMICLR_Pos)"
SCB ICSR: PENDNMICLR Mask 
.SS "#define SCB_ICSR_PENDNMICLR_Msk   (1UL << SCB_ICSR_PENDNMICLR_Pos)"
SCB ICSR: PENDNMICLR Mask 
.SS "#define SCB_ICSR_PENDNMICLR_Pos   30U"
SCB ICSR: PENDNMICLR Position 
.SS "#define SCB_ICSR_PENDNMICLR_Pos   30U"
SCB ICSR: PENDNMICLR Position 
.SS "#define SCB_ICSR_PENDNMISET_Msk   (1UL << SCB_ICSR_PENDNMISET_Pos)"
SCB ICSR: PENDNMISET Mask 
.SS "#define SCB_ICSR_PENDNMISET_Msk   (1UL << SCB_ICSR_PENDNMISET_Pos)"
SCB ICSR: PENDNMISET Mask 
.SS "#define SCB_ICSR_PENDNMISET_Pos   31U"
SCB ICSR: PENDNMISET Position 
.SS "#define SCB_ICSR_PENDNMISET_Pos   31U"
SCB ICSR: PENDNMISET Position 
.SS "#define SCB_ICSR_PENDSTCLR_Msk   (1UL << SCB_ICSR_PENDSTCLR_Pos)"
SCB ICSR: PENDSTCLR Mask 
.SS "#define SCB_ICSR_PENDSTCLR_Msk   (1UL << SCB_ICSR_PENDSTCLR_Pos)"
SCB ICSR: PENDSTCLR Mask 
.SS "#define SCB_ICSR_PENDSTCLR_Msk   (1UL << SCB_ICSR_PENDSTCLR_Pos)"
SCB ICSR: PENDSTCLR Mask 
.SS "#define SCB_ICSR_PENDSTCLR_Pos   25U"
SCB ICSR: PENDSTCLR Position 
.SS "#define SCB_ICSR_PENDSTCLR_Pos   25U"
SCB ICSR: PENDSTCLR Position 
.SS "#define SCB_ICSR_PENDSTCLR_Pos   25U"
SCB ICSR: PENDSTCLR Position 
.SS "#define SCB_ICSR_PENDSTSET_Msk   (1UL << SCB_ICSR_PENDSTSET_Pos)"
SCB ICSR: PENDSTSET Mask 
.SS "#define SCB_ICSR_PENDSTSET_Msk   (1UL << SCB_ICSR_PENDSTSET_Pos)"
SCB ICSR: PENDSTSET Mask 
.SS "#define SCB_ICSR_PENDSTSET_Msk   (1UL << SCB_ICSR_PENDSTSET_Pos)"
SCB ICSR: PENDSTSET Mask 
.SS "#define SCB_ICSR_PENDSTSET_Pos   26U"
SCB ICSR: PENDSTSET Position 
.SS "#define SCB_ICSR_PENDSTSET_Pos   26U"
SCB ICSR: PENDSTSET Position 
.SS "#define SCB_ICSR_PENDSTSET_Pos   26U"
SCB ICSR: PENDSTSET Position 
.SS "#define SCB_ICSR_PENDSVCLR_Msk   (1UL << SCB_ICSR_PENDSVCLR_Pos)"
SCB ICSR: PENDSVCLR Mask 
.SS "#define SCB_ICSR_PENDSVCLR_Msk   (1UL << SCB_ICSR_PENDSVCLR_Pos)"
SCB ICSR: PENDSVCLR Mask 
.SS "#define SCB_ICSR_PENDSVCLR_Msk   (1UL << SCB_ICSR_PENDSVCLR_Pos)"
SCB ICSR: PENDSVCLR Mask 
.SS "#define SCB_ICSR_PENDSVCLR_Pos   27U"
SCB ICSR: PENDSVCLR Position 
.SS "#define SCB_ICSR_PENDSVCLR_Pos   27U"
SCB ICSR: PENDSVCLR Position 
.SS "#define SCB_ICSR_PENDSVCLR_Pos   27U"
SCB ICSR: PENDSVCLR Position 
.SS "#define SCB_ICSR_PENDSVSET_Msk   (1UL << SCB_ICSR_PENDSVSET_Pos)"
SCB ICSR: PENDSVSET Mask 
.SS "#define SCB_ICSR_PENDSVSET_Msk   (1UL << SCB_ICSR_PENDSVSET_Pos)"
SCB ICSR: PENDSVSET Mask 
.SS "#define SCB_ICSR_PENDSVSET_Msk   (1UL << SCB_ICSR_PENDSVSET_Pos)"
SCB ICSR: PENDSVSET Mask 
.SS "#define SCB_ICSR_PENDSVSET_Pos   28U"
SCB ICSR: PENDSVSET Position 
.SS "#define SCB_ICSR_PENDSVSET_Pos   28U"
SCB ICSR: PENDSVSET Position 
.SS "#define SCB_ICSR_PENDSVSET_Pos   28U"
SCB ICSR: PENDSVSET Position 
.SS "#define SCB_ICSR_RETTOBASE_Msk   (1UL << SCB_ICSR_RETTOBASE_Pos)"
SCB ICSR: RETTOBASE Mask 
.SS "#define SCB_ICSR_RETTOBASE_Msk   (1UL << SCB_ICSR_RETTOBASE_Pos)"
SCB ICSR: RETTOBASE Mask 
.SS "#define SCB_ICSR_RETTOBASE_Msk   (1UL << SCB_ICSR_RETTOBASE_Pos)"
SCB ICSR: RETTOBASE Mask 
.SS "#define SCB_ICSR_RETTOBASE_Pos   11U"
SCB ICSR: RETTOBASE Position 
.SS "#define SCB_ICSR_RETTOBASE_Pos   11U"
SCB ICSR: RETTOBASE Position 
.SS "#define SCB_ICSR_RETTOBASE_Pos   11U"
SCB ICSR: RETTOBASE Position 
.SS "#define SCB_ICSR_STTNS_Msk   (1UL << SCB_ICSR_STTNS_Pos)"
SCB ICSR: STTNS Mask (Security Extension) 
.SS "#define SCB_ICSR_STTNS_Msk   (1UL << SCB_ICSR_STTNS_Pos)"
SCB ICSR: STTNS Mask (Security Extension) 
.SS "#define SCB_ICSR_STTNS_Pos   24U"
SCB ICSR: STTNS Position (Security Extension) 
.SS "#define SCB_ICSR_STTNS_Pos   24U"
SCB ICSR: STTNS Position (Security Extension) 
.SS "#define SCB_ICSR_VECTACTIVE_Msk   (0x1FFUL /*<< SCB_ICSR_VECTACTIVE_Pos*/)"
SCB ICSR: VECTACTIVE Mask 
.SS "#define SCB_ICSR_VECTACTIVE_Msk   (0x1FFUL /*<< SCB_ICSR_VECTACTIVE_Pos*/)"
SCB ICSR: VECTACTIVE Mask 
.SS "#define SCB_ICSR_VECTACTIVE_Msk   (0x1FFUL /*<< SCB_ICSR_VECTACTIVE_Pos*/)"
SCB ICSR: VECTACTIVE Mask 
.SS "#define SCB_ICSR_VECTACTIVE_Pos   0U"
SCB ICSR: VECTACTIVE Position 
.SS "#define SCB_ICSR_VECTACTIVE_Pos   0U"
SCB ICSR: VECTACTIVE Position 
.SS "#define SCB_ICSR_VECTACTIVE_Pos   0U"
SCB ICSR: VECTACTIVE Position 
.SS "#define SCB_ICSR_VECTPENDING_Msk   (0x1FFUL << SCB_ICSR_VECTPENDING_Pos)"
SCB ICSR: VECTPENDING Mask 
.SS "#define SCB_ICSR_VECTPENDING_Msk   (0x1FFUL << SCB_ICSR_VECTPENDING_Pos)"
SCB ICSR: VECTPENDING Mask 
.SS "#define SCB_ICSR_VECTPENDING_Msk   (0x1FFUL << SCB_ICSR_VECTPENDING_Pos)"
SCB ICSR: VECTPENDING Mask 
.SS "#define SCB_ICSR_VECTPENDING_Pos   12U"
SCB ICSR: VECTPENDING Position 
.SS "#define SCB_ICSR_VECTPENDING_Pos   12U"
SCB ICSR: VECTPENDING Position 
.SS "#define SCB_ICSR_VECTPENDING_Pos   12U"
SCB ICSR: VECTPENDING Position 
.SS "#define SCB_ITCMCR_EN_Msk   (1UL /*<< SCB_ITCMCR_EN_Pos*/)"
SCB ITCMCR: EN Mask 
.SS "#define SCB_ITCMCR_EN_Pos   0U"
SCB ITCMCR: EN Position 
.SS "#define SCB_ITCMCR_RETEN_Msk   (1UL << SCB_ITCMCR_RETEN_Pos)"
SCB ITCMCR: RETEN Mask 
.SS "#define SCB_ITCMCR_RETEN_Pos   2U"
SCB ITCMCR: RETEN Position 
.SS "#define SCB_ITCMCR_RMW_Msk   (1UL << SCB_ITCMCR_RMW_Pos)"
SCB ITCMCR: RMW Mask 
.SS "#define SCB_ITCMCR_RMW_Pos   1U"
SCB ITCMCR: RMW Position 
.SS "#define SCB_ITCMCR_SZ_Msk   (0xFUL << SCB_ITCMCR_SZ_Pos)"
SCB ITCMCR: SZ Mask 
.SS "#define SCB_ITCMCR_SZ_Pos   3U"
SCB ITCMCR: SZ Position 
.SS "#define SCB_NSACR_CP10_Msk   (1UL << SCB_NSACR_CP10_Pos)"
SCB NSACR: CP10 Mask 
.SS "#define SCB_NSACR_CP10_Pos   10U"
SCB NSACR: CP10 Position 
.SS "#define SCB_NSACR_CP11_Msk   (1UL << SCB_NSACR_CP11_Pos)"
SCB NSACR: CP11 Mask 
.SS "#define SCB_NSACR_CP11_Pos   11U"
SCB NSACR: CP11 Position 
.SS "#define SCB_NSACR_CPn_Msk   (1UL /*<< SCB_NSACR_CPn_Pos*/)"
SCB NSACR: CPn Mask 
.SS "#define SCB_NSACR_CPn_Pos   0U"
SCB NSACR: CPn Position 
.SS "#define SCB_SCR_SEVONPEND_Msk   (1UL << SCB_SCR_SEVONPEND_Pos)"
SCB SCR: SEVONPEND Mask 
.SS "#define SCB_SCR_SEVONPEND_Msk   (1UL << SCB_SCR_SEVONPEND_Pos)"
SCB SCR: SEVONPEND Mask 
.SS "#define SCB_SCR_SEVONPEND_Msk   (1UL << SCB_SCR_SEVONPEND_Pos)"
SCB SCR: SEVONPEND Mask 
.SS "#define SCB_SCR_SEVONPEND_Pos   4U"
SCB SCR: SEVONPEND Position 
.SS "#define SCB_SCR_SEVONPEND_Pos   4U"
SCB SCR: SEVONPEND Position 
.SS "#define SCB_SCR_SEVONPEND_Pos   4U"
SCB SCR: SEVONPEND Position 
.SS "#define SCB_SCR_SLEEPDEEP_Msk   (1UL << SCB_SCR_SLEEPDEEP_Pos)"
SCB SCR: SLEEPDEEP Mask 
.SS "#define SCB_SCR_SLEEPDEEP_Msk   (1UL << SCB_SCR_SLEEPDEEP_Pos)"
SCB SCR: SLEEPDEEP Mask 
.SS "#define SCB_SCR_SLEEPDEEP_Msk   (1UL << SCB_SCR_SLEEPDEEP_Pos)"
SCB SCR: SLEEPDEEP Mask 
.SS "#define SCB_SCR_SLEEPDEEP_Pos   2U"
SCB SCR: SLEEPDEEP Position 
.SS "#define SCB_SCR_SLEEPDEEP_Pos   2U"
SCB SCR: SLEEPDEEP Position 
.SS "#define SCB_SCR_SLEEPDEEP_Pos   2U"
SCB SCR: SLEEPDEEP Position 
.SS "#define SCB_SCR_SLEEPDEEPS_Msk   (1UL << SCB_SCR_SLEEPDEEPS_Pos)"
SCB SCR: SLEEPDEEPS Mask 
.SS "#define SCB_SCR_SLEEPDEEPS_Msk   (1UL << SCB_SCR_SLEEPDEEPS_Pos)"
SCB SCR: SLEEPDEEPS Mask 
.SS "#define SCB_SCR_SLEEPDEEPS_Pos   3U"
SCB SCR: SLEEPDEEPS Position 
.SS "#define SCB_SCR_SLEEPDEEPS_Pos   3U"
SCB SCR: SLEEPDEEPS Position 
.SS "#define SCB_SCR_SLEEPONEXIT_Msk   (1UL << SCB_SCR_SLEEPONEXIT_Pos)"
SCB SCR: SLEEPONEXIT Mask 
.SS "#define SCB_SCR_SLEEPONEXIT_Msk   (1UL << SCB_SCR_SLEEPONEXIT_Pos)"
SCB SCR: SLEEPONEXIT Mask 
.SS "#define SCB_SCR_SLEEPONEXIT_Msk   (1UL << SCB_SCR_SLEEPONEXIT_Pos)"
SCB SCR: SLEEPONEXIT Mask 
.SS "#define SCB_SCR_SLEEPONEXIT_Pos   1U"
SCB SCR: SLEEPONEXIT Position 
.SS "#define SCB_SCR_SLEEPONEXIT_Pos   1U"
SCB SCR: SLEEPONEXIT Position 
.SS "#define SCB_SCR_SLEEPONEXIT_Pos   1U"
SCB SCR: SLEEPONEXIT Position 
.SS "#define SCB_SHCSR_BUSFAULTACT_Msk   (1UL << SCB_SHCSR_BUSFAULTACT_Pos)"
SCB SHCSR: BUSFAULTACT Mask 
.SS "#define SCB_SHCSR_BUSFAULTACT_Msk   (1UL << SCB_SHCSR_BUSFAULTACT_Pos)"
SCB SHCSR: BUSFAULTACT Mask 
.SS "#define SCB_SHCSR_BUSFAULTACT_Pos   1U"
SCB SHCSR: BUSFAULTACT Position 
.SS "#define SCB_SHCSR_BUSFAULTACT_Pos   1U"
SCB SHCSR: BUSFAULTACT Position 
.SS "#define SCB_SHCSR_BUSFAULTENA_Msk   (1UL << SCB_SHCSR_BUSFAULTENA_Pos)"
SCB SHCSR: BUSFAULTENA Mask 
.SS "#define SCB_SHCSR_BUSFAULTENA_Msk   (1UL << SCB_SHCSR_BUSFAULTENA_Pos)"
SCB SHCSR: BUSFAULTENA Mask 
.SS "#define SCB_SHCSR_BUSFAULTENA_Pos   17U"
SCB SHCSR: BUSFAULTENA Position 
.SS "#define SCB_SHCSR_BUSFAULTENA_Pos   17U"
SCB SHCSR: BUSFAULTENA Position 
.SS "#define SCB_SHCSR_BUSFAULTPENDED_Msk   (1UL << SCB_SHCSR_BUSFAULTPENDED_Pos)"
SCB SHCSR: BUSFAULTPENDED Mask 
.SS "#define SCB_SHCSR_BUSFAULTPENDED_Msk   (1UL << SCB_SHCSR_BUSFAULTPENDED_Pos)"
SCB SHCSR: BUSFAULTPENDED Mask 
.SS "#define SCB_SHCSR_BUSFAULTPENDED_Pos   14U"
SCB SHCSR: BUSFAULTPENDED Position 
.SS "#define SCB_SHCSR_BUSFAULTPENDED_Pos   14U"
SCB SHCSR: BUSFAULTPENDED Position 
.SS "#define SCB_SHCSR_HARDFAULTACT_Msk   (1UL << SCB_SHCSR_HARDFAULTACT_Pos)"
SCB SHCSR: HARDFAULTACT Mask 
.SS "#define SCB_SHCSR_HARDFAULTACT_Msk   (1UL << SCB_SHCSR_HARDFAULTACT_Pos)"
SCB SHCSR: HARDFAULTACT Mask 
.SS "#define SCB_SHCSR_HARDFAULTACT_Pos   2U"
SCB SHCSR: HARDFAULTACT Position 
.SS "#define SCB_SHCSR_HARDFAULTACT_Pos   2U"
SCB SHCSR: HARDFAULTACT Position 
.SS "#define SCB_SHCSR_HARDFAULTPENDED_Msk   (1UL << SCB_SHCSR_HARDFAULTPENDED_Pos)"
SCB SHCSR: HARDFAULTPENDED Mask 
.SS "#define SCB_SHCSR_HARDFAULTPENDED_Msk   (1UL << SCB_SHCSR_HARDFAULTPENDED_Pos)"
SCB SHCSR: HARDFAULTPENDED Mask 
.SS "#define SCB_SHCSR_HARDFAULTPENDED_Pos   21U"
SCB SHCSR: HARDFAULTPENDED Position 
.SS "#define SCB_SHCSR_HARDFAULTPENDED_Pos   21U"
SCB SHCSR: HARDFAULTPENDED Position 
.SS "#define SCB_SHCSR_MEMFAULTACT_Msk   (1UL /*<< SCB_SHCSR_MEMFAULTACT_Pos*/)"
SCB SHCSR: MEMFAULTACT Mask 
.SS "#define SCB_SHCSR_MEMFAULTACT_Msk   (1UL /*<< SCB_SHCSR_MEMFAULTACT_Pos*/)"
SCB SHCSR: MEMFAULTACT Mask 
.SS "#define SCB_SHCSR_MEMFAULTACT_Pos   0U"
SCB SHCSR: MEMFAULTACT Position 
.SS "#define SCB_SHCSR_MEMFAULTACT_Pos   0U"
SCB SHCSR: MEMFAULTACT Position 
.SS "#define SCB_SHCSR_MEMFAULTENA_Msk   (1UL << SCB_SHCSR_MEMFAULTENA_Pos)"
SCB SHCSR: MEMFAULTENA Mask 
.SS "#define SCB_SHCSR_MEMFAULTENA_Msk   (1UL << SCB_SHCSR_MEMFAULTENA_Pos)"
SCB SHCSR: MEMFAULTENA Mask 
.SS "#define SCB_SHCSR_MEMFAULTENA_Pos   16U"
SCB SHCSR: MEMFAULTENA Position 
.SS "#define SCB_SHCSR_MEMFAULTENA_Pos   16U"
SCB SHCSR: MEMFAULTENA Position 
.SS "#define SCB_SHCSR_MEMFAULTPENDED_Msk   (1UL << SCB_SHCSR_MEMFAULTPENDED_Pos)"
SCB SHCSR: MEMFAULTPENDED Mask 
.SS "#define SCB_SHCSR_MEMFAULTPENDED_Msk   (1UL << SCB_SHCSR_MEMFAULTPENDED_Pos)"
SCB SHCSR: MEMFAULTPENDED Mask 
.SS "#define SCB_SHCSR_MEMFAULTPENDED_Pos   13U"
SCB SHCSR: MEMFAULTPENDED Position 
.SS "#define SCB_SHCSR_MEMFAULTPENDED_Pos   13U"
SCB SHCSR: MEMFAULTPENDED Position 
.SS "#define SCB_SHCSR_MONITORACT_Msk   (1UL << SCB_SHCSR_MONITORACT_Pos)"
SCB SHCSR: MONITORACT Mask 
.SS "#define SCB_SHCSR_MONITORACT_Msk   (1UL << SCB_SHCSR_MONITORACT_Pos)"
SCB SHCSR: MONITORACT Mask 
.SS "#define SCB_SHCSR_MONITORACT_Pos   8U"
SCB SHCSR: MONITORACT Position 
.SS "#define SCB_SHCSR_MONITORACT_Pos   8U"
SCB SHCSR: MONITORACT Position 
.SS "#define SCB_SHCSR_NMIACT_Msk   (1UL << SCB_SHCSR_NMIACT_Pos)"
SCB SHCSR: NMIACT Mask 
.SS "#define SCB_SHCSR_NMIACT_Msk   (1UL << SCB_SHCSR_NMIACT_Pos)"
SCB SHCSR: NMIACT Mask 
.SS "#define SCB_SHCSR_NMIACT_Pos   5U"
SCB SHCSR: NMIACT Position 
.SS "#define SCB_SHCSR_NMIACT_Pos   5U"
SCB SHCSR: NMIACT Position 
.SS "#define SCB_SHCSR_PENDSVACT_Msk   (1UL << SCB_SHCSR_PENDSVACT_Pos)"
SCB SHCSR: PENDSVACT Mask 
.SS "#define SCB_SHCSR_PENDSVACT_Msk   (1UL << SCB_SHCSR_PENDSVACT_Pos)"
SCB SHCSR: PENDSVACT Mask 
.SS "#define SCB_SHCSR_PENDSVACT_Msk   (1UL << SCB_SHCSR_PENDSVACT_Pos)"
SCB SHCSR: PENDSVACT Mask 
.SS "#define SCB_SHCSR_PENDSVACT_Pos   10U"
SCB SHCSR: PENDSVACT Position 
.SS "#define SCB_SHCSR_PENDSVACT_Pos   10U"
SCB SHCSR: PENDSVACT Position 
.SS "#define SCB_SHCSR_PENDSVACT_Pos   10U"
SCB SHCSR: PENDSVACT Position 
.SS "#define SCB_SHCSR_SECUREFAULTACT_Msk   (1UL << SCB_SHCSR_SECUREFAULTACT_Pos)"
SCB SHCSR: SECUREFAULTACT Mask 
.SS "#define SCB_SHCSR_SECUREFAULTACT_Pos   4U"
SCB SHCSR: SECUREFAULTACT Position 
.SS "#define SCB_SHCSR_SECUREFAULTENA_Msk   (1UL << SCB_SHCSR_SECUREFAULTENA_Pos)"
SCB SHCSR: SECUREFAULTENA Mask 
.SS "#define SCB_SHCSR_SECUREFAULTENA_Pos   19U"
SCB SHCSR: SECUREFAULTENA Position 
.SS "#define SCB_SHCSR_SECUREFAULTPENDED_Msk   (1UL << SCB_SHCSR_SECUREFAULTPENDED_Pos)"
SCB SHCSR: SECUREFAULTPENDED Mask 
.SS "#define SCB_SHCSR_SECUREFAULTPENDED_Pos   20U"
SCB SHCSR: SECUREFAULTPENDED Position 
.SS "#define SCB_SHCSR_SVCALLACT_Msk   (1UL << SCB_SHCSR_SVCALLACT_Pos)"
SCB SHCSR: SVCALLACT Mask 
.SS "#define SCB_SHCSR_SVCALLACT_Msk   (1UL << SCB_SHCSR_SVCALLACT_Pos)"
SCB SHCSR: SVCALLACT Mask 
.SS "#define SCB_SHCSR_SVCALLACT_Msk   (1UL << SCB_SHCSR_SVCALLACT_Pos)"
SCB SHCSR: SVCALLACT Mask 
.SS "#define SCB_SHCSR_SVCALLACT_Pos   7U"
SCB SHCSR: SVCALLACT Position 
.SS "#define SCB_SHCSR_SVCALLACT_Pos   7U"
SCB SHCSR: SVCALLACT Position 
.SS "#define SCB_SHCSR_SVCALLACT_Pos   7U"
SCB SHCSR: SVCALLACT Position 
.SS "#define SCB_SHCSR_SVCALLPENDED_Msk   (1UL << SCB_SHCSR_SVCALLPENDED_Pos)"
SCB SHCSR: SVCALLPENDED Mask 
.SS "#define SCB_SHCSR_SVCALLPENDED_Msk   (1UL << SCB_SHCSR_SVCALLPENDED_Pos)"
SCB SHCSR: SVCALLPENDED Mask 
.SS "#define SCB_SHCSR_SVCALLPENDED_Msk   (1UL << SCB_SHCSR_SVCALLPENDED_Pos)"
SCB SHCSR: SVCALLPENDED Mask 
.SS "#define SCB_SHCSR_SVCALLPENDED_Pos   15U"
SCB SHCSR: SVCALLPENDED Position 
.SS "#define SCB_SHCSR_SVCALLPENDED_Pos   15U"
SCB SHCSR: SVCALLPENDED Position 
.SS "#define SCB_SHCSR_SVCALLPENDED_Pos   15U"
SCB SHCSR: SVCALLPENDED Position 
.SS "#define SCB_SHCSR_SYSTICKACT_Msk   (1UL << SCB_SHCSR_SYSTICKACT_Pos)"
SCB SHCSR: SYSTICKACT Mask 
.SS "#define SCB_SHCSR_SYSTICKACT_Msk   (1UL << SCB_SHCSR_SYSTICKACT_Pos)"
SCB SHCSR: SYSTICKACT Mask 
.SS "#define SCB_SHCSR_SYSTICKACT_Msk   (1UL << SCB_SHCSR_SYSTICKACT_Pos)"
SCB SHCSR: SYSTICKACT Mask 
.SS "#define SCB_SHCSR_SYSTICKACT_Pos   11U"
SCB SHCSR: SYSTICKACT Position 
.SS "#define SCB_SHCSR_SYSTICKACT_Pos   11U"
SCB SHCSR: SYSTICKACT Position 
.SS "#define SCB_SHCSR_SYSTICKACT_Pos   11U"
SCB SHCSR: SYSTICKACT Position 
.SS "#define SCB_SHCSR_USGFAULTACT_Msk   (1UL << SCB_SHCSR_USGFAULTACT_Pos)"
SCB SHCSR: USGFAULTACT Mask 
.SS "#define SCB_SHCSR_USGFAULTACT_Msk   (1UL << SCB_SHCSR_USGFAULTACT_Pos)"
SCB SHCSR: USGFAULTACT Mask 
.SS "#define SCB_SHCSR_USGFAULTACT_Pos   3U"
SCB SHCSR: USGFAULTACT Position 
.SS "#define SCB_SHCSR_USGFAULTACT_Pos   3U"
SCB SHCSR: USGFAULTACT Position 
.SS "#define SCB_SHCSR_USGFAULTENA_Msk   (1UL << SCB_SHCSR_USGFAULTENA_Pos)"
SCB SHCSR: USGFAULTENA Mask 
.SS "#define SCB_SHCSR_USGFAULTENA_Msk   (1UL << SCB_SHCSR_USGFAULTENA_Pos)"
SCB SHCSR: USGFAULTENA Mask 
.SS "#define SCB_SHCSR_USGFAULTENA_Pos   18U"
SCB SHCSR: USGFAULTENA Position 
.SS "#define SCB_SHCSR_USGFAULTENA_Pos   18U"
SCB SHCSR: USGFAULTENA Position 
.SS "#define SCB_SHCSR_USGFAULTPENDED_Msk   (1UL << SCB_SHCSR_USGFAULTPENDED_Pos)"
SCB SHCSR: USGFAULTPENDED Mask 
.SS "#define SCB_SHCSR_USGFAULTPENDED_Msk   (1UL << SCB_SHCSR_USGFAULTPENDED_Pos)"
SCB SHCSR: USGFAULTPENDED Mask 
.SS "#define SCB_SHCSR_USGFAULTPENDED_Pos   12U"
SCB SHCSR: USGFAULTPENDED Position 
.SS "#define SCB_SHCSR_USGFAULTPENDED_Pos   12U"
SCB SHCSR: USGFAULTPENDED Position 
.SS "#define SCB_STIR_INTID_Msk   (0x1FFUL /*<< SCB_STIR_INTID_Pos*/)"
SCB STIR: INTID Mask 
.SS "#define SCB_STIR_INTID_Pos   0U"
SCB STIR: INTID Position 
.SS "#define SCB_VTOR_TBLOFF_Msk   (0x1FFFFFFUL << SCB_VTOR_TBLOFF_Pos)"
SCB VTOR: TBLOFF Mask 
.SS "#define SCB_VTOR_TBLOFF_Msk   (0x1FFFFFFUL << SCB_VTOR_TBLOFF_Pos)"
SCB VTOR: TBLOFF Mask 
.SS "#define SCB_VTOR_TBLOFF_Pos   7U"
SCB VTOR: TBLOFF Position 
.SS "#define SCB_VTOR_TBLOFF_Pos   7U"
SCB VTOR: TBLOFF Position 
.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
