.TH "CMSIS_FPU" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_FPU \- Type definitions for the Floating Point Unit (FPU)  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBFPU_Type\fP"
.br
.RI "Structure type to access the Floating Point Unit (FPU)\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFPU_FPCCR_ASPEN_Pos\fP   31U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_ASPEN_Msk\fP   (1UL << FPU_FPCCR_ASPEN_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_LSPEN_Pos\fP   30U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_LSPEN_Msk\fP   (1UL << FPU_FPCCR_LSPEN_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_LSPENS_Pos\fP   29U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_LSPENS_Msk\fP   (1UL << FPU_FPCCR_LSPENS_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_CLRONRET_Pos\fP   28U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_CLRONRET_Msk\fP   (1UL << FPU_FPCCR_CLRONRET_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_CLRONRETS_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_CLRONRETS_Msk\fP   (1UL << FPU_FPCCR_CLRONRETS_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_TS_Pos\fP   26U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_TS_Msk\fP   (1UL << FPU_FPCCR_TS_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_UFRDY_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_UFRDY_Msk\fP   (1UL << FPU_FPCCR_UFRDY_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_SPLIMVIOL_Pos\fP   9U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_SPLIMVIOL_Msk\fP   (1UL << FPU_FPCCR_SPLIMVIOL_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_MONRDY_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_MONRDY_Msk\fP   (1UL << FPU_FPCCR_MONRDY_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_SFRDY_Pos\fP   7U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_SFRDY_Msk\fP   (1UL << FPU_FPCCR_SFRDY_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_BFRDY_Pos\fP   6U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_BFRDY_Msk\fP   (1UL << FPU_FPCCR_BFRDY_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_MMRDY_Pos\fP   5U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_MMRDY_Msk\fP   (1UL << FPU_FPCCR_MMRDY_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_HFRDY_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_HFRDY_Msk\fP   (1UL << FPU_FPCCR_HFRDY_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_THREAD_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_THREAD_Msk\fP   (1UL << FPU_FPCCR_THREAD_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_S_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_S_Msk\fP   (1UL << FPU_FPCCR_S_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_USER_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_USER_Msk\fP   (1UL << FPU_FPCCR_USER_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_LSPACT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_LSPACT_Msk\fP   (1UL /*<< FPU_FPCCR_LSPACT_Pos*/)"
.br
.ti -1c
.RI "#define \fBFPU_FPCAR_ADDRESS_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBFPU_FPCAR_ADDRESS_Msk\fP   (0x1FFFFFFFUL << FPU_FPCAR_ADDRESS_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPDSCR_AHP_Pos\fP   26U"
.br
.ti -1c
.RI "#define \fBFPU_FPDSCR_AHP_Msk\fP   (1UL << FPU_FPDSCR_AHP_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPDSCR_DN_Pos\fP   25U"
.br
.ti -1c
.RI "#define \fBFPU_FPDSCR_DN_Msk\fP   (1UL << FPU_FPDSCR_DN_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPDSCR_FZ_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBFPU_FPDSCR_FZ_Msk\fP   (1UL << FPU_FPDSCR_FZ_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPDSCR_RMode_Pos\fP   22U"
.br
.ti -1c
.RI "#define \fBFPU_FPDSCR_RMode_Msk\fP   (3UL << FPU_FPDSCR_RMode_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_FP_rounding_modes_Pos\fP   28U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_FP_rounding_modes_Msk\fP   (0xFUL << FPU_MVFR0_FP_rounding_modes_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Short_vectors_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Short_vectors_Msk\fP   (0xFUL << FPU_MVFR0_Short_vectors_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Square_root_Pos\fP   20U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Square_root_Msk\fP   (0xFUL << FPU_MVFR0_Square_root_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Divide_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Divide_Msk\fP   (0xFUL << FPU_MVFR0_Divide_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_FP_excep_trapping_Pos\fP   12U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_FP_excep_trapping_Msk\fP   (0xFUL << FPU_MVFR0_FP_excep_trapping_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Double_precision_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Double_precision_Msk\fP   (0xFUL << FPU_MVFR0_Double_precision_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Single_precision_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Single_precision_Msk\fP   (0xFUL << FPU_MVFR0_Single_precision_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_A_SIMD_registers_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_A_SIMD_registers_Msk\fP   (0xFUL /*<< FPU_MVFR0_A_SIMD_registers_Pos*/)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR1_FP_fused_MAC_Pos\fP   28U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR1_FP_fused_MAC_Msk\fP   (0xFUL << FPU_MVFR1_FP_fused_MAC_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR1_FP_HPFP_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR1_FP_HPFP_Msk\fP   (0xFUL << FPU_MVFR1_FP_HPFP_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR1_D_NaN_mode_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR1_D_NaN_mode_Msk\fP   (0xFUL << FPU_MVFR1_D_NaN_mode_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR1_FtZ_mode_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR1_FtZ_mode_Msk\fP   (0xFUL /*<< FPU_MVFR1_FtZ_mode_Pos*/)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_ASPEN_Pos\fP   31U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_ASPEN_Msk\fP   (1UL << FPU_FPCCR_ASPEN_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_LSPEN_Pos\fP   30U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_LSPEN_Msk\fP   (1UL << FPU_FPCCR_LSPEN_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_MONRDY_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_MONRDY_Msk\fP   (1UL << FPU_FPCCR_MONRDY_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_BFRDY_Pos\fP   6U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_BFRDY_Msk\fP   (1UL << FPU_FPCCR_BFRDY_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_MMRDY_Pos\fP   5U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_MMRDY_Msk\fP   (1UL << FPU_FPCCR_MMRDY_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_HFRDY_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_HFRDY_Msk\fP   (1UL << FPU_FPCCR_HFRDY_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_THREAD_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_THREAD_Msk\fP   (1UL << FPU_FPCCR_THREAD_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_USER_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_USER_Msk\fP   (1UL << FPU_FPCCR_USER_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_LSPACT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_LSPACT_Msk\fP   (1UL /*<< FPU_FPCCR_LSPACT_Pos*/)"
.br
.ti -1c
.RI "#define \fBFPU_FPCAR_ADDRESS_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBFPU_FPCAR_ADDRESS_Msk\fP   (0x1FFFFFFFUL << FPU_FPCAR_ADDRESS_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPDSCR_AHP_Pos\fP   26U"
.br
.ti -1c
.RI "#define \fBFPU_FPDSCR_AHP_Msk\fP   (1UL << FPU_FPDSCR_AHP_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPDSCR_DN_Pos\fP   25U"
.br
.ti -1c
.RI "#define \fBFPU_FPDSCR_DN_Msk\fP   (1UL << FPU_FPDSCR_DN_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPDSCR_FZ_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBFPU_FPDSCR_FZ_Msk\fP   (1UL << FPU_FPDSCR_FZ_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPDSCR_RMode_Pos\fP   22U"
.br
.ti -1c
.RI "#define \fBFPU_FPDSCR_RMode_Msk\fP   (3UL << FPU_FPDSCR_RMode_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_FP_rounding_modes_Pos\fP   28U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_FP_rounding_modes_Msk\fP   (0xFUL << FPU_MVFR0_FP_rounding_modes_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Short_vectors_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Short_vectors_Msk\fP   (0xFUL << FPU_MVFR0_Short_vectors_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Square_root_Pos\fP   20U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Square_root_Msk\fP   (0xFUL << FPU_MVFR0_Square_root_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Divide_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Divide_Msk\fP   (0xFUL << FPU_MVFR0_Divide_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_FP_excep_trapping_Pos\fP   12U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_FP_excep_trapping_Msk\fP   (0xFUL << FPU_MVFR0_FP_excep_trapping_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Double_precision_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Double_precision_Msk\fP   (0xFUL << FPU_MVFR0_Double_precision_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Single_precision_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Single_precision_Msk\fP   (0xFUL << FPU_MVFR0_Single_precision_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_A_SIMD_registers_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_A_SIMD_registers_Msk\fP   (0xFUL /*<< FPU_MVFR0_A_SIMD_registers_Pos*/)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR1_FP_fused_MAC_Pos\fP   28U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR1_FP_fused_MAC_Msk\fP   (0xFUL << FPU_MVFR1_FP_fused_MAC_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR1_FP_HPFP_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR1_FP_HPFP_Msk\fP   (0xFUL << FPU_MVFR1_FP_HPFP_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR1_D_NaN_mode_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR1_D_NaN_mode_Msk\fP   (0xFUL << FPU_MVFR1_D_NaN_mode_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR1_FtZ_mode_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR1_FtZ_mode_Msk\fP   (0xFUL /*<< FPU_MVFR1_FtZ_mode_Pos*/)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Type definitions for the Floating Point Unit (FPU) 


.SH "Macro Definition Documentation"
.PP 
.SS "#define FPU_FPCAR_ADDRESS_Msk   (0x1FFFFFFFUL << FPU_FPCAR_ADDRESS_Pos)"
FPCAR: ADDRESS bit Mask 
.SS "#define FPU_FPCAR_ADDRESS_Msk   (0x1FFFFFFFUL << FPU_FPCAR_ADDRESS_Pos)"
FPCAR: ADDRESS bit Mask 
.SS "#define FPU_FPCAR_ADDRESS_Pos   3U"
FPCAR: ADDRESS bit Position 
.SS "#define FPU_FPCAR_ADDRESS_Pos   3U"
FPCAR: ADDRESS bit Position 
.SS "#define FPU_FPCCR_ASPEN_Msk   (1UL << FPU_FPCCR_ASPEN_Pos)"
FPCCR: ASPEN bit Mask 
.SS "#define FPU_FPCCR_ASPEN_Msk   (1UL << FPU_FPCCR_ASPEN_Pos)"
FPCCR: ASPEN bit Mask 
.SS "#define FPU_FPCCR_ASPEN_Pos   31U"
FPCCR: ASPEN bit Position 
.SS "#define FPU_FPCCR_ASPEN_Pos   31U"
FPCCR: ASPEN bit Position 
.SS "#define FPU_FPCCR_BFRDY_Msk   (1UL << FPU_FPCCR_BFRDY_Pos)"
FPCCR: BFRDY bit Mask 
.SS "#define FPU_FPCCR_BFRDY_Msk   (1UL << FPU_FPCCR_BFRDY_Pos)"
FPCCR: BFRDY bit Mask 
.SS "#define FPU_FPCCR_BFRDY_Pos   6U"
FPCCR: BFRDY Position 
.SS "#define FPU_FPCCR_BFRDY_Pos   6U"
FPCCR: BFRDY Position 
.SS "#define FPU_FPCCR_CLRONRET_Msk   (1UL << FPU_FPCCR_CLRONRET_Pos)"
FPCCR: CLRONRET bit Mask 
.SS "#define FPU_FPCCR_CLRONRET_Pos   28U"
FPCCR: CLRONRET Position 
.SS "#define FPU_FPCCR_CLRONRETS_Msk   (1UL << FPU_FPCCR_CLRONRETS_Pos)"
FPCCR: CLRONRETS bit Mask 
.SS "#define FPU_FPCCR_CLRONRETS_Pos   27U"
FPCCR: CLRONRETS Position 
.SS "#define FPU_FPCCR_HFRDY_Msk   (1UL << FPU_FPCCR_HFRDY_Pos)"
FPCCR: HFRDY bit Mask 
.SS "#define FPU_FPCCR_HFRDY_Msk   (1UL << FPU_FPCCR_HFRDY_Pos)"
FPCCR: HFRDY bit Mask 
.SS "#define FPU_FPCCR_HFRDY_Pos   4U"
FPCCR: HFRDY Position 
.SS "#define FPU_FPCCR_HFRDY_Pos   4U"
FPCCR: HFRDY Position 
.SS "#define FPU_FPCCR_LSPACT_Msk   (1UL /*<< FPU_FPCCR_LSPACT_Pos*/)"
FPCCR: Lazy state preservation active bit Mask 
.SS "#define FPU_FPCCR_LSPACT_Msk   (1UL /*<< FPU_FPCCR_LSPACT_Pos*/)"
FPCCR: Lazy state preservation active bit Mask 
.SS "#define FPU_FPCCR_LSPACT_Pos   0U"
FPCCR: Lazy state preservation active bit Position 
.SS "#define FPU_FPCCR_LSPACT_Pos   0U"
FPCCR: Lazy state preservation active bit Position 
.SS "#define FPU_FPCCR_LSPEN_Msk   (1UL << FPU_FPCCR_LSPEN_Pos)"
FPCCR: LSPEN bit Mask 
.SS "#define FPU_FPCCR_LSPEN_Msk   (1UL << FPU_FPCCR_LSPEN_Pos)"
FPCCR: LSPEN bit Mask 
.SS "#define FPU_FPCCR_LSPEN_Pos   30U"
FPCCR: LSPEN Position 
.SS "#define FPU_FPCCR_LSPEN_Pos   30U"
FPCCR: LSPEN Position 
.SS "#define FPU_FPCCR_LSPENS_Msk   (1UL << FPU_FPCCR_LSPENS_Pos)"
FPCCR: LSPENS bit Mask 
.SS "#define FPU_FPCCR_LSPENS_Pos   29U"
FPCCR: LSPENS Position 
.SS "#define FPU_FPCCR_MMRDY_Msk   (1UL << FPU_FPCCR_MMRDY_Pos)"
FPCCR: MMRDY bit Mask 
.SS "#define FPU_FPCCR_MMRDY_Msk   (1UL << FPU_FPCCR_MMRDY_Pos)"
FPCCR: MMRDY bit Mask 
.SS "#define FPU_FPCCR_MMRDY_Pos   5U"
FPCCR: MMRDY Position 
.SS "#define FPU_FPCCR_MMRDY_Pos   5U"
FPCCR: MMRDY Position 
.SS "#define FPU_FPCCR_MONRDY_Msk   (1UL << FPU_FPCCR_MONRDY_Pos)"
FPCCR: MONRDY bit Mask 
.SS "#define FPU_FPCCR_MONRDY_Msk   (1UL << FPU_FPCCR_MONRDY_Pos)"
FPCCR: MONRDY bit Mask 
.SS "#define FPU_FPCCR_MONRDY_Pos   8U"
FPCCR: MONRDY Position 
.SS "#define FPU_FPCCR_MONRDY_Pos   8U"
FPCCR: MONRDY Position 
.SS "#define FPU_FPCCR_S_Msk   (1UL << FPU_FPCCR_S_Pos)"
FPCCR: Security status of the FP context bit Mask 
.SS "#define FPU_FPCCR_S_Pos   2U"
FPCCR: Security status of the FP context bit Position 
.SS "#define FPU_FPCCR_SFRDY_Msk   (1UL << FPU_FPCCR_SFRDY_Pos)"
FPCCR: SFRDY bit Mask 
.SS "#define FPU_FPCCR_SFRDY_Pos   7U"
FPCCR: SFRDY Position 
.SS "#define FPU_FPCCR_SPLIMVIOL_Msk   (1UL << FPU_FPCCR_SPLIMVIOL_Pos)"
FPCCR: SPLIMVIOL bit Mask 
.SS "#define FPU_FPCCR_SPLIMVIOL_Pos   9U"
FPCCR: SPLIMVIOL Position 
.SS "#define FPU_FPCCR_THREAD_Msk   (1UL << FPU_FPCCR_THREAD_Pos)"
FPCCR: processor mode active bit Mask 
.SS "#define FPU_FPCCR_THREAD_Msk   (1UL << FPU_FPCCR_THREAD_Pos)"
FPCCR: processor mode active bit Mask 
.SS "#define FPU_FPCCR_THREAD_Pos   3U"
FPCCR: processor mode bit Position 
.SS "#define FPU_FPCCR_THREAD_Pos   3U"
FPCCR: processor mode bit Position 
.SS "#define FPU_FPCCR_TS_Msk   (1UL << FPU_FPCCR_TS_Pos)"
FPCCR: TS bit Mask 
.SS "#define FPU_FPCCR_TS_Pos   26U"
FPCCR: TS Position 
.SS "#define FPU_FPCCR_UFRDY_Msk   (1UL << FPU_FPCCR_UFRDY_Pos)"
FPCCR: UFRDY bit Mask 
.SS "#define FPU_FPCCR_UFRDY_Pos   10U"
FPCCR: UFRDY Position 
.SS "#define FPU_FPCCR_USER_Msk   (1UL << FPU_FPCCR_USER_Pos)"
FPCCR: privilege level bit Mask 
.SS "#define FPU_FPCCR_USER_Msk   (1UL << FPU_FPCCR_USER_Pos)"
FPCCR: privilege level bit Mask 
.SS "#define FPU_FPCCR_USER_Pos   1U"
FPCCR: privilege level bit Position 
.SS "#define FPU_FPCCR_USER_Pos   1U"
FPCCR: privilege level bit Position 
.SS "#define FPU_FPDSCR_AHP_Msk   (1UL << FPU_FPDSCR_AHP_Pos)"
FPDSCR: AHP bit Mask 
.SS "#define FPU_FPDSCR_AHP_Msk   (1UL << FPU_FPDSCR_AHP_Pos)"
FPDSCR: AHP bit Mask 
.SS "#define FPU_FPDSCR_AHP_Pos   26U"
FPDSCR: AHP bit Position 
.SS "#define FPU_FPDSCR_AHP_Pos   26U"
FPDSCR: AHP bit Position 
.SS "#define FPU_FPDSCR_DN_Msk   (1UL << FPU_FPDSCR_DN_Pos)"
FPDSCR: DN bit Mask 
.SS "#define FPU_FPDSCR_DN_Msk   (1UL << FPU_FPDSCR_DN_Pos)"
FPDSCR: DN bit Mask 
.SS "#define FPU_FPDSCR_DN_Pos   25U"
FPDSCR: DN bit Position 
.SS "#define FPU_FPDSCR_DN_Pos   25U"
FPDSCR: DN bit Position 
.SS "#define FPU_FPDSCR_FZ_Msk   (1UL << FPU_FPDSCR_FZ_Pos)"
FPDSCR: FZ bit Mask 
.SS "#define FPU_FPDSCR_FZ_Msk   (1UL << FPU_FPDSCR_FZ_Pos)"
FPDSCR: FZ bit Mask 
.SS "#define FPU_FPDSCR_FZ_Pos   24U"
FPDSCR: FZ bit Position 
.SS "#define FPU_FPDSCR_FZ_Pos   24U"
FPDSCR: FZ bit Position 
.SS "#define FPU_FPDSCR_RMode_Msk   (3UL << FPU_FPDSCR_RMode_Pos)"
FPDSCR: RMode bit Mask 
.SS "#define FPU_FPDSCR_RMode_Msk   (3UL << FPU_FPDSCR_RMode_Pos)"
FPDSCR: RMode bit Mask 
.SS "#define FPU_FPDSCR_RMode_Pos   22U"
FPDSCR: RMode bit Position 
.SS "#define FPU_FPDSCR_RMode_Pos   22U"
FPDSCR: RMode bit Position 
.SS "#define FPU_MVFR0_A_SIMD_registers_Msk   (0xFUL /*<< FPU_MVFR0_A_SIMD_registers_Pos*/)"
MVFR0: A_SIMD registers bits Mask 
.SS "#define FPU_MVFR0_A_SIMD_registers_Msk   (0xFUL /*<< FPU_MVFR0_A_SIMD_registers_Pos*/)"
MVFR0: A_SIMD registers bits Mask 
.SS "#define FPU_MVFR0_A_SIMD_registers_Pos   0U"
MVFR0: A_SIMD registers bits Position 
.SS "#define FPU_MVFR0_A_SIMD_registers_Pos   0U"
MVFR0: A_SIMD registers bits Position 
.SS "#define FPU_MVFR0_Divide_Msk   (0xFUL << FPU_MVFR0_Divide_Pos)"
MVFR0: Divide bits Mask 
.SS "#define FPU_MVFR0_Divide_Msk   (0xFUL << FPU_MVFR0_Divide_Pos)"
MVFR0: Divide bits Mask 
.SS "#define FPU_MVFR0_Divide_Pos   16U"
MVFR0: Divide bits Position 
.SS "#define FPU_MVFR0_Divide_Pos   16U"
MVFR0: Divide bits Position 
.SS "#define FPU_MVFR0_Double_precision_Msk   (0xFUL << FPU_MVFR0_Double_precision_Pos)"
MVFR0: Double-precision bits Mask 
.SS "#define FPU_MVFR0_Double_precision_Msk   (0xFUL << FPU_MVFR0_Double_precision_Pos)"
MVFR0: Double-precision bits Mask 
.SS "#define FPU_MVFR0_Double_precision_Pos   8U"
MVFR0: Double-precision bits Position 
.SS "#define FPU_MVFR0_Double_precision_Pos   8U"
MVFR0: Double-precision bits Position 
.SS "#define FPU_MVFR0_FP_excep_trapping_Msk   (0xFUL << FPU_MVFR0_FP_excep_trapping_Pos)"
MVFR0: FP exception trapping bits Mask 
.SS "#define FPU_MVFR0_FP_excep_trapping_Msk   (0xFUL << FPU_MVFR0_FP_excep_trapping_Pos)"
MVFR0: FP exception trapping bits Mask 
.SS "#define FPU_MVFR0_FP_excep_trapping_Pos   12U"
MVFR0: FP exception trapping bits Position 
.SS "#define FPU_MVFR0_FP_excep_trapping_Pos   12U"
MVFR0: FP exception trapping bits Position 
.SS "#define FPU_MVFR0_FP_rounding_modes_Msk   (0xFUL << FPU_MVFR0_FP_rounding_modes_Pos)"
MVFR0: FP rounding modes bits Mask 
.SS "#define FPU_MVFR0_FP_rounding_modes_Msk   (0xFUL << FPU_MVFR0_FP_rounding_modes_Pos)"
MVFR0: FP rounding modes bits Mask 
.SS "#define FPU_MVFR0_FP_rounding_modes_Pos   28U"
MVFR0: FP rounding modes bits Position 
.SS "#define FPU_MVFR0_FP_rounding_modes_Pos   28U"
MVFR0: FP rounding modes bits Position 
.SS "#define FPU_MVFR0_Short_vectors_Msk   (0xFUL << FPU_MVFR0_Short_vectors_Pos)"
MVFR0: Short vectors bits Mask 
.SS "#define FPU_MVFR0_Short_vectors_Msk   (0xFUL << FPU_MVFR0_Short_vectors_Pos)"
MVFR0: Short vectors bits Mask 
.SS "#define FPU_MVFR0_Short_vectors_Pos   24U"
MVFR0: Short vectors bits Position 
.SS "#define FPU_MVFR0_Short_vectors_Pos   24U"
MVFR0: Short vectors bits Position 
.SS "#define FPU_MVFR0_Single_precision_Msk   (0xFUL << FPU_MVFR0_Single_precision_Pos)"
MVFR0: Single-precision bits Mask 
.SS "#define FPU_MVFR0_Single_precision_Msk   (0xFUL << FPU_MVFR0_Single_precision_Pos)"
MVFR0: Single-precision bits Mask 
.SS "#define FPU_MVFR0_Single_precision_Pos   4U"
MVFR0: Single-precision bits Position 
.SS "#define FPU_MVFR0_Single_precision_Pos   4U"
MVFR0: Single-precision bits Position 
.SS "#define FPU_MVFR0_Square_root_Msk   (0xFUL << FPU_MVFR0_Square_root_Pos)"
MVFR0: Square root bits Mask 
.SS "#define FPU_MVFR0_Square_root_Msk   (0xFUL << FPU_MVFR0_Square_root_Pos)"
MVFR0: Square root bits Mask 
.SS "#define FPU_MVFR0_Square_root_Pos   20U"
MVFR0: Square root bits Position 
.SS "#define FPU_MVFR0_Square_root_Pos   20U"
MVFR0: Square root bits Position 
.SS "#define FPU_MVFR1_D_NaN_mode_Msk   (0xFUL << FPU_MVFR1_D_NaN_mode_Pos)"
MVFR1: D_NaN mode bits Mask 
.SS "#define FPU_MVFR1_D_NaN_mode_Msk   (0xFUL << FPU_MVFR1_D_NaN_mode_Pos)"
MVFR1: D_NaN mode bits Mask 
.SS "#define FPU_MVFR1_D_NaN_mode_Pos   4U"
MVFR1: D_NaN mode bits Position 
.SS "#define FPU_MVFR1_D_NaN_mode_Pos   4U"
MVFR1: D_NaN mode bits Position 
.SS "#define FPU_MVFR1_FP_fused_MAC_Msk   (0xFUL << FPU_MVFR1_FP_fused_MAC_Pos)"
MVFR1: FP fused MAC bits Mask 
.SS "#define FPU_MVFR1_FP_fused_MAC_Msk   (0xFUL << FPU_MVFR1_FP_fused_MAC_Pos)"
MVFR1: FP fused MAC bits Mask 
.SS "#define FPU_MVFR1_FP_fused_MAC_Pos   28U"
MVFR1: FP fused MAC bits Position 
.SS "#define FPU_MVFR1_FP_fused_MAC_Pos   28U"
MVFR1: FP fused MAC bits Position 
.SS "#define FPU_MVFR1_FP_HPFP_Msk   (0xFUL << FPU_MVFR1_FP_HPFP_Pos)"
MVFR1: FP HPFP bits Mask 
.SS "#define FPU_MVFR1_FP_HPFP_Msk   (0xFUL << FPU_MVFR1_FP_HPFP_Pos)"
MVFR1: FP HPFP bits Mask 
.SS "#define FPU_MVFR1_FP_HPFP_Pos   24U"
MVFR1: FP HPFP bits Position 
.SS "#define FPU_MVFR1_FP_HPFP_Pos   24U"
MVFR1: FP HPFP bits Position 
.SS "#define FPU_MVFR1_FtZ_mode_Msk   (0xFUL /*<< FPU_MVFR1_FtZ_mode_Pos*/)"
MVFR1: FtZ mode bits Mask 
.SS "#define FPU_MVFR1_FtZ_mode_Msk   (0xFUL /*<< FPU_MVFR1_FtZ_mode_Pos*/)"
MVFR1: FtZ mode bits Mask 
.SS "#define FPU_MVFR1_FtZ_mode_Pos   0U"
MVFR1: FtZ mode bits Position 
.SS "#define FPU_MVFR1_FtZ_mode_Pos   0U"
MVFR1: FtZ mode bits Position 
.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
