.TH "CMSIS_SysTick" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_SysTick \- Type definitions for the System Timer Registers\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBSysTick_Type\fP"
.br
.RI "Structure type to access the System Timer (SysTick)\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSysTick_CTRL_COUNTFLAG_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_COUNTFLAG_Msk\fP   (1UL << SysTick_CTRL_COUNTFLAG_Pos)"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_CLKSOURCE_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_CLKSOURCE_Msk\fP   (1UL << SysTick_CTRL_CLKSOURCE_Pos)"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_TICKINT_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_TICKINT_Msk\fP   (1UL << SysTick_CTRL_TICKINT_Pos)"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_ENABLE_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_ENABLE_Msk\fP   (1UL /*<< SysTick_CTRL_ENABLE_Pos*/)"
.br
.ti -1c
.RI "#define \fBSysTick_LOAD_RELOAD_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSysTick_LOAD_RELOAD_Msk\fP   (0xFFFFFFUL /*<< SysTick_LOAD_RELOAD_Pos*/)"
.br
.ti -1c
.RI "#define \fBSysTick_VAL_CURRENT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSysTick_VAL_CURRENT_Msk\fP   (0xFFFFFFUL /*<< SysTick_VAL_CURRENT_Pos*/)"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_NOREF_Pos\fP   31U"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_NOREF_Msk\fP   (1UL << SysTick_CALIB_NOREF_Pos)"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_SKEW_Pos\fP   30U"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_SKEW_Msk\fP   (1UL << SysTick_CALIB_SKEW_Pos)"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_TENMS_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_TENMS_Msk\fP   (0xFFFFFFUL /*<< SysTick_CALIB_TENMS_Pos*/)"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_COUNTFLAG_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_COUNTFLAG_Msk\fP   (1UL << SysTick_CTRL_COUNTFLAG_Pos)"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_CLKSOURCE_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_CLKSOURCE_Msk\fP   (1UL << SysTick_CTRL_CLKSOURCE_Pos)"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_TICKINT_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_TICKINT_Msk\fP   (1UL << SysTick_CTRL_TICKINT_Pos)"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_ENABLE_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_ENABLE_Msk\fP   (1UL /*<< SysTick_CTRL_ENABLE_Pos*/)"
.br
.ti -1c
.RI "#define \fBSysTick_LOAD_RELOAD_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSysTick_LOAD_RELOAD_Msk\fP   (0xFFFFFFUL /*<< SysTick_LOAD_RELOAD_Pos*/)"
.br
.ti -1c
.RI "#define \fBSysTick_VAL_CURRENT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSysTick_VAL_CURRENT_Msk\fP   (0xFFFFFFUL /*<< SysTick_VAL_CURRENT_Pos*/)"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_NOREF_Pos\fP   31U"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_NOREF_Msk\fP   (1UL << SysTick_CALIB_NOREF_Pos)"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_SKEW_Pos\fP   30U"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_SKEW_Msk\fP   (1UL << SysTick_CALIB_SKEW_Pos)"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_TENMS_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_TENMS_Msk\fP   (0xFFFFFFUL /*<< SysTick_CALIB_TENMS_Pos*/)"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_COUNTFLAG_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_COUNTFLAG_Msk\fP   (1UL << SysTick_CTRL_COUNTFLAG_Pos)"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_CLKSOURCE_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_CLKSOURCE_Msk\fP   (1UL << SysTick_CTRL_CLKSOURCE_Pos)"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_TICKINT_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_TICKINT_Msk\fP   (1UL << SysTick_CTRL_TICKINT_Pos)"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_ENABLE_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_ENABLE_Msk\fP   (1UL /*<< SysTick_CTRL_ENABLE_Pos*/)"
.br
.ti -1c
.RI "#define \fBSysTick_LOAD_RELOAD_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSysTick_LOAD_RELOAD_Msk\fP   (0xFFFFFFUL /*<< SysTick_LOAD_RELOAD_Pos*/)"
.br
.ti -1c
.RI "#define \fBSysTick_VAL_CURRENT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSysTick_VAL_CURRENT_Msk\fP   (0xFFFFFFUL /*<< SysTick_VAL_CURRENT_Pos*/)"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_NOREF_Pos\fP   31U"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_NOREF_Msk\fP   (1UL << SysTick_CALIB_NOREF_Pos)"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_SKEW_Pos\fP   30U"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_SKEW_Msk\fP   (1UL << SysTick_CALIB_SKEW_Pos)"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_TENMS_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_TENMS_Msk\fP   (0xFFFFFFUL /*<< SysTick_CALIB_TENMS_Pos*/)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Type definitions for the System Timer Registers\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define SysTick_CALIB_NOREF_Msk   (1UL << SysTick_CALIB_NOREF_Pos)"
SysTick CALIB: NOREF Mask 
.SS "#define SysTick_CALIB_NOREF_Msk   (1UL << SysTick_CALIB_NOREF_Pos)"
SysTick CALIB: NOREF Mask 
.SS "#define SysTick_CALIB_NOREF_Msk   (1UL << SysTick_CALIB_NOREF_Pos)"
SysTick CALIB: NOREF Mask 
.SS "#define SysTick_CALIB_NOREF_Pos   31U"
SysTick CALIB: NOREF Position 
.SS "#define SysTick_CALIB_NOREF_Pos   31U"
SysTick CALIB: NOREF Position 
.SS "#define SysTick_CALIB_NOREF_Pos   31U"
SysTick CALIB: NOREF Position 
.SS "#define SysTick_CALIB_SKEW_Msk   (1UL << SysTick_CALIB_SKEW_Pos)"
SysTick CALIB: SKEW Mask 
.SS "#define SysTick_CALIB_SKEW_Msk   (1UL << SysTick_CALIB_SKEW_Pos)"
SysTick CALIB: SKEW Mask 
.SS "#define SysTick_CALIB_SKEW_Msk   (1UL << SysTick_CALIB_SKEW_Pos)"
SysTick CALIB: SKEW Mask 
.SS "#define SysTick_CALIB_SKEW_Pos   30U"
SysTick CALIB: SKEW Position 
.SS "#define SysTick_CALIB_SKEW_Pos   30U"
SysTick CALIB: SKEW Position 
.SS "#define SysTick_CALIB_SKEW_Pos   30U"
SysTick CALIB: SKEW Position 
.SS "#define SysTick_CALIB_TENMS_Msk   (0xFFFFFFUL /*<< SysTick_CALIB_TENMS_Pos*/)"
SysTick CALIB: TENMS Mask 
.SS "#define SysTick_CALIB_TENMS_Msk   (0xFFFFFFUL /*<< SysTick_CALIB_TENMS_Pos*/)"
SysTick CALIB: TENMS Mask 
.SS "#define SysTick_CALIB_TENMS_Msk   (0xFFFFFFUL /*<< SysTick_CALIB_TENMS_Pos*/)"
SysTick CALIB: TENMS Mask 
.SS "#define SysTick_CALIB_TENMS_Pos   0U"
SysTick CALIB: TENMS Position 
.SS "#define SysTick_CALIB_TENMS_Pos   0U"
SysTick CALIB: TENMS Position 
.SS "#define SysTick_CALIB_TENMS_Pos   0U"
SysTick CALIB: TENMS Position 
.SS "#define SysTick_CTRL_CLKSOURCE_Msk   (1UL << SysTick_CTRL_CLKSOURCE_Pos)"
SysTick CTRL: CLKSOURCE Mask 
.SS "#define SysTick_CTRL_CLKSOURCE_Msk   (1UL << SysTick_CTRL_CLKSOURCE_Pos)"
SysTick CTRL: CLKSOURCE Mask 
.SS "#define SysTick_CTRL_CLKSOURCE_Msk   (1UL << SysTick_CTRL_CLKSOURCE_Pos)"
SysTick CTRL: CLKSOURCE Mask 
.SS "#define SysTick_CTRL_CLKSOURCE_Pos   2U"
SysTick CTRL: CLKSOURCE Position 
.SS "#define SysTick_CTRL_CLKSOURCE_Pos   2U"
SysTick CTRL: CLKSOURCE Position 
.SS "#define SysTick_CTRL_CLKSOURCE_Pos   2U"
SysTick CTRL: CLKSOURCE Position 
.SS "#define SysTick_CTRL_COUNTFLAG_Msk   (1UL << SysTick_CTRL_COUNTFLAG_Pos)"
SysTick CTRL: COUNTFLAG Mask 
.SS "#define SysTick_CTRL_COUNTFLAG_Msk   (1UL << SysTick_CTRL_COUNTFLAG_Pos)"
SysTick CTRL: COUNTFLAG Mask 
.SS "#define SysTick_CTRL_COUNTFLAG_Msk   (1UL << SysTick_CTRL_COUNTFLAG_Pos)"
SysTick CTRL: COUNTFLAG Mask 
.SS "#define SysTick_CTRL_COUNTFLAG_Pos   16U"
SysTick CTRL: COUNTFLAG Position 
.SS "#define SysTick_CTRL_COUNTFLAG_Pos   16U"
SysTick CTRL: COUNTFLAG Position 
.SS "#define SysTick_CTRL_COUNTFLAG_Pos   16U"
SysTick CTRL: COUNTFLAG Position 
.SS "#define SysTick_CTRL_ENABLE_Msk   (1UL /*<< SysTick_CTRL_ENABLE_Pos*/)"
SysTick CTRL: ENABLE Mask 
.SS "#define SysTick_CTRL_ENABLE_Msk   (1UL /*<< SysTick_CTRL_ENABLE_Pos*/)"
SysTick CTRL: ENABLE Mask 
.SS "#define SysTick_CTRL_ENABLE_Msk   (1UL /*<< SysTick_CTRL_ENABLE_Pos*/)"
SysTick CTRL: ENABLE Mask 
.SS "#define SysTick_CTRL_ENABLE_Pos   0U"
SysTick CTRL: ENABLE Position 
.SS "#define SysTick_CTRL_ENABLE_Pos   0U"
SysTick CTRL: ENABLE Position 
.SS "#define SysTick_CTRL_ENABLE_Pos   0U"
SysTick CTRL: ENABLE Position 
.SS "#define SysTick_CTRL_TICKINT_Msk   (1UL << SysTick_CTRL_TICKINT_Pos)"
SysTick CTRL: TICKINT Mask 
.SS "#define SysTick_CTRL_TICKINT_Msk   (1UL << SysTick_CTRL_TICKINT_Pos)"
SysTick CTRL: TICKINT Mask 
.SS "#define SysTick_CTRL_TICKINT_Msk   (1UL << SysTick_CTRL_TICKINT_Pos)"
SysTick CTRL: TICKINT Mask 
.SS "#define SysTick_CTRL_TICKINT_Pos   1U"
SysTick CTRL: TICKINT Position 
.SS "#define SysTick_CTRL_TICKINT_Pos   1U"
SysTick CTRL: TICKINT Position 
.SS "#define SysTick_CTRL_TICKINT_Pos   1U"
SysTick CTRL: TICKINT Position 
.SS "#define SysTick_LOAD_RELOAD_Msk   (0xFFFFFFUL /*<< SysTick_LOAD_RELOAD_Pos*/)"
SysTick LOAD: RELOAD Mask 
.SS "#define SysTick_LOAD_RELOAD_Msk   (0xFFFFFFUL /*<< SysTick_LOAD_RELOAD_Pos*/)"
SysTick LOAD: RELOAD Mask 
.SS "#define SysTick_LOAD_RELOAD_Msk   (0xFFFFFFUL /*<< SysTick_LOAD_RELOAD_Pos*/)"
SysTick LOAD: RELOAD Mask 
.SS "#define SysTick_LOAD_RELOAD_Pos   0U"
SysTick LOAD: RELOAD Position 
.SS "#define SysTick_LOAD_RELOAD_Pos   0U"
SysTick LOAD: RELOAD Position 
.SS "#define SysTick_LOAD_RELOAD_Pos   0U"
SysTick LOAD: RELOAD Position 
.SS "#define SysTick_VAL_CURRENT_Msk   (0xFFFFFFUL /*<< SysTick_VAL_CURRENT_Pos*/)"
SysTick VAL: CURRENT Mask 
.SS "#define SysTick_VAL_CURRENT_Msk   (0xFFFFFFUL /*<< SysTick_VAL_CURRENT_Pos*/)"
SysTick VAL: CURRENT Mask 
.SS "#define SysTick_VAL_CURRENT_Msk   (0xFFFFFFUL /*<< SysTick_VAL_CURRENT_Pos*/)"
SysTick VAL: CURRENT Mask 
.SS "#define SysTick_VAL_CURRENT_Pos   0U"
SysTick VAL: CURRENT Position 
.SS "#define SysTick_VAL_CURRENT_Pos   0U"
SysTick VAL: CURRENT Position 
.SS "#define SysTick_VAL_CURRENT_Pos   0U"
SysTick VAL: CURRENT Position 
.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
