.TH "CMSIS_glob_defs" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_glob_defs
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBIO Type Qualifiers\fP are used 
.PD 0

.IP "\(bu" 2
to specify the access to peripheral variables\&. 
.IP "\(bu" 2
for automatic generation of peripheral register debug information\&. 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
