.TH "CMSIS_Core_NVICFunctions" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_Core_NVICFunctions \- Functions that manage interrupts and exceptions via the NVIC\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNVIC_EnableIRQ\fP   \fB__NVIC_EnableIRQ\fP"
.br
.ti -1c
.RI "#define \fBNVIC_GetEnableIRQ\fP   \fB__NVIC_GetEnableIRQ\fP"
.br
.ti -1c
.RI "#define \fBNVIC_DisableIRQ\fP   \fB__NVIC_DisableIRQ\fP"
.br
.ti -1c
.RI "#define \fBNVIC_GetPendingIRQ\fP   \fB__NVIC_GetPendingIRQ\fP"
.br
.ti -1c
.RI "#define \fBNVIC_SetPendingIRQ\fP   \fB__NVIC_SetPendingIRQ\fP"
.br
.ti -1c
.RI "#define \fBNVIC_ClearPendingIRQ\fP   \fB__NVIC_ClearPendingIRQ\fP"
.br
.ti -1c
.RI "#define \fBNVIC_GetActive\fP   \fB__NVIC_GetActive\fP"
.br
.ti -1c
.RI "#define \fBNVIC_SetPriority\fP   \fB__NVIC_SetPriority\fP"
.br
.ti -1c
.RI "#define \fBNVIC_GetPriority\fP   \fB__NVIC_GetPriority\fP"
.br
.ti -1c
.RI "#define \fBNVIC_SystemReset\fP   \fB__NVIC_SystemReset\fP"
.br
.ti -1c
.RI "#define \fBNVIC_SetVector\fP   \fB__NVIC_SetVector\fP"
.br
.ti -1c
.RI "#define \fBNVIC_GetVector\fP   \fB__NVIC_GetVector\fP"
.br
.ti -1c
.RI "#define \fBNVIC_USER_IRQ_OFFSET\fP   16"
.br
.ti -1c
.RI "#define \fB_BIT_SHIFT\fP(\fBIRQn\fP)   (  ((((uint32_t)(int32_t)(\fBIRQn\fP))         )      &  0x03UL) * 8UL)"
.br
.ti -1c
.RI "#define \fB_SHP_IDX\fP(\fBIRQn\fP)   ( (((((uint32_t)(int32_t)(\fBIRQn\fP)) & 0x0FUL)\-8UL) >>    2UL)      )"
.br
.ti -1c
.RI "#define \fB_IP_IDX\fP(\fBIRQn\fP)   (   (((uint32_t)(int32_t)(\fBIRQn\fP))                >>    2UL)      )"
.br
.ti -1c
.RI "#define \fBNVIC_SetPriorityGrouping\fP   \fB__NVIC_SetPriorityGrouping\fP"
.br
.ti -1c
.RI "#define \fBNVIC_GetPriorityGrouping\fP   \fB__NVIC_GetPriorityGrouping\fP"
.br
.ti -1c
.RI "#define \fBNVIC_EnableIRQ\fP   \fB__NVIC_EnableIRQ\fP"
.br
.ti -1c
.RI "#define \fBNVIC_GetEnableIRQ\fP   \fB__NVIC_GetEnableIRQ\fP"
.br
.ti -1c
.RI "#define \fBNVIC_DisableIRQ\fP   \fB__NVIC_DisableIRQ\fP"
.br
.ti -1c
.RI "#define \fBNVIC_GetPendingIRQ\fP   \fB__NVIC_GetPendingIRQ\fP"
.br
.ti -1c
.RI "#define \fBNVIC_SetPendingIRQ\fP   \fB__NVIC_SetPendingIRQ\fP"
.br
.ti -1c
.RI "#define \fBNVIC_ClearPendingIRQ\fP   \fB__NVIC_ClearPendingIRQ\fP"
.br
.ti -1c
.RI "#define \fBNVIC_GetActive\fP   \fB__NVIC_GetActive\fP"
.br
.ti -1c
.RI "#define \fBNVIC_SetPriority\fP   \fB__NVIC_SetPriority\fP"
.br
.ti -1c
.RI "#define \fBNVIC_GetPriority\fP   \fB__NVIC_GetPriority\fP"
.br
.ti -1c
.RI "#define \fBNVIC_SystemReset\fP   \fB__NVIC_SystemReset\fP"
.br
.ti -1c
.RI "#define \fBNVIC_SetVector\fP   \fB__NVIC_SetVector\fP"
.br
.ti -1c
.RI "#define \fBNVIC_GetVector\fP   \fB__NVIC_GetVector\fP"
.br
.ti -1c
.RI "#define \fBNVIC_USER_IRQ_OFFSET\fP   16"
.br
.ti -1c
.RI "#define \fBNVIC_SetPriorityGrouping\fP   \fB__NVIC_SetPriorityGrouping\fP"
.br
.ti -1c
.RI "#define \fBNVIC_GetPriorityGrouping\fP   \fB__NVIC_GetPriorityGrouping\fP"
.br
.ti -1c
.RI "#define \fBNVIC_EnableIRQ\fP   \fB__NVIC_EnableIRQ\fP"
.br
.ti -1c
.RI "#define \fBNVIC_GetEnableIRQ\fP   \fB__NVIC_GetEnableIRQ\fP"
.br
.ti -1c
.RI "#define \fBNVIC_DisableIRQ\fP   \fB__NVIC_DisableIRQ\fP"
.br
.ti -1c
.RI "#define \fBNVIC_GetPendingIRQ\fP   \fB__NVIC_GetPendingIRQ\fP"
.br
.ti -1c
.RI "#define \fBNVIC_SetPendingIRQ\fP   \fB__NVIC_SetPendingIRQ\fP"
.br
.ti -1c
.RI "#define \fBNVIC_ClearPendingIRQ\fP   \fB__NVIC_ClearPendingIRQ\fP"
.br
.ti -1c
.RI "#define \fBNVIC_GetActive\fP   \fB__NVIC_GetActive\fP"
.br
.ti -1c
.RI "#define \fBNVIC_SetPriority\fP   \fB__NVIC_SetPriority\fP"
.br
.ti -1c
.RI "#define \fBNVIC_GetPriority\fP   \fB__NVIC_GetPriority\fP"
.br
.ti -1c
.RI "#define \fBNVIC_SystemReset\fP   \fB__NVIC_SystemReset\fP"
.br
.ti -1c
.RI "#define \fBNVIC_SetVector\fP   \fB__NVIC_SetVector\fP"
.br
.ti -1c
.RI "#define \fBNVIC_GetVector\fP   \fB__NVIC_GetVector\fP"
.br
.ti -1c
.RI "#define \fBNVIC_USER_IRQ_OFFSET\fP   16"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__STATIC_INLINE\fP void \fB__NVIC_EnableIRQ\fP (\fBIRQn_Type\fP \fBIRQn\fP)"
.br
.RI "Enable Interrupt\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP uint32_t \fB__NVIC_GetEnableIRQ\fP (\fBIRQn_Type\fP \fBIRQn\fP)"
.br
.RI "Get Interrupt Enable status\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP void \fB__NVIC_DisableIRQ\fP (\fBIRQn_Type\fP \fBIRQn\fP)"
.br
.RI "Disable Interrupt\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP uint32_t \fB__NVIC_GetPendingIRQ\fP (\fBIRQn_Type\fP \fBIRQn\fP)"
.br
.RI "Get Pending Interrupt\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP void \fB__NVIC_SetPendingIRQ\fP (\fBIRQn_Type\fP \fBIRQn\fP)"
.br
.RI "Set Pending Interrupt\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP void \fB__NVIC_ClearPendingIRQ\fP (\fBIRQn_Type\fP \fBIRQn\fP)"
.br
.RI "Clear Pending Interrupt\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP uint32_t \fB__NVIC_GetActive\fP (\fBIRQn_Type\fP \fBIRQn\fP)"
.br
.RI "Get Active Interrupt\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP void \fB__NVIC_SetPriority\fP (\fBIRQn_Type\fP \fBIRQn\fP, uint32_t priority)"
.br
.RI "Set Interrupt Priority\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP uint32_t \fB__NVIC_GetPriority\fP (\fBIRQn_Type\fP \fBIRQn\fP)"
.br
.RI "Get Interrupt Priority\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP void \fB__NVIC_SetVector\fP (\fBIRQn_Type\fP \fBIRQn\fP, uint32_t vector)"
.br
.RI "Set Interrupt Vector\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP uint32_t \fB__NVIC_GetVector\fP (\fBIRQn_Type\fP \fBIRQn\fP)"
.br
.RI "Get Interrupt Vector\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP void \fB__NVIC_SystemReset\fP (void)"
.br
.RI "System Reset\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP void \fB__NVIC_SetPriorityGrouping\fP (uint32_t PriorityGroup)"
.br
.RI "Set Priority Grouping\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP uint32_t \fB__NVIC_GetPriorityGrouping\fP (void)"
.br
.RI "Get Priority Grouping\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP uint32_t \fBNVIC_EncodePriority\fP (uint32_t PriorityGroup, uint32_t PreemptPriority, uint32_t SubPriority)"
.br
.RI "Encode Priority\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP void \fBNVIC_DecodePriority\fP (uint32_t Priority, uint32_t PriorityGroup, uint32_t *const pPreemptPriority, uint32_t *const pSubPriority)"
.br
.RI "Decode Priority\&. "
.in -1c
.SH "Detailed Description"
.PP 
Functions that manage interrupts and exceptions via the NVIC\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define _BIT_SHIFT(\fBIRQn\fP)   (  ((((uint32_t)(int32_t)(\fBIRQn\fP))         )      &  0x03UL) * 8UL)"

.SS "#define _IP_IDX(\fBIRQn\fP)   (   (((uint32_t)(int32_t)(\fBIRQn\fP))                >>    2UL)      )"

.SS "#define _SHP_IDX(\fBIRQn\fP)   ( (((((uint32_t)(int32_t)(\fBIRQn\fP)) & 0x0FUL)\-8UL) >>    2UL)      )"

.SS "#define NVIC_ClearPendingIRQ   \fB__NVIC_ClearPendingIRQ\fP"

.SS "#define NVIC_ClearPendingIRQ   \fB__NVIC_ClearPendingIRQ\fP"

.SS "#define NVIC_ClearPendingIRQ   \fB__NVIC_ClearPendingIRQ\fP"

.SS "#define NVIC_DisableIRQ   \fB__NVIC_DisableIRQ\fP"

.SS "#define NVIC_DisableIRQ   \fB__NVIC_DisableIRQ\fP"

.SS "#define NVIC_DisableIRQ   \fB__NVIC_DisableIRQ\fP"

.SS "#define NVIC_EnableIRQ   \fB__NVIC_EnableIRQ\fP"

.SS "#define NVIC_EnableIRQ   \fB__NVIC_EnableIRQ\fP"

.SS "#define NVIC_EnableIRQ   \fB__NVIC_EnableIRQ\fP"

.SS "#define NVIC_GetActive   \fB__NVIC_GetActive\fP"

.SS "#define NVIC_GetActive   \fB__NVIC_GetActive\fP"

.SS "#define NVIC_GetActive   \fB__NVIC_GetActive\fP"

.SS "#define NVIC_GetEnableIRQ   \fB__NVIC_GetEnableIRQ\fP"

.SS "#define NVIC_GetEnableIRQ   \fB__NVIC_GetEnableIRQ\fP"

.SS "#define NVIC_GetEnableIRQ   \fB__NVIC_GetEnableIRQ\fP"

.SS "#define NVIC_GetPendingIRQ   \fB__NVIC_GetPendingIRQ\fP"

.SS "#define NVIC_GetPendingIRQ   \fB__NVIC_GetPendingIRQ\fP"

.SS "#define NVIC_GetPendingIRQ   \fB__NVIC_GetPendingIRQ\fP"

.SS "#define NVIC_GetPriority   \fB__NVIC_GetPriority\fP"

.SS "#define NVIC_GetPriority   \fB__NVIC_GetPriority\fP"

.SS "#define NVIC_GetPriority   \fB__NVIC_GetPriority\fP"

.SS "#define NVIC_GetPriorityGrouping   \fB__NVIC_GetPriorityGrouping\fP"

.SS "#define NVIC_GetPriorityGrouping   \fB__NVIC_GetPriorityGrouping\fP"

.SS "#define NVIC_GetVector   \fB__NVIC_GetVector\fP"

.SS "#define NVIC_GetVector   \fB__NVIC_GetVector\fP"

.SS "#define NVIC_GetVector   \fB__NVIC_GetVector\fP"

.SS "#define NVIC_SetPendingIRQ   \fB__NVIC_SetPendingIRQ\fP"

.SS "#define NVIC_SetPendingIRQ   \fB__NVIC_SetPendingIRQ\fP"

.SS "#define NVIC_SetPendingIRQ   \fB__NVIC_SetPendingIRQ\fP"

.SS "#define NVIC_SetPriority   \fB__NVIC_SetPriority\fP"

.SS "#define NVIC_SetPriority   \fB__NVIC_SetPriority\fP"

.SS "#define NVIC_SetPriority   \fB__NVIC_SetPriority\fP"

.SS "#define NVIC_SetPriorityGrouping   \fB__NVIC_SetPriorityGrouping\fP"

.SS "#define NVIC_SetPriorityGrouping   \fB__NVIC_SetPriorityGrouping\fP"

.SS "#define NVIC_SetVector   \fB__NVIC_SetVector\fP"

.SS "#define NVIC_SetVector   \fB__NVIC_SetVector\fP"

.SS "#define NVIC_SetVector   \fB__NVIC_SetVector\fP"

.SS "#define NVIC_SystemReset   \fB__NVIC_SystemReset\fP"

.SS "#define NVIC_SystemReset   \fB__NVIC_SystemReset\fP"

.SS "#define NVIC_SystemReset   \fB__NVIC_SystemReset\fP"

.SS "#define NVIC_USER_IRQ_OFFSET   16"

.SS "#define NVIC_USER_IRQ_OFFSET   16"

.SS "#define NVIC_USER_IRQ_OFFSET   16"

.SH "Function Documentation"
.PP 
.SS "\fB__STATIC_INLINE\fP void __NVIC_ClearPendingIRQ (\fBIRQn_Type\fP IRQn)"

.PP
Clear Pending Interrupt\&. Clears the pending bit of a device specific interrupt in the NVIC pending register\&. 
.PP
\fBParameters:\fP
.RS 4
\fIIRQn\fP Device specific interrupt number\&. 
.RE
.PP
\fBNote:\fP
.RS 4
IRQn must not be negative\&. 
.RE
.PP

.SS "\fB__STATIC_INLINE\fP void __NVIC_DisableIRQ (\fBIRQn_Type\fP IRQn)"

.PP
Disable Interrupt\&. Disables a device specific interrupt in the NVIC interrupt controller\&. 
.PP
\fBParameters:\fP
.RS 4
\fIIRQn\fP Device specific interrupt number\&. 
.RE
.PP
\fBNote:\fP
.RS 4
IRQn must not be negative\&. 
.RE
.PP

.SS "\fB__STATIC_INLINE\fP void __NVIC_EnableIRQ (\fBIRQn_Type\fP IRQn)"

.PP
Enable Interrupt\&. Enables a device specific interrupt in the NVIC interrupt controller\&. 
.PP
\fBParameters:\fP
.RS 4
\fIIRQn\fP Device specific interrupt number\&. 
.RE
.PP
\fBNote:\fP
.RS 4
IRQn must not be negative\&. 
.RE
.PP

.SS "\fB__STATIC_INLINE\fP uint32_t __NVIC_GetActive (\fBIRQn_Type\fP IRQn)"

.PP
Get Active Interrupt\&. Reads the active register in the NVIC and returns the active bit for the device specific interrupt\&. 
.PP
\fBParameters:\fP
.RS 4
\fIIRQn\fP Device specific interrupt number\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
0 Interrupt status is not active\&. 
.PP
1 Interrupt status is active\&. 
.RE
.PP
\fBNote:\fP
.RS 4
IRQn must not be negative\&. 
.RE
.PP

.SS "\fB__STATIC_INLINE\fP uint32_t __NVIC_GetEnableIRQ (\fBIRQn_Type\fP IRQn)"

.PP
Get Interrupt Enable status\&. Returns a device specific interrupt enable status from the NVIC interrupt controller\&. 
.PP
\fBParameters:\fP
.RS 4
\fIIRQn\fP Device specific interrupt number\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
0 Interrupt is not enabled\&. 
.PP
1 Interrupt is enabled\&. 
.RE
.PP
\fBNote:\fP
.RS 4
IRQn must not be negative\&. 
.RE
.PP

.SS "\fB__STATIC_INLINE\fP uint32_t __NVIC_GetPendingIRQ (\fBIRQn_Type\fP IRQn)"

.PP
Get Pending Interrupt\&. Reads the NVIC pending register and returns the pending bit for the specified device specific interrupt\&. 
.PP
\fBParameters:\fP
.RS 4
\fIIRQn\fP Device specific interrupt number\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
0 Interrupt status is not pending\&. 
.PP
1 Interrupt status is pending\&. 
.RE
.PP
\fBNote:\fP
.RS 4
IRQn must not be negative\&. 
.RE
.PP

.SS "\fB__STATIC_INLINE\fP uint32_t __NVIC_GetPriority (\fBIRQn_Type\fP IRQn)"

.PP
Get Interrupt Priority\&. Reads the priority of a device specific interrupt or a processor exception\&. The interrupt number can be positive to specify a device specific interrupt, or negative to specify a processor exception\&. 
.PP
\fBParameters:\fP
.RS 4
\fIIRQn\fP Interrupt number\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Interrupt Priority\&. Value is aligned automatically to the implemented priority bits of the microcontroller\&. 
.RE
.PP

.SS "\fB__STATIC_INLINE\fP uint32_t __NVIC_GetPriorityGrouping (void)"

.PP
Get Priority Grouping\&. Reads the priority grouping field from the NVIC Interrupt Controller\&. 
.PP
\fBReturns:\fP
.RS 4
Priority grouping field (SCB->AIRCR [10:8] PRIGROUP field)\&. 
.RE
.PP

.SS "\fB__STATIC_INLINE\fP uint32_t __NVIC_GetVector (\fBIRQn_Type\fP IRQn)"

.PP
Get Interrupt Vector\&. Reads an interrupt vector from interrupt vector table\&. The interrupt number can be positive to specify a device specific interrupt, or negative to specify a processor exception\&. 
.PP
\fBParameters:\fP
.RS 4
\fIIRQn\fP Interrupt number\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Address of interrupt handler function 
.RE
.PP

.SS "\fB__STATIC_INLINE\fP void __NVIC_SetPendingIRQ (\fBIRQn_Type\fP IRQn)"

.PP
Set Pending Interrupt\&. Sets the pending bit of a device specific interrupt in the NVIC pending register\&. 
.PP
\fBParameters:\fP
.RS 4
\fIIRQn\fP Device specific interrupt number\&. 
.RE
.PP
\fBNote:\fP
.RS 4
IRQn must not be negative\&. 
.RE
.PP

.SS "\fB__STATIC_INLINE\fP void __NVIC_SetPriority (\fBIRQn_Type\fP IRQn, uint32_t priority)"

.PP
Set Interrupt Priority\&. Sets the priority of a device specific interrupt or a processor exception\&. The interrupt number can be positive to specify a device specific interrupt, or negative to specify a processor exception\&. 
.PP
\fBParameters:\fP
.RS 4
\fIIRQn\fP Interrupt number\&. 
.br
\fIpriority\fP Priority to set\&. 
.RE
.PP
\fBNote:\fP
.RS 4
The priority cannot be set for every processor exception\&. 
.RE
.PP

.SS "\fB__STATIC_INLINE\fP void __NVIC_SetPriorityGrouping (uint32_t PriorityGroup)"

.PP
Set Priority Grouping\&. Sets the priority grouping field using the required unlock sequence\&. The parameter PriorityGroup is assigned to the field SCB->AIRCR [10:8] PRIGROUP field\&. Only values from 0\&.\&.7 are used\&. In case of a conflict between priority grouping and available priority bits (__NVIC_PRIO_BITS), the smallest possible priority group is set\&. 
.PP
\fBParameters:\fP
.RS 4
\fIPriorityGroup\fP Priority grouping field\&. 
.RE
.PP

.SS "\fB__STATIC_INLINE\fP void __NVIC_SetVector (\fBIRQn_Type\fP IRQn, uint32_t vector)"

.PP
Set Interrupt Vector\&. Sets an interrupt vector in SRAM based interrupt vector table\&. The interrupt number can be positive to specify a device specific interrupt, or negative to specify a processor exception\&. VTOR must been relocated to SRAM before\&. If VTOR is not present address 0 must be mapped to SRAM\&. 
.PP
\fBParameters:\fP
.RS 4
\fIIRQn\fP Interrupt number 
.br
\fIvector\fP Address of interrupt handler function
.RE
.PP
Sets an interrupt vector in SRAM based interrupt vector table\&. The interrupt number can be positive to specify a device specific interrupt, or negative to specify a processor exception\&. VTOR must been relocated to SRAM before\&. 
.PP
\fBParameters:\fP
.RS 4
\fIIRQn\fP Interrupt number 
.br
\fIvector\fP Address of interrupt handler function 
.RE
.PP

.SS "\fB__STATIC_INLINE\fP void __NVIC_SystemReset (void)"

.PP
System Reset\&. Initiates a system reset request to reset the MCU\&. 
.SS "\fB__STATIC_INLINE\fP void NVIC_DecodePriority (uint32_t Priority, uint32_t PriorityGroup, uint32_t *const pPreemptPriority, uint32_t *const pSubPriority)"

.PP
Decode Priority\&. Decodes an interrupt priority value with a given priority group to preemptive priority value and subpriority value\&. In case of a conflict between priority grouping and available priority bits (__NVIC_PRIO_BITS) the smallest possible priority group is set\&. 
.PP
\fBParameters:\fP
.RS 4
\fIPriority\fP Priority value, which can be retrieved with the function \fBNVIC_GetPriority()\fP\&. 
.br
\fIPriorityGroup\fP Used priority group\&. 
.br
\fIpPreemptPriority\fP Preemptive priority value (starting from 0)\&. 
.br
\fIpSubPriority\fP Subpriority value (starting from 0)\&. 
.RE
.PP

.SS "\fB__STATIC_INLINE\fP uint32_t NVIC_EncodePriority (uint32_t PriorityGroup, uint32_t PreemptPriority, uint32_t SubPriority)"

.PP
Encode Priority\&. Encodes the priority for an interrupt with the given priority group, preemptive priority value, and subpriority value\&. In case of a conflict between priority grouping and available priority bits (__NVIC_PRIO_BITS), the smallest possible priority group is set\&. 
.PP
\fBParameters:\fP
.RS 4
\fIPriorityGroup\fP Used priority group\&. 
.br
\fIPreemptPriority\fP Preemptive priority value (starting from 0)\&. 
.br
\fISubPriority\fP Subpriority value (starting from 0)\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Encoded priority\&. Value can be used in the function \fBNVIC_SetPriority()\fP\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
