.TH "CMSIS_DWT" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_DWT \- Type definitions for the Data Watchpoint and Trace (DWT)  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBDWT_Type\fP"
.br
.RI "Structure type to access the Data Watchpoint and Trace Register (DWT)\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDWT_CTRL_NUMCOMP_Pos\fP   28U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NUMCOMP_Msk\fP   (0xFUL << DWT_CTRL_NUMCOMP_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOTRCPKT_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOTRCPKT_Msk\fP   (0x1UL << DWT_CTRL_NOTRCPKT_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOEXTTRIG_Pos\fP   26U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOEXTTRIG_Msk\fP   (0x1UL << DWT_CTRL_NOEXTTRIG_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOCYCCNT_Pos\fP   25U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOCYCCNT_Msk\fP   (0x1UL << DWT_CTRL_NOCYCCNT_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOPRFCNT_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOPRFCNT_Msk\fP   (0x1UL << DWT_CTRL_NOPRFCNT_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_ID_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_ID_Msk\fP   (0x1FUL << DWT_FUNCTION_ID_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_MATCHED_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_MATCHED_Msk\fP   (0x1UL << DWT_FUNCTION_MATCHED_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_DATAVSIZE_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_DATAVSIZE_Msk\fP   (0x3UL << DWT_FUNCTION_DATAVSIZE_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_ACTION_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_ACTION_Msk\fP   (0x3UL << DWT_FUNCTION_ACTION_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_MATCH_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_MATCH_Msk\fP   (0xFUL /*<< DWT_FUNCTION_MATCH_Pos*/)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NUMCOMP_Pos\fP   28U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NUMCOMP_Msk\fP   (0xFUL << DWT_CTRL_NUMCOMP_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOTRCPKT_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOTRCPKT_Msk\fP   (0x1UL << DWT_CTRL_NOTRCPKT_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOEXTTRIG_Pos\fP   26U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOEXTTRIG_Msk\fP   (0x1UL << DWT_CTRL_NOEXTTRIG_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOCYCCNT_Pos\fP   25U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOCYCCNT_Msk\fP   (0x1UL << DWT_CTRL_NOCYCCNT_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOPRFCNT_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOPRFCNT_Msk\fP   (0x1UL << DWT_CTRL_NOPRFCNT_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_CYCDISS_Pos\fP   23U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_CYCDISS_Msk\fP   (0x1UL << DWT_CTRL_CYCDISS_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_CYCEVTENA_Pos\fP   22U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_CYCEVTENA_Msk\fP   (0x1UL << DWT_CTRL_CYCEVTENA_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_FOLDEVTENA_Pos\fP   21U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_FOLDEVTENA_Msk\fP   (0x1UL << DWT_CTRL_FOLDEVTENA_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_LSUEVTENA_Pos\fP   20U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_LSUEVTENA_Msk\fP   (0x1UL << DWT_CTRL_LSUEVTENA_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_SLEEPEVTENA_Pos\fP   19U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_SLEEPEVTENA_Msk\fP   (0x1UL << DWT_CTRL_SLEEPEVTENA_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_EXCEVTENA_Pos\fP   18U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_EXCEVTENA_Msk\fP   (0x1UL << DWT_CTRL_EXCEVTENA_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_CPIEVTENA_Pos\fP   17U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_CPIEVTENA_Msk\fP   (0x1UL << DWT_CTRL_CPIEVTENA_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_EXCTRCENA_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_EXCTRCENA_Msk\fP   (0x1UL << DWT_CTRL_EXCTRCENA_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_PCSAMPLENA_Pos\fP   12U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_PCSAMPLENA_Msk\fP   (0x1UL << DWT_CTRL_PCSAMPLENA_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_SYNCTAP_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_SYNCTAP_Msk\fP   (0x3UL << DWT_CTRL_SYNCTAP_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_CYCTAP_Pos\fP   9U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_CYCTAP_Msk\fP   (0x1UL << DWT_CTRL_CYCTAP_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_POSTINIT_Pos\fP   5U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_POSTINIT_Msk\fP   (0xFUL << DWT_CTRL_POSTINIT_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_POSTPRESET_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_POSTPRESET_Msk\fP   (0xFUL << DWT_CTRL_POSTPRESET_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_CYCCNTENA_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_CYCCNTENA_Msk\fP   (0x1UL /*<< DWT_CTRL_CYCCNTENA_Pos*/)"
.br
.ti -1c
.RI "#define \fBDWT_CPICNT_CPICNT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDWT_CPICNT_CPICNT_Msk\fP   (0xFFUL /*<< DWT_CPICNT_CPICNT_Pos*/)"
.br
.ti -1c
.RI "#define \fBDWT_EXCCNT_EXCCNT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDWT_EXCCNT_EXCCNT_Msk\fP   (0xFFUL /*<< DWT_EXCCNT_EXCCNT_Pos*/)"
.br
.ti -1c
.RI "#define \fBDWT_SLEEPCNT_SLEEPCNT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDWT_SLEEPCNT_SLEEPCNT_Msk\fP   (0xFFUL /*<< DWT_SLEEPCNT_SLEEPCNT_Pos*/)"
.br
.ti -1c
.RI "#define \fBDWT_LSUCNT_LSUCNT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDWT_LSUCNT_LSUCNT_Msk\fP   (0xFFUL /*<< DWT_LSUCNT_LSUCNT_Pos*/)"
.br
.ti -1c
.RI "#define \fBDWT_FOLDCNT_FOLDCNT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDWT_FOLDCNT_FOLDCNT_Msk\fP   (0xFFUL /*<< DWT_FOLDCNT_FOLDCNT_Pos*/)"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_ID_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_ID_Msk\fP   (0x1FUL << DWT_FUNCTION_ID_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_MATCHED_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_MATCHED_Msk\fP   (0x1UL << DWT_FUNCTION_MATCHED_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_DATAVSIZE_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_DATAVSIZE_Msk\fP   (0x3UL << DWT_FUNCTION_DATAVSIZE_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_ACTION_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_ACTION_Msk\fP   (0x1UL << DWT_FUNCTION_ACTION_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_MATCH_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_MATCH_Msk\fP   (0xFUL /*<< DWT_FUNCTION_MATCH_Pos*/)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NUMCOMP_Pos\fP   28U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NUMCOMP_Msk\fP   (0xFUL << DWT_CTRL_NUMCOMP_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOTRCPKT_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOTRCPKT_Msk\fP   (0x1UL << DWT_CTRL_NOTRCPKT_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOEXTTRIG_Pos\fP   26U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOEXTTRIG_Msk\fP   (0x1UL << DWT_CTRL_NOEXTTRIG_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOCYCCNT_Pos\fP   25U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOCYCCNT_Msk\fP   (0x1UL << DWT_CTRL_NOCYCCNT_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOPRFCNT_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOPRFCNT_Msk\fP   (0x1UL << DWT_CTRL_NOPRFCNT_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_CYCEVTENA_Pos\fP   22U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_CYCEVTENA_Msk\fP   (0x1UL << DWT_CTRL_CYCEVTENA_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_FOLDEVTENA_Pos\fP   21U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_FOLDEVTENA_Msk\fP   (0x1UL << DWT_CTRL_FOLDEVTENA_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_LSUEVTENA_Pos\fP   20U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_LSUEVTENA_Msk\fP   (0x1UL << DWT_CTRL_LSUEVTENA_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_SLEEPEVTENA_Pos\fP   19U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_SLEEPEVTENA_Msk\fP   (0x1UL << DWT_CTRL_SLEEPEVTENA_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_EXCEVTENA_Pos\fP   18U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_EXCEVTENA_Msk\fP   (0x1UL << DWT_CTRL_EXCEVTENA_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_CPIEVTENA_Pos\fP   17U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_CPIEVTENA_Msk\fP   (0x1UL << DWT_CTRL_CPIEVTENA_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_EXCTRCENA_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_EXCTRCENA_Msk\fP   (0x1UL << DWT_CTRL_EXCTRCENA_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_PCSAMPLENA_Pos\fP   12U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_PCSAMPLENA_Msk\fP   (0x1UL << DWT_CTRL_PCSAMPLENA_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_SYNCTAP_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_SYNCTAP_Msk\fP   (0x3UL << DWT_CTRL_SYNCTAP_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_CYCTAP_Pos\fP   9U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_CYCTAP_Msk\fP   (0x1UL << DWT_CTRL_CYCTAP_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_POSTINIT_Pos\fP   5U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_POSTINIT_Msk\fP   (0xFUL << DWT_CTRL_POSTINIT_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_POSTPRESET_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_POSTPRESET_Msk\fP   (0xFUL << DWT_CTRL_POSTPRESET_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_CYCCNTENA_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_CYCCNTENA_Msk\fP   (0x1UL /*<< DWT_CTRL_CYCCNTENA_Pos*/)"
.br
.ti -1c
.RI "#define \fBDWT_CPICNT_CPICNT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDWT_CPICNT_CPICNT_Msk\fP   (0xFFUL /*<< DWT_CPICNT_CPICNT_Pos*/)"
.br
.ti -1c
.RI "#define \fBDWT_EXCCNT_EXCCNT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDWT_EXCCNT_EXCCNT_Msk\fP   (0xFFUL /*<< DWT_EXCCNT_EXCCNT_Pos*/)"
.br
.ti -1c
.RI "#define \fBDWT_SLEEPCNT_SLEEPCNT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDWT_SLEEPCNT_SLEEPCNT_Msk\fP   (0xFFUL /*<< DWT_SLEEPCNT_SLEEPCNT_Pos*/)"
.br
.ti -1c
.RI "#define \fBDWT_LSUCNT_LSUCNT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDWT_LSUCNT_LSUCNT_Msk\fP   (0xFFUL /*<< DWT_LSUCNT_LSUCNT_Pos*/)"
.br
.ti -1c
.RI "#define \fBDWT_FOLDCNT_FOLDCNT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDWT_FOLDCNT_FOLDCNT_Msk\fP   (0xFFUL /*<< DWT_FOLDCNT_FOLDCNT_Pos*/)"
.br
.ti -1c
.RI "#define \fBDWT_MASK_MASK_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDWT_MASK_MASK_Msk\fP   (0x1FUL /*<< DWT_MASK_MASK_Pos*/)"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_MATCHED_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_MATCHED_Msk\fP   (0x1UL << DWT_FUNCTION_MATCHED_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_DATAVADDR1_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_DATAVADDR1_Msk\fP   (0xFUL << DWT_FUNCTION_DATAVADDR1_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_DATAVADDR0_Pos\fP   12U"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_DATAVADDR0_Msk\fP   (0xFUL << DWT_FUNCTION_DATAVADDR0_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_DATAVSIZE_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_DATAVSIZE_Msk\fP   (0x3UL << DWT_FUNCTION_DATAVSIZE_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_LNK1ENA_Pos\fP   9U"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_LNK1ENA_Msk\fP   (0x1UL << DWT_FUNCTION_LNK1ENA_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_DATAVMATCH_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_DATAVMATCH_Msk\fP   (0x1UL << DWT_FUNCTION_DATAVMATCH_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_CYCMATCH_Pos\fP   7U"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_CYCMATCH_Msk\fP   (0x1UL << DWT_FUNCTION_CYCMATCH_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_EMITRANGE_Pos\fP   5U"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_EMITRANGE_Msk\fP   (0x1UL << DWT_FUNCTION_EMITRANGE_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_FUNCTION_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_FUNCTION_Msk\fP   (0xFUL /*<< DWT_FUNCTION_FUNCTION_Pos*/)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Type definitions for the Data Watchpoint and Trace (DWT) 


.SH "Macro Definition Documentation"
.PP 
.SS "#define DWT_CPICNT_CPICNT_Msk   (0xFFUL /*<< DWT_CPICNT_CPICNT_Pos*/)"
DWT CPICNT: CPICNT Mask 
.SS "#define DWT_CPICNT_CPICNT_Msk   (0xFFUL /*<< DWT_CPICNT_CPICNT_Pos*/)"
DWT CPICNT: CPICNT Mask 
.SS "#define DWT_CPICNT_CPICNT_Pos   0U"
DWT CPICNT: CPICNT Position 
.SS "#define DWT_CPICNT_CPICNT_Pos   0U"
DWT CPICNT: CPICNT Position 
.SS "#define DWT_CTRL_CPIEVTENA_Msk   (0x1UL << DWT_CTRL_CPIEVTENA_Pos)"
DWT CTRL: CPIEVTENA Mask 
.SS "#define DWT_CTRL_CPIEVTENA_Msk   (0x1UL << DWT_CTRL_CPIEVTENA_Pos)"
DWT CTRL: CPIEVTENA Mask 
.SS "#define DWT_CTRL_CPIEVTENA_Pos   17U"
DWT CTRL: CPIEVTENA Position 
.SS "#define DWT_CTRL_CPIEVTENA_Pos   17U"
DWT CTRL: CPIEVTENA Position 
.SS "#define DWT_CTRL_CYCCNTENA_Msk   (0x1UL /*<< DWT_CTRL_CYCCNTENA_Pos*/)"
DWT CTRL: CYCCNTENA Mask 
.SS "#define DWT_CTRL_CYCCNTENA_Msk   (0x1UL /*<< DWT_CTRL_CYCCNTENA_Pos*/)"
DWT CTRL: CYCCNTENA Mask 
.SS "#define DWT_CTRL_CYCCNTENA_Pos   0U"
DWT CTRL: CYCCNTENA Position 
.SS "#define DWT_CTRL_CYCCNTENA_Pos   0U"
DWT CTRL: CYCCNTENA Position 
.SS "#define DWT_CTRL_CYCDISS_Msk   (0x1UL << DWT_CTRL_CYCDISS_Pos)"
DWT CTRL: CYCDISS Mask 
.SS "#define DWT_CTRL_CYCDISS_Pos   23U"
DWT CTRL: CYCDISS Position 
.SS "#define DWT_CTRL_CYCEVTENA_Msk   (0x1UL << DWT_CTRL_CYCEVTENA_Pos)"
DWT CTRL: CYCEVTENA Mask 
.SS "#define DWT_CTRL_CYCEVTENA_Msk   (0x1UL << DWT_CTRL_CYCEVTENA_Pos)"
DWT CTRL: CYCEVTENA Mask 
.SS "#define DWT_CTRL_CYCEVTENA_Pos   22U"
DWT CTRL: CYCEVTENA Position 
.SS "#define DWT_CTRL_CYCEVTENA_Pos   22U"
DWT CTRL: CYCEVTENA Position 
.SS "#define DWT_CTRL_CYCTAP_Msk   (0x1UL << DWT_CTRL_CYCTAP_Pos)"
DWT CTRL: CYCTAP Mask 
.SS "#define DWT_CTRL_CYCTAP_Msk   (0x1UL << DWT_CTRL_CYCTAP_Pos)"
DWT CTRL: CYCTAP Mask 
.SS "#define DWT_CTRL_CYCTAP_Pos   9U"
DWT CTRL: CYCTAP Position 
.SS "#define DWT_CTRL_CYCTAP_Pos   9U"
DWT CTRL: CYCTAP Position 
.SS "#define DWT_CTRL_EXCEVTENA_Msk   (0x1UL << DWT_CTRL_EXCEVTENA_Pos)"
DWT CTRL: EXCEVTENA Mask 
.SS "#define DWT_CTRL_EXCEVTENA_Msk   (0x1UL << DWT_CTRL_EXCEVTENA_Pos)"
DWT CTRL: EXCEVTENA Mask 
.SS "#define DWT_CTRL_EXCEVTENA_Pos   18U"
DWT CTRL: EXCEVTENA Position 
.SS "#define DWT_CTRL_EXCEVTENA_Pos   18U"
DWT CTRL: EXCEVTENA Position 
.SS "#define DWT_CTRL_EXCTRCENA_Msk   (0x1UL << DWT_CTRL_EXCTRCENA_Pos)"
DWT CTRL: EXCTRCENA Mask 
.SS "#define DWT_CTRL_EXCTRCENA_Msk   (0x1UL << DWT_CTRL_EXCTRCENA_Pos)"
DWT CTRL: EXCTRCENA Mask 
.SS "#define DWT_CTRL_EXCTRCENA_Pos   16U"
DWT CTRL: EXCTRCENA Position 
.SS "#define DWT_CTRL_EXCTRCENA_Pos   16U"
DWT CTRL: EXCTRCENA Position 
.SS "#define DWT_CTRL_FOLDEVTENA_Msk   (0x1UL << DWT_CTRL_FOLDEVTENA_Pos)"
DWT CTRL: FOLDEVTENA Mask 
.SS "#define DWT_CTRL_FOLDEVTENA_Msk   (0x1UL << DWT_CTRL_FOLDEVTENA_Pos)"
DWT CTRL: FOLDEVTENA Mask 
.SS "#define DWT_CTRL_FOLDEVTENA_Pos   21U"
DWT CTRL: FOLDEVTENA Position 
.SS "#define DWT_CTRL_FOLDEVTENA_Pos   21U"
DWT CTRL: FOLDEVTENA Position 
.SS "#define DWT_CTRL_LSUEVTENA_Msk   (0x1UL << DWT_CTRL_LSUEVTENA_Pos)"
DWT CTRL: LSUEVTENA Mask 
.SS "#define DWT_CTRL_LSUEVTENA_Msk   (0x1UL << DWT_CTRL_LSUEVTENA_Pos)"
DWT CTRL: LSUEVTENA Mask 
.SS "#define DWT_CTRL_LSUEVTENA_Pos   20U"
DWT CTRL: LSUEVTENA Position 
.SS "#define DWT_CTRL_LSUEVTENA_Pos   20U"
DWT CTRL: LSUEVTENA Position 
.SS "#define DWT_CTRL_NOCYCCNT_Msk   (0x1UL << DWT_CTRL_NOCYCCNT_Pos)"
DWT CTRL: NOCYCCNT Mask 
.SS "#define DWT_CTRL_NOCYCCNT_Msk   (0x1UL << DWT_CTRL_NOCYCCNT_Pos)"
DWT CTRL: NOCYCCNT Mask 
.SS "#define DWT_CTRL_NOCYCCNT_Msk   (0x1UL << DWT_CTRL_NOCYCCNT_Pos)"
DWT CTRL: NOCYCCNT Mask 
.SS "#define DWT_CTRL_NOCYCCNT_Pos   25U"
DWT CTRL: NOCYCCNT Position 
.SS "#define DWT_CTRL_NOCYCCNT_Pos   25U"
DWT CTRL: NOCYCCNT Position 
.SS "#define DWT_CTRL_NOCYCCNT_Pos   25U"
DWT CTRL: NOCYCCNT Position 
.SS "#define DWT_CTRL_NOEXTTRIG_Msk   (0x1UL << DWT_CTRL_NOEXTTRIG_Pos)"
DWT CTRL: NOEXTTRIG Mask 
.SS "#define DWT_CTRL_NOEXTTRIG_Msk   (0x1UL << DWT_CTRL_NOEXTTRIG_Pos)"
DWT CTRL: NOEXTTRIG Mask 
.SS "#define DWT_CTRL_NOEXTTRIG_Msk   (0x1UL << DWT_CTRL_NOEXTTRIG_Pos)"
DWT CTRL: NOEXTTRIG Mask 
.SS "#define DWT_CTRL_NOEXTTRIG_Pos   26U"
DWT CTRL: NOEXTTRIG Position 
.SS "#define DWT_CTRL_NOEXTTRIG_Pos   26U"
DWT CTRL: NOEXTTRIG Position 
.SS "#define DWT_CTRL_NOEXTTRIG_Pos   26U"
DWT CTRL: NOEXTTRIG Position 
.SS "#define DWT_CTRL_NOPRFCNT_Msk   (0x1UL << DWT_CTRL_NOPRFCNT_Pos)"
DWT CTRL: NOPRFCNT Mask 
.SS "#define DWT_CTRL_NOPRFCNT_Msk   (0x1UL << DWT_CTRL_NOPRFCNT_Pos)"
DWT CTRL: NOPRFCNT Mask 
.SS "#define DWT_CTRL_NOPRFCNT_Msk   (0x1UL << DWT_CTRL_NOPRFCNT_Pos)"
DWT CTRL: NOPRFCNT Mask 
.SS "#define DWT_CTRL_NOPRFCNT_Pos   24U"
DWT CTRL: NOPRFCNT Position 
.SS "#define DWT_CTRL_NOPRFCNT_Pos   24U"
DWT CTRL: NOPRFCNT Position 
.SS "#define DWT_CTRL_NOPRFCNT_Pos   24U"
DWT CTRL: NOPRFCNT Position 
.SS "#define DWT_CTRL_NOTRCPKT_Msk   (0x1UL << DWT_CTRL_NOTRCPKT_Pos)"
DWT CTRL: NOTRCPKT Mask 
.SS "#define DWT_CTRL_NOTRCPKT_Msk   (0x1UL << DWT_CTRL_NOTRCPKT_Pos)"
DWT CTRL: NOTRCPKT Mask 
.SS "#define DWT_CTRL_NOTRCPKT_Msk   (0x1UL << DWT_CTRL_NOTRCPKT_Pos)"
DWT CTRL: NOTRCPKT Mask 
.SS "#define DWT_CTRL_NOTRCPKT_Pos   27U"
DWT CTRL: NOTRCPKT Position 
.SS "#define DWT_CTRL_NOTRCPKT_Pos   27U"
DWT CTRL: NOTRCPKT Position 
.SS "#define DWT_CTRL_NOTRCPKT_Pos   27U"
DWT CTRL: NOTRCPKT Position 
.SS "#define DWT_CTRL_NUMCOMP_Msk   (0xFUL << DWT_CTRL_NUMCOMP_Pos)"
DWT CTRL: NUMCOMP Mask 
.SS "#define DWT_CTRL_NUMCOMP_Msk   (0xFUL << DWT_CTRL_NUMCOMP_Pos)"
DWT CTRL: NUMCOMP Mask 
.SS "#define DWT_CTRL_NUMCOMP_Msk   (0xFUL << DWT_CTRL_NUMCOMP_Pos)"
DWT CTRL: NUMCOMP Mask 
.SS "#define DWT_CTRL_NUMCOMP_Pos   28U"
DWT CTRL: NUMCOMP Position 
.SS "#define DWT_CTRL_NUMCOMP_Pos   28U"
DWT CTRL: NUMCOMP Position 
.SS "#define DWT_CTRL_NUMCOMP_Pos   28U"
DWT CTRL: NUMCOMP Position 
.SS "#define DWT_CTRL_PCSAMPLENA_Msk   (0x1UL << DWT_CTRL_PCSAMPLENA_Pos)"
DWT CTRL: PCSAMPLENA Mask 
.SS "#define DWT_CTRL_PCSAMPLENA_Msk   (0x1UL << DWT_CTRL_PCSAMPLENA_Pos)"
DWT CTRL: PCSAMPLENA Mask 
.SS "#define DWT_CTRL_PCSAMPLENA_Pos   12U"
DWT CTRL: PCSAMPLENA Position 
.SS "#define DWT_CTRL_PCSAMPLENA_Pos   12U"
DWT CTRL: PCSAMPLENA Position 
.SS "#define DWT_CTRL_POSTINIT_Msk   (0xFUL << DWT_CTRL_POSTINIT_Pos)"
DWT CTRL: POSTINIT Mask 
.SS "#define DWT_CTRL_POSTINIT_Msk   (0xFUL << DWT_CTRL_POSTINIT_Pos)"
DWT CTRL: POSTINIT Mask 
.SS "#define DWT_CTRL_POSTINIT_Pos   5U"
DWT CTRL: POSTINIT Position 
.SS "#define DWT_CTRL_POSTINIT_Pos   5U"
DWT CTRL: POSTINIT Position 
.SS "#define DWT_CTRL_POSTPRESET_Msk   (0xFUL << DWT_CTRL_POSTPRESET_Pos)"
DWT CTRL: POSTPRESET Mask 
.SS "#define DWT_CTRL_POSTPRESET_Msk   (0xFUL << DWT_CTRL_POSTPRESET_Pos)"
DWT CTRL: POSTPRESET Mask 
.SS "#define DWT_CTRL_POSTPRESET_Pos   1U"
DWT CTRL: POSTPRESET Position 
.SS "#define DWT_CTRL_POSTPRESET_Pos   1U"
DWT CTRL: POSTPRESET Position 
.SS "#define DWT_CTRL_SLEEPEVTENA_Msk   (0x1UL << DWT_CTRL_SLEEPEVTENA_Pos)"
DWT CTRL: SLEEPEVTENA Mask 
.SS "#define DWT_CTRL_SLEEPEVTENA_Msk   (0x1UL << DWT_CTRL_SLEEPEVTENA_Pos)"
DWT CTRL: SLEEPEVTENA Mask 
.SS "#define DWT_CTRL_SLEEPEVTENA_Pos   19U"
DWT CTRL: SLEEPEVTENA Position 
.SS "#define DWT_CTRL_SLEEPEVTENA_Pos   19U"
DWT CTRL: SLEEPEVTENA Position 
.SS "#define DWT_CTRL_SYNCTAP_Msk   (0x3UL << DWT_CTRL_SYNCTAP_Pos)"
DWT CTRL: SYNCTAP Mask 
.SS "#define DWT_CTRL_SYNCTAP_Msk   (0x3UL << DWT_CTRL_SYNCTAP_Pos)"
DWT CTRL: SYNCTAP Mask 
.SS "#define DWT_CTRL_SYNCTAP_Pos   10U"
DWT CTRL: SYNCTAP Position 
.SS "#define DWT_CTRL_SYNCTAP_Pos   10U"
DWT CTRL: SYNCTAP Position 
.SS "#define DWT_EXCCNT_EXCCNT_Msk   (0xFFUL /*<< DWT_EXCCNT_EXCCNT_Pos*/)"
DWT EXCCNT: EXCCNT Mask 
.SS "#define DWT_EXCCNT_EXCCNT_Msk   (0xFFUL /*<< DWT_EXCCNT_EXCCNT_Pos*/)"
DWT EXCCNT: EXCCNT Mask 
.SS "#define DWT_EXCCNT_EXCCNT_Pos   0U"
DWT EXCCNT: EXCCNT Position 
.SS "#define DWT_EXCCNT_EXCCNT_Pos   0U"
DWT EXCCNT: EXCCNT Position 
.SS "#define DWT_FOLDCNT_FOLDCNT_Msk   (0xFFUL /*<< DWT_FOLDCNT_FOLDCNT_Pos*/)"
DWT FOLDCNT: FOLDCNT Mask 
.SS "#define DWT_FOLDCNT_FOLDCNT_Msk   (0xFFUL /*<< DWT_FOLDCNT_FOLDCNT_Pos*/)"
DWT FOLDCNT: FOLDCNT Mask 
.SS "#define DWT_FOLDCNT_FOLDCNT_Pos   0U"
DWT FOLDCNT: FOLDCNT Position 
.SS "#define DWT_FOLDCNT_FOLDCNT_Pos   0U"
DWT FOLDCNT: FOLDCNT Position 
.SS "#define DWT_FUNCTION_ACTION_Msk   (0x3UL << DWT_FUNCTION_ACTION_Pos)"
DWT FUNCTION: ACTION Mask 
.SS "#define DWT_FUNCTION_ACTION_Msk   (0x1UL << DWT_FUNCTION_ACTION_Pos)"
DWT FUNCTION: ACTION Mask 
.SS "#define DWT_FUNCTION_ACTION_Pos   4U"
DWT FUNCTION: ACTION Position 
.SS "#define DWT_FUNCTION_ACTION_Pos   4U"
DWT FUNCTION: ACTION Position 
.SS "#define DWT_FUNCTION_CYCMATCH_Msk   (0x1UL << DWT_FUNCTION_CYCMATCH_Pos)"
DWT FUNCTION: CYCMATCH Mask 
.SS "#define DWT_FUNCTION_CYCMATCH_Pos   7U"
DWT FUNCTION: CYCMATCH Position 
.SS "#define DWT_FUNCTION_DATAVADDR0_Msk   (0xFUL << DWT_FUNCTION_DATAVADDR0_Pos)"
DWT FUNCTION: DATAVADDR0 Mask 
.SS "#define DWT_FUNCTION_DATAVADDR0_Pos   12U"
DWT FUNCTION: DATAVADDR0 Position 
.SS "#define DWT_FUNCTION_DATAVADDR1_Msk   (0xFUL << DWT_FUNCTION_DATAVADDR1_Pos)"
DWT FUNCTION: DATAVADDR1 Mask 
.SS "#define DWT_FUNCTION_DATAVADDR1_Pos   16U"
DWT FUNCTION: DATAVADDR1 Position 
.SS "#define DWT_FUNCTION_DATAVMATCH_Msk   (0x1UL << DWT_FUNCTION_DATAVMATCH_Pos)"
DWT FUNCTION: DATAVMATCH Mask 
.SS "#define DWT_FUNCTION_DATAVMATCH_Pos   8U"
DWT FUNCTION: DATAVMATCH Position 
.SS "#define DWT_FUNCTION_DATAVSIZE_Msk   (0x3UL << DWT_FUNCTION_DATAVSIZE_Pos)"
DWT FUNCTION: DATAVSIZE Mask 
.SS "#define DWT_FUNCTION_DATAVSIZE_Msk   (0x3UL << DWT_FUNCTION_DATAVSIZE_Pos)"
DWT FUNCTION: DATAVSIZE Mask 
.SS "#define DWT_FUNCTION_DATAVSIZE_Msk   (0x3UL << DWT_FUNCTION_DATAVSIZE_Pos)"
DWT FUNCTION: DATAVSIZE Mask 
.SS "#define DWT_FUNCTION_DATAVSIZE_Pos   10U"
DWT FUNCTION: DATAVSIZE Position 
.SS "#define DWT_FUNCTION_DATAVSIZE_Pos   10U"
DWT FUNCTION: DATAVSIZE Position 
.SS "#define DWT_FUNCTION_DATAVSIZE_Pos   10U"
DWT FUNCTION: DATAVSIZE Position 
.SS "#define DWT_FUNCTION_EMITRANGE_Msk   (0x1UL << DWT_FUNCTION_EMITRANGE_Pos)"
DWT FUNCTION: EMITRANGE Mask 
.SS "#define DWT_FUNCTION_EMITRANGE_Pos   5U"
DWT FUNCTION: EMITRANGE Position 
.SS "#define DWT_FUNCTION_FUNCTION_Msk   (0xFUL /*<< DWT_FUNCTION_FUNCTION_Pos*/)"
DWT FUNCTION: FUNCTION Mask 
.SS "#define DWT_FUNCTION_FUNCTION_Pos   0U"
DWT FUNCTION: FUNCTION Position 
.SS "#define DWT_FUNCTION_ID_Msk   (0x1FUL << DWT_FUNCTION_ID_Pos)"
DWT FUNCTION: ID Mask 
.SS "#define DWT_FUNCTION_ID_Msk   (0x1FUL << DWT_FUNCTION_ID_Pos)"
DWT FUNCTION: ID Mask 
.SS "#define DWT_FUNCTION_ID_Pos   27U"
DWT FUNCTION: ID Position 
.SS "#define DWT_FUNCTION_ID_Pos   27U"
DWT FUNCTION: ID Position 
.SS "#define DWT_FUNCTION_LNK1ENA_Msk   (0x1UL << DWT_FUNCTION_LNK1ENA_Pos)"
DWT FUNCTION: LNK1ENA Mask 
.SS "#define DWT_FUNCTION_LNK1ENA_Pos   9U"
DWT FUNCTION: LNK1ENA Position 
.SS "#define DWT_FUNCTION_MATCH_Msk   (0xFUL /*<< DWT_FUNCTION_MATCH_Pos*/)"
DWT FUNCTION: MATCH Mask 
.SS "#define DWT_FUNCTION_MATCH_Msk   (0xFUL /*<< DWT_FUNCTION_MATCH_Pos*/)"
DWT FUNCTION: MATCH Mask 
.SS "#define DWT_FUNCTION_MATCH_Pos   0U"
DWT FUNCTION: MATCH Position 
.SS "#define DWT_FUNCTION_MATCH_Pos   0U"
DWT FUNCTION: MATCH Position 
.SS "#define DWT_FUNCTION_MATCHED_Msk   (0x1UL << DWT_FUNCTION_MATCHED_Pos)"
DWT FUNCTION: MATCHED Mask 
.SS "#define DWT_FUNCTION_MATCHED_Msk   (0x1UL << DWT_FUNCTION_MATCHED_Pos)"
DWT FUNCTION: MATCHED Mask 
.SS "#define DWT_FUNCTION_MATCHED_Msk   (0x1UL << DWT_FUNCTION_MATCHED_Pos)"
DWT FUNCTION: MATCHED Mask 
.SS "#define DWT_FUNCTION_MATCHED_Pos   24U"
DWT FUNCTION: MATCHED Position 
.SS "#define DWT_FUNCTION_MATCHED_Pos   24U"
DWT FUNCTION: MATCHED Position 
.SS "#define DWT_FUNCTION_MATCHED_Pos   24U"
DWT FUNCTION: MATCHED Position 
.SS "#define DWT_LSUCNT_LSUCNT_Msk   (0xFFUL /*<< DWT_LSUCNT_LSUCNT_Pos*/)"
DWT LSUCNT: LSUCNT Mask 
.SS "#define DWT_LSUCNT_LSUCNT_Msk   (0xFFUL /*<< DWT_LSUCNT_LSUCNT_Pos*/)"
DWT LSUCNT: LSUCNT Mask 
.SS "#define DWT_LSUCNT_LSUCNT_Pos   0U"
DWT LSUCNT: LSUCNT Position 
.SS "#define DWT_LSUCNT_LSUCNT_Pos   0U"
DWT LSUCNT: LSUCNT Position 
.SS "#define DWT_MASK_MASK_Msk   (0x1FUL /*<< DWT_MASK_MASK_Pos*/)"
DWT MASK: MASK Mask 
.SS "#define DWT_MASK_MASK_Pos   0U"
DWT MASK: MASK Position 
.SS "#define DWT_SLEEPCNT_SLEEPCNT_Msk   (0xFFUL /*<< DWT_SLEEPCNT_SLEEPCNT_Pos*/)"
DWT SLEEPCNT: SLEEPCNT Mask 
.SS "#define DWT_SLEEPCNT_SLEEPCNT_Msk   (0xFFUL /*<< DWT_SLEEPCNT_SLEEPCNT_Pos*/)"
DWT SLEEPCNT: SLEEPCNT Mask 
.SS "#define DWT_SLEEPCNT_SLEEPCNT_Pos   0U"
DWT SLEEPCNT: SLEEPCNT Position 
.SS "#define DWT_SLEEPCNT_SLEEPCNT_Pos   0U"
DWT SLEEPCNT: SLEEPCNT Position 
.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
