.TH "CMSIS_core_base" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_core_base \- Definitions for base addresses, unions, and structures\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSCS_BASE\fP   (0xE000E000UL)"
.br
.ti -1c
.RI "#define \fBDWT_BASE\fP   (0xE0001000UL)"
.br
.ti -1c
.RI "#define \fBTPI_BASE\fP   (0xE0040000UL)"
.br
.ti -1c
.RI "#define \fBCoreDebug_BASE\fP   (0xE000EDF0UL)"
.br
.ti -1c
.RI "#define \fBSysTick_BASE\fP   (\fBSCS_BASE\fP +  0x0010UL)"
.br
.ti -1c
.RI "#define \fBNVIC_BASE\fP   (\fBSCS_BASE\fP +  0x0100UL)"
.br
.ti -1c
.RI "#define \fBSCB_BASE\fP   (\fBSCS_BASE\fP +  0x0D00UL)"
.br
.ti -1c
.RI "#define \fBSCB\fP   ((\fBSCB_Type\fP       *)     \fBSCB_BASE\fP         )"
.br
.ti -1c
.RI "#define \fBSysTick\fP   ((\fBSysTick_Type\fP   *)     \fBSysTick_BASE\fP     )"
.br
.ti -1c
.RI "#define \fBNVIC\fP   ((\fBNVIC_Type\fP      *)     \fBNVIC_BASE\fP        )"
.br
.ti -1c
.RI "#define \fBDWT\fP   ((\fBDWT_Type\fP       *)     \fBDWT_BASE\fP         )"
.br
.ti -1c
.RI "#define \fBTPI\fP   ((\fBTPI_Type\fP       *)     \fBTPI_BASE\fP         )"
.br
.ti -1c
.RI "#define \fBCoreDebug\fP   ((\fBCoreDebug_Type\fP *)     \fBCoreDebug_BASE\fP   )"
.br
.ti -1c
.RI "#define \fBSCS_BASE\fP   (0xE000E000UL)"
.br
.ti -1c
.RI "#define \fBITM_BASE\fP   (0xE0000000UL)"
.br
.ti -1c
.RI "#define \fBDWT_BASE\fP   (0xE0001000UL)"
.br
.ti -1c
.RI "#define \fBTPI_BASE\fP   (0xE0040000UL)"
.br
.ti -1c
.RI "#define \fBCoreDebug_BASE\fP   (0xE000EDF0UL)"
.br
.ti -1c
.RI "#define \fBSysTick_BASE\fP   (\fBSCS_BASE\fP +  0x0010UL)"
.br
.ti -1c
.RI "#define \fBNVIC_BASE\fP   (\fBSCS_BASE\fP +  0x0100UL)"
.br
.ti -1c
.RI "#define \fBSCB_BASE\fP   (\fBSCS_BASE\fP +  0x0D00UL)"
.br
.ti -1c
.RI "#define \fBSCnSCB\fP   ((\fBSCnSCB_Type\fP    *)     \fBSCS_BASE\fP         )"
.br
.ti -1c
.RI "#define \fBSCB\fP   ((\fBSCB_Type\fP       *)     \fBSCB_BASE\fP         )"
.br
.ti -1c
.RI "#define \fBSysTick\fP   ((\fBSysTick_Type\fP   *)     \fBSysTick_BASE\fP     )"
.br
.ti -1c
.RI "#define \fBNVIC\fP   ((\fBNVIC_Type\fP      *)     \fBNVIC_BASE\fP        )"
.br
.ti -1c
.RI "#define \fBITM\fP   ((\fBITM_Type\fP       *)     \fBITM_BASE\fP         )"
.br
.ti -1c
.RI "#define \fBDWT\fP   ((\fBDWT_Type\fP       *)     \fBDWT_BASE\fP         )"
.br
.ti -1c
.RI "#define \fBTPI\fP   ((\fBTPI_Type\fP       *)     \fBTPI_BASE\fP         )"
.br
.ti -1c
.RI "#define \fBCoreDebug\fP   ((\fBCoreDebug_Type\fP *)     \fBCoreDebug_BASE\fP   )"
.br
.ti -1c
.RI "#define \fBFPU_BASE\fP   (\fBSCS_BASE\fP +  0x0F30UL)"
.br
.ti -1c
.RI "#define \fBFPU\fP   ((\fBFPU_Type\fP       *)     \fBFPU_BASE\fP         )"
.br
.ti -1c
.RI "#define \fBSCS_BASE\fP   (0xE000E000UL)"
.br
.ti -1c
.RI "#define \fBITM_BASE\fP   (0xE0000000UL)"
.br
.ti -1c
.RI "#define \fBDWT_BASE\fP   (0xE0001000UL)"
.br
.ti -1c
.RI "#define \fBTPI_BASE\fP   (0xE0040000UL)"
.br
.ti -1c
.RI "#define \fBCoreDebug_BASE\fP   (0xE000EDF0UL)"
.br
.ti -1c
.RI "#define \fBSysTick_BASE\fP   (\fBSCS_BASE\fP +  0x0010UL)"
.br
.ti -1c
.RI "#define \fBNVIC_BASE\fP   (\fBSCS_BASE\fP +  0x0100UL)"
.br
.ti -1c
.RI "#define \fBSCB_BASE\fP   (\fBSCS_BASE\fP +  0x0D00UL)"
.br
.ti -1c
.RI "#define \fBSCnSCB\fP   ((\fBSCnSCB_Type\fP    *)     \fBSCS_BASE\fP      )"
.br
.ti -1c
.RI "#define \fBSCB\fP   ((\fBSCB_Type\fP       *)     \fBSCB_BASE\fP      )"
.br
.ti -1c
.RI "#define \fBSysTick\fP   ((\fBSysTick_Type\fP   *)     \fBSysTick_BASE\fP  )"
.br
.ti -1c
.RI "#define \fBNVIC\fP   ((\fBNVIC_Type\fP      *)     \fBNVIC_BASE\fP     )"
.br
.ti -1c
.RI "#define \fBITM\fP   ((\fBITM_Type\fP       *)     \fBITM_BASE\fP      )"
.br
.ti -1c
.RI "#define \fBDWT\fP   ((\fBDWT_Type\fP       *)     \fBDWT_BASE\fP      )"
.br
.ti -1c
.RI "#define \fBTPI\fP   ((\fBTPI_Type\fP       *)     \fBTPI_BASE\fP      )"
.br
.ti -1c
.RI "#define \fBCoreDebug\fP   ((\fBCoreDebug_Type\fP *)     \fBCoreDebug_BASE\fP)"
.br
.ti -1c
.RI "#define \fBFPU_BASE\fP   (\fBSCS_BASE\fP +  0x0F30UL)"
.br
.ti -1c
.RI "#define \fBFPU\fP   ((\fBFPU_Type\fP       *)     \fBFPU_BASE\fP      )"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definitions for base addresses, unions, and structures\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define CoreDebug   ((\fBCoreDebug_Type\fP *)     \fBCoreDebug_BASE\fP   )"
Core Debug configuration struct 
.SS "#define CoreDebug   ((\fBCoreDebug_Type\fP *)     \fBCoreDebug_BASE\fP)"
Core Debug configuration struct 
.SS "#define CoreDebug   ((\fBCoreDebug_Type\fP *)     \fBCoreDebug_BASE\fP   )"
Core Debug configuration struct 
.SS "#define CoreDebug_BASE   (0xE000EDF0UL)"
Core Debug Base Address 
.SS "#define CoreDebug_BASE   (0xE000EDF0UL)"
Core Debug Base Address 
.SS "#define CoreDebug_BASE   (0xE000EDF0UL)"
Core Debug Base Address 
.SS "#define DWT   ((\fBDWT_Type\fP       *)     \fBDWT_BASE\fP         )"
DWT configuration struct 
.SS "#define DWT   ((\fBDWT_Type\fP       *)     \fBDWT_BASE\fP      )"
DWT configuration struct 
.SS "#define DWT   ((\fBDWT_Type\fP       *)     \fBDWT_BASE\fP         )"
DWT configuration struct 
.SS "#define DWT_BASE   (0xE0001000UL)"
DWT Base Address 
.SS "#define DWT_BASE   (0xE0001000UL)"
DWT Base Address 
.SS "#define DWT_BASE   (0xE0001000UL)"
DWT Base Address 
.SS "#define FPU   ((\fBFPU_Type\fP       *)     \fBFPU_BASE\fP      )"
Floating Point Unit 
.SS "#define FPU   ((\fBFPU_Type\fP       *)     \fBFPU_BASE\fP         )"
Floating Point Unit 
.SS "#define FPU_BASE   (\fBSCS_BASE\fP +  0x0F30UL)"
Floating Point Unit 
.SS "#define FPU_BASE   (\fBSCS_BASE\fP +  0x0F30UL)"
Floating Point Unit 
.SS "#define ITM   ((\fBITM_Type\fP       *)     \fBITM_BASE\fP      )"
ITM configuration struct 
.SS "#define ITM   ((\fBITM_Type\fP       *)     \fBITM_BASE\fP         )"
ITM configuration struct 
.SS "#define ITM_BASE   (0xE0000000UL)"
ITM Base Address 
.SS "#define ITM_BASE   (0xE0000000UL)"
ITM Base Address 
.SS "#define NVIC   ((\fBNVIC_Type\fP      *)     \fBNVIC_BASE\fP        )"
NVIC configuration struct 
.SS "#define NVIC   ((\fBNVIC_Type\fP      *)     \fBNVIC_BASE\fP     )"
NVIC configuration struct 
.SS "#define NVIC   ((\fBNVIC_Type\fP      *)     \fBNVIC_BASE\fP        )"
NVIC configuration struct 
.SS "#define NVIC_BASE   (\fBSCS_BASE\fP +  0x0100UL)"
NVIC Base Address 
.SS "#define NVIC_BASE   (\fBSCS_BASE\fP +  0x0100UL)"
NVIC Base Address 
.SS "#define NVIC_BASE   (\fBSCS_BASE\fP +  0x0100UL)"
NVIC Base Address 
.SS "#define SCB   ((\fBSCB_Type\fP       *)     \fBSCB_BASE\fP         )"
SCB configuration struct 
.SS "#define SCB   ((\fBSCB_Type\fP       *)     \fBSCB_BASE\fP      )"
SCB configuration struct 
.SS "#define SCB   ((\fBSCB_Type\fP       *)     \fBSCB_BASE\fP         )"
SCB configuration struct 
.SS "#define SCB_BASE   (\fBSCS_BASE\fP +  0x0D00UL)"
System Control Block Base Address 
.SS "#define SCB_BASE   (\fBSCS_BASE\fP +  0x0D00UL)"
System Control Block Base Address 
.SS "#define SCB_BASE   (\fBSCS_BASE\fP +  0x0D00UL)"
System Control Block Base Address 
.SS "#define SCnSCB   ((\fBSCnSCB_Type\fP    *)     \fBSCS_BASE\fP      )"
System control Register not in SCB 
.SS "#define SCnSCB   ((\fBSCnSCB_Type\fP    *)     \fBSCS_BASE\fP         )"
System control Register not in SCB 
.SS "#define SCS_BASE   (0xE000E000UL)"
System Control Space Base Address 
.SS "#define SCS_BASE   (0xE000E000UL)"
System Control Space Base Address 
.SS "#define SCS_BASE   (0xE000E000UL)"
System Control Space Base Address 
.SS "#define SysTick   ((\fBSysTick_Type\fP   *)     \fBSysTick_BASE\fP     )"
SysTick configuration struct 
.SS "#define SysTick   ((\fBSysTick_Type\fP   *)     \fBSysTick_BASE\fP  )"
SysTick configuration struct 
.SS "#define SysTick   ((\fBSysTick_Type\fP   *)     \fBSysTick_BASE\fP     )"
SysTick configuration struct 
.SS "#define SysTick_BASE   (\fBSCS_BASE\fP +  0x0010UL)"
SysTick Base Address 
.SS "#define SysTick_BASE   (\fBSCS_BASE\fP +  0x0010UL)"
SysTick Base Address 
.SS "#define SysTick_BASE   (\fBSCS_BASE\fP +  0x0010UL)"
SysTick Base Address 
.SS "#define TPI   ((\fBTPI_Type\fP       *)     \fBTPI_BASE\fP         )"
TPI configuration struct 
.SS "#define TPI   ((\fBTPI_Type\fP       *)     \fBTPI_BASE\fP      )"
TPI configuration struct 
.SS "#define TPI   ((\fBTPI_Type\fP       *)     \fBTPI_BASE\fP         )"
TPI configuration struct 
.SS "#define TPI_BASE   (0xE0040000UL)"
TPI Base Address 
.SS "#define TPI_BASE   (0xE0040000UL)"
TPI Base Address 
.SS "#define TPI_BASE   (0xE0040000UL)"
TPI Base Address 
.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
