.TH "CMT_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMT_Type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MK64F12\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint8_t \fBCGH1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBCGL1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBCGH2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBCGL2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBOC\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBMSC\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBCMD1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBCMD2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBCMD3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBCMD4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBPPS\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBDMA\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
CMT - Register Layout Typedef 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
