.TH "CONTROL_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CONTROL_Type \- Union type to access the Control Registers (CONTROL)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <core_armv8mbl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBnPRIV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBSPSEL\fP:1"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:30"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fBw\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBnPRIV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBSPSEL\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBFPCA\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBSFPA\fP:1"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:28"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBnPRIV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBSPSEL\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBFPCA\fP:1"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:29"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Union type to access the Control Registers (CONTROL)\&. 
.SH "Field Documentation"
.PP 
.SS "uint32_t _reserved0"
bit: 3\&.\&.31 Reserved 
.SS "uint32_t _reserved1"
bit: 2\&.\&.31 Reserved
.PP
bit: 4\&.\&.31 Reserved 
.SS "struct { \&.\&.\&. }   b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }   b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }   b"
Structure used for bit access 
.SS "uint32_t FPCA"
bit: 2 Floating-point context active
.PP
bit: 2 FP extension active flag 
.SS "uint32_t nPRIV"
bit: 0 Execution privilege in Thread mode 
.SS "uint32_t SFPA"
bit: 3 Secure floating-point active 
.SS "uint32_t SPSEL"
bit: 1 Stack-pointer select
.PP
bit: 1 Stack to be used 
.SS "uint32_t w"
Type used for word access 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
