.TH "CoreDebug_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreDebug_Type \- Structure type to access the Core Debug Register (CoreDebug)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <core_armv8mbl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBDHCSR\fP"
.br
.ti -1c
.RI "\fB__OM\fP uint32_t \fBDCRSR\fP"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBDCRDR\fP"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBDEMCR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED4\fP [1U]"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBDAUTHCTRL\fP"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBDSCSR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure type to access the Core Debug Register (CoreDebug)\&. 
.SH "Field Documentation"
.PP 
.SS "\fB__IOM\fP uint32_t DAUTHCTRL"
Offset: 0x014 (R/W) Debug Authentication Control Register 
.SS "\fB__IOM\fP uint32_t DCRDR"
Offset: 0x008 (R/W) Debug Core Register Data Register 
.SS "\fB__OM\fP uint32_t DCRSR"
Offset: 0x004 ( /W) Debug Core Register Selector Register 
.SS "\fB__IOM\fP uint32_t DEMCR"
Offset: 0x00C (R/W) Debug Exception and Monitor Control Register 
.SS "\fB__IOM\fP uint32_t DHCSR"
Offset: 0x000 (R/W) Debug Halting Control and Status Register 
.SS "\fB__IOM\fP uint32_t DSCSR"
Offset: 0x018 (R/W) Debug Security Control and Status Register 
.SS "uint32_t RESERVED4"


.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
