.TH "SDK/CMSIS/core_armv8mml.h" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDK/CMSIS/core_armv8mml.h \- CMSIS Armv8-M Mainline Core Peripheral Access Layer Header File\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include 'cmsis_version\&.h'\fP
.br
\fC#include 'cmsis_compiler\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "union \fBAPSR_Type\fP"
.br
.RI "Union type to access the Application Program Status Register (APSR)\&. "
.ti -1c
.RI "union \fBIPSR_Type\fP"
.br
.RI "Union type to access the Interrupt Program Status Register (IPSR)\&. "
.ti -1c
.RI "union \fBxPSR_Type\fP"
.br
.RI "Union type to access the Special-Purpose Program Status Registers (xPSR)\&. "
.ti -1c
.RI "union \fBCONTROL_Type\fP"
.br
.RI "Union type to access the Control Registers (CONTROL)\&. "
.ti -1c
.RI "struct \fBNVIC_Type\fP"
.br
.RI "Structure type to access the Nested Vectored Interrupt Controller (NVIC)\&. "
.ti -1c
.RI "struct \fBSCB_Type\fP"
.br
.RI "Structure type to access the System Control Block (SCB)\&. "
.ti -1c
.RI "struct \fBSCnSCB_Type\fP"
.br
.RI "Structure type to access the System Control and ID Register not in the SCB\&. "
.ti -1c
.RI "struct \fBSysTick_Type\fP"
.br
.RI "Structure type to access the System Timer (SysTick)\&. "
.ti -1c
.RI "struct \fBITM_Type\fP"
.br
.RI "Structure type to access the Instrumentation Trace Macrocell Register (ITM)\&. "
.ti -1c
.RI "struct \fBDWT_Type\fP"
.br
.RI "Structure type to access the Data Watchpoint and Trace Register (DWT)\&. "
.ti -1c
.RI "struct \fBTPI_Type\fP"
.br
.RI "Structure type to access the Trace Port Interface Register (TPI)\&. "
.ti -1c
.RI "struct \fBFPU_Type\fP"
.br
.RI "Structure type to access the Floating Point Unit (FPU)\&. "
.ti -1c
.RI "struct \fBCoreDebug_Type\fP"
.br
.RI "Structure type to access the Core Debug Register (CoreDebug)\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__CORE_ARMV8MML_H_GENERIC\fP"
.br
.ti -1c
.RI "#define \fBAPSR_N_Pos\fP   31U"
.br
.ti -1c
.RI "#define \fBAPSR_N_Msk\fP   (1UL << APSR_N_Pos)"
.br
.ti -1c
.RI "#define \fBAPSR_Z_Pos\fP   30U"
.br
.ti -1c
.RI "#define \fBAPSR_Z_Msk\fP   (1UL << APSR_Z_Pos)"
.br
.ti -1c
.RI "#define \fBAPSR_C_Pos\fP   29U"
.br
.ti -1c
.RI "#define \fBAPSR_C_Msk\fP   (1UL << APSR_C_Pos)"
.br
.ti -1c
.RI "#define \fBAPSR_V_Pos\fP   28U"
.br
.ti -1c
.RI "#define \fBAPSR_V_Msk\fP   (1UL << APSR_V_Pos)"
.br
.ti -1c
.RI "#define \fBAPSR_Q_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBAPSR_Q_Msk\fP   (1UL << APSR_Q_Pos)"
.br
.ti -1c
.RI "#define \fBAPSR_GE_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBAPSR_GE_Msk\fP   (0xFUL << APSR_GE_Pos)"
.br
.ti -1c
.RI "#define \fBIPSR_ISR_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBIPSR_ISR_Msk\fP   (0x1FFUL /*<< IPSR_ISR_Pos*/)"
.br
.ti -1c
.RI "#define \fBxPSR_N_Pos\fP   31U"
.br
.ti -1c
.RI "#define \fBxPSR_N_Msk\fP   (1UL << xPSR_N_Pos)"
.br
.ti -1c
.RI "#define \fBxPSR_Z_Pos\fP   30U"
.br
.ti -1c
.RI "#define \fBxPSR_Z_Msk\fP   (1UL << xPSR_Z_Pos)"
.br
.ti -1c
.RI "#define \fBxPSR_C_Pos\fP   29U"
.br
.ti -1c
.RI "#define \fBxPSR_C_Msk\fP   (1UL << xPSR_C_Pos)"
.br
.ti -1c
.RI "#define \fBxPSR_V_Pos\fP   28U"
.br
.ti -1c
.RI "#define \fBxPSR_V_Msk\fP   (1UL << xPSR_V_Pos)"
.br
.ti -1c
.RI "#define \fBxPSR_Q_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBxPSR_Q_Msk\fP   (1UL << xPSR_Q_Pos)"
.br
.ti -1c
.RI "#define \fBxPSR_IT_Pos\fP   25U"
.br
.ti -1c
.RI "#define \fBxPSR_IT_Msk\fP   (3UL << xPSR_IT_Pos)"
.br
.ti -1c
.RI "#define \fBxPSR_T_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBxPSR_T_Msk\fP   (1UL << xPSR_T_Pos)"
.br
.ti -1c
.RI "#define \fBxPSR_GE_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBxPSR_GE_Msk\fP   (0xFUL << xPSR_GE_Pos)"
.br
.ti -1c
.RI "#define \fBxPSR_ISR_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBxPSR_ISR_Msk\fP   (0x1FFUL /*<< xPSR_ISR_Pos*/)"
.br
.ti -1c
.RI "#define \fBCONTROL_SFPA_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBCONTROL_SFPA_Msk\fP   (1UL << CONTROL_SFPA_Pos)"
.br
.ti -1c
.RI "#define \fBCONTROL_FPCA_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBCONTROL_FPCA_Msk\fP   (1UL << CONTROL_FPCA_Pos)"
.br
.ti -1c
.RI "#define \fBCONTROL_SPSEL_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBCONTROL_SPSEL_Msk\fP   (1UL << CONTROL_SPSEL_Pos)"
.br
.ti -1c
.RI "#define \fBCONTROL_nPRIV_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBCONTROL_nPRIV_Msk\fP   (1UL /*<< CONTROL_nPRIV_Pos*/)"
.br
.ti -1c
.RI "#define \fBNVIC_STIR_INTID_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBNVIC_STIR_INTID_Msk\fP   (0x1FFUL /*<< NVIC_STIR_INTID_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_IMPLEMENTER_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_IMPLEMENTER_Msk\fP   (0xFFUL << SCB_CPUID_IMPLEMENTER_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_VARIANT_Pos\fP   20U"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_VARIANT_Msk\fP   (0xFUL << SCB_CPUID_VARIANT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_ARCHITECTURE_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_ARCHITECTURE_Msk\fP   (0xFUL << SCB_CPUID_ARCHITECTURE_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_PARTNO_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_PARTNO_Msk\fP   (0xFFFUL << SCB_CPUID_PARTNO_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_REVISION_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_REVISION_Msk\fP   (0xFUL /*<< SCB_CPUID_REVISION_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDNMISET_Pos\fP   31U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDNMISET_Msk\fP   (1UL << SCB_ICSR_PENDNMISET_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDNMICLR_Pos\fP   30U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDNMICLR_Msk\fP   (1UL << SCB_ICSR_PENDNMICLR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSVSET_Pos\fP   28U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSVSET_Msk\fP   (1UL << SCB_ICSR_PENDSVSET_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSVCLR_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSVCLR_Msk\fP   (1UL << SCB_ICSR_PENDSVCLR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSTSET_Pos\fP   26U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSTSET_Msk\fP   (1UL << SCB_ICSR_PENDSTSET_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSTCLR_Pos\fP   25U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSTCLR_Msk\fP   (1UL << SCB_ICSR_PENDSTCLR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_STTNS_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_STTNS_Msk\fP   (1UL << SCB_ICSR_STTNS_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_ISRPREEMPT_Pos\fP   23U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_ISRPREEMPT_Msk\fP   (1UL << SCB_ICSR_ISRPREEMPT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_ISRPENDING_Pos\fP   22U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_ISRPENDING_Msk\fP   (1UL << SCB_ICSR_ISRPENDING_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_VECTPENDING_Pos\fP   12U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_VECTPENDING_Msk\fP   (0x1FFUL << SCB_ICSR_VECTPENDING_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_RETTOBASE_Pos\fP   11U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_RETTOBASE_Msk\fP   (1UL << SCB_ICSR_RETTOBASE_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_VECTACTIVE_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_VECTACTIVE_Msk\fP   (0x1FFUL /*<< SCB_ICSR_VECTACTIVE_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_VTOR_TBLOFF_Pos\fP   7U"
.br
.ti -1c
.RI "#define \fBSCB_VTOR_TBLOFF_Msk\fP   (0x1FFFFFFUL << SCB_VTOR_TBLOFF_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTKEY_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTKEY_Msk\fP   (0xFFFFUL << SCB_AIRCR_VECTKEY_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTKEYSTAT_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTKEYSTAT_Msk\fP   (0xFFFFUL << SCB_AIRCR_VECTKEYSTAT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_ENDIANESS_Pos\fP   15U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_ENDIANESS_Msk\fP   (1UL << SCB_AIRCR_ENDIANESS_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_PRIS_Pos\fP   14U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_PRIS_Msk\fP   (1UL << SCB_AIRCR_PRIS_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_BFHFNMINS_Pos\fP   13U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_BFHFNMINS_Msk\fP   (1UL << SCB_AIRCR_BFHFNMINS_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_PRIGROUP_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_PRIGROUP_Msk\fP   (7UL << SCB_AIRCR_PRIGROUP_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_SYSRESETREQS_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_SYSRESETREQS_Msk\fP   (1UL << SCB_AIRCR_SYSRESETREQS_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_SYSRESETREQ_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_SYSRESETREQ_Msk\fP   (1UL << SCB_AIRCR_SYSRESETREQ_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTCLRACTIVE_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTCLRACTIVE_Msk\fP   (1UL << SCB_AIRCR_VECTCLRACTIVE_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SEVONPEND_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SEVONPEND_Msk\fP   (1UL << SCB_SCR_SEVONPEND_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SLEEPDEEPS_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SLEEPDEEPS_Msk\fP   (1UL << SCB_SCR_SLEEPDEEPS_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SLEEPDEEP_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SLEEPDEEP_Msk\fP   (1UL << SCB_SCR_SLEEPDEEP_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SLEEPONEXIT_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SLEEPONEXIT_Msk\fP   (1UL << SCB_SCR_SLEEPONEXIT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_BP_Pos\fP   18U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_BP_Msk\fP   (1UL << SCB_CCR_BP_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_IC_Pos\fP   17U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_IC_Msk\fP   (1UL << SCB_CCR_IC_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_DC_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_DC_Msk\fP   (1UL << SCB_CCR_DC_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_STKOFHFNMIGN_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_STKOFHFNMIGN_Msk\fP   (1UL << SCB_CCR_STKOFHFNMIGN_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_BFHFNMIGN_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_BFHFNMIGN_Msk\fP   (1UL << SCB_CCR_BFHFNMIGN_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_DIV_0_TRP_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_DIV_0_TRP_Msk\fP   (1UL << SCB_CCR_DIV_0_TRP_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_UNALIGN_TRP_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_UNALIGN_TRP_Msk\fP   (1UL << SCB_CCR_UNALIGN_TRP_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_USERSETMPEND_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_CCR_USERSETMPEND_Msk\fP   (1UL << SCB_CCR_USERSETMPEND_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_HARDFAULTPENDED_Pos\fP   21U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_HARDFAULTPENDED_Msk\fP   (1UL << SCB_SHCSR_HARDFAULTPENDED_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SECUREFAULTPENDED_Pos\fP   20U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SECUREFAULTPENDED_Msk\fP   (1UL << SCB_SHCSR_SECUREFAULTPENDED_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SECUREFAULTENA_Pos\fP   19U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SECUREFAULTENA_Msk\fP   (1UL << SCB_SHCSR_SECUREFAULTENA_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_USGFAULTENA_Pos\fP   18U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_USGFAULTENA_Msk\fP   (1UL << SCB_SHCSR_USGFAULTENA_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_BUSFAULTENA_Pos\fP   17U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_BUSFAULTENA_Msk\fP   (1UL << SCB_SHCSR_BUSFAULTENA_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_MEMFAULTENA_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_MEMFAULTENA_Msk\fP   (1UL << SCB_SHCSR_MEMFAULTENA_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SVCALLPENDED_Pos\fP   15U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SVCALLPENDED_Msk\fP   (1UL << SCB_SHCSR_SVCALLPENDED_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_BUSFAULTPENDED_Pos\fP   14U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_BUSFAULTPENDED_Msk\fP   (1UL << SCB_SHCSR_BUSFAULTPENDED_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_MEMFAULTPENDED_Pos\fP   13U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_MEMFAULTPENDED_Msk\fP   (1UL << SCB_SHCSR_MEMFAULTPENDED_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_USGFAULTPENDED_Pos\fP   12U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_USGFAULTPENDED_Msk\fP   (1UL << SCB_SHCSR_USGFAULTPENDED_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SYSTICKACT_Pos\fP   11U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SYSTICKACT_Msk\fP   (1UL << SCB_SHCSR_SYSTICKACT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_PENDSVACT_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_PENDSVACT_Msk\fP   (1UL << SCB_SHCSR_PENDSVACT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_MONITORACT_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_MONITORACT_Msk\fP   (1UL << SCB_SHCSR_MONITORACT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SVCALLACT_Pos\fP   7U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SVCALLACT_Msk\fP   (1UL << SCB_SHCSR_SVCALLACT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_NMIACT_Pos\fP   5U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_NMIACT_Msk\fP   (1UL << SCB_SHCSR_NMIACT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SECUREFAULTACT_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SECUREFAULTACT_Msk\fP   (1UL << SCB_SHCSR_SECUREFAULTACT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_USGFAULTACT_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_USGFAULTACT_Msk\fP   (1UL << SCB_SHCSR_USGFAULTACT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_HARDFAULTACT_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_HARDFAULTACT_Msk\fP   (1UL << SCB_SHCSR_HARDFAULTACT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_BUSFAULTACT_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_BUSFAULTACT_Msk\fP   (1UL << SCB_SHCSR_BUSFAULTACT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_MEMFAULTACT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_MEMFAULTACT_Msk\fP   (1UL /*<< SCB_SHCSR_MEMFAULTACT_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_USGFAULTSR_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_USGFAULTSR_Msk\fP   (0xFFFFUL << SCB_CFSR_USGFAULTSR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_BUSFAULTSR_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_BUSFAULTSR_Msk\fP   (0xFFUL << SCB_CFSR_BUSFAULTSR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MEMFAULTSR_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MEMFAULTSR_Msk\fP   (0xFFUL /*<< SCB_CFSR_MEMFAULTSR_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MMARVALID_Pos\fP   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 7U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MMARVALID_Msk\fP   (1UL << SCB_CFSR_MMARVALID_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MLSPERR_Pos\fP   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 5U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MLSPERR_Msk\fP   (1UL << SCB_CFSR_MLSPERR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MSTKERR_Pos\fP   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 4U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MSTKERR_Msk\fP   (1UL << SCB_CFSR_MSTKERR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MUNSTKERR_Pos\fP   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 3U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_MUNSTKERR_Msk\fP   (1UL << SCB_CFSR_MUNSTKERR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_DACCVIOL_Pos\fP   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 1U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_DACCVIOL_Msk\fP   (1UL << SCB_CFSR_DACCVIOL_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_IACCVIOL_Pos\fP   (\fBSCB_SHCSR_MEMFAULTACT_Pos\fP + 0U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_IACCVIOL_Msk\fP   (1UL /*<< SCB_CFSR_IACCVIOL_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_BFARVALID_Pos\fP   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 7U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_BFARVALID_Msk\fP   (1UL << SCB_CFSR_BFARVALID_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_LSPERR_Pos\fP   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 5U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_LSPERR_Msk\fP   (1UL << SCB_CFSR_LSPERR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_STKERR_Pos\fP   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 4U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_STKERR_Msk\fP   (1UL << SCB_CFSR_STKERR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_UNSTKERR_Pos\fP   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 3U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_UNSTKERR_Msk\fP   (1UL << SCB_CFSR_UNSTKERR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_IMPRECISERR_Pos\fP   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 2U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_IMPRECISERR_Msk\fP   (1UL << SCB_CFSR_IMPRECISERR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_PRECISERR_Pos\fP   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 1U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_PRECISERR_Msk\fP   (1UL << SCB_CFSR_PRECISERR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_IBUSERR_Pos\fP   (\fBSCB_CFSR_BUSFAULTSR_Pos\fP + 0U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_IBUSERR_Msk\fP   (1UL << SCB_CFSR_IBUSERR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_DIVBYZERO_Pos\fP   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 9U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_DIVBYZERO_Msk\fP   (1UL << SCB_CFSR_DIVBYZERO_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_UNALIGNED_Pos\fP   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 8U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_UNALIGNED_Msk\fP   (1UL << SCB_CFSR_UNALIGNED_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_STKOF_Pos\fP   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 4U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_STKOF_Msk\fP   (1UL << SCB_CFSR_STKOF_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_NOCP_Pos\fP   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 3U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_NOCP_Msk\fP   (1UL << SCB_CFSR_NOCP_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_INVPC_Pos\fP   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 2U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_INVPC_Msk\fP   (1UL << SCB_CFSR_INVPC_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_INVSTATE_Pos\fP   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 1U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_INVSTATE_Msk\fP   (1UL << SCB_CFSR_INVSTATE_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_UNDEFINSTR_Pos\fP   (\fBSCB_CFSR_USGFAULTSR_Pos\fP + 0U)"
.br
.ti -1c
.RI "#define \fBSCB_CFSR_UNDEFINSTR_Msk\fP   (1UL << SCB_CFSR_UNDEFINSTR_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_HFSR_DEBUGEVT_Pos\fP   31U"
.br
.ti -1c
.RI "#define \fBSCB_HFSR_DEBUGEVT_Msk\fP   (1UL << SCB_HFSR_DEBUGEVT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_HFSR_FORCED_Pos\fP   30U"
.br
.ti -1c
.RI "#define \fBSCB_HFSR_FORCED_Msk\fP   (1UL << SCB_HFSR_FORCED_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_HFSR_VECTTBL_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_HFSR_VECTTBL_Msk\fP   (1UL << SCB_HFSR_VECTTBL_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_EXTERNAL_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_EXTERNAL_Msk\fP   (1UL << SCB_DFSR_EXTERNAL_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_VCATCH_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_VCATCH_Msk\fP   (1UL << SCB_DFSR_VCATCH_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_DWTTRAP_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_DWTTRAP_Msk\fP   (1UL << SCB_DFSR_DWTTRAP_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_BKPT_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_BKPT_Msk\fP   (1UL << SCB_DFSR_BKPT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_HALTED_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_HALTED_Msk\fP   (1UL /*<< SCB_DFSR_HALTED_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_NSACR_CP11_Pos\fP   11U"
.br
.ti -1c
.RI "#define \fBSCB_NSACR_CP11_Msk\fP   (1UL << SCB_NSACR_CP11_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_NSACR_CP10_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBSCB_NSACR_CP10_Msk\fP   (1UL << SCB_NSACR_CP10_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_NSACR_CPn_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_NSACR_CPn_Msk\fP   (1UL /*<< SCB_NSACR_CPn_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_CLIDR_LOUU_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBSCB_CLIDR_LOUU_Msk\fP   (7UL << SCB_CLIDR_LOUU_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CLIDR_LOC_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBSCB_CLIDR_LOC_Msk\fP   (7UL << SCB_CLIDR_LOC_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CTR_FORMAT_Pos\fP   29U"
.br
.ti -1c
.RI "#define \fBSCB_CTR_FORMAT_Msk\fP   (7UL << SCB_CTR_FORMAT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CTR_CWG_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBSCB_CTR_CWG_Msk\fP   (0xFUL << SCB_CTR_CWG_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CTR_ERG_Pos\fP   20U"
.br
.ti -1c
.RI "#define \fBSCB_CTR_ERG_Msk\fP   (0xFUL << SCB_CTR_ERG_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CTR_DMINLINE_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBSCB_CTR_DMINLINE_Msk\fP   (0xFUL << SCB_CTR_DMINLINE_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CTR_IMINLINE_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_CTR_IMINLINE_Msk\fP   (0xFUL /*<< SCB_CTR_IMINLINE_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_CCSIDR_WT_Pos\fP   31U"
.br
.ti -1c
.RI "#define \fBSCB_CCSIDR_WT_Msk\fP   (1UL << SCB_CCSIDR_WT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCSIDR_WB_Pos\fP   30U"
.br
.ti -1c
.RI "#define \fBSCB_CCSIDR_WB_Msk\fP   (1UL << SCB_CCSIDR_WB_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCSIDR_RA_Pos\fP   29U"
.br
.ti -1c
.RI "#define \fBSCB_CCSIDR_RA_Msk\fP   (1UL << SCB_CCSIDR_RA_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCSIDR_WA_Pos\fP   28U"
.br
.ti -1c
.RI "#define \fBSCB_CCSIDR_WA_Msk\fP   (1UL << SCB_CCSIDR_WA_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCSIDR_NUMSETS_Pos\fP   13U"
.br
.ti -1c
.RI "#define \fBSCB_CCSIDR_NUMSETS_Msk\fP   (0x7FFFUL << SCB_CCSIDR_NUMSETS_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCSIDR_ASSOCIATIVITY_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBSCB_CCSIDR_ASSOCIATIVITY_Msk\fP   (0x3FFUL << SCB_CCSIDR_ASSOCIATIVITY_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CCSIDR_LINESIZE_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_CCSIDR_LINESIZE_Msk\fP   (7UL /*<< SCB_CCSIDR_LINESIZE_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_CSSELR_LEVEL_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_CSSELR_LEVEL_Msk\fP   (7UL << SCB_CSSELR_LEVEL_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CSSELR_IND_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_CSSELR_IND_Msk\fP   (1UL /*<< SCB_CSSELR_IND_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_STIR_INTID_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_STIR_INTID_Msk\fP   (0x1FFUL /*<< SCB_STIR_INTID_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_DCISW_WAY_Pos\fP   30U"
.br
.ti -1c
.RI "#define \fBSCB_DCISW_WAY_Msk\fP   (3UL << SCB_DCISW_WAY_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DCISW_SET_Pos\fP   5U"
.br
.ti -1c
.RI "#define \fBSCB_DCISW_SET_Msk\fP   (0x1FFUL << SCB_DCISW_SET_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DCCSW_WAY_Pos\fP   30U"
.br
.ti -1c
.RI "#define \fBSCB_DCCSW_WAY_Msk\fP   (3UL << SCB_DCCSW_WAY_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DCCSW_SET_Pos\fP   5U"
.br
.ti -1c
.RI "#define \fBSCB_DCCSW_SET_Msk\fP   (0x1FFUL << SCB_DCCSW_SET_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DCCISW_WAY_Pos\fP   30U"
.br
.ti -1c
.RI "#define \fBSCB_DCCISW_WAY_Msk\fP   (3UL << SCB_DCCISW_WAY_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DCCISW_SET_Pos\fP   5U"
.br
.ti -1c
.RI "#define \fBSCB_DCCISW_SET_Msk\fP   (0x1FFUL << SCB_DCCISW_SET_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ITCMCR_SZ_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBSCB_ITCMCR_SZ_Msk\fP   (0xFUL << SCB_ITCMCR_SZ_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ITCMCR_RETEN_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCB_ITCMCR_RETEN_Msk\fP   (1UL << SCB_ITCMCR_RETEN_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ITCMCR_RMW_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_ITCMCR_RMW_Msk\fP   (1UL << SCB_ITCMCR_RMW_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ITCMCR_EN_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_ITCMCR_EN_Msk\fP   (1UL /*<< SCB_ITCMCR_EN_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_DTCMCR_SZ_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBSCB_DTCMCR_SZ_Msk\fP   (0xFUL << SCB_DTCMCR_SZ_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DTCMCR_RETEN_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCB_DTCMCR_RETEN_Msk\fP   (1UL << SCB_DTCMCR_RETEN_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DTCMCR_RMW_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_DTCMCR_RMW_Msk\fP   (1UL << SCB_DTCMCR_RMW_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_DTCMCR_EN_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_DTCMCR_EN_Msk\fP   (1UL /*<< SCB_DTCMCR_EN_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_AHBPCR_SZ_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_AHBPCR_SZ_Msk\fP   (7UL << SCB_AHBPCR_SZ_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AHBPCR_EN_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_AHBPCR_EN_Msk\fP   (1UL /*<< SCB_AHBPCR_EN_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_CACR_FORCEWT_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCB_CACR_FORCEWT_Msk\fP   (1UL << SCB_CACR_FORCEWT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CACR_ECCEN_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_CACR_ECCEN_Msk\fP   (1UL << SCB_CACR_ECCEN_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_CACR_SIWT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_CACR_SIWT_Msk\fP   (1UL /*<< SCB_CACR_SIWT_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_AHBSCR_INITCOUNT_Pos\fP   11U"
.br
.ti -1c
.RI "#define \fBSCB_AHBSCR_INITCOUNT_Msk\fP   (0x1FUL << SCB_AHBPCR_INITCOUNT_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AHBSCR_TPRI_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCB_AHBSCR_TPRI_Msk\fP   (0x1FFUL << SCB_AHBPCR_TPRI_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_AHBSCR_CTL_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_AHBSCR_CTL_Msk\fP   (3UL /*<< SCB_AHBPCR_CTL_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCB_ABFSR_AXIMTYPE_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBSCB_ABFSR_AXIMTYPE_Msk\fP   (3UL << SCB_ABFSR_AXIMTYPE_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ABFSR_EPPB_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBSCB_ABFSR_EPPB_Msk\fP   (1UL << SCB_ABFSR_EPPB_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ABFSR_AXIM_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBSCB_ABFSR_AXIM_Msk\fP   (1UL << SCB_ABFSR_AXIM_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ABFSR_AHBP_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCB_ABFSR_AHBP_Msk\fP   (1UL << SCB_ABFSR_AHBP_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ABFSR_DTCM_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCB_ABFSR_DTCM_Msk\fP   (1UL << SCB_ABFSR_DTCM_Pos)"
.br
.ti -1c
.RI "#define \fBSCB_ABFSR_ITCM_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCB_ABFSR_ITCM_Msk\fP   (1UL /*<< SCB_ABFSR_ITCM_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Msk\fP   (0xFUL /*<< SCnSCB_ICTR_INTLINESNUM_Pos*/)"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_COUNTFLAG_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_COUNTFLAG_Msk\fP   (1UL << SysTick_CTRL_COUNTFLAG_Pos)"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_CLKSOURCE_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_CLKSOURCE_Msk\fP   (1UL << SysTick_CTRL_CLKSOURCE_Pos)"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_TICKINT_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_TICKINT_Msk\fP   (1UL << SysTick_CTRL_TICKINT_Pos)"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_ENABLE_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_ENABLE_Msk\fP   (1UL /*<< SysTick_CTRL_ENABLE_Pos*/)"
.br
.ti -1c
.RI "#define \fBSysTick_LOAD_RELOAD_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSysTick_LOAD_RELOAD_Msk\fP   (0xFFFFFFUL /*<< SysTick_LOAD_RELOAD_Pos*/)"
.br
.ti -1c
.RI "#define \fBSysTick_VAL_CURRENT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSysTick_VAL_CURRENT_Msk\fP   (0xFFFFFFUL /*<< SysTick_VAL_CURRENT_Pos*/)"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_NOREF_Pos\fP   31U"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_NOREF_Msk\fP   (1UL << SysTick_CALIB_NOREF_Pos)"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_SKEW_Pos\fP   30U"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_SKEW_Msk\fP   (1UL << SysTick_CALIB_SKEW_Pos)"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_TENMS_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_TENMS_Msk\fP   (0xFFFFFFUL /*<< SysTick_CALIB_TENMS_Pos*/)"
.br
.ti -1c
.RI "#define \fBITM_STIM_DISABLED_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBITM_STIM_DISABLED_Msk\fP   (0x1UL << ITM_STIM_DISABLED_Pos)"
.br
.ti -1c
.RI "#define \fBITM_STIM_FIFOREADY_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBITM_STIM_FIFOREADY_Msk\fP   (0x1UL /*<< ITM_STIM_FIFOREADY_Pos*/)"
.br
.ti -1c
.RI "#define \fBITM_TPR_PRIVMASK_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBITM_TPR_PRIVMASK_Msk\fP   (0xFUL /*<< ITM_TPR_PRIVMASK_Pos*/)"
.br
.ti -1c
.RI "#define \fBITM_TCR_BUSY_Pos\fP   23U"
.br
.ti -1c
.RI "#define \fBITM_TCR_BUSY_Msk\fP   (1UL << ITM_TCR_BUSY_Pos)"
.br
.ti -1c
.RI "#define \fBITM_TCR_TRACEBUSID_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBITM_TCR_TRACEBUSID_Msk\fP   (0x7FUL << ITM_TCR_TRACEBUSID_Pos)"
.br
.ti -1c
.RI "#define \fBITM_TCR_GTSFREQ_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBITM_TCR_GTSFREQ_Msk\fP   (3UL << ITM_TCR_GTSFREQ_Pos)"
.br
.ti -1c
.RI "#define \fBITM_TCR_TSPRESCALE_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBITM_TCR_TSPRESCALE_Msk\fP   (3UL << ITM_TCR_TSPRESCALE_Pos)"
.br
.ti -1c
.RI "#define \fBITM_TCR_STALLENA_Pos\fP   5U"
.br
.ti -1c
.RI "#define \fBITM_TCR_STALLENA_Msk\fP   (1UL << ITM_TCR_STALLENA_Pos)"
.br
.ti -1c
.RI "#define \fBITM_TCR_SWOENA_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBITM_TCR_SWOENA_Msk\fP   (1UL << ITM_TCR_SWOENA_Pos)"
.br
.ti -1c
.RI "#define \fBITM_TCR_DWTENA_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBITM_TCR_DWTENA_Msk\fP   (1UL << ITM_TCR_DWTENA_Pos)"
.br
.ti -1c
.RI "#define \fBITM_TCR_SYNCENA_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBITM_TCR_SYNCENA_Msk\fP   (1UL << ITM_TCR_SYNCENA_Pos)"
.br
.ti -1c
.RI "#define \fBITM_TCR_TSENA_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBITM_TCR_TSENA_Msk\fP   (1UL << ITM_TCR_TSENA_Pos)"
.br
.ti -1c
.RI "#define \fBITM_TCR_ITMENA_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBITM_TCR_ITMENA_Msk\fP   (1UL /*<< ITM_TCR_ITMENA_Pos*/)"
.br
.ti -1c
.RI "#define \fBITM_IWR_ATVALIDM_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBITM_IWR_ATVALIDM_Msk\fP   (1UL /*<< ITM_IWR_ATVALIDM_Pos*/)"
.br
.ti -1c
.RI "#define \fBITM_IRR_ATREADYM_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBITM_IRR_ATREADYM_Msk\fP   (1UL /*<< ITM_IRR_ATREADYM_Pos*/)"
.br
.ti -1c
.RI "#define \fBITM_IMCR_INTEGRATION_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBITM_IMCR_INTEGRATION_Msk\fP   (1UL /*<< ITM_IMCR_INTEGRATION_Pos*/)"
.br
.ti -1c
.RI "#define \fBITM_LSR_ByteAcc_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBITM_LSR_ByteAcc_Msk\fP   (1UL << ITM_LSR_ByteAcc_Pos)"
.br
.ti -1c
.RI "#define \fBITM_LSR_Access_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBITM_LSR_Access_Msk\fP   (1UL << ITM_LSR_Access_Pos)"
.br
.ti -1c
.RI "#define \fBITM_LSR_Present_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBITM_LSR_Present_Msk\fP   (1UL /*<< ITM_LSR_Present_Pos*/)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NUMCOMP_Pos\fP   28U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NUMCOMP_Msk\fP   (0xFUL << DWT_CTRL_NUMCOMP_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOTRCPKT_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOTRCPKT_Msk\fP   (0x1UL << DWT_CTRL_NOTRCPKT_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOEXTTRIG_Pos\fP   26U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOEXTTRIG_Msk\fP   (0x1UL << DWT_CTRL_NOEXTTRIG_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOCYCCNT_Pos\fP   25U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOCYCCNT_Msk\fP   (0x1UL << DWT_CTRL_NOCYCCNT_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOPRFCNT_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_NOPRFCNT_Msk\fP   (0x1UL << DWT_CTRL_NOPRFCNT_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_CYCDISS_Pos\fP   23U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_CYCDISS_Msk\fP   (0x1UL << DWT_CTRL_CYCDISS_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_CYCEVTENA_Pos\fP   22U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_CYCEVTENA_Msk\fP   (0x1UL << DWT_CTRL_CYCEVTENA_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_FOLDEVTENA_Pos\fP   21U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_FOLDEVTENA_Msk\fP   (0x1UL << DWT_CTRL_FOLDEVTENA_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_LSUEVTENA_Pos\fP   20U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_LSUEVTENA_Msk\fP   (0x1UL << DWT_CTRL_LSUEVTENA_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_SLEEPEVTENA_Pos\fP   19U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_SLEEPEVTENA_Msk\fP   (0x1UL << DWT_CTRL_SLEEPEVTENA_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_EXCEVTENA_Pos\fP   18U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_EXCEVTENA_Msk\fP   (0x1UL << DWT_CTRL_EXCEVTENA_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_CPIEVTENA_Pos\fP   17U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_CPIEVTENA_Msk\fP   (0x1UL << DWT_CTRL_CPIEVTENA_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_EXCTRCENA_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_EXCTRCENA_Msk\fP   (0x1UL << DWT_CTRL_EXCTRCENA_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_PCSAMPLENA_Pos\fP   12U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_PCSAMPLENA_Msk\fP   (0x1UL << DWT_CTRL_PCSAMPLENA_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_SYNCTAP_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_SYNCTAP_Msk\fP   (0x3UL << DWT_CTRL_SYNCTAP_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_CYCTAP_Pos\fP   9U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_CYCTAP_Msk\fP   (0x1UL << DWT_CTRL_CYCTAP_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_POSTINIT_Pos\fP   5U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_POSTINIT_Msk\fP   (0xFUL << DWT_CTRL_POSTINIT_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_POSTPRESET_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_POSTPRESET_Msk\fP   (0xFUL << DWT_CTRL_POSTPRESET_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_CYCCNTENA_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDWT_CTRL_CYCCNTENA_Msk\fP   (0x1UL /*<< DWT_CTRL_CYCCNTENA_Pos*/)"
.br
.ti -1c
.RI "#define \fBDWT_CPICNT_CPICNT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDWT_CPICNT_CPICNT_Msk\fP   (0xFFUL /*<< DWT_CPICNT_CPICNT_Pos*/)"
.br
.ti -1c
.RI "#define \fBDWT_EXCCNT_EXCCNT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDWT_EXCCNT_EXCCNT_Msk\fP   (0xFFUL /*<< DWT_EXCCNT_EXCCNT_Pos*/)"
.br
.ti -1c
.RI "#define \fBDWT_SLEEPCNT_SLEEPCNT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDWT_SLEEPCNT_SLEEPCNT_Msk\fP   (0xFFUL /*<< DWT_SLEEPCNT_SLEEPCNT_Pos*/)"
.br
.ti -1c
.RI "#define \fBDWT_LSUCNT_LSUCNT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDWT_LSUCNT_LSUCNT_Msk\fP   (0xFFUL /*<< DWT_LSUCNT_LSUCNT_Pos*/)"
.br
.ti -1c
.RI "#define \fBDWT_FOLDCNT_FOLDCNT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDWT_FOLDCNT_FOLDCNT_Msk\fP   (0xFFUL /*<< DWT_FOLDCNT_FOLDCNT_Pos*/)"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_ID_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_ID_Msk\fP   (0x1FUL << DWT_FUNCTION_ID_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_MATCHED_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_MATCHED_Msk\fP   (0x1UL << DWT_FUNCTION_MATCHED_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_DATAVSIZE_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_DATAVSIZE_Msk\fP   (0x3UL << DWT_FUNCTION_DATAVSIZE_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_ACTION_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_ACTION_Msk\fP   (0x1UL << DWT_FUNCTION_ACTION_Pos)"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_MATCH_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDWT_FUNCTION_MATCH_Msk\fP   (0xFUL /*<< DWT_FUNCTION_MATCH_Pos*/)"
.br
.ti -1c
.RI "#define \fBTPI_ACPR_PRESCALER_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ACPR_PRESCALER_Msk\fP   (0x1FFFUL /*<< TPI_ACPR_PRESCALER_Pos*/)"
.br
.ti -1c
.RI "#define \fBTPI_SPPR_TXMODE_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_SPPR_TXMODE_Msk\fP   (0x3UL /*<< TPI_SPPR_TXMODE_Pos*/)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtNonStop_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtNonStop_Msk\fP   (0x1UL << TPI_FFSR_FtNonStop_Pos)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_TCPresent_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_TCPresent_Msk\fP   (0x1UL << TPI_FFSR_TCPresent_Pos)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtStopped_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtStopped_Msk\fP   (0x1UL << TPI_FFSR_FtStopped_Pos)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FlInProg_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FlInProg_Msk\fP   (0x1UL /*<< TPI_FFSR_FlInProg_Pos*/)"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_TrigIn_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_TrigIn_Msk\fP   (0x1UL << TPI_FFCR_TrigIn_Pos)"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_EnFCont_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_EnFCont_Msk\fP   (0x1UL << TPI_FFCR_EnFCont_Pos)"
.br
.ti -1c
.RI "#define \fBTPI_TRIGGER_TRIGGER_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_TRIGGER_TRIGGER_Msk\fP   (0x1UL /*<< TPI_TRIGGER_TRIGGER_Pos*/)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ITM_ATVALID_Pos\fP   29U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ITM_ATVALID_Msk\fP   (0x3UL << TPI_FIFO0_ITM_ATVALID_Pos)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ITM_bytecount_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ITM_bytecount_Msk\fP   (0x3UL << TPI_FIFO0_ITM_bytecount_Pos)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM_ATVALID_Pos\fP   26U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM_ATVALID_Msk\fP   (0x3UL << TPI_FIFO0_ETM_ATVALID_Pos)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM_bytecount_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM_bytecount_Msk\fP   (0x3UL << TPI_FIFO0_ETM_bytecount_Pos)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM2_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM2_Msk\fP   (0xFFUL << TPI_FIFO0_ETM2_Pos)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM1_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM1_Msk\fP   (0xFFUL << TPI_FIFO0_ETM1_Pos)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM0_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM0_Msk\fP   (0xFFUL /*<< TPI_FIFO0_ETM0_Pos*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_ATREADY_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_ATREADY_Msk\fP   (0x1UL /*<< TPI_ITATBCTR2_ATREADY_Pos*/)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM_ATVALID_Pos\fP   29U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM_ATVALID_Msk\fP   (0x3UL << TPI_FIFO1_ITM_ATVALID_Pos)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM_bytecount_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM_bytecount_Msk\fP   (0x3UL << TPI_FIFO1_ITM_bytecount_Pos)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ETM_ATVALID_Pos\fP   26U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ETM_ATVALID_Msk\fP   (0x3UL << TPI_FIFO1_ETM_ATVALID_Pos)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ETM_bytecount_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ETM_bytecount_Msk\fP   (0x3UL << TPI_FIFO1_ETM_bytecount_Pos)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM2_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM2_Msk\fP   (0xFFUL << TPI_FIFO1_ITM2_Pos)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM1_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM1_Msk\fP   (0xFFUL << TPI_FIFO1_ITM1_Pos)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM0_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM0_Msk\fP   (0xFFUL /*<< TPI_FIFO1_ITM0_Pos*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_ATREADY_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_ATREADY_Msk\fP   (0x1UL /*<< TPI_ITATBCTR0_ATREADY_Pos*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITCTRL_Mode_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITCTRL_Mode_Msk\fP   (0x1UL /*<< TPI_ITCTRL_Mode_Pos*/)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NRZVALID_Pos\fP   11U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NRZVALID_Msk\fP   (0x1UL << TPI_DEVID_NRZVALID_Pos)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MANCVALID_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MANCVALID_Msk\fP   (0x1UL << TPI_DEVID_MANCVALID_Pos)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_PTINVALID_Pos\fP   9U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_PTINVALID_Msk\fP   (0x1UL << TPI_DEVID_PTINVALID_Pos)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MinBufSz_Pos\fP   6U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MinBufSz_Msk\fP   (0x7UL << TPI_DEVID_MinBufSz_Pos)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_AsynClkIn_Pos\fP   5U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_AsynClkIn_Msk\fP   (0x1UL << TPI_DEVID_AsynClkIn_Pos)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NrTraceInput_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NrTraceInput_Msk\fP   (0x1FUL /*<< TPI_DEVID_NrTraceInput_Pos*/)"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_MajorType_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_MajorType_Msk\fP   (0xFUL << TPI_DEVTYPE_MajorType_Pos)"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_SubType_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_SubType_Msk\fP   (0xFUL /*<< TPI_DEVTYPE_SubType_Pos*/)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_ASPEN_Pos\fP   31U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_ASPEN_Msk\fP   (1UL << FPU_FPCCR_ASPEN_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_LSPEN_Pos\fP   30U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_LSPEN_Msk\fP   (1UL << FPU_FPCCR_LSPEN_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_LSPENS_Pos\fP   29U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_LSPENS_Msk\fP   (1UL << FPU_FPCCR_LSPENS_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_CLRONRET_Pos\fP   28U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_CLRONRET_Msk\fP   (1UL << FPU_FPCCR_CLRONRET_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_CLRONRETS_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_CLRONRETS_Msk\fP   (1UL << FPU_FPCCR_CLRONRETS_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_TS_Pos\fP   26U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_TS_Msk\fP   (1UL << FPU_FPCCR_TS_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_UFRDY_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_UFRDY_Msk\fP   (1UL << FPU_FPCCR_UFRDY_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_SPLIMVIOL_Pos\fP   9U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_SPLIMVIOL_Msk\fP   (1UL << FPU_FPCCR_SPLIMVIOL_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_MONRDY_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_MONRDY_Msk\fP   (1UL << FPU_FPCCR_MONRDY_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_SFRDY_Pos\fP   7U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_SFRDY_Msk\fP   (1UL << FPU_FPCCR_SFRDY_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_BFRDY_Pos\fP   6U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_BFRDY_Msk\fP   (1UL << FPU_FPCCR_BFRDY_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_MMRDY_Pos\fP   5U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_MMRDY_Msk\fP   (1UL << FPU_FPCCR_MMRDY_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_HFRDY_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_HFRDY_Msk\fP   (1UL << FPU_FPCCR_HFRDY_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_THREAD_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_THREAD_Msk\fP   (1UL << FPU_FPCCR_THREAD_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_S_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_S_Msk\fP   (1UL << FPU_FPCCR_S_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_USER_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_USER_Msk\fP   (1UL << FPU_FPCCR_USER_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_LSPACT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBFPU_FPCCR_LSPACT_Msk\fP   (1UL /*<< FPU_FPCCR_LSPACT_Pos*/)"
.br
.ti -1c
.RI "#define \fBFPU_FPCAR_ADDRESS_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBFPU_FPCAR_ADDRESS_Msk\fP   (0x1FFFFFFFUL << FPU_FPCAR_ADDRESS_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPDSCR_AHP_Pos\fP   26U"
.br
.ti -1c
.RI "#define \fBFPU_FPDSCR_AHP_Msk\fP   (1UL << FPU_FPDSCR_AHP_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPDSCR_DN_Pos\fP   25U"
.br
.ti -1c
.RI "#define \fBFPU_FPDSCR_DN_Msk\fP   (1UL << FPU_FPDSCR_DN_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPDSCR_FZ_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBFPU_FPDSCR_FZ_Msk\fP   (1UL << FPU_FPDSCR_FZ_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_FPDSCR_RMode_Pos\fP   22U"
.br
.ti -1c
.RI "#define \fBFPU_FPDSCR_RMode_Msk\fP   (3UL << FPU_FPDSCR_RMode_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_FP_rounding_modes_Pos\fP   28U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_FP_rounding_modes_Msk\fP   (0xFUL << FPU_MVFR0_FP_rounding_modes_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Short_vectors_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Short_vectors_Msk\fP   (0xFUL << FPU_MVFR0_Short_vectors_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Square_root_Pos\fP   20U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Square_root_Msk\fP   (0xFUL << FPU_MVFR0_Square_root_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Divide_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Divide_Msk\fP   (0xFUL << FPU_MVFR0_Divide_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_FP_excep_trapping_Pos\fP   12U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_FP_excep_trapping_Msk\fP   (0xFUL << FPU_MVFR0_FP_excep_trapping_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Double_precision_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Double_precision_Msk\fP   (0xFUL << FPU_MVFR0_Double_precision_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Single_precision_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_Single_precision_Msk\fP   (0xFUL << FPU_MVFR0_Single_precision_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_A_SIMD_registers_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR0_A_SIMD_registers_Msk\fP   (0xFUL /*<< FPU_MVFR0_A_SIMD_registers_Pos*/)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR1_FP_fused_MAC_Pos\fP   28U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR1_FP_fused_MAC_Msk\fP   (0xFUL << FPU_MVFR1_FP_fused_MAC_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR1_FP_HPFP_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR1_FP_HPFP_Msk\fP   (0xFUL << FPU_MVFR1_FP_HPFP_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR1_D_NaN_mode_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR1_D_NaN_mode_Msk\fP   (0xFUL << FPU_MVFR1_D_NaN_mode_Pos)"
.br
.ti -1c
.RI "#define \fBFPU_MVFR1_FtZ_mode_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBFPU_MVFR1_FtZ_mode_Msk\fP   (0xFUL /*<< FPU_MVFR1_FtZ_mode_Pos*/)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_DBGKEY_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_DBGKEY_Msk\fP   (0xFFFFUL << CoreDebug_DHCSR_DBGKEY_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_S_RESTART_ST_Pos\fP   26U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_S_RESTART_ST_Msk\fP   (1UL << CoreDebug_DHCSR_S_RESTART_ST_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_S_RESET_ST_Pos\fP   25U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_S_RESET_ST_Msk\fP   (1UL << CoreDebug_DHCSR_S_RESET_ST_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_S_RETIRE_ST_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_S_RETIRE_ST_Msk\fP   (1UL << CoreDebug_DHCSR_S_RETIRE_ST_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_S_LOCKUP_Pos\fP   19U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_S_LOCKUP_Msk\fP   (1UL << CoreDebug_DHCSR_S_LOCKUP_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_S_SLEEP_Pos\fP   18U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_S_SLEEP_Msk\fP   (1UL << CoreDebug_DHCSR_S_SLEEP_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_S_HALT_Pos\fP   17U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_S_HALT_Msk\fP   (1UL << CoreDebug_DHCSR_S_HALT_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_S_REGRDY_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_S_REGRDY_Msk\fP   (1UL << CoreDebug_DHCSR_S_REGRDY_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_C_SNAPSTALL_Pos\fP   5U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_C_SNAPSTALL_Msk\fP   (1UL << CoreDebug_DHCSR_C_SNAPSTALL_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_C_MASKINTS_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_C_MASKINTS_Msk\fP   (1UL << CoreDebug_DHCSR_C_MASKINTS_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_C_STEP_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_C_STEP_Msk\fP   (1UL << CoreDebug_DHCSR_C_STEP_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_C_HALT_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_C_HALT_Msk\fP   (1UL << CoreDebug_DHCSR_C_HALT_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_C_DEBUGEN_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_C_DEBUGEN_Msk\fP   (1UL /*<< CoreDebug_DHCSR_C_DEBUGEN_Pos*/)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DCRSR_REGWnR_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DCRSR_REGWnR_Msk\fP   (1UL << CoreDebug_DCRSR_REGWnR_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DCRSR_REGSEL_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DCRSR_REGSEL_Msk\fP   (0x1FUL /*<< CoreDebug_DCRSR_REGSEL_Pos*/)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_TRCENA_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_TRCENA_Msk\fP   (1UL << CoreDebug_DEMCR_TRCENA_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_MON_REQ_Pos\fP   19U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_MON_REQ_Msk\fP   (1UL << CoreDebug_DEMCR_MON_REQ_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_MON_STEP_Pos\fP   18U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_MON_STEP_Msk\fP   (1UL << CoreDebug_DEMCR_MON_STEP_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_MON_PEND_Pos\fP   17U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_MON_PEND_Msk\fP   (1UL << CoreDebug_DEMCR_MON_PEND_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_MON_EN_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_MON_EN_Msk\fP   (1UL << CoreDebug_DEMCR_MON_EN_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_VC_HARDERR_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_VC_HARDERR_Msk\fP   (1UL << CoreDebug_DEMCR_VC_HARDERR_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_VC_INTERR_Pos\fP   9U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_VC_INTERR_Msk\fP   (1UL << CoreDebug_DEMCR_VC_INTERR_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_VC_BUSERR_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_VC_BUSERR_Msk\fP   (1UL << CoreDebug_DEMCR_VC_BUSERR_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_VC_STATERR_Pos\fP   7U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_VC_STATERR_Msk\fP   (1UL << CoreDebug_DEMCR_VC_STATERR_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_VC_CHKERR_Pos\fP   6U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_VC_CHKERR_Msk\fP   (1UL << CoreDebug_DEMCR_VC_CHKERR_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_VC_NOCPERR_Pos\fP   5U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_VC_NOCPERR_Msk\fP   (1UL << CoreDebug_DEMCR_VC_NOCPERR_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_VC_MMERR_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_VC_MMERR_Msk\fP   (1UL << CoreDebug_DEMCR_VC_MMERR_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_VC_CORERESET_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_VC_CORERESET_Msk\fP   (1UL /*<< CoreDebug_DEMCR_VC_CORERESET_Pos*/)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DAUTHCTRL_INTSPNIDEN_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DAUTHCTRL_INTSPNIDEN_Msk\fP   (1UL << CoreDebug_DAUTHCTRL_INTSPNIDEN_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DAUTHCTRL_SPNIDENSEL_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DAUTHCTRL_SPNIDENSEL_Msk\fP   (1UL << CoreDebug_DAUTHCTRL_SPNIDENSEL_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DAUTHCTRL_INTSPIDEN_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DAUTHCTRL_INTSPIDEN_Msk\fP   (1UL << CoreDebug_DAUTHCTRL_INTSPIDEN_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DAUTHCTRL_SPIDENSEL_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DAUTHCTRL_SPIDENSEL_Msk\fP   (1UL /*<< CoreDebug_DAUTHCTRL_SPIDENSEL_Pos*/)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DSCSR_CDS_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DSCSR_CDS_Msk\fP   (1UL << CoreDebug_DSCSR_CDS_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DSCSR_SBRSEL_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DSCSR_SBRSEL_Msk\fP   (1UL << CoreDebug_DSCSR_SBRSEL_Pos)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DSCSR_SBRSELEN_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBCoreDebug_DSCSR_SBRSELEN_Msk\fP   (1UL /*<< CoreDebug_DSCSR_SBRSELEN_Pos*/)"
.br
.ti -1c
.RI "#define \fB_VAL2FLD\fP(field,  value)   (((uint32_t)(value) << field ## _Pos) & field ## _Msk)"
.br
.RI "Mask and shift a bit field value for use in a register bit range\&. "
.ti -1c
.RI "#define \fB_FLD2VAL\fP(field,  value)   (((uint32_t)(value) & field ## _Msk) >> field ## _Pos)"
.br
.RI "Mask and shift a register value to extract a bit filed value\&. "
.ti -1c
.RI "#define \fBSCS_BASE\fP   (0xE000E000UL)"
.br
.ti -1c
.RI "#define \fBITM_BASE\fP   (0xE0000000UL)"
.br
.ti -1c
.RI "#define \fBDWT_BASE\fP   (0xE0001000UL)"
.br
.ti -1c
.RI "#define \fBTPI_BASE\fP   (0xE0040000UL)"
.br
.ti -1c
.RI "#define \fBCoreDebug_BASE\fP   (0xE000EDF0UL)"
.br
.ti -1c
.RI "#define \fBSysTick_BASE\fP   (\fBSCS_BASE\fP +  0x0010UL)"
.br
.ti -1c
.RI "#define \fBNVIC_BASE\fP   (\fBSCS_BASE\fP +  0x0100UL)"
.br
.ti -1c
.RI "#define \fBSCB_BASE\fP   (\fBSCS_BASE\fP +  0x0D00UL)"
.br
.ti -1c
.RI "#define \fBSCnSCB\fP   ((\fBSCnSCB_Type\fP    *)     \fBSCS_BASE\fP         )"
.br
.ti -1c
.RI "#define \fBSCB\fP   ((\fBSCB_Type\fP       *)     \fBSCB_BASE\fP         )"
.br
.ti -1c
.RI "#define \fBSysTick\fP   ((\fBSysTick_Type\fP   *)     \fBSysTick_BASE\fP     )"
.br
.ti -1c
.RI "#define \fBNVIC\fP   ((\fBNVIC_Type\fP      *)     \fBNVIC_BASE\fP        )"
.br
.ti -1c
.RI "#define \fBITM\fP   ((\fBITM_Type\fP       *)     \fBITM_BASE\fP         )"
.br
.ti -1c
.RI "#define \fBDWT\fP   ((\fBDWT_Type\fP       *)     \fBDWT_BASE\fP         )"
.br
.ti -1c
.RI "#define \fBTPI\fP   ((\fBTPI_Type\fP       *)     \fBTPI_BASE\fP         )"
.br
.ti -1c
.RI "#define \fBCoreDebug\fP   ((\fBCoreDebug_Type\fP *)     \fBCoreDebug_BASE\fP   )"
.br
.ti -1c
.RI "#define \fBFPU_BASE\fP   (\fBSCS_BASE\fP +  0x0F30UL)"
.br
.ti -1c
.RI "#define \fBFPU\fP   ((\fBFPU_Type\fP       *)     \fBFPU_BASE\fP         )"
.br
.ti -1c
.RI "#define \fBNVIC_SetPriorityGrouping\fP   \fB__NVIC_SetPriorityGrouping\fP"
.br
.ti -1c
.RI "#define \fBNVIC_GetPriorityGrouping\fP   \fB__NVIC_GetPriorityGrouping\fP"
.br
.ti -1c
.RI "#define \fBNVIC_EnableIRQ\fP   \fB__NVIC_EnableIRQ\fP"
.br
.ti -1c
.RI "#define \fBNVIC_GetEnableIRQ\fP   \fB__NVIC_GetEnableIRQ\fP"
.br
.ti -1c
.RI "#define \fBNVIC_DisableIRQ\fP   \fB__NVIC_DisableIRQ\fP"
.br
.ti -1c
.RI "#define \fBNVIC_GetPendingIRQ\fP   \fB__NVIC_GetPendingIRQ\fP"
.br
.ti -1c
.RI "#define \fBNVIC_SetPendingIRQ\fP   \fB__NVIC_SetPendingIRQ\fP"
.br
.ti -1c
.RI "#define \fBNVIC_ClearPendingIRQ\fP   \fB__NVIC_ClearPendingIRQ\fP"
.br
.ti -1c
.RI "#define \fBNVIC_GetActive\fP   \fB__NVIC_GetActive\fP"
.br
.ti -1c
.RI "#define \fBNVIC_SetPriority\fP   \fB__NVIC_SetPriority\fP"
.br
.ti -1c
.RI "#define \fBNVIC_GetPriority\fP   \fB__NVIC_GetPriority\fP"
.br
.ti -1c
.RI "#define \fBNVIC_SystemReset\fP   \fB__NVIC_SystemReset\fP"
.br
.ti -1c
.RI "#define \fBNVIC_SetVector\fP   \fB__NVIC_SetVector\fP"
.br
.ti -1c
.RI "#define \fBNVIC_GetVector\fP   \fB__NVIC_GetVector\fP"
.br
.ti -1c
.RI "#define \fBNVIC_USER_IRQ_OFFSET\fP   16"
.br
.ti -1c
.RI "#define \fBITM_RXBUFFER_EMPTY\fP   ((int32_t)0x5AA55AA5U)"
.br
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "#define \fB__ARMv8MML_CMSIS_VERSION_MAIN\fP   (\fB__CM_CMSIS_VERSION_MAIN\fP)"
.br
.ti -1c
.RI "#define \fB__ARMv8MML_CMSIS_VERSION_SUB\fP   (\fB__CM_CMSIS_VERSION_SUB\fP)"
.br
.ti -1c
.RI "#define \fB__ARMv8MML_CMSIS_VERSION\fP"
.br
.ti -1c
.RI "#define \fB__CORTEX_M\fP   (81U)"
.br
.ti -1c
.RI "#define \fB__CORE_ARMV8MML_H_DEPENDANT\fP"
.br
.ti -1c
.RI "#define \fB__I\fP   volatile const"
.br
.ti -1c
.RI "#define \fB__O\fP   volatile"
.br
.ti -1c
.RI "#define \fB__IO\fP   volatile"
.br
.ti -1c
.RI "#define \fB__IM\fP   volatile const      /*! Defines 'read only' structure member permissions */"
.br
.ti -1c
.RI "#define \fB__OM\fP   volatile            /*! Defines 'write only' structure member permissions */"
.br
.ti -1c
.RI "#define \fB__IOM\fP   volatile            /*! Defines 'read / write' structure member permissions */"
.br
.in -1c
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__STATIC_INLINE\fP void \fB__NVIC_SetPriorityGrouping\fP (uint32_t PriorityGroup)"
.br
.RI "Set Priority Grouping\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP uint32_t \fB__NVIC_GetPriorityGrouping\fP (void)"
.br
.RI "Get Priority Grouping\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP void \fB__NVIC_EnableIRQ\fP (\fBIRQn_Type\fP \fBIRQn\fP)"
.br
.RI "Enable Interrupt\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP uint32_t \fB__NVIC_GetEnableIRQ\fP (\fBIRQn_Type\fP \fBIRQn\fP)"
.br
.RI "Get Interrupt Enable status\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP void \fB__NVIC_DisableIRQ\fP (\fBIRQn_Type\fP \fBIRQn\fP)"
.br
.RI "Disable Interrupt\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP uint32_t \fB__NVIC_GetPendingIRQ\fP (\fBIRQn_Type\fP \fBIRQn\fP)"
.br
.RI "Get Pending Interrupt\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP void \fB__NVIC_SetPendingIRQ\fP (\fBIRQn_Type\fP \fBIRQn\fP)"
.br
.RI "Set Pending Interrupt\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP void \fB__NVIC_ClearPendingIRQ\fP (\fBIRQn_Type\fP \fBIRQn\fP)"
.br
.RI "Clear Pending Interrupt\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP uint32_t \fB__NVIC_GetActive\fP (\fBIRQn_Type\fP \fBIRQn\fP)"
.br
.RI "Get Active Interrupt\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP void \fB__NVIC_SetPriority\fP (\fBIRQn_Type\fP \fBIRQn\fP, uint32_t priority)"
.br
.RI "Set Interrupt Priority\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP uint32_t \fB__NVIC_GetPriority\fP (\fBIRQn_Type\fP \fBIRQn\fP)"
.br
.RI "Get Interrupt Priority\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP uint32_t \fBNVIC_EncodePriority\fP (uint32_t PriorityGroup, uint32_t PreemptPriority, uint32_t SubPriority)"
.br
.RI "Encode Priority\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP void \fBNVIC_DecodePriority\fP (uint32_t Priority, uint32_t PriorityGroup, uint32_t *const pPreemptPriority, uint32_t *const pSubPriority)"
.br
.RI "Decode Priority\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP void \fB__NVIC_SetVector\fP (\fBIRQn_Type\fP \fBIRQn\fP, uint32_t vector)"
.br
.RI "Set Interrupt Vector\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP uint32_t \fB__NVIC_GetVector\fP (\fBIRQn_Type\fP \fBIRQn\fP)"
.br
.RI "Get Interrupt Vector\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP void \fB__NVIC_SystemReset\fP (void)"
.br
.RI "System Reset\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP uint32_t \fBSCB_GetFPUType\fP (void)"
.br
.RI "get FPU type "
.ti -1c
.RI "\fB__STATIC_INLINE\fP uint32_t \fBITM_SendChar\fP (uint32_t ch)"
.br
.RI "ITM Send Character\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP int32_t \fBITM_ReceiveChar\fP (void)"
.br
.RI "ITM Receive Character\&. "
.ti -1c
.RI "\fB__STATIC_INLINE\fP int32_t \fBITM_CheckChar\fP (void)"
.br
.RI "ITM Check Character\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "volatile int32_t \fBITM_RxBuffer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
CMSIS Armv8-M Mainline Core Peripheral Access Layer Header File\&. 


.PP
\fBVersion:\fP
.RS 4
V5\&.0\&.4 
.RE
.PP
\fBDate:\fP
.RS 4
10\&. January 2018 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define __ARMv8MML_CMSIS_VERSION"
\fBValue:\fP
.PP
.nf
((__ARMv8MML_CMSIS_VERSION_MAIN << 16U) | \
                                         __ARMv8MML_CMSIS_VERSION_SUB           )
.fi

.PP
\fBDeprecated\fP
.RS 4
CMSIS HAL version number 
.RE
.PP

.SS "#define __ARMv8MML_CMSIS_VERSION_MAIN   (\fB__CM_CMSIS_VERSION_MAIN\fP)"

.PP
\fBDeprecated\fP
.RS 4
[31:16] CMSIS HAL main version 
.RE
.PP

.SS "#define __ARMv8MML_CMSIS_VERSION_SUB   (\fB__CM_CMSIS_VERSION_SUB\fP)"

.PP
\fBDeprecated\fP
.RS 4
[15:0] CMSIS HAL sub version 
.RE
.PP

.SS "#define __CORE_ARMV8MML_H_DEPENDANT"
__FPU_USED indicates whether an FPU is used or not\&. For this, __FPU_PRESENT has to be checked prior to making use of FPU specific registers and functions\&. 
.SS "#define __CORE_ARMV8MML_H_GENERIC"

.SS "#define __CORTEX_M   (81U)"
Cortex-M Core 
.SS "#define __I   volatile const"
Defines 'read only' permissions 
.SS "#define __IM   volatile const      /*! Defines 'read only' structure member permissions */"

.SS "#define __IO   volatile"
Defines 'read / write' permissions 
.SS "#define __IOM   volatile            /*! Defines 'read / write' structure member permissions */"

.SS "#define __O   volatile"
Defines 'write only' permissions 
.SS "#define __OM   volatile            /*! Defines 'write only' structure member permissions */"

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
