.TH "Cortex_Core_Configuration" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cortex_Core_Configuration
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__MPU_PRESENT\fP   0"
.br
.ti -1c
.RI "#define \fB__NVIC_PRIO_BITS\fP   4"
.br
.ti -1c
.RI "#define \fB__Vendor_SysTickConfig\fP   0"
.br
.ti -1c
.RI "#define \fB__FPU_PRESENT\fP   1"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define __FPU_PRESENT   1"
Defines if an FPU is present or not 
.SS "#define __MPU_PRESENT   0"
Defines if an MPU is present or not 
.SS "#define __NVIC_PRIO_BITS   4"
Number of priority bits implemented in the NVIC 
.SS "#define __Vendor_SysTickConfig   0"
Vendor specific implementation of SysTickConfig is defined 
.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
