.TH "CRC_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CRC_Type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MK64F12\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      \fB__IO\fP uint16_t \fBDATAL\fP"
.br
.ti -1c
.RI "      \fB__IO\fP uint16_t \fBDATAH\fP"
.br
.ti -1c
.RI "   } \fBACCESS16BIT\fP"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBDATA\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      \fB__IO\fP uint8_t \fBDATALL\fP"
.br
.ti -1c
.RI "      \fB__IO\fP uint8_t \fBDATALU\fP"
.br
.ti -1c
.RI "      \fB__IO\fP uint8_t \fBDATAHL\fP"
.br
.ti -1c
.RI "      \fB__IO\fP uint8_t \fBDATAHU\fP"
.br
.ti -1c
.RI "   } \fBACCESS8BIT\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      \fB__IO\fP uint16_t \fBGPOLYL\fP"
.br
.ti -1c
.RI "      \fB__IO\fP uint16_t \fBGPOLYH\fP"
.br
.ti -1c
.RI "   } \fBGPOLY_ACCESS16BIT\fP"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBGPOLY\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      \fB__IO\fP uint8_t \fBGPOLYLL\fP"
.br
.ti -1c
.RI "      \fB__IO\fP uint8_t \fBGPOLYLU\fP"
.br
.ti -1c
.RI "      \fB__IO\fP uint8_t \fBGPOLYHL\fP"
.br
.ti -1c
.RI "      \fB__IO\fP uint8_t \fBGPOLYHU\fP"
.br
.ti -1c
.RI "   } \fBGPOLY_ACCESS8BIT\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBCTRL\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      uint8_t \fBRESERVED_0\fP [3]"
.br
.ti -1c
.RI "      \fB__IO\fP uint8_t \fBCTRLHU\fP"
.br
.ti -1c
.RI "   } \fBCTRL_ACCESS8BIT\fP"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
CRC - Register Layout Typedef 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
