.TH "Debug/drivers Directory Reference" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Debug/drivers Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDRV_Board\&.d\fP"
.br
.ti -1c
.RI "file \fBDRV_Display\&.d\fP"
.br
.ti -1c
.RI "file \fBDRV_Encoder\&.d\fP"
.br
.ti -1c
.RI "file \fBDRV_LEDs\&.d\fP"
.br
.ti -1c
.RI "file \fBDRV_Reader\&.d\fP"
.br
.ti -1c
.RI "file \fBDRV_Timers\&.d\fP"
.br
.ti -1c
.RI "file \fBPDRV_GPIO\&.d\fP"
.br
.ti -1c
.RI "file \fBPDRV_SysTick\&.d\fP"
.br
.in -1c
