.TH "SDK/startup Directory Reference" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDK/startup Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBhardware\&.c\fP"
.br
.ti -1c
.RI "file \fBhardware\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.RI "FW main\&. "
.ti -1c
.RI "file \fBsemihost_hardfault\&.c\fP"
.br
.ti -1c
.RI "file \fBstartup_mk64f12\&.c\fP"
.br
.in -1c
