.TH "drivers Directory Reference" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drivers Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDRV_Board\&.c\fP"
.br
.RI "FRDM Board management\&. "
.ti -1c
.RI "file \fBDRV_Board\&.h\fP"
.br
.RI "FRDM Board management\&. "
.ti -1c
.RI "file \fBDRV_Display\&.c\fP"
.br
.RI "7-segment display driver "
.ti -1c
.RI "file \fBDRV_Display\&.h\fP"
.br
.RI "7-segment display driver "
.ti -1c
.RI "file \fBDRV_Encoder\&.c\fP"
.br
.RI "Rotary encoder driver\&. "
.ti -1c
.RI "file \fBDRV_Encoder\&.h\fP"
.br
.RI "Rotary encoder driver\&. "
.ti -1c
.RI "file \fBDRV_LEDs\&.c\fP"
.br
.RI "LEDs driver\&. "
.ti -1c
.RI "file \fBDRV_LEDs\&.h\fP"
.br
.RI "LEDs driver\&. "
.ti -1c
.RI "file \fBDRV_Reader\&.c\fP"
.br
.RI "Card Reader driver\&. "
.ti -1c
.RI "file \fBDRV_Reader\&.h\fP"
.br
.RI "Card Reader driver\&. "
.ti -1c
.RI "file \fBDRV_Stub_Display\&.c\fP"
.br
.RI "stdout-based display stub driver "
.ti -1c
.RI "file \fBDRV_Stub_Encoder\&.c\fP"
.br
.RI "Rotary Encoder stub driver\&. "
.ti -1c
.RI "file \fBDRV_Timers\&.c\fP"
.br
.RI "Timers driver\&. "
.ti -1c
.RI "file \fBDRV_Timers\&.h\fP"
.br
.RI "Timers driver\&. "
.ti -1c
.RI "file \fBPDRV_GPIO\&.c\fP"
.br
.RI "GPIO driver\&. "
.ti -1c
.RI "file \fBPDRV_GPIO\&.h\fP"
.br
.RI "GPIO driver\&. "
.ti -1c
.RI "file \fBPDRV_SysTick\&.c\fP"
.br
.RI "SysTick driver\&. "
.ti -1c
.RI "file \fBPDRV_SysTick\&.h\fP"
.br
.RI "SysTick driver\&. "
.in -1c
