.TH "source Directory Reference" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAccountManager\&.c\fP"
.br
.ti -1c
.RI "file \fBAccountManager\&.h\fP"
.br
.ti -1c
.RI "file \fBApp\&.c\fP"
.br
.RI "Application functions\&. "
.ti -1c
.RI "file \fBNumberEditor\&.c\fP"
.br
.ti -1c
.RI "file \fBNumberEditor\&.h\fP"
.br
.in -1c
