.TH "DAC_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DAC_Type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MK64F12\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBDATL\fP"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBDATH\fP"
.br
.ti -1c
.RI "} \fBDAT\fP [16]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBC0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBC1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBC2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
DAC - Register Layout Typedef 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
