.TH "deprecated" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 

.IP "\fBGlobal \fB__ARMv8MBL_CMSIS_VERSION\fP \fP" 1c
CMSIS HAL version number  
.IP "\fBGlobal \fB__ARMv8MBL_CMSIS_VERSION_MAIN\fP \fP" 1c
[31:16] CMSIS HAL main version  
.IP "\fBGlobal \fB__ARMv8MBL_CMSIS_VERSION_SUB\fP \fP" 1c
[15:0] CMSIS HAL sub version  
.IP "\fBGlobal \fB__ARMv8MML_CMSIS_VERSION\fP \fP" 1c
CMSIS HAL version number  
.IP "\fBGlobal \fB__ARMv8MML_CMSIS_VERSION_MAIN\fP \fP" 1c
[31:16] CMSIS HAL main version  
.IP "\fBGlobal \fB__ARMv8MML_CMSIS_VERSION_SUB\fP \fP" 1c
[15:0] CMSIS HAL sub version  
.IP "\fBGlobal \fB__CM4_CMSIS_VERSION\fP \fP" 1c
CMSIS HAL version number  
.IP "\fBGlobal \fB__CM4_CMSIS_VERSION_MAIN\fP \fP" 1c
[31:16] CMSIS HAL main version  
.IP "\fBGlobal \fB__CM4_CMSIS_VERSION_SUB\fP \fP" 1c
[15:0] CMSIS HAL sub version 
.PP

