.TH "DMAMUX_Register_Masks" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMAMUX_Register_Masks
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDMAMUX_BASE\fP   (0x40021000u)"
.br
.ti -1c
.RI "#define \fBDMAMUX\fP   ((\fBDMAMUX_Type\fP *)\fBDMAMUX_BASE\fP)"
.br
.ti -1c
.RI "#define \fBDMAMUX_BASE_ADDRS\fP   { \fBDMAMUX_BASE\fP }"
.br
.ti -1c
.RI "#define \fBDMAMUX_BASE_PTRS\fP   { \fBDMAMUX\fP }"
.br
.in -1c
.SS "CHCFG - Channel Configuration register"

.in +1c
.ti -1c
.RI "#define \fBDMAMUX_CHCFG_SOURCE_MASK\fP   (0x3FU)"
.br
.ti -1c
.RI "#define \fBDMAMUX_CHCFG_SOURCE_SHIFT\fP   (0U)"
.br
.ti -1c
.RI "#define \fBDMAMUX_CHCFG_SOURCE\fP(x)   (((uint8_t)(((uint8_t)(x)) << \fBDMAMUX_CHCFG_SOURCE_SHIFT\fP)) & \fBDMAMUX_CHCFG_SOURCE_MASK\fP)"
.br
.ti -1c
.RI "#define \fBDMAMUX_CHCFG_TRIG_MASK\fP   (0x40U)"
.br
.ti -1c
.RI "#define \fBDMAMUX_CHCFG_TRIG_SHIFT\fP   (6U)"
.br
.ti -1c
.RI "#define \fBDMAMUX_CHCFG_TRIG\fP(x)   (((uint8_t)(((uint8_t)(x)) << \fBDMAMUX_CHCFG_TRIG_SHIFT\fP)) & \fBDMAMUX_CHCFG_TRIG_MASK\fP)"
.br
.ti -1c
.RI "#define \fBDMAMUX_CHCFG_ENBL_MASK\fP   (0x80U)"
.br
.ti -1c
.RI "#define \fBDMAMUX_CHCFG_ENBL_SHIFT\fP   (7U)"
.br
.ti -1c
.RI "#define \fBDMAMUX_CHCFG_ENBL\fP(x)   (((uint8_t)(((uint8_t)(x)) << \fBDMAMUX_CHCFG_ENBL_SHIFT\fP)) & \fBDMAMUX_CHCFG_ENBL_MASK\fP)"
.br
.ti -1c
.RI "#define \fBDMAMUX_CHCFG_COUNT\fP   (16U)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define DMAMUX   ((\fBDMAMUX_Type\fP *)\fBDMAMUX_BASE\fP)"
Peripheral DMAMUX base pointer 
.SS "#define DMAMUX_BASE   (0x40021000u)"
Peripheral DMAMUX base address 
.SS "#define DMAMUX_BASE_ADDRS   { \fBDMAMUX_BASE\fP }"
Array initializer of DMAMUX peripheral base addresses 
.SS "#define DMAMUX_BASE_PTRS   { \fBDMAMUX\fP }"
Array initializer of DMAMUX peripheral base pointers 
.SS "#define DMAMUX_CHCFG_COUNT   (16U)"

.SS "#define DMAMUX_CHCFG_ENBL(x)   (((uint8_t)(((uint8_t)(x)) << \fBDMAMUX_CHCFG_ENBL_SHIFT\fP)) & \fBDMAMUX_CHCFG_ENBL_MASK\fP)"

.SS "#define DMAMUX_CHCFG_ENBL_MASK   (0x80U)"

.SS "#define DMAMUX_CHCFG_ENBL_SHIFT   (7U)"

.SS "#define DMAMUX_CHCFG_SOURCE(x)   (((uint8_t)(((uint8_t)(x)) << \fBDMAMUX_CHCFG_SOURCE_SHIFT\fP)) & \fBDMAMUX_CHCFG_SOURCE_MASK\fP)"

.SS "#define DMAMUX_CHCFG_SOURCE_MASK   (0x3FU)"

.SS "#define DMAMUX_CHCFG_SOURCE_SHIFT   (0U)"

.SS "#define DMAMUX_CHCFG_TRIG(x)   (((uint8_t)(((uint8_t)(x)) << \fBDMAMUX_CHCFG_TRIG_SHIFT\fP)) & \fBDMAMUX_CHCFG_TRIG_MASK\fP)"

.SS "#define DMAMUX_CHCFG_TRIG_MASK   (0x40U)"

.SS "#define DMAMUX_CHCFG_TRIG_SHIFT   (6U)"

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
