.TH "drivers/DRV_Board.h" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drivers/DRV_Board.h \- FRDM Board management\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <PDRV_GPIO\&.h>\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBLED_t\fP { \fBRED\fP, \fBGREEN\fP, \fBBLUE\fP }"
.br
.ti -1c
.RI "enum \fBSW_t\fP { \fBSW2\fP, \fBSW3\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitBoard\fP ()"
.br
.RI "Initialize FRDM Board\&. "
.ti -1c
.RI "void \fBsetLED\fP (\fBLED_t\fP led, bool value)"
.br
.RI "Sets value of LED\&. "
.ti -1c
.RI "void \fBclearLED\fP (\fBLED_t\fP led)"
.br
.RI "Turn off LED\&. "
.ti -1c
.RI "void \fBtoggleLED\fP (\fBLED_t\fP led)"
.br
.RI "Toggle LED\&. "
.ti -1c
.RI "bool \fBgetSW\fP (\fBSW_t\fP sw)"
.br
.RI "Read value of switch\&. "
.in -1c
.SH "Detailed Description"
.PP 
FRDM Board management\&. 


.PP
\fBAuthor:\fP
.RS 4
Grupo 1 
.RE
.PP

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLED_t\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIRED \fP\fP
.TP
\fB\fIGREEN \fP\fP
.TP
\fB\fIBLUE \fP\fP
.SS "enum \fBSW_t\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISW2 \fP\fP
.TP
\fB\fISW3 \fP\fP
.SH "Function Documentation"
.PP 
.SS "void clearLED (\fBLED_t\fP led)"

.PP
Turn off LED\&. 
.PP
\fBParameters:\fP
.RS 4
\fIled\fP led: RED, GREEN, BLUE 
.RE
.PP

.SS "bool getSW (\fBSW_t\fP sw)"

.PP
Read value of switch\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsw\fP sw: SW2, SW3 
.RE
.PP

.SS "void initBoard ()"

.PP
Initialize FRDM Board\&. 
.SS "void setLED (\fBLED_t\fP led, bool value)"

.PP
Sets value of LED\&. 
.PP
\fBParameters:\fP
.RS 4
\fIled\fP led: RED, GREEN, BLUE 
.br
\fIvalue\fP value: true or false 
.RE
.PP

.SS "void toggleLED (\fBLED_t\fP led)"

.PP
Toggle LED\&. 
.PP
\fBParameters:\fP
.RS 4
\fIled\fP led: RED, GREEN, BLUE 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
