.TH "drivers/DRV_Stub_Display.c" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drivers/DRV_Stub_Display.c \- stdout-based display stub driver  

.SH SYNOPSIS
.br
.PP
\fC#include 'DRV_Display\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDISPLAY_DEVELOPMENT_MODE\fP   1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitDisplay\fP ()"
.br
.RI "Initialize display\&. "
.ti -1c
.RI "void \fBdispClearBuffer\fP ()"
.br
.RI "Clears the display buffer\&. "
.ti -1c
.RI "void \fBdispWriteBuffer\fP (int c, const char *buffer)"
.br
.RI "Sets word of length c in the buffer\&. "
.ti -1c
.RI "void \fBdispWriteChar\fP (int n, const char character)"
.br
.RI "Sets character in position n of the buffer\&. "
.ti -1c
.RI "bool \fBdispValidChar\fP (char character)"
.br
.ti -1c
.RI "void \fBdispScrollRight\fP ()"
.br
.RI "Scroll display to the right\&. "
.ti -1c
.RI "void \fBdispScrollLeft\fP ()"
.br
.RI "Scroll display to the left\&. "
.ti -1c
.RI "void \fBdispStartAutoScroll\fP (int speed)"
.br
.RI "Initialize autoscroll with specified speed\&. "
.ti -1c
.RI "void \fBdispStopAutoScroll\fP ()"
.br
.RI "Stop autoscroll\&. "
.ti -1c
.RI "void \fBdispResetScroll\fP ()"
.br
.ti -1c
.RI "void \fBdispSetBufferPos\fP (int n)"
.br
.RI "Sets n as the starting print position for the buffer\&. "
.ti -1c
.RI "uint8_t \fBdispGetBufferPos\fP ()"
.br
.RI "Get starting print position\&. "
.ti -1c
.RI "void \fBdispClearLED\fP (int n)"
.br
.RI "Turn off a LED\&. "
.ti -1c
.RI "void \fBdispSetLED\fP (int n)"
.br
.RI "Turn on a LED\&. "
.ti -1c
.RI "void \fBdispToggleLED\fP ()"
.br
.ti -1c
.RI "void \fBdispSetDP\fP (int i)"
.br
.RI "Turns on the decimal point of the nth seven segment\&. "
.ti -1c
.RI "void \fBdispClearDP\fP (int i)"
.br
.RI "Turns off the decimal point of the nth seven segment\&. "
.ti -1c
.RI "void \fBdispToggleDP\fP (int i)"
.br
.RI "Toggles the decimal point of the nth seven segment\&. "
.ti -1c
.RI "void \fBdispUpdateBrightness\fP (int brightness)"
.br
.RI "Updates the brightness of the display\&. "
.in -1c
.SH "Detailed Description"
.PP 
stdout-based display stub driver 


.PP
\fBAuthor:\fP
.RS 4
Grupo 1 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define DISPLAY_DEVELOPMENT_MODE   1"

.SH "Function Documentation"
.PP 
.SS "void dispClearBuffer ()"

.PP
Clears the display buffer\&. 
.SS "void dispClearDP (int n)"

.PP
Turns off the decimal point of the nth seven segment\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn\fP DP index = 0, 1, 2, 3 
.RE
.PP

.SS "void dispClearLED (int n)"

.PP
Turn off a LED\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn\fP Index of LED to turn off 
.RE
.PP

.SS "uint8_t dispGetBufferPos ()"

.PP
Get starting print position\&. 
.SS "void dispResetScroll ()"

.SS "void dispScrollLeft ()"

.PP
Scroll display to the left\&. 
.SS "void dispScrollRight ()"

.PP
Scroll display to the right\&. 
.SS "void dispSetBufferPos (int n)"

.PP
Sets n as the starting print position for the buffer\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn\fP New buffer position 
.RE
.PP

.SS "void dispSetDP (int n)"

.PP
Turns on the decimal point of the nth seven segment\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn\fP DP index = 0, 1, 2, 3 
.RE
.PP

.SS "void dispSetLED (int n)"

.PP
Turn on a LED\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn\fP Index of LED to turn on 
.RE
.PP

.SS "void dispStartAutoScroll (int speed)"

.PP
Initialize autoscroll with specified speed\&. 
.PP
\fBParameters:\fP
.RS 4
\fIspeed\fP Scroll speed 
.RE
.PP

.SS "void dispStopAutoScroll ()"

.PP
Stop autoscroll\&. 
.SS "void dispToggleDP (int n)"

.PP
Toggles the decimal point of the nth seven segment\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn\fP DP index = 0, 1, 2, 3 
.RE
.PP

.SS "void dispToggleLED ()"

.SS "void dispUpdateBrightness (int brightness)"

.PP
Updates the brightness of the display\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbrightness\fP brightness: int between one and nine 
.RE
.PP

.SS "bool dispValidChar (char character)"

.SS "void dispWriteBuffer (int c, const char * word)"

.PP
Sets word of length c in the buffer\&. 
.PP
\fBParameters:\fP
.RS 4
\fIc\fP Length of word 
.br
\fIword\fP Word to write 
.RE
.PP

.SS "void dispWriteChar (int n, char character)"

.PP
Sets character in position n of the buffer\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn\fP Index of char to write 
.br
\fIcharacter\fP Value of char 
.RE
.PP

.SS "void initDisplay ()"

.PP
Initialize display\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
