.TH "drivers/DRV_LEDs.c" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drivers/DRV_LEDs.c \- LEDs driver\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'DRV_LEDs\&.h'\fP
.br
\fC#include 'DRV_Timers\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBselector_data_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTATUS0\fP   \fBPORTNUM2PIN\fP(\fBPC\fP,2)"
.br
.ti -1c
.RI "#define \fBSTATUS1\fP   \fBPORTNUM2PIN\fP(\fBPC\fP,3)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBselector_data_t\fP \fBselector_data_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitLEDs\fP ()"
.br
.RI "Initializes the LEDs\&. "
.ti -1c
.RI "void \fBdispClearLED\fP (int n)"
.br
.RI "Turn off a LED\&. "
.ti -1c
.RI "void \fBdispSetLED\fP (int n)"
.br
.RI "Turn on a LED\&. "
.ti -1c
.RI "void \fBdispToggleLED\fP (int n)"
.br
.RI "Toggle a LED\&. "
.in -1c
.SH "Detailed Description"
.PP 
LEDs driver\&. 


.PP
\fBAuthor:\fP
.RS 4
Grupo 1 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define STATUS0   \fBPORTNUM2PIN\fP(\fBPC\fP,2)"

.SS "#define STATUS1   \fBPORTNUM2PIN\fP(\fBPC\fP,3)"

.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBselector_data_t\fP \fBselector_data_t\fP"

.SH "Function Documentation"
.PP 
.SS "void dispClearLED (int n)"

.PP
Turn off a LED\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn\fP Index of LED to turn off 
.RE
.PP

.SS "void dispSetLED (int n)"

.PP
Turn on a LED\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn\fP Index of LED to turn on 
.RE
.PP

.SS "void dispToggleLED (int n)"

.PP
Toggle a LED\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn\fP Index of LED to toggle 
.RE
.PP
\fBReturns:\fP
.RS 4
1 = timer expired 
.RE
.PP

.SS "void initLEDs ()"

.PP
Initializes the LEDs\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
