.TH "drivers/DRV_Encoder.c" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drivers/DRV_Encoder.c \- Rotary encoder driver\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'DRV_Board\&.h'\fP
.br
\fC#include 'DRV_Encoder\&.h'\fP
.br
\fC#include 'DRV_Timers\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPIN_A\fP   \fBPORTNUM2PIN\fP(\fBPA\fP,1)"
.br
.ti -1c
.RI "#define \fBPIN_B\fP   \fBPORTNUM2PIN\fP(\fBPB\fP,23)"
.br
.ti -1c
.RI "#define \fBPIN_SWA\fP   \fBPORTNUM2PIN\fP(\fBPA\fP,2)"
.br
.ti -1c
.RI "#define \fBSW_ACTIVE\fP   \fBLOW\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBstates\fP { \fBSTART\fP, \fBCW1\fP, \fBCW2\fP, \fBCW3\fP, \fBACW1\fP, \fBACW2\fP, \fBACW3\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBencoderGetStatus\fP ()"
.br
.ti -1c
.RI "\fBencoderResult_t\fP \fBencoderGetEvent\fP ()"
.br
.ti -1c
.RI "void \fBinitEncoder\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Rotary encoder driver\&. 


.PP
\fBAuthor:\fP
.RS 4
Grupo 1 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define PIN_A   \fBPORTNUM2PIN\fP(\fBPA\fP,1)"

.SS "#define PIN_B   \fBPORTNUM2PIN\fP(\fBPB\fP,23)"

.SS "#define PIN_SWA   \fBPORTNUM2PIN\fP(\fBPA\fP,2)"

.SS "#define SW_ACTIVE   \fBLOW\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBstates\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISTART \fP\fP
.TP
\fB\fICW1 \fP\fP
.TP
\fB\fICW2 \fP\fP
.TP
\fB\fICW3 \fP\fP
.TP
\fB\fIACW1 \fP\fP
.TP
\fB\fIACW2 \fP\fP
.TP
\fB\fIACW3 \fP\fP
.SH "Function Documentation"
.PP 
.SS "\fBencoderResult_t\fP encoderGetEvent ()"

.SS "bool encoderGetStatus ()"

.SS "void initEncoder ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
