.TH "EWM_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EWM_Type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MK64F12\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint8_t \fBCTRL\fP"
.br
.ti -1c
.RI "\fB__O\fP uint8_t \fBSERV\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBCMPL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBCMPH\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
EWM - Register Layout Typedef 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
