.TH "FB_Register_Masks" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FB_Register_Masks
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFB_BASE\fP   (0x4000C000u)"
.br
.ti -1c
.RI "#define \fBFB\fP   ((\fBFB_Type\fP *)\fBFB_BASE\fP)"
.br
.ti -1c
.RI "#define \fBFB_BASE_ADDRS\fP   { \fBFB_BASE\fP }"
.br
.ti -1c
.RI "#define \fBFB_BASE_PTRS\fP   { \fBFB\fP }"
.br
.in -1c
.SS "CSAR - Chip Select Address Register"

.in +1c
.ti -1c
.RI "#define \fBFB_CSAR_BA_MASK\fP   (0xFFFF0000U)"
.br
.ti -1c
.RI "#define \fBFB_CSAR_BA_SHIFT\fP   (16U)"
.br
.ti -1c
.RI "#define \fBFB_CSAR_BA\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSAR_BA_SHIFT\fP)) & \fBFB_CSAR_BA_MASK\fP)"
.br
.ti -1c
.RI "#define \fBFB_CSAR_COUNT\fP   (6U)"
.br
.in -1c
.SS "CSMR - Chip Select Mask Register"

.in +1c
.ti -1c
.RI "#define \fBFB_CSMR_V_MASK\fP   (0x1U)"
.br
.ti -1c
.RI "#define \fBFB_CSMR_V_SHIFT\fP   (0U)"
.br
.ti -1c
.RI "#define \fBFB_CSMR_V\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSMR_V_SHIFT\fP)) & \fBFB_CSMR_V_MASK\fP)"
.br
.ti -1c
.RI "#define \fBFB_CSMR_WP_MASK\fP   (0x100U)"
.br
.ti -1c
.RI "#define \fBFB_CSMR_WP_SHIFT\fP   (8U)"
.br
.ti -1c
.RI "#define \fBFB_CSMR_WP\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSMR_WP_SHIFT\fP)) & \fBFB_CSMR_WP_MASK\fP)"
.br
.ti -1c
.RI "#define \fBFB_CSMR_BAM_MASK\fP   (0xFFFF0000U)"
.br
.ti -1c
.RI "#define \fBFB_CSMR_BAM_SHIFT\fP   (16U)"
.br
.ti -1c
.RI "#define \fBFB_CSMR_BAM\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSMR_BAM_SHIFT\fP)) & \fBFB_CSMR_BAM_MASK\fP)"
.br
.ti -1c
.RI "#define \fBFB_CSMR_COUNT\fP   (6U)"
.br
.in -1c
.SS "CSCR - Chip Select Control Register"

.in +1c
.ti -1c
.RI "#define \fBFB_CSCR_BSTW_MASK\fP   (0x8U)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_BSTW_SHIFT\fP   (3U)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_BSTW\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSCR_BSTW_SHIFT\fP)) & \fBFB_CSCR_BSTW_MASK\fP)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_BSTR_MASK\fP   (0x10U)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_BSTR_SHIFT\fP   (4U)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_BSTR\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSCR_BSTR_SHIFT\fP)) & \fBFB_CSCR_BSTR_MASK\fP)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_BEM_MASK\fP   (0x20U)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_BEM_SHIFT\fP   (5U)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_BEM\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSCR_BEM_SHIFT\fP)) & \fBFB_CSCR_BEM_MASK\fP)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_PS_MASK\fP   (0xC0U)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_PS_SHIFT\fP   (6U)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_PS\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSCR_PS_SHIFT\fP)) & \fBFB_CSCR_PS_MASK\fP)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_AA_MASK\fP   (0x100U)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_AA_SHIFT\fP   (8U)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_AA\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSCR_AA_SHIFT\fP)) & \fBFB_CSCR_AA_MASK\fP)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_BLS_MASK\fP   (0x200U)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_BLS_SHIFT\fP   (9U)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_BLS\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSCR_BLS_SHIFT\fP)) & \fBFB_CSCR_BLS_MASK\fP)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_WS_MASK\fP   (0xFC00U)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_WS_SHIFT\fP   (10U)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_WS\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSCR_WS_SHIFT\fP)) & \fBFB_CSCR_WS_MASK\fP)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_WRAH_MASK\fP   (0x30000U)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_WRAH_SHIFT\fP   (16U)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_WRAH\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSCR_WRAH_SHIFT\fP)) & \fBFB_CSCR_WRAH_MASK\fP)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_RDAH_MASK\fP   (0xC0000U)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_RDAH_SHIFT\fP   (18U)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_RDAH\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSCR_RDAH_SHIFT\fP)) & \fBFB_CSCR_RDAH_MASK\fP)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_ASET_MASK\fP   (0x300000U)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_ASET_SHIFT\fP   (20U)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_ASET\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSCR_ASET_SHIFT\fP)) & \fBFB_CSCR_ASET_MASK\fP)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_EXTS_MASK\fP   (0x400000U)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_EXTS_SHIFT\fP   (22U)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_EXTS\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSCR_EXTS_SHIFT\fP)) & \fBFB_CSCR_EXTS_MASK\fP)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_SWSEN_MASK\fP   (0x800000U)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_SWSEN_SHIFT\fP   (23U)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_SWSEN\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSCR_SWSEN_SHIFT\fP)) & \fBFB_CSCR_SWSEN_MASK\fP)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_SWS_MASK\fP   (0xFC000000U)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_SWS_SHIFT\fP   (26U)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_SWS\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSCR_SWS_SHIFT\fP)) & \fBFB_CSCR_SWS_MASK\fP)"
.br
.ti -1c
.RI "#define \fBFB_CSCR_COUNT\fP   (6U)"
.br
.in -1c
.SS "CSPMCR - Chip Select port Multiplexing Control Register"

.in +1c
.ti -1c
.RI "#define \fBFB_CSPMCR_GROUP5_MASK\fP   (0xF000U)"
.br
.ti -1c
.RI "#define \fBFB_CSPMCR_GROUP5_SHIFT\fP   (12U)"
.br
.ti -1c
.RI "#define \fBFB_CSPMCR_GROUP5\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSPMCR_GROUP5_SHIFT\fP)) & \fBFB_CSPMCR_GROUP5_MASK\fP)"
.br
.ti -1c
.RI "#define \fBFB_CSPMCR_GROUP4_MASK\fP   (0xF0000U)"
.br
.ti -1c
.RI "#define \fBFB_CSPMCR_GROUP4_SHIFT\fP   (16U)"
.br
.ti -1c
.RI "#define \fBFB_CSPMCR_GROUP4\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSPMCR_GROUP4_SHIFT\fP)) & \fBFB_CSPMCR_GROUP4_MASK\fP)"
.br
.ti -1c
.RI "#define \fBFB_CSPMCR_GROUP3_MASK\fP   (0xF00000U)"
.br
.ti -1c
.RI "#define \fBFB_CSPMCR_GROUP3_SHIFT\fP   (20U)"
.br
.ti -1c
.RI "#define \fBFB_CSPMCR_GROUP3\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSPMCR_GROUP3_SHIFT\fP)) & \fBFB_CSPMCR_GROUP3_MASK\fP)"
.br
.ti -1c
.RI "#define \fBFB_CSPMCR_GROUP2_MASK\fP   (0xF000000U)"
.br
.ti -1c
.RI "#define \fBFB_CSPMCR_GROUP2_SHIFT\fP   (24U)"
.br
.ti -1c
.RI "#define \fBFB_CSPMCR_GROUP2\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSPMCR_GROUP2_SHIFT\fP)) & \fBFB_CSPMCR_GROUP2_MASK\fP)"
.br
.ti -1c
.RI "#define \fBFB_CSPMCR_GROUP1_MASK\fP   (0xF0000000U)"
.br
.ti -1c
.RI "#define \fBFB_CSPMCR_GROUP1_SHIFT\fP   (28U)"
.br
.ti -1c
.RI "#define \fBFB_CSPMCR_GROUP1\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSPMCR_GROUP1_SHIFT\fP)) & \fBFB_CSPMCR_GROUP1_MASK\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define FB   ((\fBFB_Type\fP *)\fBFB_BASE\fP)"
Peripheral FB base pointer 
.SS "#define FB_BASE   (0x4000C000u)"
Peripheral FB base address 
.SS "#define FB_BASE_ADDRS   { \fBFB_BASE\fP }"
Array initializer of FB peripheral base addresses 
.SS "#define FB_BASE_PTRS   { \fBFB\fP }"
Array initializer of FB peripheral base pointers 
.SS "#define FB_CSAR_BA(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSAR_BA_SHIFT\fP)) & \fBFB_CSAR_BA_MASK\fP)"

.SS "#define FB_CSAR_BA_MASK   (0xFFFF0000U)"

.SS "#define FB_CSAR_BA_SHIFT   (16U)"

.SS "#define FB_CSAR_COUNT   (6U)"

.SS "#define FB_CSCR_AA(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSCR_AA_SHIFT\fP)) & \fBFB_CSCR_AA_MASK\fP)"

.SS "#define FB_CSCR_AA_MASK   (0x100U)"

.SS "#define FB_CSCR_AA_SHIFT   (8U)"

.SS "#define FB_CSCR_ASET(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSCR_ASET_SHIFT\fP)) & \fBFB_CSCR_ASET_MASK\fP)"

.SS "#define FB_CSCR_ASET_MASK   (0x300000U)"

.SS "#define FB_CSCR_ASET_SHIFT   (20U)"

.SS "#define FB_CSCR_BEM(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSCR_BEM_SHIFT\fP)) & \fBFB_CSCR_BEM_MASK\fP)"

.SS "#define FB_CSCR_BEM_MASK   (0x20U)"

.SS "#define FB_CSCR_BEM_SHIFT   (5U)"

.SS "#define FB_CSCR_BLS(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSCR_BLS_SHIFT\fP)) & \fBFB_CSCR_BLS_MASK\fP)"

.SS "#define FB_CSCR_BLS_MASK   (0x200U)"

.SS "#define FB_CSCR_BLS_SHIFT   (9U)"

.SS "#define FB_CSCR_BSTR(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSCR_BSTR_SHIFT\fP)) & \fBFB_CSCR_BSTR_MASK\fP)"

.SS "#define FB_CSCR_BSTR_MASK   (0x10U)"

.SS "#define FB_CSCR_BSTR_SHIFT   (4U)"

.SS "#define FB_CSCR_BSTW(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSCR_BSTW_SHIFT\fP)) & \fBFB_CSCR_BSTW_MASK\fP)"

.SS "#define FB_CSCR_BSTW_MASK   (0x8U)"

.SS "#define FB_CSCR_BSTW_SHIFT   (3U)"

.SS "#define FB_CSCR_COUNT   (6U)"

.SS "#define FB_CSCR_EXTS(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSCR_EXTS_SHIFT\fP)) & \fBFB_CSCR_EXTS_MASK\fP)"

.SS "#define FB_CSCR_EXTS_MASK   (0x400000U)"

.SS "#define FB_CSCR_EXTS_SHIFT   (22U)"

.SS "#define FB_CSCR_PS(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSCR_PS_SHIFT\fP)) & \fBFB_CSCR_PS_MASK\fP)"

.SS "#define FB_CSCR_PS_MASK   (0xC0U)"

.SS "#define FB_CSCR_PS_SHIFT   (6U)"

.SS "#define FB_CSCR_RDAH(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSCR_RDAH_SHIFT\fP)) & \fBFB_CSCR_RDAH_MASK\fP)"

.SS "#define FB_CSCR_RDAH_MASK   (0xC0000U)"

.SS "#define FB_CSCR_RDAH_SHIFT   (18U)"

.SS "#define FB_CSCR_SWS(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSCR_SWS_SHIFT\fP)) & \fBFB_CSCR_SWS_MASK\fP)"

.SS "#define FB_CSCR_SWS_MASK   (0xFC000000U)"

.SS "#define FB_CSCR_SWS_SHIFT   (26U)"

.SS "#define FB_CSCR_SWSEN(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSCR_SWSEN_SHIFT\fP)) & \fBFB_CSCR_SWSEN_MASK\fP)"

.SS "#define FB_CSCR_SWSEN_MASK   (0x800000U)"

.SS "#define FB_CSCR_SWSEN_SHIFT   (23U)"

.SS "#define FB_CSCR_WRAH(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSCR_WRAH_SHIFT\fP)) & \fBFB_CSCR_WRAH_MASK\fP)"

.SS "#define FB_CSCR_WRAH_MASK   (0x30000U)"

.SS "#define FB_CSCR_WRAH_SHIFT   (16U)"

.SS "#define FB_CSCR_WS(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSCR_WS_SHIFT\fP)) & \fBFB_CSCR_WS_MASK\fP)"

.SS "#define FB_CSCR_WS_MASK   (0xFC00U)"

.SS "#define FB_CSCR_WS_SHIFT   (10U)"

.SS "#define FB_CSMR_BAM(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSMR_BAM_SHIFT\fP)) & \fBFB_CSMR_BAM_MASK\fP)"

.SS "#define FB_CSMR_BAM_MASK   (0xFFFF0000U)"

.SS "#define FB_CSMR_BAM_SHIFT   (16U)"

.SS "#define FB_CSMR_COUNT   (6U)"

.SS "#define FB_CSMR_V(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSMR_V_SHIFT\fP)) & \fBFB_CSMR_V_MASK\fP)"

.SS "#define FB_CSMR_V_MASK   (0x1U)"

.SS "#define FB_CSMR_V_SHIFT   (0U)"

.SS "#define FB_CSMR_WP(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSMR_WP_SHIFT\fP)) & \fBFB_CSMR_WP_MASK\fP)"

.SS "#define FB_CSMR_WP_MASK   (0x100U)"

.SS "#define FB_CSMR_WP_SHIFT   (8U)"

.SS "#define FB_CSPMCR_GROUP1(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSPMCR_GROUP1_SHIFT\fP)) & \fBFB_CSPMCR_GROUP1_MASK\fP)"

.SS "#define FB_CSPMCR_GROUP1_MASK   (0xF0000000U)"

.SS "#define FB_CSPMCR_GROUP1_SHIFT   (28U)"

.SS "#define FB_CSPMCR_GROUP2(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSPMCR_GROUP2_SHIFT\fP)) & \fBFB_CSPMCR_GROUP2_MASK\fP)"

.SS "#define FB_CSPMCR_GROUP2_MASK   (0xF000000U)"

.SS "#define FB_CSPMCR_GROUP2_SHIFT   (24U)"

.SS "#define FB_CSPMCR_GROUP3(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSPMCR_GROUP3_SHIFT\fP)) & \fBFB_CSPMCR_GROUP3_MASK\fP)"

.SS "#define FB_CSPMCR_GROUP3_MASK   (0xF00000U)"

.SS "#define FB_CSPMCR_GROUP3_SHIFT   (20U)"

.SS "#define FB_CSPMCR_GROUP4(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSPMCR_GROUP4_SHIFT\fP)) & \fBFB_CSPMCR_GROUP4_MASK\fP)"

.SS "#define FB_CSPMCR_GROUP4_MASK   (0xF0000U)"

.SS "#define FB_CSPMCR_GROUP4_SHIFT   (16U)"

.SS "#define FB_CSPMCR_GROUP5(x)   (((uint32_t)(((uint32_t)(x)) << \fBFB_CSPMCR_GROUP5_SHIFT\fP)) & \fBFB_CSPMCR_GROUP5_MASK\fP)"

.SS "#define FB_CSPMCR_GROUP5_MASK   (0xF000U)"

.SS "#define FB_CSPMCR_GROUP5_SHIFT   (12U)"

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
