.TH "FB_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FB_Type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MK64F12\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBCSAR\fP"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBCSMR\fP"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBCSCR\fP"
.br
.ti -1c
.RI "} \fBCS\fP [6]"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_0\fP [24]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCSPMCR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
FB - Register Layout Typedef 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
