.TH "FPU_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FPU_Type \- Structure type to access the Floating Point Unit (FPU)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <core_armv8mml\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBRESERVED0\fP [1U]"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBFPCCR\fP"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBFPCAR\fP"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBFPDSCR\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBMVFR0\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBMVFR1\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure type to access the Floating Point Unit (FPU)\&. 
.SH "Field Documentation"
.PP 
.SS "\fB__IOM\fP uint32_t FPCAR"
Offset: 0x008 (R/W) Floating-Point Context Address Register 
.SS "\fB__IOM\fP uint32_t FPCCR"
Offset: 0x004 (R/W) Floating-Point Context Control Register 
.SS "\fB__IOM\fP uint32_t FPDSCR"
Offset: 0x00C (R/W) Floating-Point Default Status Control Register 
.SS "\fB__IM\fP uint32_t MVFR0"
Offset: 0x010 (R/ ) Media and FP Feature Register 0 
.SS "\fB__IM\fP uint32_t MVFR1"
Offset: 0x014 (R/ ) Media and FP Feature Register 1 
.SS "uint32_t RESERVED0"


.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
