.TH "FTFE_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTFE_Type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MK64F12\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint8_t \fBFSTAT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBFCNFG\fP"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBFSEC\fP"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBFOPT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBFCCOB3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBFCCOB2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBFCCOB1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBFCCOB0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBFCCOB7\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBFCCOB6\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBFCCOB5\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBFCCOB4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBFCCOBB\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBFCCOBA\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBFCCOB9\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBFCCOB8\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBFPROT3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBFPROT2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBFPROT1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBFPROT0\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_0\fP [2]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBFEPROT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBFDPROT\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
FTFE - Register Layout Typedef 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
