.TH "FTM_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTM_Type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MK64F12\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSC\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCNT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMOD\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBCnSC\fP"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBCnV\fP"
.br
.ti -1c
.RI "} \fBCONTROLS\fP [8]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCNTIN\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSTATUS\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMODE\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSYNC\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOUTINIT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOUTMASK\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCOMBINE\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDEADTIME\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBEXTTRIG\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPOL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFMS\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFILTER\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFLTCTRL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBQDCTRL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCONF\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFLTPOL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSYNCONF\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBINVCTRL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSWOCTRL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPWMLOAD\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
FTM - Register Layout Typedef 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
