.TH "SDK/startup/hardware.c" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDK/startup/hardware.c
.SH SYNOPSIS
.br
.PP
\fC#include 'hardware\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBhw_Init\fP (void)"
.br
.ti -1c
.RI "void \fBhw_EnableInterrupts\fP (void)"
.br
.ti -1c
.RI "void \fBhw_DisableInterrupts\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void hw_DisableInterrupts (void)"

.SS "void hw_EnableInterrupts (void)"

.SS "void hw_Init (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
