.TH "SDK/startup/hardware.h" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDK/startup/hardware.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include 'fsl_device_registers\&.h'\fP
.br
\fC#include 'core_cm4\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__CORE_CLOCK__\fP   100000000U"
.br
.ti -1c
.RI "#define \fB__FOREVER__\fP   for(;;)"
.br
.ti -1c
.RI "#define \fB__ISR__\fP   void \fB__attribute__\fP ((interrupt))"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBhw_Init\fP (void)"
.br
.ti -1c
.RI "void \fBhw_EnableInterrupts\fP (void)"
.br
.ti -1c
.RI "void \fBhw_DisableInterrupts\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Nicolás Magliola 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define __CORE_CLOCK__   100000000U"

.SS "#define __FOREVER__   for(;;)"

.SS "#define __ISR__   void \fB__attribute__\fP ((interrupt))"

.SH "Function Documentation"
.PP 
.SS "void hw_DisableInterrupts (void)"

.SS "void hw_EnableInterrupts (void)"

.SS "void hw_Init (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
