.TH "I2C_Peripheral_Access_Layer" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2C_Peripheral_Access_Layer
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBI2C Register Masks\fP"
.br
.ti -1c
.RI "\fBI2S Peripheral Access Layer\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBI2C_Type\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
