.TH "I2C_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2C_Type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MK64F12\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint8_t \fBA1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBF\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBC1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBS\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBD\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBC2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBFLT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBRA\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBSMB\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBA2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBSLTH\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBSLTL\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
I2C - Register Layout Typedef 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
