.TH "I2S_Register_Masks" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2S_Register_Masks
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBI2S0_BASE\fP   (0x4002F000u)"
.br
.ti -1c
.RI "#define \fBI2S0\fP   ((\fBI2S_Type\fP *)\fBI2S0_BASE\fP)"
.br
.ti -1c
.RI "#define \fBI2S_BASE_ADDRS\fP   { \fBI2S0_BASE\fP }"
.br
.ti -1c
.RI "#define \fBI2S_BASE_PTRS\fP   { \fBI2S0\fP }"
.br
.ti -1c
.RI "#define \fBI2S_RX_IRQS\fP   { \fBI2S0_Rx_IRQn\fP }"
.br
.ti -1c
.RI "#define \fBI2S_TX_IRQS\fP   { \fBI2S0_Tx_IRQn\fP }"
.br
.in -1c
.SS "TCSR - SAI Transmit Control Register"

.in +1c
.ti -1c
.RI "#define \fBI2S_TCSR_FRDE_MASK\fP   (0x1U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_FRDE_SHIFT\fP   (0U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_FRDE\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_FRDE_SHIFT\fP)) & \fBI2S_TCSR_FRDE_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_FWDE_MASK\fP   (0x2U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_FWDE_SHIFT\fP   (1U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_FWDE\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_FWDE_SHIFT\fP)) & \fBI2S_TCSR_FWDE_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_FRIE_MASK\fP   (0x100U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_FRIE_SHIFT\fP   (8U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_FRIE\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_FRIE_SHIFT\fP)) & \fBI2S_TCSR_FRIE_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_FWIE_MASK\fP   (0x200U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_FWIE_SHIFT\fP   (9U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_FWIE\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_FWIE_SHIFT\fP)) & \fBI2S_TCSR_FWIE_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_FEIE_MASK\fP   (0x400U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_FEIE_SHIFT\fP   (10U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_FEIE\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_FEIE_SHIFT\fP)) & \fBI2S_TCSR_FEIE_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_SEIE_MASK\fP   (0x800U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_SEIE_SHIFT\fP   (11U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_SEIE\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_SEIE_SHIFT\fP)) & \fBI2S_TCSR_SEIE_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_WSIE_MASK\fP   (0x1000U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_WSIE_SHIFT\fP   (12U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_WSIE\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_WSIE_SHIFT\fP)) & \fBI2S_TCSR_WSIE_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_FRF_MASK\fP   (0x10000U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_FRF_SHIFT\fP   (16U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_FRF\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_FRF_SHIFT\fP)) & \fBI2S_TCSR_FRF_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_FWF_MASK\fP   (0x20000U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_FWF_SHIFT\fP   (17U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_FWF\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_FWF_SHIFT\fP)) & \fBI2S_TCSR_FWF_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_FEF_MASK\fP   (0x40000U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_FEF_SHIFT\fP   (18U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_FEF\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_FEF_SHIFT\fP)) & \fBI2S_TCSR_FEF_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_SEF_MASK\fP   (0x80000U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_SEF_SHIFT\fP   (19U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_SEF\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_SEF_SHIFT\fP)) & \fBI2S_TCSR_SEF_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_WSF_MASK\fP   (0x100000U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_WSF_SHIFT\fP   (20U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_WSF\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_WSF_SHIFT\fP)) & \fBI2S_TCSR_WSF_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_SR_MASK\fP   (0x1000000U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_SR_SHIFT\fP   (24U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_SR\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_SR_SHIFT\fP)) & \fBI2S_TCSR_SR_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_FR_MASK\fP   (0x2000000U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_FR_SHIFT\fP   (25U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_FR\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_FR_SHIFT\fP)) & \fBI2S_TCSR_FR_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_BCE_MASK\fP   (0x10000000U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_BCE_SHIFT\fP   (28U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_BCE\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_BCE_SHIFT\fP)) & \fBI2S_TCSR_BCE_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_DBGE_MASK\fP   (0x20000000U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_DBGE_SHIFT\fP   (29U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_DBGE\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_DBGE_SHIFT\fP)) & \fBI2S_TCSR_DBGE_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_STOPE_MASK\fP   (0x40000000U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_STOPE_SHIFT\fP   (30U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_STOPE\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_STOPE_SHIFT\fP)) & \fBI2S_TCSR_STOPE_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_TE_MASK\fP   (0x80000000U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_TE_SHIFT\fP   (31U)"
.br
.ti -1c
.RI "#define \fBI2S_TCSR_TE\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_TE_SHIFT\fP)) & \fBI2S_TCSR_TE_MASK\fP)"
.br
.in -1c
.SS "TCR1 - SAI Transmit Configuration 1 Register"

.in +1c
.ti -1c
.RI "#define \fBI2S_TCR1_TFW_MASK\fP   (0x7U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR1_TFW_SHIFT\fP   (0U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR1_TFW\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR1_TFW_SHIFT\fP)) & \fBI2S_TCR1_TFW_MASK\fP)"
.br
.in -1c
.SS "TCR2 - SAI Transmit Configuration 2 Register"

.in +1c
.ti -1c
.RI "#define \fBI2S_TCR2_DIV_MASK\fP   (0xFFU)"
.br
.ti -1c
.RI "#define \fBI2S_TCR2_DIV_SHIFT\fP   (0U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR2_DIV\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR2_DIV_SHIFT\fP)) & \fBI2S_TCR2_DIV_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCR2_BCD_MASK\fP   (0x1000000U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR2_BCD_SHIFT\fP   (24U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR2_BCD\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR2_BCD_SHIFT\fP)) & \fBI2S_TCR2_BCD_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCR2_BCP_MASK\fP   (0x2000000U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR2_BCP_SHIFT\fP   (25U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR2_BCP\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR2_BCP_SHIFT\fP)) & \fBI2S_TCR2_BCP_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCR2_MSEL_MASK\fP   (0xC000000U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR2_MSEL_SHIFT\fP   (26U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR2_MSEL\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR2_MSEL_SHIFT\fP)) & \fBI2S_TCR2_MSEL_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCR2_BCI_MASK\fP   (0x10000000U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR2_BCI_SHIFT\fP   (28U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR2_BCI\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR2_BCI_SHIFT\fP)) & \fBI2S_TCR2_BCI_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCR2_BCS_MASK\fP   (0x20000000U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR2_BCS_SHIFT\fP   (29U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR2_BCS\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR2_BCS_SHIFT\fP)) & \fBI2S_TCR2_BCS_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCR2_SYNC_MASK\fP   (0xC0000000U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR2_SYNC_SHIFT\fP   (30U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR2_SYNC\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR2_SYNC_SHIFT\fP)) & \fBI2S_TCR2_SYNC_MASK\fP)"
.br
.in -1c
.SS "TCR3 - SAI Transmit Configuration 3 Register"

.in +1c
.ti -1c
.RI "#define \fBI2S_TCR3_WDFL_MASK\fP   (0x1FU)"
.br
.ti -1c
.RI "#define \fBI2S_TCR3_WDFL_SHIFT\fP   (0U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR3_WDFL\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR3_WDFL_SHIFT\fP)) & \fBI2S_TCR3_WDFL_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCR3_TCE_MASK\fP   (0x30000U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR3_TCE_SHIFT\fP   (16U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR3_TCE\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR3_TCE_SHIFT\fP)) & \fBI2S_TCR3_TCE_MASK\fP)"
.br
.in -1c
.SS "TCR4 - SAI Transmit Configuration 4 Register"

.in +1c
.ti -1c
.RI "#define \fBI2S_TCR4_FSD_MASK\fP   (0x1U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR4_FSD_SHIFT\fP   (0U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR4_FSD\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR4_FSD_SHIFT\fP)) & \fBI2S_TCR4_FSD_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCR4_FSP_MASK\fP   (0x2U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR4_FSP_SHIFT\fP   (1U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR4_FSP\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR4_FSP_SHIFT\fP)) & \fBI2S_TCR4_FSP_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCR4_FSE_MASK\fP   (0x8U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR4_FSE_SHIFT\fP   (3U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR4_FSE\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR4_FSE_SHIFT\fP)) & \fBI2S_TCR4_FSE_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCR4_MF_MASK\fP   (0x10U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR4_MF_SHIFT\fP   (4U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR4_MF\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR4_MF_SHIFT\fP)) & \fBI2S_TCR4_MF_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCR4_SYWD_MASK\fP   (0x1F00U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR4_SYWD_SHIFT\fP   (8U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR4_SYWD\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR4_SYWD_SHIFT\fP)) & \fBI2S_TCR4_SYWD_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCR4_FRSZ_MASK\fP   (0x1F0000U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR4_FRSZ_SHIFT\fP   (16U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR4_FRSZ\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR4_FRSZ_SHIFT\fP)) & \fBI2S_TCR4_FRSZ_MASK\fP)"
.br
.in -1c
.SS "TCR5 - SAI Transmit Configuration 5 Register"

.in +1c
.ti -1c
.RI "#define \fBI2S_TCR5_FBT_MASK\fP   (0x1F00U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR5_FBT_SHIFT\fP   (8U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR5_FBT\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR5_FBT_SHIFT\fP)) & \fBI2S_TCR5_FBT_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCR5_W0W_MASK\fP   (0x1F0000U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR5_W0W_SHIFT\fP   (16U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR5_W0W\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR5_W0W_SHIFT\fP)) & \fBI2S_TCR5_W0W_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TCR5_WNW_MASK\fP   (0x1F000000U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR5_WNW_SHIFT\fP   (24U)"
.br
.ti -1c
.RI "#define \fBI2S_TCR5_WNW\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR5_WNW_SHIFT\fP)) & \fBI2S_TCR5_WNW_MASK\fP)"
.br
.in -1c
.SS "TDR - SAI Transmit Data Register"

.in +1c
.ti -1c
.RI "#define \fBI2S_TDR_TDR_MASK\fP   (0xFFFFFFFFU)"
.br
.ti -1c
.RI "#define \fBI2S_TDR_TDR_SHIFT\fP   (0U)"
.br
.ti -1c
.RI "#define \fBI2S_TDR_TDR\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TDR_TDR_SHIFT\fP)) & \fBI2S_TDR_TDR_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TDR_COUNT\fP   (2U)"
.br
.in -1c
.SS "TFR - SAI Transmit FIFO Register"

.in +1c
.ti -1c
.RI "#define \fBI2S_TFR_RFP_MASK\fP   (0xFU)"
.br
.ti -1c
.RI "#define \fBI2S_TFR_RFP_SHIFT\fP   (0U)"
.br
.ti -1c
.RI "#define \fBI2S_TFR_RFP\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TFR_RFP_SHIFT\fP)) & \fBI2S_TFR_RFP_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TFR_WFP_MASK\fP   (0xF0000U)"
.br
.ti -1c
.RI "#define \fBI2S_TFR_WFP_SHIFT\fP   (16U)"
.br
.ti -1c
.RI "#define \fBI2S_TFR_WFP\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TFR_WFP_SHIFT\fP)) & \fBI2S_TFR_WFP_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_TFR_COUNT\fP   (2U)"
.br
.in -1c
.SS "TMR - SAI Transmit Mask Register"

.in +1c
.ti -1c
.RI "#define \fBI2S_TMR_TWM_MASK\fP   (0xFFFFFFFFU)"
.br
.ti -1c
.RI "#define \fBI2S_TMR_TWM_SHIFT\fP   (0U)"
.br
.ti -1c
.RI "#define \fBI2S_TMR_TWM\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TMR_TWM_SHIFT\fP)) & \fBI2S_TMR_TWM_MASK\fP)"
.br
.in -1c
.SS "RCSR - SAI Receive Control Register"

.in +1c
.ti -1c
.RI "#define \fBI2S_RCSR_FRDE_MASK\fP   (0x1U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_FRDE_SHIFT\fP   (0U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_FRDE\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_FRDE_SHIFT\fP)) & \fBI2S_RCSR_FRDE_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_FWDE_MASK\fP   (0x2U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_FWDE_SHIFT\fP   (1U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_FWDE\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_FWDE_SHIFT\fP)) & \fBI2S_RCSR_FWDE_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_FRIE_MASK\fP   (0x100U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_FRIE_SHIFT\fP   (8U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_FRIE\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_FRIE_SHIFT\fP)) & \fBI2S_RCSR_FRIE_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_FWIE_MASK\fP   (0x200U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_FWIE_SHIFT\fP   (9U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_FWIE\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_FWIE_SHIFT\fP)) & \fBI2S_RCSR_FWIE_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_FEIE_MASK\fP   (0x400U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_FEIE_SHIFT\fP   (10U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_FEIE\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_FEIE_SHIFT\fP)) & \fBI2S_RCSR_FEIE_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_SEIE_MASK\fP   (0x800U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_SEIE_SHIFT\fP   (11U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_SEIE\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_SEIE_SHIFT\fP)) & \fBI2S_RCSR_SEIE_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_WSIE_MASK\fP   (0x1000U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_WSIE_SHIFT\fP   (12U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_WSIE\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_WSIE_SHIFT\fP)) & \fBI2S_RCSR_WSIE_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_FRF_MASK\fP   (0x10000U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_FRF_SHIFT\fP   (16U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_FRF\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_FRF_SHIFT\fP)) & \fBI2S_RCSR_FRF_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_FWF_MASK\fP   (0x20000U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_FWF_SHIFT\fP   (17U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_FWF\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_FWF_SHIFT\fP)) & \fBI2S_RCSR_FWF_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_FEF_MASK\fP   (0x40000U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_FEF_SHIFT\fP   (18U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_FEF\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_FEF_SHIFT\fP)) & \fBI2S_RCSR_FEF_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_SEF_MASK\fP   (0x80000U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_SEF_SHIFT\fP   (19U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_SEF\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_SEF_SHIFT\fP)) & \fBI2S_RCSR_SEF_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_WSF_MASK\fP   (0x100000U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_WSF_SHIFT\fP   (20U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_WSF\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_WSF_SHIFT\fP)) & \fBI2S_RCSR_WSF_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_SR_MASK\fP   (0x1000000U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_SR_SHIFT\fP   (24U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_SR\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_SR_SHIFT\fP)) & \fBI2S_RCSR_SR_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_FR_MASK\fP   (0x2000000U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_FR_SHIFT\fP   (25U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_FR\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_FR_SHIFT\fP)) & \fBI2S_RCSR_FR_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_BCE_MASK\fP   (0x10000000U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_BCE_SHIFT\fP   (28U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_BCE\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_BCE_SHIFT\fP)) & \fBI2S_RCSR_BCE_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_DBGE_MASK\fP   (0x20000000U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_DBGE_SHIFT\fP   (29U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_DBGE\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_DBGE_SHIFT\fP)) & \fBI2S_RCSR_DBGE_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_STOPE_MASK\fP   (0x40000000U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_STOPE_SHIFT\fP   (30U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_STOPE\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_STOPE_SHIFT\fP)) & \fBI2S_RCSR_STOPE_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_RE_MASK\fP   (0x80000000U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_RE_SHIFT\fP   (31U)"
.br
.ti -1c
.RI "#define \fBI2S_RCSR_RE\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_RE_SHIFT\fP)) & \fBI2S_RCSR_RE_MASK\fP)"
.br
.in -1c
.SS "RCR1 - SAI Receive Configuration 1 Register"

.in +1c
.ti -1c
.RI "#define \fBI2S_RCR1_RFW_MASK\fP   (0x7U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR1_RFW_SHIFT\fP   (0U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR1_RFW\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR1_RFW_SHIFT\fP)) & \fBI2S_RCR1_RFW_MASK\fP)"
.br
.in -1c
.SS "RCR2 - SAI Receive Configuration 2 Register"

.in +1c
.ti -1c
.RI "#define \fBI2S_RCR2_DIV_MASK\fP   (0xFFU)"
.br
.ti -1c
.RI "#define \fBI2S_RCR2_DIV_SHIFT\fP   (0U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR2_DIV\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR2_DIV_SHIFT\fP)) & \fBI2S_RCR2_DIV_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCR2_BCD_MASK\fP   (0x1000000U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR2_BCD_SHIFT\fP   (24U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR2_BCD\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR2_BCD_SHIFT\fP)) & \fBI2S_RCR2_BCD_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCR2_BCP_MASK\fP   (0x2000000U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR2_BCP_SHIFT\fP   (25U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR2_BCP\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR2_BCP_SHIFT\fP)) & \fBI2S_RCR2_BCP_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCR2_MSEL_MASK\fP   (0xC000000U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR2_MSEL_SHIFT\fP   (26U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR2_MSEL\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR2_MSEL_SHIFT\fP)) & \fBI2S_RCR2_MSEL_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCR2_BCI_MASK\fP   (0x10000000U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR2_BCI_SHIFT\fP   (28U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR2_BCI\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR2_BCI_SHIFT\fP)) & \fBI2S_RCR2_BCI_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCR2_BCS_MASK\fP   (0x20000000U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR2_BCS_SHIFT\fP   (29U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR2_BCS\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR2_BCS_SHIFT\fP)) & \fBI2S_RCR2_BCS_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCR2_SYNC_MASK\fP   (0xC0000000U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR2_SYNC_SHIFT\fP   (30U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR2_SYNC\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR2_SYNC_SHIFT\fP)) & \fBI2S_RCR2_SYNC_MASK\fP)"
.br
.in -1c
.SS "RCR3 - SAI Receive Configuration 3 Register"

.in +1c
.ti -1c
.RI "#define \fBI2S_RCR3_WDFL_MASK\fP   (0x1FU)"
.br
.ti -1c
.RI "#define \fBI2S_RCR3_WDFL_SHIFT\fP   (0U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR3_WDFL\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR3_WDFL_SHIFT\fP)) & \fBI2S_RCR3_WDFL_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCR3_RCE_MASK\fP   (0x30000U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR3_RCE_SHIFT\fP   (16U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR3_RCE\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR3_RCE_SHIFT\fP)) & \fBI2S_RCR3_RCE_MASK\fP)"
.br
.in -1c
.SS "RCR4 - SAI Receive Configuration 4 Register"

.in +1c
.ti -1c
.RI "#define \fBI2S_RCR4_FSD_MASK\fP   (0x1U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR4_FSD_SHIFT\fP   (0U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR4_FSD\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR4_FSD_SHIFT\fP)) & \fBI2S_RCR4_FSD_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCR4_FSP_MASK\fP   (0x2U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR4_FSP_SHIFT\fP   (1U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR4_FSP\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR4_FSP_SHIFT\fP)) & \fBI2S_RCR4_FSP_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCR4_FSE_MASK\fP   (0x8U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR4_FSE_SHIFT\fP   (3U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR4_FSE\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR4_FSE_SHIFT\fP)) & \fBI2S_RCR4_FSE_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCR4_MF_MASK\fP   (0x10U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR4_MF_SHIFT\fP   (4U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR4_MF\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR4_MF_SHIFT\fP)) & \fBI2S_RCR4_MF_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCR4_SYWD_MASK\fP   (0x1F00U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR4_SYWD_SHIFT\fP   (8U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR4_SYWD\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR4_SYWD_SHIFT\fP)) & \fBI2S_RCR4_SYWD_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCR4_FRSZ_MASK\fP   (0x1F0000U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR4_FRSZ_SHIFT\fP   (16U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR4_FRSZ\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR4_FRSZ_SHIFT\fP)) & \fBI2S_RCR4_FRSZ_MASK\fP)"
.br
.in -1c
.SS "RCR5 - SAI Receive Configuration 5 Register"

.in +1c
.ti -1c
.RI "#define \fBI2S_RCR5_FBT_MASK\fP   (0x1F00U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR5_FBT_SHIFT\fP   (8U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR5_FBT\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR5_FBT_SHIFT\fP)) & \fBI2S_RCR5_FBT_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCR5_W0W_MASK\fP   (0x1F0000U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR5_W0W_SHIFT\fP   (16U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR5_W0W\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR5_W0W_SHIFT\fP)) & \fBI2S_RCR5_W0W_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RCR5_WNW_MASK\fP   (0x1F000000U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR5_WNW_SHIFT\fP   (24U)"
.br
.ti -1c
.RI "#define \fBI2S_RCR5_WNW\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR5_WNW_SHIFT\fP)) & \fBI2S_RCR5_WNW_MASK\fP)"
.br
.in -1c
.SS "RDR - SAI Receive Data Register"

.in +1c
.ti -1c
.RI "#define \fBI2S_RDR_RDR_MASK\fP   (0xFFFFFFFFU)"
.br
.ti -1c
.RI "#define \fBI2S_RDR_RDR_SHIFT\fP   (0U)"
.br
.ti -1c
.RI "#define \fBI2S_RDR_RDR\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RDR_RDR_SHIFT\fP)) & \fBI2S_RDR_RDR_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RDR_COUNT\fP   (2U)"
.br
.in -1c
.SS "RFR - SAI Receive FIFO Register"

.in +1c
.ti -1c
.RI "#define \fBI2S_RFR_RFP_MASK\fP   (0xFU)"
.br
.ti -1c
.RI "#define \fBI2S_RFR_RFP_SHIFT\fP   (0U)"
.br
.ti -1c
.RI "#define \fBI2S_RFR_RFP\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RFR_RFP_SHIFT\fP)) & \fBI2S_RFR_RFP_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RFR_WFP_MASK\fP   (0xF0000U)"
.br
.ti -1c
.RI "#define \fBI2S_RFR_WFP_SHIFT\fP   (16U)"
.br
.ti -1c
.RI "#define \fBI2S_RFR_WFP\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RFR_WFP_SHIFT\fP)) & \fBI2S_RFR_WFP_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_RFR_COUNT\fP   (2U)"
.br
.in -1c
.SS "RMR - SAI Receive Mask Register"

.in +1c
.ti -1c
.RI "#define \fBI2S_RMR_RWM_MASK\fP   (0xFFFFFFFFU)"
.br
.ti -1c
.RI "#define \fBI2S_RMR_RWM_SHIFT\fP   (0U)"
.br
.ti -1c
.RI "#define \fBI2S_RMR_RWM\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RMR_RWM_SHIFT\fP)) & \fBI2S_RMR_RWM_MASK\fP)"
.br
.in -1c
.SS "MCR - SAI MCLK Control Register"

.in +1c
.ti -1c
.RI "#define \fBI2S_MCR_MICS_MASK\fP   (0x3000000U)"
.br
.ti -1c
.RI "#define \fBI2S_MCR_MICS_SHIFT\fP   (24U)"
.br
.ti -1c
.RI "#define \fBI2S_MCR_MICS\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_MCR_MICS_SHIFT\fP)) & \fBI2S_MCR_MICS_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_MCR_MOE_MASK\fP   (0x40000000U)"
.br
.ti -1c
.RI "#define \fBI2S_MCR_MOE_SHIFT\fP   (30U)"
.br
.ti -1c
.RI "#define \fBI2S_MCR_MOE\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_MCR_MOE_SHIFT\fP)) & \fBI2S_MCR_MOE_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_MCR_DUF_MASK\fP   (0x80000000U)"
.br
.ti -1c
.RI "#define \fBI2S_MCR_DUF_SHIFT\fP   (31U)"
.br
.ti -1c
.RI "#define \fBI2S_MCR_DUF\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_MCR_DUF_SHIFT\fP)) & \fBI2S_MCR_DUF_MASK\fP)"
.br
.in -1c
.SS "MDR - SAI MCLK Divide Register"

.in +1c
.ti -1c
.RI "#define \fBI2S_MDR_DIVIDE_MASK\fP   (0xFFFU)"
.br
.ti -1c
.RI "#define \fBI2S_MDR_DIVIDE_SHIFT\fP   (0U)"
.br
.ti -1c
.RI "#define \fBI2S_MDR_DIVIDE\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_MDR_DIVIDE_SHIFT\fP)) & \fBI2S_MDR_DIVIDE_MASK\fP)"
.br
.ti -1c
.RI "#define \fBI2S_MDR_FRACT_MASK\fP   (0xFF000U)"
.br
.ti -1c
.RI "#define \fBI2S_MDR_FRACT_SHIFT\fP   (12U)"
.br
.ti -1c
.RI "#define \fBI2S_MDR_FRACT\fP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_MDR_FRACT_SHIFT\fP)) & \fBI2S_MDR_FRACT_MASK\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define I2S0   ((\fBI2S_Type\fP *)\fBI2S0_BASE\fP)"
Peripheral I2S0 base pointer 
.SS "#define I2S0_BASE   (0x4002F000u)"
Peripheral I2S0 base address 
.SS "#define I2S_BASE_ADDRS   { \fBI2S0_BASE\fP }"
Array initializer of I2S peripheral base addresses 
.SS "#define I2S_BASE_PTRS   { \fBI2S0\fP }"
Array initializer of I2S peripheral base pointers 
.SS "#define I2S_MCR_DUF(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_MCR_DUF_SHIFT\fP)) & \fBI2S_MCR_DUF_MASK\fP)"

.SS "#define I2S_MCR_DUF_MASK   (0x80000000U)"

.SS "#define I2S_MCR_DUF_SHIFT   (31U)"

.SS "#define I2S_MCR_MICS(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_MCR_MICS_SHIFT\fP)) & \fBI2S_MCR_MICS_MASK\fP)"

.SS "#define I2S_MCR_MICS_MASK   (0x3000000U)"

.SS "#define I2S_MCR_MICS_SHIFT   (24U)"

.SS "#define I2S_MCR_MOE(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_MCR_MOE_SHIFT\fP)) & \fBI2S_MCR_MOE_MASK\fP)"

.SS "#define I2S_MCR_MOE_MASK   (0x40000000U)"

.SS "#define I2S_MCR_MOE_SHIFT   (30U)"

.SS "#define I2S_MDR_DIVIDE(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_MDR_DIVIDE_SHIFT\fP)) & \fBI2S_MDR_DIVIDE_MASK\fP)"

.SS "#define I2S_MDR_DIVIDE_MASK   (0xFFFU)"

.SS "#define I2S_MDR_DIVIDE_SHIFT   (0U)"

.SS "#define I2S_MDR_FRACT(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_MDR_FRACT_SHIFT\fP)) & \fBI2S_MDR_FRACT_MASK\fP)"

.SS "#define I2S_MDR_FRACT_MASK   (0xFF000U)"

.SS "#define I2S_MDR_FRACT_SHIFT   (12U)"

.SS "#define I2S_RCR1_RFW(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR1_RFW_SHIFT\fP)) & \fBI2S_RCR1_RFW_MASK\fP)"

.SS "#define I2S_RCR1_RFW_MASK   (0x7U)"

.SS "#define I2S_RCR1_RFW_SHIFT   (0U)"

.SS "#define I2S_RCR2_BCD(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR2_BCD_SHIFT\fP)) & \fBI2S_RCR2_BCD_MASK\fP)"

.SS "#define I2S_RCR2_BCD_MASK   (0x1000000U)"

.SS "#define I2S_RCR2_BCD_SHIFT   (24U)"

.SS "#define I2S_RCR2_BCI(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR2_BCI_SHIFT\fP)) & \fBI2S_RCR2_BCI_MASK\fP)"

.SS "#define I2S_RCR2_BCI_MASK   (0x10000000U)"

.SS "#define I2S_RCR2_BCI_SHIFT   (28U)"

.SS "#define I2S_RCR2_BCP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR2_BCP_SHIFT\fP)) & \fBI2S_RCR2_BCP_MASK\fP)"

.SS "#define I2S_RCR2_BCP_MASK   (0x2000000U)"

.SS "#define I2S_RCR2_BCP_SHIFT   (25U)"

.SS "#define I2S_RCR2_BCS(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR2_BCS_SHIFT\fP)) & \fBI2S_RCR2_BCS_MASK\fP)"

.SS "#define I2S_RCR2_BCS_MASK   (0x20000000U)"

.SS "#define I2S_RCR2_BCS_SHIFT   (29U)"

.SS "#define I2S_RCR2_DIV(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR2_DIV_SHIFT\fP)) & \fBI2S_RCR2_DIV_MASK\fP)"

.SS "#define I2S_RCR2_DIV_MASK   (0xFFU)"

.SS "#define I2S_RCR2_DIV_SHIFT   (0U)"

.SS "#define I2S_RCR2_MSEL(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR2_MSEL_SHIFT\fP)) & \fBI2S_RCR2_MSEL_MASK\fP)"

.SS "#define I2S_RCR2_MSEL_MASK   (0xC000000U)"

.SS "#define I2S_RCR2_MSEL_SHIFT   (26U)"

.SS "#define I2S_RCR2_SYNC(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR2_SYNC_SHIFT\fP)) & \fBI2S_RCR2_SYNC_MASK\fP)"

.SS "#define I2S_RCR2_SYNC_MASK   (0xC0000000U)"

.SS "#define I2S_RCR2_SYNC_SHIFT   (30U)"

.SS "#define I2S_RCR3_RCE(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR3_RCE_SHIFT\fP)) & \fBI2S_RCR3_RCE_MASK\fP)"

.SS "#define I2S_RCR3_RCE_MASK   (0x30000U)"

.SS "#define I2S_RCR3_RCE_SHIFT   (16U)"

.SS "#define I2S_RCR3_WDFL(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR3_WDFL_SHIFT\fP)) & \fBI2S_RCR3_WDFL_MASK\fP)"

.SS "#define I2S_RCR3_WDFL_MASK   (0x1FU)"

.SS "#define I2S_RCR3_WDFL_SHIFT   (0U)"

.SS "#define I2S_RCR4_FRSZ(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR4_FRSZ_SHIFT\fP)) & \fBI2S_RCR4_FRSZ_MASK\fP)"

.SS "#define I2S_RCR4_FRSZ_MASK   (0x1F0000U)"

.SS "#define I2S_RCR4_FRSZ_SHIFT   (16U)"

.SS "#define I2S_RCR4_FSD(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR4_FSD_SHIFT\fP)) & \fBI2S_RCR4_FSD_MASK\fP)"

.SS "#define I2S_RCR4_FSD_MASK   (0x1U)"

.SS "#define I2S_RCR4_FSD_SHIFT   (0U)"

.SS "#define I2S_RCR4_FSE(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR4_FSE_SHIFT\fP)) & \fBI2S_RCR4_FSE_MASK\fP)"

.SS "#define I2S_RCR4_FSE_MASK   (0x8U)"

.SS "#define I2S_RCR4_FSE_SHIFT   (3U)"

.SS "#define I2S_RCR4_FSP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR4_FSP_SHIFT\fP)) & \fBI2S_RCR4_FSP_MASK\fP)"

.SS "#define I2S_RCR4_FSP_MASK   (0x2U)"

.SS "#define I2S_RCR4_FSP_SHIFT   (1U)"

.SS "#define I2S_RCR4_MF(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR4_MF_SHIFT\fP)) & \fBI2S_RCR4_MF_MASK\fP)"

.SS "#define I2S_RCR4_MF_MASK   (0x10U)"

.SS "#define I2S_RCR4_MF_SHIFT   (4U)"

.SS "#define I2S_RCR4_SYWD(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR4_SYWD_SHIFT\fP)) & \fBI2S_RCR4_SYWD_MASK\fP)"

.SS "#define I2S_RCR4_SYWD_MASK   (0x1F00U)"

.SS "#define I2S_RCR4_SYWD_SHIFT   (8U)"

.SS "#define I2S_RCR5_FBT(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR5_FBT_SHIFT\fP)) & \fBI2S_RCR5_FBT_MASK\fP)"

.SS "#define I2S_RCR5_FBT_MASK   (0x1F00U)"

.SS "#define I2S_RCR5_FBT_SHIFT   (8U)"

.SS "#define I2S_RCR5_W0W(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR5_W0W_SHIFT\fP)) & \fBI2S_RCR5_W0W_MASK\fP)"

.SS "#define I2S_RCR5_W0W_MASK   (0x1F0000U)"

.SS "#define I2S_RCR5_W0W_SHIFT   (16U)"

.SS "#define I2S_RCR5_WNW(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCR5_WNW_SHIFT\fP)) & \fBI2S_RCR5_WNW_MASK\fP)"

.SS "#define I2S_RCR5_WNW_MASK   (0x1F000000U)"

.SS "#define I2S_RCR5_WNW_SHIFT   (24U)"

.SS "#define I2S_RCSR_BCE(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_BCE_SHIFT\fP)) & \fBI2S_RCSR_BCE_MASK\fP)"

.SS "#define I2S_RCSR_BCE_MASK   (0x10000000U)"

.SS "#define I2S_RCSR_BCE_SHIFT   (28U)"

.SS "#define I2S_RCSR_DBGE(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_DBGE_SHIFT\fP)) & \fBI2S_RCSR_DBGE_MASK\fP)"

.SS "#define I2S_RCSR_DBGE_MASK   (0x20000000U)"

.SS "#define I2S_RCSR_DBGE_SHIFT   (29U)"

.SS "#define I2S_RCSR_FEF(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_FEF_SHIFT\fP)) & \fBI2S_RCSR_FEF_MASK\fP)"

.SS "#define I2S_RCSR_FEF_MASK   (0x40000U)"

.SS "#define I2S_RCSR_FEF_SHIFT   (18U)"

.SS "#define I2S_RCSR_FEIE(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_FEIE_SHIFT\fP)) & \fBI2S_RCSR_FEIE_MASK\fP)"

.SS "#define I2S_RCSR_FEIE_MASK   (0x400U)"

.SS "#define I2S_RCSR_FEIE_SHIFT   (10U)"

.SS "#define I2S_RCSR_FR(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_FR_SHIFT\fP)) & \fBI2S_RCSR_FR_MASK\fP)"

.SS "#define I2S_RCSR_FR_MASK   (0x2000000U)"

.SS "#define I2S_RCSR_FR_SHIFT   (25U)"

.SS "#define I2S_RCSR_FRDE(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_FRDE_SHIFT\fP)) & \fBI2S_RCSR_FRDE_MASK\fP)"

.SS "#define I2S_RCSR_FRDE_MASK   (0x1U)"

.SS "#define I2S_RCSR_FRDE_SHIFT   (0U)"

.SS "#define I2S_RCSR_FRF(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_FRF_SHIFT\fP)) & \fBI2S_RCSR_FRF_MASK\fP)"

.SS "#define I2S_RCSR_FRF_MASK   (0x10000U)"

.SS "#define I2S_RCSR_FRF_SHIFT   (16U)"

.SS "#define I2S_RCSR_FRIE(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_FRIE_SHIFT\fP)) & \fBI2S_RCSR_FRIE_MASK\fP)"

.SS "#define I2S_RCSR_FRIE_MASK   (0x100U)"

.SS "#define I2S_RCSR_FRIE_SHIFT   (8U)"

.SS "#define I2S_RCSR_FWDE(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_FWDE_SHIFT\fP)) & \fBI2S_RCSR_FWDE_MASK\fP)"

.SS "#define I2S_RCSR_FWDE_MASK   (0x2U)"

.SS "#define I2S_RCSR_FWDE_SHIFT   (1U)"

.SS "#define I2S_RCSR_FWF(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_FWF_SHIFT\fP)) & \fBI2S_RCSR_FWF_MASK\fP)"

.SS "#define I2S_RCSR_FWF_MASK   (0x20000U)"

.SS "#define I2S_RCSR_FWF_SHIFT   (17U)"

.SS "#define I2S_RCSR_FWIE(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_FWIE_SHIFT\fP)) & \fBI2S_RCSR_FWIE_MASK\fP)"

.SS "#define I2S_RCSR_FWIE_MASK   (0x200U)"

.SS "#define I2S_RCSR_FWIE_SHIFT   (9U)"

.SS "#define I2S_RCSR_RE(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_RE_SHIFT\fP)) & \fBI2S_RCSR_RE_MASK\fP)"

.SS "#define I2S_RCSR_RE_MASK   (0x80000000U)"

.SS "#define I2S_RCSR_RE_SHIFT   (31U)"

.SS "#define I2S_RCSR_SEF(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_SEF_SHIFT\fP)) & \fBI2S_RCSR_SEF_MASK\fP)"

.SS "#define I2S_RCSR_SEF_MASK   (0x80000U)"

.SS "#define I2S_RCSR_SEF_SHIFT   (19U)"

.SS "#define I2S_RCSR_SEIE(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_SEIE_SHIFT\fP)) & \fBI2S_RCSR_SEIE_MASK\fP)"

.SS "#define I2S_RCSR_SEIE_MASK   (0x800U)"

.SS "#define I2S_RCSR_SEIE_SHIFT   (11U)"

.SS "#define I2S_RCSR_SR(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_SR_SHIFT\fP)) & \fBI2S_RCSR_SR_MASK\fP)"

.SS "#define I2S_RCSR_SR_MASK   (0x1000000U)"

.SS "#define I2S_RCSR_SR_SHIFT   (24U)"

.SS "#define I2S_RCSR_STOPE(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_STOPE_SHIFT\fP)) & \fBI2S_RCSR_STOPE_MASK\fP)"

.SS "#define I2S_RCSR_STOPE_MASK   (0x40000000U)"

.SS "#define I2S_RCSR_STOPE_SHIFT   (30U)"

.SS "#define I2S_RCSR_WSF(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_WSF_SHIFT\fP)) & \fBI2S_RCSR_WSF_MASK\fP)"

.SS "#define I2S_RCSR_WSF_MASK   (0x100000U)"

.SS "#define I2S_RCSR_WSF_SHIFT   (20U)"

.SS "#define I2S_RCSR_WSIE(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RCSR_WSIE_SHIFT\fP)) & \fBI2S_RCSR_WSIE_MASK\fP)"

.SS "#define I2S_RCSR_WSIE_MASK   (0x1000U)"

.SS "#define I2S_RCSR_WSIE_SHIFT   (12U)"

.SS "#define I2S_RDR_COUNT   (2U)"

.SS "#define I2S_RDR_RDR(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RDR_RDR_SHIFT\fP)) & \fBI2S_RDR_RDR_MASK\fP)"

.SS "#define I2S_RDR_RDR_MASK   (0xFFFFFFFFU)"

.SS "#define I2S_RDR_RDR_SHIFT   (0U)"

.SS "#define I2S_RFR_COUNT   (2U)"

.SS "#define I2S_RFR_RFP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RFR_RFP_SHIFT\fP)) & \fBI2S_RFR_RFP_MASK\fP)"

.SS "#define I2S_RFR_RFP_MASK   (0xFU)"

.SS "#define I2S_RFR_RFP_SHIFT   (0U)"

.SS "#define I2S_RFR_WFP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RFR_WFP_SHIFT\fP)) & \fBI2S_RFR_WFP_MASK\fP)"

.SS "#define I2S_RFR_WFP_MASK   (0xF0000U)"

.SS "#define I2S_RFR_WFP_SHIFT   (16U)"

.SS "#define I2S_RMR_RWM(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_RMR_RWM_SHIFT\fP)) & \fBI2S_RMR_RWM_MASK\fP)"

.SS "#define I2S_RMR_RWM_MASK   (0xFFFFFFFFU)"

.SS "#define I2S_RMR_RWM_SHIFT   (0U)"

.SS "#define I2S_RX_IRQS   { \fBI2S0_Rx_IRQn\fP }"
Interrupt vectors for the I2S peripheral type 
.SS "#define I2S_TCR1_TFW(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR1_TFW_SHIFT\fP)) & \fBI2S_TCR1_TFW_MASK\fP)"

.SS "#define I2S_TCR1_TFW_MASK   (0x7U)"

.SS "#define I2S_TCR1_TFW_SHIFT   (0U)"

.SS "#define I2S_TCR2_BCD(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR2_BCD_SHIFT\fP)) & \fBI2S_TCR2_BCD_MASK\fP)"

.SS "#define I2S_TCR2_BCD_MASK   (0x1000000U)"

.SS "#define I2S_TCR2_BCD_SHIFT   (24U)"

.SS "#define I2S_TCR2_BCI(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR2_BCI_SHIFT\fP)) & \fBI2S_TCR2_BCI_MASK\fP)"

.SS "#define I2S_TCR2_BCI_MASK   (0x10000000U)"

.SS "#define I2S_TCR2_BCI_SHIFT   (28U)"

.SS "#define I2S_TCR2_BCP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR2_BCP_SHIFT\fP)) & \fBI2S_TCR2_BCP_MASK\fP)"

.SS "#define I2S_TCR2_BCP_MASK   (0x2000000U)"

.SS "#define I2S_TCR2_BCP_SHIFT   (25U)"

.SS "#define I2S_TCR2_BCS(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR2_BCS_SHIFT\fP)) & \fBI2S_TCR2_BCS_MASK\fP)"

.SS "#define I2S_TCR2_BCS_MASK   (0x20000000U)"

.SS "#define I2S_TCR2_BCS_SHIFT   (29U)"

.SS "#define I2S_TCR2_DIV(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR2_DIV_SHIFT\fP)) & \fBI2S_TCR2_DIV_MASK\fP)"

.SS "#define I2S_TCR2_DIV_MASK   (0xFFU)"

.SS "#define I2S_TCR2_DIV_SHIFT   (0U)"

.SS "#define I2S_TCR2_MSEL(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR2_MSEL_SHIFT\fP)) & \fBI2S_TCR2_MSEL_MASK\fP)"

.SS "#define I2S_TCR2_MSEL_MASK   (0xC000000U)"

.SS "#define I2S_TCR2_MSEL_SHIFT   (26U)"

.SS "#define I2S_TCR2_SYNC(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR2_SYNC_SHIFT\fP)) & \fBI2S_TCR2_SYNC_MASK\fP)"

.SS "#define I2S_TCR2_SYNC_MASK   (0xC0000000U)"

.SS "#define I2S_TCR2_SYNC_SHIFT   (30U)"

.SS "#define I2S_TCR3_TCE(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR3_TCE_SHIFT\fP)) & \fBI2S_TCR3_TCE_MASK\fP)"

.SS "#define I2S_TCR3_TCE_MASK   (0x30000U)"

.SS "#define I2S_TCR3_TCE_SHIFT   (16U)"

.SS "#define I2S_TCR3_WDFL(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR3_WDFL_SHIFT\fP)) & \fBI2S_TCR3_WDFL_MASK\fP)"

.SS "#define I2S_TCR3_WDFL_MASK   (0x1FU)"

.SS "#define I2S_TCR3_WDFL_SHIFT   (0U)"

.SS "#define I2S_TCR4_FRSZ(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR4_FRSZ_SHIFT\fP)) & \fBI2S_TCR4_FRSZ_MASK\fP)"

.SS "#define I2S_TCR4_FRSZ_MASK   (0x1F0000U)"

.SS "#define I2S_TCR4_FRSZ_SHIFT   (16U)"

.SS "#define I2S_TCR4_FSD(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR4_FSD_SHIFT\fP)) & \fBI2S_TCR4_FSD_MASK\fP)"

.SS "#define I2S_TCR4_FSD_MASK   (0x1U)"

.SS "#define I2S_TCR4_FSD_SHIFT   (0U)"

.SS "#define I2S_TCR4_FSE(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR4_FSE_SHIFT\fP)) & \fBI2S_TCR4_FSE_MASK\fP)"

.SS "#define I2S_TCR4_FSE_MASK   (0x8U)"

.SS "#define I2S_TCR4_FSE_SHIFT   (3U)"

.SS "#define I2S_TCR4_FSP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR4_FSP_SHIFT\fP)) & \fBI2S_TCR4_FSP_MASK\fP)"

.SS "#define I2S_TCR4_FSP_MASK   (0x2U)"

.SS "#define I2S_TCR4_FSP_SHIFT   (1U)"

.SS "#define I2S_TCR4_MF(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR4_MF_SHIFT\fP)) & \fBI2S_TCR4_MF_MASK\fP)"

.SS "#define I2S_TCR4_MF_MASK   (0x10U)"

.SS "#define I2S_TCR4_MF_SHIFT   (4U)"

.SS "#define I2S_TCR4_SYWD(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR4_SYWD_SHIFT\fP)) & \fBI2S_TCR4_SYWD_MASK\fP)"

.SS "#define I2S_TCR4_SYWD_MASK   (0x1F00U)"

.SS "#define I2S_TCR4_SYWD_SHIFT   (8U)"

.SS "#define I2S_TCR5_FBT(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR5_FBT_SHIFT\fP)) & \fBI2S_TCR5_FBT_MASK\fP)"

.SS "#define I2S_TCR5_FBT_MASK   (0x1F00U)"

.SS "#define I2S_TCR5_FBT_SHIFT   (8U)"

.SS "#define I2S_TCR5_W0W(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR5_W0W_SHIFT\fP)) & \fBI2S_TCR5_W0W_MASK\fP)"

.SS "#define I2S_TCR5_W0W_MASK   (0x1F0000U)"

.SS "#define I2S_TCR5_W0W_SHIFT   (16U)"

.SS "#define I2S_TCR5_WNW(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCR5_WNW_SHIFT\fP)) & \fBI2S_TCR5_WNW_MASK\fP)"

.SS "#define I2S_TCR5_WNW_MASK   (0x1F000000U)"

.SS "#define I2S_TCR5_WNW_SHIFT   (24U)"

.SS "#define I2S_TCSR_BCE(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_BCE_SHIFT\fP)) & \fBI2S_TCSR_BCE_MASK\fP)"

.SS "#define I2S_TCSR_BCE_MASK   (0x10000000U)"

.SS "#define I2S_TCSR_BCE_SHIFT   (28U)"

.SS "#define I2S_TCSR_DBGE(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_DBGE_SHIFT\fP)) & \fBI2S_TCSR_DBGE_MASK\fP)"

.SS "#define I2S_TCSR_DBGE_MASK   (0x20000000U)"

.SS "#define I2S_TCSR_DBGE_SHIFT   (29U)"

.SS "#define I2S_TCSR_FEF(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_FEF_SHIFT\fP)) & \fBI2S_TCSR_FEF_MASK\fP)"

.SS "#define I2S_TCSR_FEF_MASK   (0x40000U)"

.SS "#define I2S_TCSR_FEF_SHIFT   (18U)"

.SS "#define I2S_TCSR_FEIE(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_FEIE_SHIFT\fP)) & \fBI2S_TCSR_FEIE_MASK\fP)"

.SS "#define I2S_TCSR_FEIE_MASK   (0x400U)"

.SS "#define I2S_TCSR_FEIE_SHIFT   (10U)"

.SS "#define I2S_TCSR_FR(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_FR_SHIFT\fP)) & \fBI2S_TCSR_FR_MASK\fP)"

.SS "#define I2S_TCSR_FR_MASK   (0x2000000U)"

.SS "#define I2S_TCSR_FR_SHIFT   (25U)"

.SS "#define I2S_TCSR_FRDE(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_FRDE_SHIFT\fP)) & \fBI2S_TCSR_FRDE_MASK\fP)"

.SS "#define I2S_TCSR_FRDE_MASK   (0x1U)"

.SS "#define I2S_TCSR_FRDE_SHIFT   (0U)"

.SS "#define I2S_TCSR_FRF(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_FRF_SHIFT\fP)) & \fBI2S_TCSR_FRF_MASK\fP)"

.SS "#define I2S_TCSR_FRF_MASK   (0x10000U)"

.SS "#define I2S_TCSR_FRF_SHIFT   (16U)"

.SS "#define I2S_TCSR_FRIE(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_FRIE_SHIFT\fP)) & \fBI2S_TCSR_FRIE_MASK\fP)"

.SS "#define I2S_TCSR_FRIE_MASK   (0x100U)"

.SS "#define I2S_TCSR_FRIE_SHIFT   (8U)"

.SS "#define I2S_TCSR_FWDE(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_FWDE_SHIFT\fP)) & \fBI2S_TCSR_FWDE_MASK\fP)"

.SS "#define I2S_TCSR_FWDE_MASK   (0x2U)"

.SS "#define I2S_TCSR_FWDE_SHIFT   (1U)"

.SS "#define I2S_TCSR_FWF(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_FWF_SHIFT\fP)) & \fBI2S_TCSR_FWF_MASK\fP)"

.SS "#define I2S_TCSR_FWF_MASK   (0x20000U)"

.SS "#define I2S_TCSR_FWF_SHIFT   (17U)"

.SS "#define I2S_TCSR_FWIE(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_FWIE_SHIFT\fP)) & \fBI2S_TCSR_FWIE_MASK\fP)"

.SS "#define I2S_TCSR_FWIE_MASK   (0x200U)"

.SS "#define I2S_TCSR_FWIE_SHIFT   (9U)"

.SS "#define I2S_TCSR_SEF(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_SEF_SHIFT\fP)) & \fBI2S_TCSR_SEF_MASK\fP)"

.SS "#define I2S_TCSR_SEF_MASK   (0x80000U)"

.SS "#define I2S_TCSR_SEF_SHIFT   (19U)"

.SS "#define I2S_TCSR_SEIE(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_SEIE_SHIFT\fP)) & \fBI2S_TCSR_SEIE_MASK\fP)"

.SS "#define I2S_TCSR_SEIE_MASK   (0x800U)"

.SS "#define I2S_TCSR_SEIE_SHIFT   (11U)"

.SS "#define I2S_TCSR_SR(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_SR_SHIFT\fP)) & \fBI2S_TCSR_SR_MASK\fP)"

.SS "#define I2S_TCSR_SR_MASK   (0x1000000U)"

.SS "#define I2S_TCSR_SR_SHIFT   (24U)"

.SS "#define I2S_TCSR_STOPE(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_STOPE_SHIFT\fP)) & \fBI2S_TCSR_STOPE_MASK\fP)"

.SS "#define I2S_TCSR_STOPE_MASK   (0x40000000U)"

.SS "#define I2S_TCSR_STOPE_SHIFT   (30U)"

.SS "#define I2S_TCSR_TE(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_TE_SHIFT\fP)) & \fBI2S_TCSR_TE_MASK\fP)"

.SS "#define I2S_TCSR_TE_MASK   (0x80000000U)"

.SS "#define I2S_TCSR_TE_SHIFT   (31U)"

.SS "#define I2S_TCSR_WSF(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_WSF_SHIFT\fP)) & \fBI2S_TCSR_WSF_MASK\fP)"

.SS "#define I2S_TCSR_WSF_MASK   (0x100000U)"

.SS "#define I2S_TCSR_WSF_SHIFT   (20U)"

.SS "#define I2S_TCSR_WSIE(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TCSR_WSIE_SHIFT\fP)) & \fBI2S_TCSR_WSIE_MASK\fP)"

.SS "#define I2S_TCSR_WSIE_MASK   (0x1000U)"

.SS "#define I2S_TCSR_WSIE_SHIFT   (12U)"

.SS "#define I2S_TDR_COUNT   (2U)"

.SS "#define I2S_TDR_TDR(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TDR_TDR_SHIFT\fP)) & \fBI2S_TDR_TDR_MASK\fP)"

.SS "#define I2S_TDR_TDR_MASK   (0xFFFFFFFFU)"

.SS "#define I2S_TDR_TDR_SHIFT   (0U)"

.SS "#define I2S_TFR_COUNT   (2U)"

.SS "#define I2S_TFR_RFP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TFR_RFP_SHIFT\fP)) & \fBI2S_TFR_RFP_MASK\fP)"

.SS "#define I2S_TFR_RFP_MASK   (0xFU)"

.SS "#define I2S_TFR_RFP_SHIFT   (0U)"

.SS "#define I2S_TFR_WFP(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TFR_WFP_SHIFT\fP)) & \fBI2S_TFR_WFP_MASK\fP)"

.SS "#define I2S_TFR_WFP_MASK   (0xF0000U)"

.SS "#define I2S_TFR_WFP_SHIFT   (16U)"

.SS "#define I2S_TMR_TWM(x)   (((uint32_t)(((uint32_t)(x)) << \fBI2S_TMR_TWM_SHIFT\fP)) & \fBI2S_TMR_TWM_MASK\fP)"

.SS "#define I2S_TMR_TWM_MASK   (0xFFFFFFFFU)"

.SS "#define I2S_TMR_TWM_SHIFT   (0U)"

.SS "#define I2S_TX_IRQS   { \fBI2S0_Tx_IRQn\fP }"

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
