.TH "I2S_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2S_Type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MK64F12\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTCSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTCR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTCR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTCR3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTCR4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTCR5\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_0\fP [8]"
.br
.ti -1c
.RI "\fB__O\fP uint32_t \fBTDR\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_1\fP [24]"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBTFR\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_2\fP [24]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTMR\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_3\fP [28]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRCSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRCR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRCR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRCR3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRCR4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRCR5\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_4\fP [8]"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBRDR\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_5\fP [24]"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBRFR\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_6\fP [24]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRMR\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_7\fP [28]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMDR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
I2S - Register Layout Typedef 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
