.TH "IPSR_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPSR_Type \- Union type to access the Interrupt Program Status Register (IPSR)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <core_armv8mbl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fBw\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Union type to access the Interrupt Program Status Register (IPSR)\&. 
.SH "Field Documentation"
.PP 
.SS "uint32_t _reserved0"
bit: 9\&.\&.31 Reserved 
.SS "struct { \&.\&.\&. }   b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }   b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }   b"
Structure used for bit access 
.SS "uint32_t ISR"
bit: 0\&.\&. 8 Exception number 
.SS "uint32_t w"
Type used for word access 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
