.TH "ITM_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ITM_Type \- Structure type to access the Instrumentation Trace Macrocell Register (ITM)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <core_armv8mml\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fB__OM\fP uint8_t \fBu8\fP"
.br
.ti -1c
.RI "   \fB__OM\fP uint16_t \fBu16\fP"
.br
.ti -1c
.RI "   \fB__OM\fP uint32_t \fBu32\fP"
.br
.ti -1c
.RI "} \fBPORT\fP [32U]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED0\fP [864U]"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBTER\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED1\fP [15U]"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBTPR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED2\fP [15U]"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBTCR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED3\fP [29U]"
.br
.ti -1c
.RI "\fB__OM\fP uint32_t \fBIWR\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBIRR\fP"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBIMCR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED4\fP [43U]"
.br
.ti -1c
.RI "\fB__OM\fP uint32_t \fBLAR\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBLSR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED5\fP [1U]"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBDEVARCH\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED6\fP [4U]"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBPID4\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBPID5\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBPID6\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBPID7\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBPID0\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBPID1\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBPID2\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBPID3\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBCID0\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBCID1\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBCID2\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBCID3\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fB__OM\fP uint8_t \fBu8\fP"
.br
.ti -1c
.RI "   \fB__OM\fP uint16_t \fBu16\fP"
.br
.ti -1c
.RI "   \fB__OM\fP uint32_t \fBu32\fP"
.br
.ti -1c
.RI "} \fBPORT\fP [32U]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure type to access the Instrumentation Trace Macrocell Register (ITM)\&. 
.SH "Field Documentation"
.PP 
.SS "\fB__IM\fP uint32_t CID0"
Offset: 0xFF0 (R/ ) ITM Component Identification Register #0 
.SS "\fB__IM\fP uint32_t CID1"
Offset: 0xFF4 (R/ ) ITM Component Identification Register #1 
.SS "\fB__IM\fP uint32_t CID2"
Offset: 0xFF8 (R/ ) ITM Component Identification Register #2 
.SS "\fB__IM\fP uint32_t CID3"
Offset: 0xFFC (R/ ) ITM Component Identification Register #3 
.SS "\fB__IM\fP uint32_t DEVARCH"
Offset: 0xFBC (R/ ) ITM Device Architecture Register 
.SS "\fB__IOM\fP uint32_t IMCR"
Offset: 0xF00 (R/W) ITM Integration Mode Control Register 
.SS "\fB__IM\fP uint32_t IRR"
Offset: 0xEFC (R/ ) ITM Integration Read Register 
.SS "\fB__OM\fP uint32_t IWR"
Offset: 0xEF8 ( /W) ITM Integration Write Register 
.SS "\fB__OM\fP uint32_t LAR"
Offset: 0xFB0 ( /W) ITM Lock Access Register 
.SS "\fB__IM\fP uint32_t LSR"
Offset: 0xFB4 (R/ ) ITM Lock Status Register 
.SS "\fB__IM\fP uint32_t PID0"
Offset: 0xFE0 (R/ ) ITM Peripheral Identification Register #0 
.SS "\fB__IM\fP uint32_t PID1"
Offset: 0xFE4 (R/ ) ITM Peripheral Identification Register #1 
.SS "\fB__IM\fP uint32_t PID2"
Offset: 0xFE8 (R/ ) ITM Peripheral Identification Register #2 
.SS "\fB__IM\fP uint32_t PID3"
Offset: 0xFEC (R/ ) ITM Peripheral Identification Register #3 
.SS "\fB__IM\fP uint32_t PID4"
Offset: 0xFD0 (R/ ) ITM Peripheral Identification Register #4 
.SS "\fB__IM\fP uint32_t PID5"
Offset: 0xFD4 (R/ ) ITM Peripheral Identification Register #5 
.SS "\fB__IM\fP uint32_t PID6"
Offset: 0xFD8 (R/ ) ITM Peripheral Identification Register #6 
.SS "\fB__IM\fP uint32_t PID7"
Offset: 0xFDC (R/ ) ITM Peripheral Identification Register #7 
.SS "__OM { \&.\&.\&. }    PORT[32U]"
Offset: 0x000 ( /W) ITM Stimulus Port Registers 
.SS "__OM { \&.\&.\&. }    PORT[32U]"
Offset: 0x000 ( /W) ITM Stimulus Port Registers 
.SS "uint32_t RESERVED0"

.SS "uint32_t RESERVED1"

.SS "uint32_t RESERVED2"

.SS "uint32_t RESERVED3"

.SS "uint32_t RESERVED4"

.SS "uint32_t RESERVED5"

.SS "uint32_t RESERVED6[4U]"

.SS "\fB__IOM\fP uint32_t TCR"
Offset: 0xE80 (R/W) ITM Trace Control Register 
.SS "\fB__IOM\fP uint32_t TER"
Offset: 0xE00 (R/W) ITM Trace Enable Register 
.SS "\fB__IOM\fP uint32_t TPR"
Offset: 0xE40 (R/W) ITM Trace Privilege Register 
.SS "\fB__OM\fP uint16_t u16"
Offset: 0x000 ( /W) ITM Stimulus Port 16-bit 
.SS "\fB__OM\fP uint32_t u32"
Offset: 0x000 ( /W) ITM Stimulus Port 32-bit 
.SS "\fB__OM\fP uint8_t u8"
Offset: 0x000 ( /W) ITM Stimulus Port 8-bit 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
