.TH "LinearInterpolate" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LinearInterpolate
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "CMSIS_INLINE \fB__STATIC_INLINE\fP \fBfloat32_t\fP \fBarm_linear_interp_f32\fP (\fBarm_linear_interp_instance_f32\fP *S, \fBfloat32_t\fP x)"
.br
.RI "Process function for the floating-point Linear Interpolation Function\&. "
.ti -1c
.RI "CMSIS_INLINE \fB__STATIC_INLINE\fP \fBq31_t\fP \fBarm_linear_interp_q31\fP (\fBq31_t\fP *pYData, \fBq31_t\fP x, uint32_t nValues)"
.br
.RI "Process function for the Q31 Linear Interpolation Function\&. "
.ti -1c
.RI "CMSIS_INLINE \fB__STATIC_INLINE\fP \fBq15_t\fP \fBarm_linear_interp_q15\fP (\fBq15_t\fP *pYData, \fBq31_t\fP x, uint32_t nValues)"
.br
.RI "Process function for the Q15 Linear Interpolation Function\&. "
.ti -1c
.RI "CMSIS_INLINE \fB__STATIC_INLINE\fP \fBq7_t\fP \fBarm_linear_interp_q7\fP (\fBq7_t\fP *pYData, \fBq31_t\fP x, uint32_t nValues)"
.br
.RI "Process function for the Q7 Linear Interpolation Function\&. "
.in -1c
.SH "Detailed Description"
.PP 
Linear interpolation is a method of curve fitting using linear polynomials\&. Linear interpolation works by effectively drawing a straight line between two neighboring samples and returning the appropriate point along that line
.PP
\fB\fP
.RS 4
Linear interpolation 
.RE
.PP
\fB\fP
.RS 4
A Linear Interpolate function calculates an output value(y), for the input(x) using linear interpolation of the input values x0, x1( nearest input values) and the output values y0 and y1(nearest output values)
.RE
.PP
\fBAlgorithm:\fP
.RS 4

.PP
.nf

      y = y0 + (x - x0) * ((y1 - y0)/(x1-x0))
      where x0, x1 are nearest values of input x
            y0, y1 are nearest values to output y
.fi
.PP
.RE
.PP
\fB\fP
.RS 4
This set of functions implements Linear interpolation process for Q7, Q15, Q31, and floating-point data types\&. The functions operate on a single sample of data and each call to the function returns a single processed value\&. \fCS\fP points to an instance of the Linear Interpolate function data structure\&. \fCx\fP is the input sample value\&. The functions returns the output value\&.
.RE
.PP
\fB\fP
.RS 4
if x is outside of the table boundary, Linear interpolation returns first value of the table if x is below input range and returns last value of table if x is above range\&. 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "CMSIS_INLINE \fB__STATIC_INLINE\fP \fBfloat32_t\fP arm_linear_interp_f32 (\fBarm_linear_interp_instance_f32\fP * S, \fBfloat32_t\fP x)"

.PP
Process function for the floating-point Linear Interpolation Function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIS\fP is an instance of the floating-point Linear Interpolation structure 
.br
\fIx\fP input sample to process 
.RE
.PP
\fBReturns:\fP
.RS 4
y processed output sample\&. 
.RE
.PP

.SS "CMSIS_INLINE \fB__STATIC_INLINE\fP \fBq15_t\fP arm_linear_interp_q15 (\fBq15_t\fP * pYData, \fBq31_t\fP x, uint32_t nValues)"

.PP
Process function for the Q15 Linear Interpolation Function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpYData\fP pointer to Q15 Linear Interpolation table 
.br
\fIx\fP input sample to process 
.br
\fInValues\fP number of table values 
.RE
.PP
\fBReturns:\fP
.RS 4
y processed output sample\&.
.RE
.PP
\fB\fP
.RS 4
Input sample \fCx\fP is in 12\&.20 format which contains 12 bits for table index and 20 bits for fractional part\&. This function can support maximum of table size 2^12\&. 
.RE
.PP

.SS "CMSIS_INLINE \fB__STATIC_INLINE\fP \fBq31_t\fP arm_linear_interp_q31 (\fBq31_t\fP * pYData, \fBq31_t\fP x, uint32_t nValues)"

.PP
Process function for the Q31 Linear Interpolation Function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpYData\fP pointer to Q31 Linear Interpolation table 
.br
\fIx\fP input sample to process 
.br
\fInValues\fP number of table values 
.RE
.PP
\fBReturns:\fP
.RS 4
y processed output sample\&.
.RE
.PP
\fB\fP
.RS 4
Input sample \fCx\fP is in 12\&.20 format which contains 12 bits for table index and 20 bits for fractional part\&. This function can support maximum of table size 2^12\&. 
.RE
.PP

.SS "CMSIS_INLINE \fB__STATIC_INLINE\fP \fBq7_t\fP arm_linear_interp_q7 (\fBq7_t\fP * pYData, \fBq31_t\fP x, uint32_t nValues)"

.PP
Process function for the Q7 Linear Interpolation Function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpYData\fP pointer to Q7 Linear Interpolation table 
.br
\fIx\fP input sample to process 
.br
\fInValues\fP number of table values 
.RE
.PP
\fBReturns:\fP
.RS 4
y processed output sample\&.
.RE
.PP
\fB\fP
.RS 4
Input sample \fCx\fP is in 12\&.20 format which contains 12 bits for table index and 20 bits for fractional part\&. This function can support maximum of table size 2^12\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
