.TH "LLWU_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LLWU_Type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MK64F12\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint8_t \fBPE1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBPE2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBPE3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBPE4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBME\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBF1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBF2\fP"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBF3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBFILT1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBFILT2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBRST\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
LLWU - Register Layout Typedef 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
