.TH "SDK/startup/main.c" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDK/startup/main.c \- FW main\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'hardware\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBApp_Init\fP (void)"
.br
.ti -1c
.RI "void \fBApp_Run\fP (void)"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
FW main\&. 


.PP
\fBAuthor:\fP
.RS 4
Nicolás Magliola 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void App_Init (void)"

.SS "void App_Run (void)"

.SS "int main (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
