.TH "MCM_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MCM_Type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MK64F12\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBRESERVED_0\fP [8]"
.br
.ti -1c
.RI "\fB__I\fP uint16_t \fBPLASC\fP"
.br
.ti -1c
.RI "\fB__I\fP uint16_t \fBPLAMC\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBISCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBETBCC\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBETBRL\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBETBCNT\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_1\fP [16]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
MCM - Register Layout Typedef 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
