.TH "SDK/CMSIS/MK64F12_features.h" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDK/CMSIS/MK64F12_features.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFSL_FEATURE_ADC16_HAS_PGA\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_ADC16_HAS_PGA_CHOPPING\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_ADC16_HAS_PGA_OFFSET_MEASUREMENT\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_ADC16_HAS_DMA\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_ADC16_HAS_DIFF_MODE\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_ADC16_HAS_FIFO\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_ADC16_FIFO_SIZE\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_ADC16_HAS_MUX_SELECT\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_ADC16_HAS_HW_TRIGGER_MASK\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_ADC16_HAS_CALIBRATION\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_ADC16_HAS_HW_AVERAGE\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_ADC16_HAS_OFFSET_CORRECTION\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_ADC16_MAX_RESOLUTION\fP   (16)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_ADC16_CONVERSION_CONTROL_COUNT\fP   (2)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_FLEXCAN_HAS_MESSAGE_BUFFER_MAX_NUMBERn\fP(x)   (16)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_FLEXCAN_HAS_DOZE_MODE_SUPPORT\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_FLEXCAN_HAS_GLITCH_FILTER\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_FLEXCAN_HAS_EXTENDED_FLAG_REGISTER\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_FLEXCAN_HAS_EXTENDED_TIMING_REGISTER\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_FLEXCAN_HAS_RX_FIFO_DMA\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_FLEXCAN_HAS_SEPARATE_BUFFER_0_FLAG\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_FLEXCAN_HAS_BUF31TO0M\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_FLEXCAN_INTERRUPT_COUNT\fP   (6)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_FLEXCAN_HAS_ERRATA_5641\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_CMP_HAS_TRIGGER_MODE\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_CMP_HAS_WINDOW_MODE\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_CMP_HAS_EXTERNAL_SAMPLE_SUPPORT\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_CMP_HAS_DMA\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_CMP_HAS_PASS_THROUGH_MODE\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_CMP_HAS_DAC_TEST\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_CRC_HAS_CRC_REG\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_DAC_BUFFER_SIZE\fP   (16)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_DAC_HAS_WATERMARK_DETECTION\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_DAC_HAS_WATERMARK_SELECTION\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_DAC_HAS_WATERMARK_1_WORD\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_DAC_HAS_WATERMARK_2_WORDS\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_DAC_HAS_WATERMARK_3_WORDS\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_DAC_HAS_WATERMARK_4_WORDS\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_DAC_HAS_BUFFER_FIFO_MODE\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_DAC_HAS_BUFFER_SWING_MODE\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_EDMA_MODULE_CHANNEL\fP   (16)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_EDMA_DMAMUX_CHANNELS\fP   (FSL_FEATURE_SOC_EDMA_COUNT * 16)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_EDMA_CHANNEL_GROUP_COUNT\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_EDMA_HAS_ERROR_IRQ\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_EDMA_ASYNCHRO_REQUEST_CHANNEL_COUNT\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_DMAMUX_MODULE_CHANNEL\fP   (16)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_DMAMUX_DMAMUX_CHANNELS\fP   (FSL_FEATURE_SOC_DMAMUX_COUNT * 16)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_DMAMUX_HAS_TRIG\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_ENET_DMA_BIG_ENDIAN_ONLY\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_ENET_SUPPORT_PTP\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_ENET_INTERRUPT_COUNT\fP   (4)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_ENET_HAS_RECEIVE_STATUS_THRESHOLD\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_EWM_HAS_CLOCK_SELECT\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_EWM_HAS_PRESCALER\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_FTM_CHANNEL_COUNTn\fP(x)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_FTM_HAS_COUNTER_RESET_BY_CAPTURE_EVENT\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_FTM_HAS_EXTENDED_DEADTIME_VALUE\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_FTM_HAS_ENABLE_PWM_OUTPUT\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_FTM_HAS_HALFCYCLE_RELOAD\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_FTM_HAS_RELOAD_INTERRUPT\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_FTM_HAS_RELOAD_INITIALIZATION_TRIGGER\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_FTM_HAS_DMA_SUPPORT\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_FTM_HAS_NO_QDCTRL\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_GPIO_HAS_FAST_GPIO\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_GPIO_HAS_INPUT_DISABLE\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_GPIO_HAS_PORT_INTERRUPT_VECTOR\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_I2C_HAS_SMBUS\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_I2C_MAX_BAUD_KBPS\fP   (400)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_I2C_HAS_ERRATA_6070\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_I2C_HAS_DMA_SUPPORT\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_I2C_HAS_START_STOP_DETECT\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_I2C_HAS_STOP_DETECT\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_I2C_HAS_STOP_HOLD_OFF\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_I2C_MAX_GLITCH_FILTER_WIDTH\fP   (15)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_I2C_HAS_HIGH_DRIVE_SELECTION\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_I2C_HAS_DOUBLE_BUFFERING\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_I2C_HAS_DOUBLE_BUFFER_ENABLE\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SAI_FIFO_COUNT\fP   (8)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SAI_CHANNEL_COUNT\fP   (2)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SAI_MAX_WORDS_PER_FRAME\fP   (32)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SAI_HAS_FIFO_COMBINE_MODE\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SAI_HAS_FIFO_PACKING\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SAI_HAS_FIFO_FUNCTION_AFTER_ERROR\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SAI_HAS_ON_DEMAND_MODE\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SAI_HAS_CLOCKING_MODE\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SAI_HAS_MCLKDIV_REGISTER\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SAI_INT_SOURCE_NUM\fP   (2)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SAI_HAS_MCR\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SAI_HAS_MDR\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN\fP   (16)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_EXTERNAL_PIN_GROUP2\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_INTERNAL_MODULE\fP   (8)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_PIN_FILTER\fP   (2)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_MF\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_PF\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_RESET_ENABLE\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_NO_INTERNAL_MODULE_WAKEUP_FLAG_REG\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN0\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN0_GPIO_IDX\fP   (GPIOE_IDX)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN0_GPIO_PIN\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN1\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN1_GPIO_IDX\fP   (GPIOE_IDX)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN1_GPIO_PIN\fP   (2)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN2\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN2_GPIO_IDX\fP   (GPIOE_IDX)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN2_GPIO_PIN\fP   (4)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN3\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN3_GPIO_IDX\fP   (GPIOA_IDX)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN3_GPIO_PIN\fP   (4)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN4\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN4_GPIO_IDX\fP   (GPIOA_IDX)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN4_GPIO_PIN\fP   (13)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN5\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN5_GPIO_IDX\fP   (GPIOB_IDX)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN5_GPIO_PIN\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN6\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN6_GPIO_IDX\fP   (GPIOC_IDX)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN6_GPIO_PIN\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN7\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN7_GPIO_IDX\fP   (GPIOC_IDX)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN7_GPIO_PIN\fP   (3)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN8\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN8_GPIO_IDX\fP   (GPIOC_IDX)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN8_GPIO_PIN\fP   (4)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN9\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN9_GPIO_IDX\fP   (GPIOC_IDX)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN9_GPIO_PIN\fP   (5)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN10\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN10_GPIO_IDX\fP   (GPIOC_IDX)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN10_GPIO_PIN\fP   (6)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN11\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN11_GPIO_IDX\fP   (GPIOC_IDX)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN11_GPIO_PIN\fP   (11)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN12\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN12_GPIO_IDX\fP   (GPIOD_IDX)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN12_GPIO_PIN\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN13\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN13_GPIO_IDX\fP   (GPIOD_IDX)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN13_GPIO_PIN\fP   (2)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN14\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN14_GPIO_IDX\fP   (GPIOD_IDX)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN14_GPIO_PIN\fP   (4)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN15\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN15_GPIO_IDX\fP   (GPIOD_IDX)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN15_GPIO_PIN\fP   (6)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN16\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN16_GPIO_IDX\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN16_GPIO_PIN\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN17\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN17_GPIO_IDX\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN17_GPIO_PIN\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN18\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN18_GPIO_IDX\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN18_GPIO_PIN\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN19\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN19_GPIO_IDX\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN19_GPIO_PIN\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN20\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN20_GPIO_IDX\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN20_GPIO_PIN\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN21\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN21_GPIO_IDX\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN21_GPIO_PIN\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN22\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN22_GPIO_IDX\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN22_GPIO_PIN\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN23\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN23_GPIO_IDX\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN23_GPIO_PIN\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN24\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN24_GPIO_IDX\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN24_GPIO_PIN\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN25\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN25_GPIO_IDX\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN25_GPIO_PIN\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN26\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN26_GPIO_IDX\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN26_GPIO_PIN\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN27\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN27_GPIO_IDX\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN27_GPIO_PIN\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN28\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN28_GPIO_IDX\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN28_GPIO_PIN\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN29\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN29_GPIO_IDX\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN29_GPIO_PIN\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN30\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN30_GPIO_IDX\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN30_GPIO_PIN\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_EXTERNAL_PIN31\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN31_GPIO_IDX\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_PIN31_GPIO_PIN\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_INTERNAL_MODULE0\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_INTERNAL_MODULE1\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_INTERNAL_MODULE2\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_INTERNAL_MODULE3\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_INTERNAL_MODULE4\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_INTERNAL_MODULE5\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_INTERNAL_MODULE6\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_INTERNAL_MODULE7\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_VERID\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_PARAM\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_REG_BITWIDTH\fP   (8)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LLWU_HAS_DMA_ENABLE_REG\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LPTMR_HAS_SHARED_IRQ_HANDLER\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LPTMR_CNR_WIDTH_IS_32B\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_LPTMR_HAS_CSR_TDRE\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_PLL_PRDIV_BASE\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_PLL_PRDIV_MAX\fP   (24)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_PLL_VDIV_BASE\fP   (24)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_PLL_REF_MIN\fP   (2000000)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_PLL_REF_MAX\fP   (4000000)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_HAS_PLL_INTERNAL_DIV\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_FRDIV_SUPPORT_1280\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_FRDIV_SUPPORT_1536\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_FFCLK_DIV\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_HAS_PLL_EXTRA_DIV\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_HAS_RTC_32K\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_HAS_PLL1\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_HAS_IRC_48M\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_HAS_OSC1\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_HAS_FCFTRIM\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_HAS_LOLRE\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_USE_OSCSEL\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_USE_PLLREFSEL\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_USE_SYSTEM_CLOCK\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_HAS_PLL\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_HAS_PLL_PRDIV\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_HAS_PLL_VDIV\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_HAS_PLL_OSC_INDEX\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_HAS_FLL\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_HAS_EXTERNAL_PLL\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_HAS_EXT_REF_LOW_POWER_CONTROL\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_HAS_PLL_FLL_SELECTION\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_HAS_PLL_OUTPUT_SELECTION\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_HAS_AUTO_TRIM_MACHINE\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_HAS_EXTERNAL_CLOCK_MONITOR\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_HAS_LOW_FREQ_IRC\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_HAS_HIGH_FREQ_IRC\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_HAS_PLL_INTERNAL_MODE\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_MCG_RESET_IS_BLPI\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_INTERRUPT_IRQ_MIN\fP   (\-14)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_INTERRUPT_IRQ_MAX\fP   (85)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_OSC_HAS_OSC1\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_OSC_HAS_OSC0\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_OSC_HAS_OSC\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_OSC_OSC_COUNT\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_OSC_HAS_EXT_REF_CLOCK_DIVIDER\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PDB_ADC_PRE_CHANNEL_COUNT\fP   (2)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PDB_HAS_DAC\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PDB_HAS_SHARED_IRQ_HANDLER\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PIT_TIMER_COUNT\fP   (4)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PIT_HAS_LIFETIME_TIMER\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PIT_HAS_CHAIN_MODE\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PIT_HAS_SHARED_IRQ_HANDLER\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PIT_HAS_MDIS\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PMC_HAS_BGEN\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PMC_HAS_BGBE\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PMC_HAS_BGBDS\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PMC_HAS_LVDV\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PMC_HAS_LVWV\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PMC_HAS_LPO\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PMC_HAS_VLPO\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PMC_HAS_ACKISO\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PMC_HAS_REGFPM\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PMC_HAS_REGONS\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PMC_HAS_HVDSC1\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PMC_HAS_PARAM\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PMC_HAS_VERID\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PORT_HAS_PIN_CONTROL_LOCK\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PORT_HAS_OPEN_DRAIN\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PORT_HAS_DIGITAL_FILTER\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PORT_HAS_DMA_REQUEST\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PORT_HAS_PULL_SELECTION\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PORT_HAS_PULL_ENABLE\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PORT_HAS_SLEW_RATE\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PORT_HAS_PASSIVE_FILTER\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PORT_HAS_DRIVE_STRENGTH\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PORT_HAS_DRIVE_STRENGTH_REGISTER\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PORT_HAS_GLITCH_FILTER\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PORT_PCR_MUX_WIDTH\fP   (3)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PORT_HAS_INTERRUPT_VECTOR\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PORT_HAS_MULTIPLE_IRQ_CONFIG\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PORT_HAS_IRQC_FLAG\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_PORT_HAS_IRQC_TRIGGER\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_RCM_HAS_LOL\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_RCM_HAS_LOC\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_RCM_HAS_JTAG\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_RCM_HAS_EZPORT\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_RCM_HAS_EZPMS\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_RCM_HAS_BOOTROM\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_RCM_HAS_SSRS\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_RCM_HAS_VERID\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_RCM_HAS_PARAM\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_RCM_HAS_SRIE\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_RCM_REG_WIDTH\fP   (8)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_RCM_HAS_CORE1\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_RCM_HAS_MDM_AP\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_RCM_HAS_WAKEUP\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SDHC_HAS_EXTERNAL_DMA_SUPPORT\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SDHC_HAS_V300_SUPPORT\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SDHC_HAS_V180_SUPPORT\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_USBFS_USE_SPECIAL_DIVIDER\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_PLLCLK_USE_SPECIAL_DIVIDER\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_RAMSIZE\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_OSC32K_OUT\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_OSC32K_SELECTION\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_OSC32K_SELECTION_WIDTH\fP   (2)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_RTC_CLOCK_OUT_SELECTION\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_USB_VOLTAGE_REGULATOR\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_USB_PHY\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_PTD7PAD\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_FBSL\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_PCR\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_MCC\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_ODE\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_LPUART_COUNT\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_UART_COUNT\fP   (4)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_UART0_ODE\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_UART1_ODE\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_UART2_ODE\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_LPUART0_ODE\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_LPUART1_ODE\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_CMTUARTPAD\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_LPUART0_TX_SRC\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_LPUART0_RX_SRC\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_LPUART1_TX_SRC\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_LPUART1_RX_SRC\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_UART0_TX_SRC\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_UART0_TX_SRC_WIDTH\fP   (2)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_UART0_RX_SRC\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_UART0_RX_SRC_WIDTH\fP   (2)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_UART1_TX_SRC\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_UART1_RX_SRC\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_UART1_RX_SRC_WIDTH\fP   (2)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_FTM\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_FTM_COUNT\fP   (4)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_FTM_TRIGGER_COUNT\fP   (2)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_FTM0_TRIGGER\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_FTM3_TRIGGER\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_FTM1_CHANNELS\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_FTM2_CHANNELS\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_FTM3_CHANNELS\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_FTM2_CHANNEL1\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_FTM0_FAULT_COUNT\fP   (3)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_FTM1_FAULT_COUNT\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_FTM2_FAULT_COUNT\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_FTM3_FAULT_COUNT\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_FTM_TRIGGER_SYNC\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_FTM_CHANNELS_OUTPUT_SRC\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_TPM\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_MAX_TPM_INDEX\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_TPM0\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_TPM0_CLK_SEL\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_TPM_CHANNELS_CONFIG_IN_SOPT4_REG\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_TPM1_CH0_SRC_SELECTION\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_TPM1_CLK_SEL\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_TPM1_CH0_SRC_SELECTION_WIDTH\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_TPM2_CH0_SRC_SELECTION\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_TPM2_CLK_SEL\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_PLL_FLL_SELECTION\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_PLL_FLL_SELECTION_WIDTH\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_NFCSRC\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_ESDHCSRC\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_SDHCSRC\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_LCDCSRC\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_TIMESRC\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_RMIISRC\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_USBSRC\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_USBFSRC\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_USBHSRC\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_LPUARTSRC\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_LPUART0SRC\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_LPUART1SRC\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_FLEXIOSRC\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_UART0SRC\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_TPMSRC\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HAS_TRACE_CLKSEL\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_ADC_COUNT\fP   (2)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_ADC0ALTTRGEN_WIDTH\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_ADC1ALTTRGEN_WIDTH\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_ADC2ALTTRGEN_WIDTH\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_ADC3ALTTRGEN_WIDTH\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HSADC0AALTTRGEN_WIDTH\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HSADC1AALTTRGEN_WIDTH\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_ADCAALTTRGEN_WIDTH\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HSADC0BALTTRGEN_WIDTH\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_HSADC1BALTTRGEN_WIDTH\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_OPT_ADCBALTTRGEN_WIDTH\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_DIVIDER_HAS_OUTDIV2\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_DIVIDER_HAS_OUTDIV3\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_DIVIDER_HAS_OUTDIV4\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_DIVIDER_OUTDIV4_WIDTH\fP   (4)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_DIVIDER_HAS_OUTDIV5\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_DIVIDER_HAS_USBDIV\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_DIVIDER_HAS_USBFSDIV\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_DIVIDER_HAS_USBHSDIV\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_DIVIDER_HAS_PLLFLLDIV\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_DIVIDER_HAS_LCDCDIV\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_DIVIDER_HAS_TRACEDIV\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_DIVIDER_HAS_NFCDIV\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_SDID_HAS_FAMILYID\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_SDID_HAS_FAMID\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_SDID_HAS_SUBFAMID\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_SDID_HAS_SERIESID\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_SDID_HAS_DIEID\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_SDID_HAS_SRAMSIZE\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_FCFG_HAS_FLASHDOZE\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_FCFG_HAS_FLASHDIS\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_FCFG_HAS_FTFDIS\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_FCFG_HAS_NVMSIZE\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_FCFG_HAS_EESIZE\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_FCFG_HAS_DEPART\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_FCFG_HAS_MAXADDR0\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_FCFG_HAS_MAXADDR1\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_FCFG_HAS_MAXADDR01\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_FCFG_HAS_MAXADDR23\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_FCFG_HAS_PFLSH\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_FCFG_HAS_PFLSH_SWAP\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_HAS_MISC_CONTROLS\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_HAS_COP_WATCHDOG\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_HAS_COP_STOP\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SIM_HAS_SCGC_LLWU\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SMC_HAS_PSTOPO\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SMC_HAS_LPOPO\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SMC_HAS_PORPO\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SMC_HAS_LPWUI\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SMC_HAS_LLS_SUBMODE\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SMC_USE_VLLSCTRL_REG\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SMC_USE_STOPCTRL_VLLSM\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SMC_HAS_RAM2_POWER_OPTION\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SMC_HAS_HIGH_SPEED_RUN_MODE\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SMC_HAS_LOW_LEAKAGE_STOP_MODE\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SMC_HAS_VERY_LOW_LEAKAGE_STOP_MODE\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SMC_HAS_SUB_STOP_MODE\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SMC_HAS_STOP_SUBMODE0\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SMC_HAS_STOP_SUBMODE1\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SMC_HAS_STOP_SUBMODE2\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SMC_HAS_PARAM\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SMC_HAS_VERID\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SMC_HAS_PMCTRL_STOPA\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SMC_HAS_SRS_TAMPER\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SMC_HAS_SRS_SECVIO\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_DSPI_FIFO_SIZEn\fP(x)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_DSPI_MAX_DATA_WIDTH\fP   (16)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_DSPI_MAX_CHIP_SELECT_COUNT\fP   (6)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_DSPI_CHIP_SELECT_COUNT\fP   (6)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_DSPI_CTAR_COUNT\fP   (2)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_DSPI_HAS_CHIP_SELECT_STROBE\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_DSPI_HAS_SEPARATE_TXDATA_CMD_FIFO\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_DSPI_16BIT_TRANSFERS\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_DSPI_HAS_SEPARATE_DMA_RX_TX_REQn\fP(x)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SYSMPU_DESCRIPTOR_COUNT\fP   (12)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SYSMPU_HAS_PROCESS_IDENTIFIER\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SYSMPU_SLAVE_COUNT\fP   (5)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SYSMPU_MASTER_COUNT\fP   (6)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SYSTICK_HAS_EXT_REF\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_SYSTICK_EXT_REF_CORE_DIV\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_USB_KHCI_COUNT\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_USB_KHCI_HOST_ENABLED\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_USB_KHCI_OTG_ENABLED\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_USB_KHCI_USB_RAM\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_USB_KHCI_KEEP_ALIVE_ENABLED\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_USB_KHCI_DYNAMIC_SOF_THRESHOLD_COMPARE_ENABLED\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_USB_KHCI_VBUS_DETECT_ENABLED\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_USB_KHCI_IRC48M_MODULE_CLOCK_ENABLED\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_USB_ENDPT_COUNT\fP   (16)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_USB_KHCI_HAS_STALL_LOW\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_USB_KHCI_HAS_STALL_HIGH\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_VREF_HAS_CHOP_OSC\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_VREF_HAS_COMPENSATION\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_VREF_MODE_LV_TYPE\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_VREF_HAS_LOW_REFERENCE\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_VREF_HAS_TRM4\fP   (0)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_WDOG_HAS_WATCHDOG\fP   (1)"
.br
.ti -1c
.RI "#define \fBFSL_FEATURE_WDOG_HAS_WAITEN\fP   (1)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FSL_FEATURE_ADC16_CONVERSION_CONTROL_COUNT   (2)"

.SS "#define FSL_FEATURE_ADC16_FIFO_SIZE   (0)"

.SS "#define FSL_FEATURE_ADC16_HAS_CALIBRATION   (1)"

.SS "#define FSL_FEATURE_ADC16_HAS_DIFF_MODE   (1)"

.SS "#define FSL_FEATURE_ADC16_HAS_DMA   (1)"

.SS "#define FSL_FEATURE_ADC16_HAS_FIFO   (0)"

.SS "#define FSL_FEATURE_ADC16_HAS_HW_AVERAGE   (1)"

.SS "#define FSL_FEATURE_ADC16_HAS_HW_TRIGGER_MASK   (0)"

.SS "#define FSL_FEATURE_ADC16_HAS_MUX_SELECT   (1)"

.SS "#define FSL_FEATURE_ADC16_HAS_OFFSET_CORRECTION   (1)"

.SS "#define FSL_FEATURE_ADC16_HAS_PGA   (0)"

.SS "#define FSL_FEATURE_ADC16_HAS_PGA_CHOPPING   (0)"

.SS "#define FSL_FEATURE_ADC16_HAS_PGA_OFFSET_MEASUREMENT   (0)"

.SS "#define FSL_FEATURE_ADC16_MAX_RESOLUTION   (16)"

.SS "#define FSL_FEATURE_CMP_HAS_DAC_TEST   (0)"

.SS "#define FSL_FEATURE_CMP_HAS_DMA   (1)"

.SS "#define FSL_FEATURE_CMP_HAS_EXTERNAL_SAMPLE_SUPPORT   (1)"

.SS "#define FSL_FEATURE_CMP_HAS_PASS_THROUGH_MODE   (1)"

.SS "#define FSL_FEATURE_CMP_HAS_TRIGGER_MODE   (0)"

.SS "#define FSL_FEATURE_CMP_HAS_WINDOW_MODE   (1)"

.SS "#define FSL_FEATURE_CRC_HAS_CRC_REG   (0)"

.SS "#define FSL_FEATURE_DAC_BUFFER_SIZE   (16)"

.SS "#define FSL_FEATURE_DAC_HAS_BUFFER_FIFO_MODE   (0)"

.SS "#define FSL_FEATURE_DAC_HAS_BUFFER_SWING_MODE   (1)"

.SS "#define FSL_FEATURE_DAC_HAS_WATERMARK_1_WORD   (1)"

.SS "#define FSL_FEATURE_DAC_HAS_WATERMARK_2_WORDS   (1)"

.SS "#define FSL_FEATURE_DAC_HAS_WATERMARK_3_WORDS   (1)"

.SS "#define FSL_FEATURE_DAC_HAS_WATERMARK_4_WORDS   (1)"

.SS "#define FSL_FEATURE_DAC_HAS_WATERMARK_DETECTION   (1)"

.SS "#define FSL_FEATURE_DAC_HAS_WATERMARK_SELECTION   (1)"

.SS "#define FSL_FEATURE_DMAMUX_DMAMUX_CHANNELS   (FSL_FEATURE_SOC_DMAMUX_COUNT * 16)"

.SS "#define FSL_FEATURE_DMAMUX_HAS_TRIG   (1)"

.SS "#define FSL_FEATURE_DMAMUX_MODULE_CHANNEL   (16)"

.SS "#define FSL_FEATURE_DSPI_16BIT_TRANSFERS   (1)"

.SS "#define FSL_FEATURE_DSPI_CHIP_SELECT_COUNT   (6)"

.SS "#define FSL_FEATURE_DSPI_CTAR_COUNT   (2)"

.SS "#define FSL_FEATURE_DSPI_FIFO_SIZEn(x)"
\fBValue:\fP
.PP
.nf
((x) == SPI0 ? (4) : \
    ((x) == SPI1 ? (1) : \
    ((x) == SPI2 ? (1) : (-1))))
.fi
.SS "#define FSL_FEATURE_DSPI_HAS_CHIP_SELECT_STROBE   (1)"

.SS "#define FSL_FEATURE_DSPI_HAS_SEPARATE_DMA_RX_TX_REQn(x)"
\fBValue:\fP
.PP
.nf
((x) == SPI0 ? (1) : \
    ((x) == SPI1 ? (0) : \
    ((x) == SPI2 ? (0) : (-1))))
.fi
.SS "#define FSL_FEATURE_DSPI_HAS_SEPARATE_TXDATA_CMD_FIFO   (0)"

.SS "#define FSL_FEATURE_DSPI_MAX_CHIP_SELECT_COUNT   (6)"

.SS "#define FSL_FEATURE_DSPI_MAX_DATA_WIDTH   (16)"

.SS "#define FSL_FEATURE_EDMA_ASYNCHRO_REQUEST_CHANNEL_COUNT   (0)"

.SS "#define FSL_FEATURE_EDMA_CHANNEL_GROUP_COUNT   (1)"

.SS "#define FSL_FEATURE_EDMA_DMAMUX_CHANNELS   (FSL_FEATURE_SOC_EDMA_COUNT * 16)"

.SS "#define FSL_FEATURE_EDMA_HAS_ERROR_IRQ   (1)"

.SS "#define FSL_FEATURE_EDMA_MODULE_CHANNEL   (16)"

.SS "#define FSL_FEATURE_ENET_DMA_BIG_ENDIAN_ONLY   (0)"

.SS "#define FSL_FEATURE_ENET_HAS_RECEIVE_STATUS_THRESHOLD   (1)"

.SS "#define FSL_FEATURE_ENET_INTERRUPT_COUNT   (4)"

.SS "#define FSL_FEATURE_ENET_SUPPORT_PTP   (1)"

.SS "#define FSL_FEATURE_EWM_HAS_CLOCK_SELECT   (0)"

.SS "#define FSL_FEATURE_EWM_HAS_PRESCALER   (0)"

.SS "#define FSL_FEATURE_FLEXCAN_HAS_BUF31TO0M   (0)"

.SS "#define FSL_FEATURE_FLEXCAN_HAS_DOZE_MODE_SUPPORT   (0)"

.SS "#define FSL_FEATURE_FLEXCAN_HAS_ERRATA_5641   (0)"

.SS "#define FSL_FEATURE_FLEXCAN_HAS_EXTENDED_FLAG_REGISTER   (0)"

.SS "#define FSL_FEATURE_FLEXCAN_HAS_EXTENDED_TIMING_REGISTER   (0)"

.SS "#define FSL_FEATURE_FLEXCAN_HAS_GLITCH_FILTER   (1)"

.SS "#define FSL_FEATURE_FLEXCAN_HAS_MESSAGE_BUFFER_MAX_NUMBERn(x)   (16)"

.SS "#define FSL_FEATURE_FLEXCAN_HAS_RX_FIFO_DMA   (0)"

.SS "#define FSL_FEATURE_FLEXCAN_HAS_SEPARATE_BUFFER_0_FLAG   (1)"

.SS "#define FSL_FEATURE_FLEXCAN_INTERRUPT_COUNT   (6)"

.SS "#define FSL_FEATURE_FTM_CHANNEL_COUNTn(x)"
\fBValue:\fP
.PP
.nf
((x) == FTM0 ? (8) : \
    ((x) == FTM1 ? (2) : \
    ((x) == FTM2 ? (2) : \
    ((x) == FTM3 ? (8) : (-1)))))
.fi
.SS "#define FSL_FEATURE_FTM_HAS_COUNTER_RESET_BY_CAPTURE_EVENT   (0)"

.SS "#define FSL_FEATURE_FTM_HAS_DMA_SUPPORT   (1)"

.SS "#define FSL_FEATURE_FTM_HAS_ENABLE_PWM_OUTPUT   (0)"

.SS "#define FSL_FEATURE_FTM_HAS_EXTENDED_DEADTIME_VALUE   (0)"

.SS "#define FSL_FEATURE_FTM_HAS_HALFCYCLE_RELOAD   (0)"

.SS "#define FSL_FEATURE_FTM_HAS_NO_QDCTRL   (0)"

.SS "#define FSL_FEATURE_FTM_HAS_RELOAD_INITIALIZATION_TRIGGER   (0)"

.SS "#define FSL_FEATURE_FTM_HAS_RELOAD_INTERRUPT   (0)"

.SS "#define FSL_FEATURE_GPIO_HAS_FAST_GPIO   (0)"

.SS "#define FSL_FEATURE_GPIO_HAS_INPUT_DISABLE   (0)"

.SS "#define FSL_FEATURE_GPIO_HAS_PORT_INTERRUPT_VECTOR   (1)"

.SS "#define FSL_FEATURE_I2C_HAS_DMA_SUPPORT   (1)"

.SS "#define FSL_FEATURE_I2C_HAS_DOUBLE_BUFFER_ENABLE   (0)"

.SS "#define FSL_FEATURE_I2C_HAS_DOUBLE_BUFFERING   (0)"

.SS "#define FSL_FEATURE_I2C_HAS_ERRATA_6070   (0)"

.SS "#define FSL_FEATURE_I2C_HAS_HIGH_DRIVE_SELECTION   (1)"

.SS "#define FSL_FEATURE_I2C_HAS_SMBUS   (1)"

.SS "#define FSL_FEATURE_I2C_HAS_START_STOP_DETECT   (1)"

.SS "#define FSL_FEATURE_I2C_HAS_STOP_DETECT   (0)"

.SS "#define FSL_FEATURE_I2C_HAS_STOP_HOLD_OFF   (1)"

.SS "#define FSL_FEATURE_I2C_MAX_BAUD_KBPS   (400)"

.SS "#define FSL_FEATURE_I2C_MAX_GLITCH_FILTER_WIDTH   (15)"

.SS "#define FSL_FEATURE_INTERRUPT_IRQ_MAX   (85)"

.SS "#define FSL_FEATURE_INTERRUPT_IRQ_MIN   (\-14)"

.SS "#define FSL_FEATURE_LLWU_EXTERNAL_PIN_GROUP2   (1)"

.SS "#define FSL_FEATURE_LLWU_HAS_DMA_ENABLE_REG   (0)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN   (16)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN0   (1)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN1   (1)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN10   (1)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN11   (1)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN12   (1)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN13   (1)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN14   (1)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN15   (1)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN16   (0)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN17   (0)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN18   (0)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN19   (0)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN2   (1)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN20   (0)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN21   (0)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN22   (0)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN23   (0)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN24   (0)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN25   (0)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN26   (0)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN27   (0)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN28   (0)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN29   (0)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN3   (1)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN30   (0)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN31   (0)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN4   (1)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN5   (1)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN6   (1)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN7   (1)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN8   (1)"

.SS "#define FSL_FEATURE_LLWU_HAS_EXTERNAL_PIN9   (1)"

.SS "#define FSL_FEATURE_LLWU_HAS_INTERNAL_MODULE   (8)"

.SS "#define FSL_FEATURE_LLWU_HAS_INTERNAL_MODULE0   (1)"

.SS "#define FSL_FEATURE_LLWU_HAS_INTERNAL_MODULE1   (1)"

.SS "#define FSL_FEATURE_LLWU_HAS_INTERNAL_MODULE2   (1)"

.SS "#define FSL_FEATURE_LLWU_HAS_INTERNAL_MODULE3   (1)"

.SS "#define FSL_FEATURE_LLWU_HAS_INTERNAL_MODULE4   (0)"

.SS "#define FSL_FEATURE_LLWU_HAS_INTERNAL_MODULE5   (1)"

.SS "#define FSL_FEATURE_LLWU_HAS_INTERNAL_MODULE6   (0)"

.SS "#define FSL_FEATURE_LLWU_HAS_INTERNAL_MODULE7   (1)"

.SS "#define FSL_FEATURE_LLWU_HAS_MF   (0)"

.SS "#define FSL_FEATURE_LLWU_HAS_NO_INTERNAL_MODULE_WAKEUP_FLAG_REG   (0)"

.SS "#define FSL_FEATURE_LLWU_HAS_PARAM   (0)"

.SS "#define FSL_FEATURE_LLWU_HAS_PF   (0)"

.SS "#define FSL_FEATURE_LLWU_HAS_PIN_FILTER   (2)"

.SS "#define FSL_FEATURE_LLWU_HAS_RESET_ENABLE   (1)"

.SS "#define FSL_FEATURE_LLWU_HAS_VERID   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN0_GPIO_IDX   (GPIOE_IDX)"

.SS "#define FSL_FEATURE_LLWU_PIN0_GPIO_PIN   (1)"

.SS "#define FSL_FEATURE_LLWU_PIN10_GPIO_IDX   (GPIOC_IDX)"

.SS "#define FSL_FEATURE_LLWU_PIN10_GPIO_PIN   (6)"

.SS "#define FSL_FEATURE_LLWU_PIN11_GPIO_IDX   (GPIOC_IDX)"

.SS "#define FSL_FEATURE_LLWU_PIN11_GPIO_PIN   (11)"

.SS "#define FSL_FEATURE_LLWU_PIN12_GPIO_IDX   (GPIOD_IDX)"

.SS "#define FSL_FEATURE_LLWU_PIN12_GPIO_PIN   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN13_GPIO_IDX   (GPIOD_IDX)"

.SS "#define FSL_FEATURE_LLWU_PIN13_GPIO_PIN   (2)"

.SS "#define FSL_FEATURE_LLWU_PIN14_GPIO_IDX   (GPIOD_IDX)"

.SS "#define FSL_FEATURE_LLWU_PIN14_GPIO_PIN   (4)"

.SS "#define FSL_FEATURE_LLWU_PIN15_GPIO_IDX   (GPIOD_IDX)"

.SS "#define FSL_FEATURE_LLWU_PIN15_GPIO_PIN   (6)"

.SS "#define FSL_FEATURE_LLWU_PIN16_GPIO_IDX   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN16_GPIO_PIN   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN17_GPIO_IDX   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN17_GPIO_PIN   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN18_GPIO_IDX   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN18_GPIO_PIN   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN19_GPIO_IDX   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN19_GPIO_PIN   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN1_GPIO_IDX   (GPIOE_IDX)"

.SS "#define FSL_FEATURE_LLWU_PIN1_GPIO_PIN   (2)"

.SS "#define FSL_FEATURE_LLWU_PIN20_GPIO_IDX   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN20_GPIO_PIN   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN21_GPIO_IDX   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN21_GPIO_PIN   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN22_GPIO_IDX   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN22_GPIO_PIN   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN23_GPIO_IDX   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN23_GPIO_PIN   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN24_GPIO_IDX   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN24_GPIO_PIN   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN25_GPIO_IDX   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN25_GPIO_PIN   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN26_GPIO_IDX   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN26_GPIO_PIN   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN27_GPIO_IDX   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN27_GPIO_PIN   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN28_GPIO_IDX   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN28_GPIO_PIN   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN29_GPIO_IDX   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN29_GPIO_PIN   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN2_GPIO_IDX   (GPIOE_IDX)"

.SS "#define FSL_FEATURE_LLWU_PIN2_GPIO_PIN   (4)"

.SS "#define FSL_FEATURE_LLWU_PIN30_GPIO_IDX   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN30_GPIO_PIN   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN31_GPIO_IDX   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN31_GPIO_PIN   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN3_GPIO_IDX   (GPIOA_IDX)"

.SS "#define FSL_FEATURE_LLWU_PIN3_GPIO_PIN   (4)"

.SS "#define FSL_FEATURE_LLWU_PIN4_GPIO_IDX   (GPIOA_IDX)"

.SS "#define FSL_FEATURE_LLWU_PIN4_GPIO_PIN   (13)"

.SS "#define FSL_FEATURE_LLWU_PIN5_GPIO_IDX   (GPIOB_IDX)"

.SS "#define FSL_FEATURE_LLWU_PIN5_GPIO_PIN   (0)"

.SS "#define FSL_FEATURE_LLWU_PIN6_GPIO_IDX   (GPIOC_IDX)"

.SS "#define FSL_FEATURE_LLWU_PIN6_GPIO_PIN   (1)"

.SS "#define FSL_FEATURE_LLWU_PIN7_GPIO_IDX   (GPIOC_IDX)"

.SS "#define FSL_FEATURE_LLWU_PIN7_GPIO_PIN   (3)"

.SS "#define FSL_FEATURE_LLWU_PIN8_GPIO_IDX   (GPIOC_IDX)"

.SS "#define FSL_FEATURE_LLWU_PIN8_GPIO_PIN   (4)"

.SS "#define FSL_FEATURE_LLWU_PIN9_GPIO_IDX   (GPIOC_IDX)"

.SS "#define FSL_FEATURE_LLWU_PIN9_GPIO_PIN   (5)"

.SS "#define FSL_FEATURE_LLWU_REG_BITWIDTH   (8)"

.SS "#define FSL_FEATURE_LPTMR_CNR_WIDTH_IS_32B   (0)"

.SS "#define FSL_FEATURE_LPTMR_HAS_CSR_TDRE   (0)"

.SS "#define FSL_FEATURE_LPTMR_HAS_SHARED_IRQ_HANDLER   (0)"

.SS "#define FSL_FEATURE_MCG_FFCLK_DIV   (1)"

.SS "#define FSL_FEATURE_MCG_FRDIV_SUPPORT_1280   (1)"

.SS "#define FSL_FEATURE_MCG_FRDIV_SUPPORT_1536   (1)"

.SS "#define FSL_FEATURE_MCG_HAS_AUTO_TRIM_MACHINE   (1)"

.SS "#define FSL_FEATURE_MCG_HAS_EXT_REF_LOW_POWER_CONTROL   (1)"

.SS "#define FSL_FEATURE_MCG_HAS_EXTERNAL_CLOCK_MONITOR   (1)"

.SS "#define FSL_FEATURE_MCG_HAS_EXTERNAL_PLL   (0)"

.SS "#define FSL_FEATURE_MCG_HAS_FCFTRIM   (1)"

.SS "#define FSL_FEATURE_MCG_HAS_FLL   (1)"

.SS "#define FSL_FEATURE_MCG_HAS_HIGH_FREQ_IRC   (0)"

.SS "#define FSL_FEATURE_MCG_HAS_IRC_48M   (1)"

.SS "#define FSL_FEATURE_MCG_HAS_LOLRE   (1)"

.SS "#define FSL_FEATURE_MCG_HAS_LOW_FREQ_IRC   (0)"

.SS "#define FSL_FEATURE_MCG_HAS_OSC1   (0)"

.SS "#define FSL_FEATURE_MCG_HAS_PLL   (1)"

.SS "#define FSL_FEATURE_MCG_HAS_PLL1   (0)"

.SS "#define FSL_FEATURE_MCG_HAS_PLL_EXTRA_DIV   (0)"

.SS "#define FSL_FEATURE_MCG_HAS_PLL_FLL_SELECTION   (1)"

.SS "#define FSL_FEATURE_MCG_HAS_PLL_INTERNAL_DIV   (0)"

.SS "#define FSL_FEATURE_MCG_HAS_PLL_INTERNAL_MODE   (0)"

.SS "#define FSL_FEATURE_MCG_HAS_PLL_OSC_INDEX   (0)"

.SS "#define FSL_FEATURE_MCG_HAS_PLL_OUTPUT_SELECTION   (0)"

.SS "#define FSL_FEATURE_MCG_HAS_PLL_PRDIV   (1)"

.SS "#define FSL_FEATURE_MCG_HAS_PLL_VDIV   (1)"

.SS "#define FSL_FEATURE_MCG_HAS_RTC_32K   (1)"

.SS "#define FSL_FEATURE_MCG_PLL_PRDIV_BASE   (1)"

.SS "#define FSL_FEATURE_MCG_PLL_PRDIV_MAX   (24)"

.SS "#define FSL_FEATURE_MCG_PLL_REF_MAX   (4000000)"

.SS "#define FSL_FEATURE_MCG_PLL_REF_MIN   (2000000)"

.SS "#define FSL_FEATURE_MCG_PLL_VDIV_BASE   (24)"

.SS "#define FSL_FEATURE_MCG_RESET_IS_BLPI   (0)"

.SS "#define FSL_FEATURE_MCG_USE_OSCSEL   (1)"

.SS "#define FSL_FEATURE_MCG_USE_PLLREFSEL   (0)"

.SS "#define FSL_FEATURE_MCG_USE_SYSTEM_CLOCK   (0)"

.SS "#define FSL_FEATURE_OSC_HAS_EXT_REF_CLOCK_DIVIDER   (0)"

.SS "#define FSL_FEATURE_OSC_HAS_OSC   (1)"

.SS "#define FSL_FEATURE_OSC_HAS_OSC0   (0)"

.SS "#define FSL_FEATURE_OSC_HAS_OSC1   (0)"

.SS "#define FSL_FEATURE_OSC_OSC_COUNT   (1)"

.SS "#define FSL_FEATURE_PDB_ADC_PRE_CHANNEL_COUNT   (2)"

.SS "#define FSL_FEATURE_PDB_HAS_DAC   (1)"

.SS "#define FSL_FEATURE_PDB_HAS_SHARED_IRQ_HANDLER   (0)"

.SS "#define FSL_FEATURE_PIT_HAS_CHAIN_MODE   (1)"

.SS "#define FSL_FEATURE_PIT_HAS_LIFETIME_TIMER   (0)"

.SS "#define FSL_FEATURE_PIT_HAS_MDIS   (1)"

.SS "#define FSL_FEATURE_PIT_HAS_SHARED_IRQ_HANDLER   (0)"

.SS "#define FSL_FEATURE_PIT_TIMER_COUNT   (4)"

.SS "#define FSL_FEATURE_PMC_HAS_ACKISO   (1)"

.SS "#define FSL_FEATURE_PMC_HAS_BGBDS   (0)"

.SS "#define FSL_FEATURE_PMC_HAS_BGBE   (1)"

.SS "#define FSL_FEATURE_PMC_HAS_BGEN   (1)"

.SS "#define FSL_FEATURE_PMC_HAS_HVDSC1   (0)"

.SS "#define FSL_FEATURE_PMC_HAS_LPO   (0)"

.SS "#define FSL_FEATURE_PMC_HAS_LVDV   (1)"

.SS "#define FSL_FEATURE_PMC_HAS_LVWV   (1)"

.SS "#define FSL_FEATURE_PMC_HAS_PARAM   (0)"

.SS "#define FSL_FEATURE_PMC_HAS_REGFPM   (0)"

.SS "#define FSL_FEATURE_PMC_HAS_REGONS   (1)"

.SS "#define FSL_FEATURE_PMC_HAS_VERID   (0)"

.SS "#define FSL_FEATURE_PMC_HAS_VLPO   (0)"

.SS "#define FSL_FEATURE_PORT_HAS_DIGITAL_FILTER   (1)"

.SS "#define FSL_FEATURE_PORT_HAS_DMA_REQUEST   (1)"

.SS "#define FSL_FEATURE_PORT_HAS_DRIVE_STRENGTH   (1)"

.SS "#define FSL_FEATURE_PORT_HAS_DRIVE_STRENGTH_REGISTER   (0)"

.SS "#define FSL_FEATURE_PORT_HAS_GLITCH_FILTER   (0)"

.SS "#define FSL_FEATURE_PORT_HAS_INTERRUPT_VECTOR   (1)"

.SS "#define FSL_FEATURE_PORT_HAS_IRQC_FLAG   (0)"

.SS "#define FSL_FEATURE_PORT_HAS_IRQC_TRIGGER   (0)"

.SS "#define FSL_FEATURE_PORT_HAS_MULTIPLE_IRQ_CONFIG   (0)"

.SS "#define FSL_FEATURE_PORT_HAS_OPEN_DRAIN   (1)"

.SS "#define FSL_FEATURE_PORT_HAS_PASSIVE_FILTER   (1)"

.SS "#define FSL_FEATURE_PORT_HAS_PIN_CONTROL_LOCK   (1)"

.SS "#define FSL_FEATURE_PORT_HAS_PULL_ENABLE   (1)"

.SS "#define FSL_FEATURE_PORT_HAS_PULL_SELECTION   (1)"

.SS "#define FSL_FEATURE_PORT_HAS_SLEW_RATE   (1)"

.SS "#define FSL_FEATURE_PORT_PCR_MUX_WIDTH   (3)"

.SS "#define FSL_FEATURE_RCM_HAS_BOOTROM   (0)"

.SS "#define FSL_FEATURE_RCM_HAS_CORE1   (0)"

.SS "#define FSL_FEATURE_RCM_HAS_EZPMS   (1)"

.SS "#define FSL_FEATURE_RCM_HAS_EZPORT   (1)"

.SS "#define FSL_FEATURE_RCM_HAS_JTAG   (1)"

.SS "#define FSL_FEATURE_RCM_HAS_LOC   (1)"

.SS "#define FSL_FEATURE_RCM_HAS_LOL   (1)"

.SS "#define FSL_FEATURE_RCM_HAS_MDM_AP   (1)"

.SS "#define FSL_FEATURE_RCM_HAS_PARAM   (0)"

.SS "#define FSL_FEATURE_RCM_HAS_SRIE   (0)"

.SS "#define FSL_FEATURE_RCM_HAS_SSRS   (0)"

.SS "#define FSL_FEATURE_RCM_HAS_VERID   (0)"

.SS "#define FSL_FEATURE_RCM_HAS_WAKEUP   (1)"

.SS "#define FSL_FEATURE_RCM_REG_WIDTH   (8)"

.SS "#define FSL_FEATURE_SAI_CHANNEL_COUNT   (2)"

.SS "#define FSL_FEATURE_SAI_FIFO_COUNT   (8)"

.SS "#define FSL_FEATURE_SAI_HAS_CLOCKING_MODE   (0)"

.SS "#define FSL_FEATURE_SAI_HAS_FIFO_COMBINE_MODE   (0)"

.SS "#define FSL_FEATURE_SAI_HAS_FIFO_FUNCTION_AFTER_ERROR   (0)"

.SS "#define FSL_FEATURE_SAI_HAS_FIFO_PACKING   (0)"

.SS "#define FSL_FEATURE_SAI_HAS_MCLKDIV_REGISTER   (1)"

.SS "#define FSL_FEATURE_SAI_HAS_MCR   (1)"

.SS "#define FSL_FEATURE_SAI_HAS_MDR   (1)"

.SS "#define FSL_FEATURE_SAI_HAS_ON_DEMAND_MODE   (0)"

.SS "#define FSL_FEATURE_SAI_INT_SOURCE_NUM   (2)"

.SS "#define FSL_FEATURE_SAI_MAX_WORDS_PER_FRAME   (32)"

.SS "#define FSL_FEATURE_SDHC_HAS_EXTERNAL_DMA_SUPPORT   (1)"

.SS "#define FSL_FEATURE_SDHC_HAS_V180_SUPPORT   (0)"

.SS "#define FSL_FEATURE_SDHC_HAS_V300_SUPPORT   (0)"

.SS "#define FSL_FEATURE_SIM_DIVIDER_HAS_LCDCDIV   (0)"

.SS "#define FSL_FEATURE_SIM_DIVIDER_HAS_NFCDIV   (0)"

.SS "#define FSL_FEATURE_SIM_DIVIDER_HAS_OUTDIV2   (1)"

.SS "#define FSL_FEATURE_SIM_DIVIDER_HAS_OUTDIV3   (1)"

.SS "#define FSL_FEATURE_SIM_DIVIDER_HAS_OUTDIV4   (1)"

.SS "#define FSL_FEATURE_SIM_DIVIDER_HAS_OUTDIV5   (0)"

.SS "#define FSL_FEATURE_SIM_DIVIDER_HAS_PLLFLLDIV   (0)"

.SS "#define FSL_FEATURE_SIM_DIVIDER_HAS_TRACEDIV   (0)"

.SS "#define FSL_FEATURE_SIM_DIVIDER_HAS_USBDIV   (1)"

.SS "#define FSL_FEATURE_SIM_DIVIDER_HAS_USBFSDIV   (0)"

.SS "#define FSL_FEATURE_SIM_DIVIDER_HAS_USBHSDIV   (0)"

.SS "#define FSL_FEATURE_SIM_DIVIDER_OUTDIV4_WIDTH   (4)"

.SS "#define FSL_FEATURE_SIM_FCFG_HAS_DEPART   (1)"

.SS "#define FSL_FEATURE_SIM_FCFG_HAS_EESIZE   (1)"

.SS "#define FSL_FEATURE_SIM_FCFG_HAS_FLASHDIS   (1)"

.SS "#define FSL_FEATURE_SIM_FCFG_HAS_FLASHDOZE   (1)"

.SS "#define FSL_FEATURE_SIM_FCFG_HAS_FTFDIS   (0)"

.SS "#define FSL_FEATURE_SIM_FCFG_HAS_MAXADDR0   (1)"

.SS "#define FSL_FEATURE_SIM_FCFG_HAS_MAXADDR01   (0)"

.SS "#define FSL_FEATURE_SIM_FCFG_HAS_MAXADDR1   (1)"

.SS "#define FSL_FEATURE_SIM_FCFG_HAS_MAXADDR23   (0)"

.SS "#define FSL_FEATURE_SIM_FCFG_HAS_NVMSIZE   (1)"

.SS "#define FSL_FEATURE_SIM_FCFG_HAS_PFLSH   (1)"

.SS "#define FSL_FEATURE_SIM_FCFG_HAS_PFLSH_SWAP   (0)"

.SS "#define FSL_FEATURE_SIM_HAS_COP_STOP   (0)"

.SS "#define FSL_FEATURE_SIM_HAS_COP_WATCHDOG   (0)"

.SS "#define FSL_FEATURE_SIM_HAS_MISC_CONTROLS   (0)"

.SS "#define FSL_FEATURE_SIM_HAS_SCGC_LLWU   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_ADC0ALTTRGEN_WIDTH   (1)"

.SS "#define FSL_FEATURE_SIM_OPT_ADC1ALTTRGEN_WIDTH   (1)"

.SS "#define FSL_FEATURE_SIM_OPT_ADC2ALTTRGEN_WIDTH   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_ADC3ALTTRGEN_WIDTH   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_ADC_COUNT   (2)"

.SS "#define FSL_FEATURE_SIM_OPT_ADCAALTTRGEN_WIDTH   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_ADCBALTTRGEN_WIDTH   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_FTM0_FAULT_COUNT   (3)"

.SS "#define FSL_FEATURE_SIM_OPT_FTM1_FAULT_COUNT   (1)"

.SS "#define FSL_FEATURE_SIM_OPT_FTM2_FAULT_COUNT   (1)"

.SS "#define FSL_FEATURE_SIM_OPT_FTM3_FAULT_COUNT   (1)"

.SS "#define FSL_FEATURE_SIM_OPT_FTM_COUNT   (4)"

.SS "#define FSL_FEATURE_SIM_OPT_FTM_TRIGGER_COUNT   (2)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_CMTUARTPAD   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_ESDHCSRC   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_FBSL   (1)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_FLEXIOSRC   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_FTM   (1)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_FTM0_TRIGGER   (1)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_FTM1_CHANNELS   (1)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_FTM2_CHANNEL1   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_FTM2_CHANNELS   (1)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_FTM3_CHANNELS   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_FTM3_TRIGGER   (1)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_FTM_CHANNELS_OUTPUT_SRC   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_FTM_TRIGGER_SYNC   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_LCDCSRC   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_LPUART0_ODE   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_LPUART0_RX_SRC   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_LPUART0_TX_SRC   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_LPUART0SRC   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_LPUART1_ODE   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_LPUART1_RX_SRC   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_LPUART1_TX_SRC   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_LPUART1SRC   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_LPUARTSRC   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_MCC   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_NFCSRC   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_ODE   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_OSC32K_OUT   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_OSC32K_SELECTION   (1)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_PCR   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_PLL_FLL_SELECTION   (1)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_PTD7PAD   (1)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_RAMSIZE   (1)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_RMIISRC   (1)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_RTC_CLOCK_OUT_SELECTION   (1)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_SDHCSRC   (1)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_TIMESRC   (1)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_TPM   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_TPM0   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_TPM0_CLK_SEL   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_TPM1_CH0_SRC_SELECTION   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_TPM1_CLK_SEL   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_TPM2_CH0_SRC_SELECTION   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_TPM2_CLK_SEL   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_TPM_CHANNELS_CONFIG_IN_SOPT4_REG   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_TPMSRC   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_TRACE_CLKSEL   (1)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_UART0_ODE   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_UART0_RX_SRC   (1)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_UART0_TX_SRC   (1)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_UART0SRC   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_UART1_ODE   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_UART1_RX_SRC   (1)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_UART1_TX_SRC   (1)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_UART2_ODE   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_USB_PHY   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_USB_VOLTAGE_REGULATOR   (1)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_USBFSRC   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_USBHSRC   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HAS_USBSRC   (1)"

.SS "#define FSL_FEATURE_SIM_OPT_HSADC0AALTTRGEN_WIDTH   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HSADC0BALTTRGEN_WIDTH   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HSADC1AALTTRGEN_WIDTH   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_HSADC1BALTTRGEN_WIDTH   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_LPUART_COUNT   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_MAX_TPM_INDEX   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_OSC32K_SELECTION_WIDTH   (2)"

.SS "#define FSL_FEATURE_SIM_OPT_PLL_FLL_SELECTION_WIDTH   (1)"

.SS "#define FSL_FEATURE_SIM_OPT_TPM1_CH0_SRC_SELECTION_WIDTH   (0)"

.SS "#define FSL_FEATURE_SIM_OPT_UART0_RX_SRC_WIDTH   (2)"

.SS "#define FSL_FEATURE_SIM_OPT_UART0_TX_SRC_WIDTH   (2)"

.SS "#define FSL_FEATURE_SIM_OPT_UART1_RX_SRC_WIDTH   (2)"

.SS "#define FSL_FEATURE_SIM_OPT_UART_COUNT   (4)"

.SS "#define FSL_FEATURE_SIM_PLLCLK_USE_SPECIAL_DIVIDER   (0)"

.SS "#define FSL_FEATURE_SIM_SDID_HAS_DIEID   (1)"

.SS "#define FSL_FEATURE_SIM_SDID_HAS_FAMID   (1)"

.SS "#define FSL_FEATURE_SIM_SDID_HAS_FAMILYID   (1)"

.SS "#define FSL_FEATURE_SIM_SDID_HAS_SERIESID   (1)"

.SS "#define FSL_FEATURE_SIM_SDID_HAS_SRAMSIZE   (0)"

.SS "#define FSL_FEATURE_SIM_SDID_HAS_SUBFAMID   (1)"

.SS "#define FSL_FEATURE_SIM_USBFS_USE_SPECIAL_DIVIDER   (0)"

.SS "#define FSL_FEATURE_SMC_HAS_HIGH_SPEED_RUN_MODE   (0)"

.SS "#define FSL_FEATURE_SMC_HAS_LLS_SUBMODE   (0)"

.SS "#define FSL_FEATURE_SMC_HAS_LOW_LEAKAGE_STOP_MODE   (1)"

.SS "#define FSL_FEATURE_SMC_HAS_LPOPO   (0)"

.SS "#define FSL_FEATURE_SMC_HAS_LPWUI   (1)"

.SS "#define FSL_FEATURE_SMC_HAS_PARAM   (0)"

.SS "#define FSL_FEATURE_SMC_HAS_PMCTRL_STOPA   (1)"

.SS "#define FSL_FEATURE_SMC_HAS_PORPO   (1)"

.SS "#define FSL_FEATURE_SMC_HAS_PSTOPO   (0)"

.SS "#define FSL_FEATURE_SMC_HAS_RAM2_POWER_OPTION   (0)"

.SS "#define FSL_FEATURE_SMC_HAS_SRS_SECVIO   (0)"

.SS "#define FSL_FEATURE_SMC_HAS_SRS_TAMPER   (0)"

.SS "#define FSL_FEATURE_SMC_HAS_STOP_SUBMODE0   (1)"

.SS "#define FSL_FEATURE_SMC_HAS_STOP_SUBMODE1   (1)"

.SS "#define FSL_FEATURE_SMC_HAS_STOP_SUBMODE2   (1)"

.SS "#define FSL_FEATURE_SMC_HAS_SUB_STOP_MODE   (1)"

.SS "#define FSL_FEATURE_SMC_HAS_VERID   (0)"

.SS "#define FSL_FEATURE_SMC_HAS_VERY_LOW_LEAKAGE_STOP_MODE   (1)"

.SS "#define FSL_FEATURE_SMC_USE_STOPCTRL_VLLSM   (0)"

.SS "#define FSL_FEATURE_SMC_USE_VLLSCTRL_REG   (1)"

.SS "#define FSL_FEATURE_SYSMPU_DESCRIPTOR_COUNT   (12)"

.SS "#define FSL_FEATURE_SYSMPU_HAS_PROCESS_IDENTIFIER   (1)"

.SS "#define FSL_FEATURE_SYSMPU_MASTER_COUNT   (6)"

.SS "#define FSL_FEATURE_SYSMPU_SLAVE_COUNT   (5)"

.SS "#define FSL_FEATURE_SYSTICK_EXT_REF_CORE_DIV   (0)"

.SS "#define FSL_FEATURE_SYSTICK_HAS_EXT_REF   (0)"

.SS "#define FSL_FEATURE_USB_ENDPT_COUNT   (16)"

.SS "#define FSL_FEATURE_USB_KHCI_COUNT   (1)"

.SS "#define FSL_FEATURE_USB_KHCI_DYNAMIC_SOF_THRESHOLD_COMPARE_ENABLED   (0)"

.SS "#define FSL_FEATURE_USB_KHCI_HAS_STALL_HIGH   (0)"

.SS "#define FSL_FEATURE_USB_KHCI_HAS_STALL_LOW   (0)"

.SS "#define FSL_FEATURE_USB_KHCI_HOST_ENABLED   (1)"

.SS "#define FSL_FEATURE_USB_KHCI_IRC48M_MODULE_CLOCK_ENABLED   (1)"

.SS "#define FSL_FEATURE_USB_KHCI_KEEP_ALIVE_ENABLED   (0)"

.SS "#define FSL_FEATURE_USB_KHCI_OTG_ENABLED   (1)"

.SS "#define FSL_FEATURE_USB_KHCI_USB_RAM   (0)"

.SS "#define FSL_FEATURE_USB_KHCI_VBUS_DETECT_ENABLED   (0)"

.SS "#define FSL_FEATURE_VREF_HAS_CHOP_OSC   (1)"

.SS "#define FSL_FEATURE_VREF_HAS_COMPENSATION   (1)"

.SS "#define FSL_FEATURE_VREF_HAS_LOW_REFERENCE   (0)"

.SS "#define FSL_FEATURE_VREF_HAS_TRM4   (0)"

.SS "#define FSL_FEATURE_VREF_MODE_LV_TYPE   (1)"

.SS "#define FSL_FEATURE_WDOG_HAS_WAITEN   (1)"

.SS "#define FSL_FEATURE_WDOG_HAS_WATCHDOG   (1)"

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
