.TH "source/NumberEditor.c" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/NumberEditor.c
.SH SYNOPSIS
.br
.PP
\fC#include 'stdlib\&.h'\fP
.br
\fC#include 'DRV_Display\&.h'\fP
.br
\fC#include 'DRV_Timers\&.h'\fP
.br
\fC#include 'NumberEditor\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBEDITOR_BUFFER_LEN\fP   (\fBDISP_BUFFER_LEN\fP)"
.br
.ti -1c
.RI "#define \fBCHAR_PREV\fP   '<'"
.br
.ti -1c
.RI "#define \fBCHAR_NEXT\fP   '>'"
.br
.ti -1c
.RI "#define \fBBLINK_DP_MS\fP   250"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBeditorState_t\fP { \fBSTATE_EDITOR_SCROLL\fP, \fBSTATE_EDITOR_MODIFY\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit_number_editor\fP ()"
.br
.ti -1c
.RI "void \fBstart_number_editor\fP (uint8_t editor_len, bool flag_next, bool flag_hidden)"
.br
.RI "TODO: completar descripcion\&. "
.ti -1c
.RI "void \fBset_number_editor_digit\fP (uint8_t n, uint8_t digit)"
.br
.ti -1c
.RI "void \fBnumber_editor_right\fP ()"
.br
.ti -1c
.RI "void \fBnumber_editor_left\fP ()"
.br
.ti -1c
.RI "\fBeditorEvent_t\fP \fBnumber_editor_click\fP ()"
.br
.ti -1c
.RI "uint32_t \fBgetBufferNumber\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BLINK_DP_MS   250"

.SS "#define CHAR_NEXT   '>'"

.SS "#define CHAR_PREV   '<'"

.SS "#define EDITOR_BUFFER_LEN   (\fBDISP_BUFFER_LEN\fP)"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBeditorState_t\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISTATE_EDITOR_SCROLL \fP\fP
.TP
\fB\fISTATE_EDITOR_MODIFY \fP\fP
.SH "Function Documentation"
.PP 
.SS "uint32_t getBufferNumber ()"

.SS "void init_number_editor ()"

.SS "\fBeditorEvent_t\fP number_editor_click ()"

.SS "void number_editor_left ()"

.SS "void number_editor_right ()"

.SS "void set_number_editor_digit (uint8_t n, uint8_t digit)"

.SS "void start_number_editor (uint8_t editor_len, bool flag_next, bool flag_hidden)"

.PP
TODO: completar descripcion\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparam1\fP Descripcion parametro 1 
.br
\fIparam2\fP Descripcion parametro 2 
.RE
.PP
\fBReturns:\fP
.RS 4
Descripcion valor que devuelve 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
