.TH "NV_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NV_Type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MK64F12\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__I\fP uint8_t \fBBACKKEY3\fP"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBBACKKEY2\fP"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBBACKKEY1\fP"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBBACKKEY0\fP"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBBACKKEY7\fP"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBBACKKEY6\fP"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBBACKKEY5\fP"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBBACKKEY4\fP"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBFPROT3\fP"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBFPROT2\fP"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBFPROT1\fP"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBFPROT0\fP"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBFSEC\fP"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBFOPT\fP"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBFEPROT\fP"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBFDPROT\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
NV - Register Layout Typedef 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
