.TH "OSC_Register_Masks" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OSC_Register_Masks
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOSC_BASE\fP   (0x40065000u)"
.br
.ti -1c
.RI "#define \fBOSC\fP   ((\fBOSC_Type\fP *)\fBOSC_BASE\fP)"
.br
.ti -1c
.RI "#define \fBOSC_BASE_ADDRS\fP   { \fBOSC_BASE\fP }"
.br
.ti -1c
.RI "#define \fBOSC_BASE_PTRS\fP   { \fBOSC\fP }"
.br
.in -1c
.SS "CR - OSC Control Register"

.in +1c
.ti -1c
.RI "#define \fBOSC_CR_SC16P_MASK\fP   (0x1U)"
.br
.ti -1c
.RI "#define \fBOSC_CR_SC16P_SHIFT\fP   (0U)"
.br
.ti -1c
.RI "#define \fBOSC_CR_SC16P\fP(x)   (((uint8_t)(((uint8_t)(x)) << \fBOSC_CR_SC16P_SHIFT\fP)) & \fBOSC_CR_SC16P_MASK\fP)"
.br
.ti -1c
.RI "#define \fBOSC_CR_SC8P_MASK\fP   (0x2U)"
.br
.ti -1c
.RI "#define \fBOSC_CR_SC8P_SHIFT\fP   (1U)"
.br
.ti -1c
.RI "#define \fBOSC_CR_SC8P\fP(x)   (((uint8_t)(((uint8_t)(x)) << \fBOSC_CR_SC8P_SHIFT\fP)) & \fBOSC_CR_SC8P_MASK\fP)"
.br
.ti -1c
.RI "#define \fBOSC_CR_SC4P_MASK\fP   (0x4U)"
.br
.ti -1c
.RI "#define \fBOSC_CR_SC4P_SHIFT\fP   (2U)"
.br
.ti -1c
.RI "#define \fBOSC_CR_SC4P\fP(x)   (((uint8_t)(((uint8_t)(x)) << \fBOSC_CR_SC4P_SHIFT\fP)) & \fBOSC_CR_SC4P_MASK\fP)"
.br
.ti -1c
.RI "#define \fBOSC_CR_SC2P_MASK\fP   (0x8U)"
.br
.ti -1c
.RI "#define \fBOSC_CR_SC2P_SHIFT\fP   (3U)"
.br
.ti -1c
.RI "#define \fBOSC_CR_SC2P\fP(x)   (((uint8_t)(((uint8_t)(x)) << \fBOSC_CR_SC2P_SHIFT\fP)) & \fBOSC_CR_SC2P_MASK\fP)"
.br
.ti -1c
.RI "#define \fBOSC_CR_EREFSTEN_MASK\fP   (0x20U)"
.br
.ti -1c
.RI "#define \fBOSC_CR_EREFSTEN_SHIFT\fP   (5U)"
.br
.ti -1c
.RI "#define \fBOSC_CR_EREFSTEN\fP(x)   (((uint8_t)(((uint8_t)(x)) << \fBOSC_CR_EREFSTEN_SHIFT\fP)) & \fBOSC_CR_EREFSTEN_MASK\fP)"
.br
.ti -1c
.RI "#define \fBOSC_CR_ERCLKEN_MASK\fP   (0x80U)"
.br
.ti -1c
.RI "#define \fBOSC_CR_ERCLKEN_SHIFT\fP   (7U)"
.br
.ti -1c
.RI "#define \fBOSC_CR_ERCLKEN\fP(x)   (((uint8_t)(((uint8_t)(x)) << \fBOSC_CR_ERCLKEN_SHIFT\fP)) & \fBOSC_CR_ERCLKEN_MASK\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define OSC   ((\fBOSC_Type\fP *)\fBOSC_BASE\fP)"
Peripheral OSC base pointer 
.SS "#define OSC_BASE   (0x40065000u)"
Peripheral OSC base address 
.SS "#define OSC_BASE_ADDRS   { \fBOSC_BASE\fP }"
Array initializer of OSC peripheral base addresses 
.SS "#define OSC_BASE_PTRS   { \fBOSC\fP }"
Array initializer of OSC peripheral base pointers 
.SS "#define OSC_CR_ERCLKEN(x)   (((uint8_t)(((uint8_t)(x)) << \fBOSC_CR_ERCLKEN_SHIFT\fP)) & \fBOSC_CR_ERCLKEN_MASK\fP)"

.SS "#define OSC_CR_ERCLKEN_MASK   (0x80U)"

.SS "#define OSC_CR_ERCLKEN_SHIFT   (7U)"

.SS "#define OSC_CR_EREFSTEN(x)   (((uint8_t)(((uint8_t)(x)) << \fBOSC_CR_EREFSTEN_SHIFT\fP)) & \fBOSC_CR_EREFSTEN_MASK\fP)"

.SS "#define OSC_CR_EREFSTEN_MASK   (0x20U)"

.SS "#define OSC_CR_EREFSTEN_SHIFT   (5U)"

.SS "#define OSC_CR_SC16P(x)   (((uint8_t)(((uint8_t)(x)) << \fBOSC_CR_SC16P_SHIFT\fP)) & \fBOSC_CR_SC16P_MASK\fP)"

.SS "#define OSC_CR_SC16P_MASK   (0x1U)"

.SS "#define OSC_CR_SC16P_SHIFT   (0U)"

.SS "#define OSC_CR_SC2P(x)   (((uint8_t)(((uint8_t)(x)) << \fBOSC_CR_SC2P_SHIFT\fP)) & \fBOSC_CR_SC2P_MASK\fP)"

.SS "#define OSC_CR_SC2P_MASK   (0x8U)"

.SS "#define OSC_CR_SC2P_SHIFT   (3U)"

.SS "#define OSC_CR_SC4P(x)   (((uint8_t)(((uint8_t)(x)) << \fBOSC_CR_SC4P_SHIFT\fP)) & \fBOSC_CR_SC4P_MASK\fP)"

.SS "#define OSC_CR_SC4P_MASK   (0x4U)"

.SS "#define OSC_CR_SC4P_SHIFT   (2U)"

.SS "#define OSC_CR_SC8P(x)   (((uint8_t)(((uint8_t)(x)) << \fBOSC_CR_SC8P_SHIFT\fP)) & \fBOSC_CR_SC8P_MASK\fP)"

.SS "#define OSC_CR_SC8P_MASK   (0x2U)"

.SS "#define OSC_CR_SC8P_SHIFT   (1U)"

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
