.TH "PDB_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PDB_Type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MK64F12\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSC\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMOD\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBCNT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBIDLY\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBC1\fP"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBS\fP"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBDLY\fP [2]"
.br
.ti -1c
.RI "   uint8_t \fBRESERVED_0\fP [24]"
.br
.ti -1c
.RI "} \fBCH\fP [2]"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBINTC\fP"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBINT\fP"
.br
.ti -1c
.RI "} \fBDAC\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_1\fP [48]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPOEN\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPODLY\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
PDB - Register Layout Typedef 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
