.TH "drivers/PDRV_SysTick.c" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drivers/PDRV_SysTick.c \- SysTick driver\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'PDRV_SysTick\&.h'\fP
.br
\fC#include 'MK64F12\&.h'\fP
.br
\fC#include 'hardware\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFCLK\fP   \fB__CORE_CLOCK__\fP"
.br
.ti -1c
.RI "#define \fBCSR_MASK\fP   0x00010007"
.br
.ti -1c
.RI "#define \fBENABLE_MASK\fP   0x01"
.br
.ti -1c
.RI "#define \fBTICKINT_MASK\fP   0x02"
.br
.ti -1c
.RI "#define \fBCLKSOURCE_MASK\fP   0x04"
.br
.ti -1c
.RI "#define \fBCOUNTFLAG_MASK\fP   0x10000"
.br
.ti -1c
.RI "#define \fBRELOAD_VALUE\fP   (\fBFCLK\fP/\fBSYSTICK_ISR_FREQUENCY_HZ\fP \- 1)"
.br
.ti -1c
.RI "#define \fBRVR_MASK\fP   0x00FFFFFF"
.br
.ti -1c
.RI "#define \fBCLEAR_VALUE\fP   0x0"
.br
.ti -1c
.RI "#define \fBCVR_MASK\fP   0x00FFFFFF"
.br
.ti -1c
.RI "#define \fBCALIB_MASK\fP   0xC0FFFFFF"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBSysTick_Init\fP (void(*funcallback)(void))"
.br
.RI "Initialize SysTic driver\&. "
.ti -1c
.RI "\fB__ISR__\fP \fBSysTick_Handler\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
SysTick driver\&. 


.PP
\fBAuthor:\fP
.RS 4
Grupo 1 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define CALIB_MASK   0xC0FFFFFF"

.SS "#define CLEAR_VALUE   0x0"

.SS "#define CLKSOURCE_MASK   0x04"

.SS "#define COUNTFLAG_MASK   0x10000"

.SS "#define CSR_MASK   0x00010007"

.SS "#define CVR_MASK   0x00FFFFFF"

.SS "#define ENABLE_MASK   0x01"

.SS "#define FCLK   \fB__CORE_CLOCK__\fP"

.SS "#define RELOAD_VALUE   (\fBFCLK\fP/\fBSYSTICK_ISR_FREQUENCY_HZ\fP \- 1)"

.SS "#define RVR_MASK   0x00FFFFFF"

.SS "#define TICKINT_MASK   0x02"

.SH "Function Documentation"
.PP 
.SS "\fBWEAK_AV\fP void SysTick_Handler (void)"

.SS "bool SysTick_Init (void(*)(void) funcallback)"

.PP
Initialize SysTic driver\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfuncallback\fP Function to be call every SysTick 
.RE
.PP
\fBReturns:\fP
.RS 4
Initialization and registration succeed 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
