.TH "drivers/PDRV_SysTick.h" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drivers/PDRV_SysTick.h \- SysTick driver\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdbool\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSYSTICK_ISR_FREQUENCY_HZ\fP   1000U"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBSysTick_Init\fP (void(*funcallback)(void))"
.br
.RI "Initialize SysTic driver\&. "
.in -1c
.SH "Detailed Description"
.PP 
SysTick driver\&. 


.PP
\fBAuthor:\fP
.RS 4
Grupo 1 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define SYSTICK_ISR_FREQUENCY_HZ   1000U"

.SH "Function Documentation"
.PP 
.SS "bool SysTick_Init (void(*)(void) funcallback)"

.PP
Initialize SysTic driver\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfuncallback\fP Function to be call every SysTick 
.RE
.PP
\fBReturns:\fP
.RS 4
Initialization and registration succeed 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
