.TH "PIT_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PIT_Type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MK64F12\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMCR\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_0\fP [252]"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBLDVAL\fP"
.br
.ti -1c
.RI "   \fB__I\fP uint32_t \fBCVAL\fP"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBTCTRL\fP"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBTFLG\fP"
.br
.ti -1c
.RI "} \fBCHANNEL\fP [4]"
.br
.in -1c
.SH "Detailed Description"
.PP 
PIT - Register Layout Typedef 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
