.TH "PMC_Register_Masks" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PMC_Register_Masks
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPMC_BASE\fP   (0x4007D000u)"
.br
.ti -1c
.RI "#define \fBPMC\fP   ((\fBPMC_Type\fP *)\fBPMC_BASE\fP)"
.br
.ti -1c
.RI "#define \fBPMC_BASE_ADDRS\fP   { \fBPMC_BASE\fP }"
.br
.ti -1c
.RI "#define \fBPMC_BASE_PTRS\fP   { \fBPMC\fP }"
.br
.ti -1c
.RI "#define \fBPMC_IRQS\fP   { \fBLVD_LVW_IRQn\fP }"
.br
.in -1c
.SS "LVDSC1 - Low Voltage Detect Status And Control 1 register"

.in +1c
.ti -1c
.RI "#define \fBPMC_LVDSC1_LVDV_MASK\fP   (0x3U)"
.br
.ti -1c
.RI "#define \fBPMC_LVDSC1_LVDV_SHIFT\fP   (0U)"
.br
.ti -1c
.RI "#define \fBPMC_LVDSC1_LVDV\fP(x)   (((uint8_t)(((uint8_t)(x)) << \fBPMC_LVDSC1_LVDV_SHIFT\fP)) & \fBPMC_LVDSC1_LVDV_MASK\fP)"
.br
.ti -1c
.RI "#define \fBPMC_LVDSC1_LVDRE_MASK\fP   (0x10U)"
.br
.ti -1c
.RI "#define \fBPMC_LVDSC1_LVDRE_SHIFT\fP   (4U)"
.br
.ti -1c
.RI "#define \fBPMC_LVDSC1_LVDRE\fP(x)   (((uint8_t)(((uint8_t)(x)) << \fBPMC_LVDSC1_LVDRE_SHIFT\fP)) & \fBPMC_LVDSC1_LVDRE_MASK\fP)"
.br
.ti -1c
.RI "#define \fBPMC_LVDSC1_LVDIE_MASK\fP   (0x20U)"
.br
.ti -1c
.RI "#define \fBPMC_LVDSC1_LVDIE_SHIFT\fP   (5U)"
.br
.ti -1c
.RI "#define \fBPMC_LVDSC1_LVDIE\fP(x)   (((uint8_t)(((uint8_t)(x)) << \fBPMC_LVDSC1_LVDIE_SHIFT\fP)) & \fBPMC_LVDSC1_LVDIE_MASK\fP)"
.br
.ti -1c
.RI "#define \fBPMC_LVDSC1_LVDACK_MASK\fP   (0x40U)"
.br
.ti -1c
.RI "#define \fBPMC_LVDSC1_LVDACK_SHIFT\fP   (6U)"
.br
.ti -1c
.RI "#define \fBPMC_LVDSC1_LVDACK\fP(x)   (((uint8_t)(((uint8_t)(x)) << \fBPMC_LVDSC1_LVDACK_SHIFT\fP)) & \fBPMC_LVDSC1_LVDACK_MASK\fP)"
.br
.ti -1c
.RI "#define \fBPMC_LVDSC1_LVDF_MASK\fP   (0x80U)"
.br
.ti -1c
.RI "#define \fBPMC_LVDSC1_LVDF_SHIFT\fP   (7U)"
.br
.ti -1c
.RI "#define \fBPMC_LVDSC1_LVDF\fP(x)   (((uint8_t)(((uint8_t)(x)) << \fBPMC_LVDSC1_LVDF_SHIFT\fP)) & \fBPMC_LVDSC1_LVDF_MASK\fP)"
.br
.in -1c
.SS "LVDSC2 - Low Voltage Detect Status And Control 2 register"

.in +1c
.ti -1c
.RI "#define \fBPMC_LVDSC2_LVWV_MASK\fP   (0x3U)"
.br
.ti -1c
.RI "#define \fBPMC_LVDSC2_LVWV_SHIFT\fP   (0U)"
.br
.ti -1c
.RI "#define \fBPMC_LVDSC2_LVWV\fP(x)   (((uint8_t)(((uint8_t)(x)) << \fBPMC_LVDSC2_LVWV_SHIFT\fP)) & \fBPMC_LVDSC2_LVWV_MASK\fP)"
.br
.ti -1c
.RI "#define \fBPMC_LVDSC2_LVWIE_MASK\fP   (0x20U)"
.br
.ti -1c
.RI "#define \fBPMC_LVDSC2_LVWIE_SHIFT\fP   (5U)"
.br
.ti -1c
.RI "#define \fBPMC_LVDSC2_LVWIE\fP(x)   (((uint8_t)(((uint8_t)(x)) << \fBPMC_LVDSC2_LVWIE_SHIFT\fP)) & \fBPMC_LVDSC2_LVWIE_MASK\fP)"
.br
.ti -1c
.RI "#define \fBPMC_LVDSC2_LVWACK_MASK\fP   (0x40U)"
.br
.ti -1c
.RI "#define \fBPMC_LVDSC2_LVWACK_SHIFT\fP   (6U)"
.br
.ti -1c
.RI "#define \fBPMC_LVDSC2_LVWACK\fP(x)   (((uint8_t)(((uint8_t)(x)) << \fBPMC_LVDSC2_LVWACK_SHIFT\fP)) & \fBPMC_LVDSC2_LVWACK_MASK\fP)"
.br
.ti -1c
.RI "#define \fBPMC_LVDSC2_LVWF_MASK\fP   (0x80U)"
.br
.ti -1c
.RI "#define \fBPMC_LVDSC2_LVWF_SHIFT\fP   (7U)"
.br
.ti -1c
.RI "#define \fBPMC_LVDSC2_LVWF\fP(x)   (((uint8_t)(((uint8_t)(x)) << \fBPMC_LVDSC2_LVWF_SHIFT\fP)) & \fBPMC_LVDSC2_LVWF_MASK\fP)"
.br
.in -1c
.SS "REGSC - Regulator Status And Control register"

.in +1c
.ti -1c
.RI "#define \fBPMC_REGSC_BGBE_MASK\fP   (0x1U)"
.br
.ti -1c
.RI "#define \fBPMC_REGSC_BGBE_SHIFT\fP   (0U)"
.br
.ti -1c
.RI "#define \fBPMC_REGSC_BGBE\fP(x)   (((uint8_t)(((uint8_t)(x)) << \fBPMC_REGSC_BGBE_SHIFT\fP)) & \fBPMC_REGSC_BGBE_MASK\fP)"
.br
.ti -1c
.RI "#define \fBPMC_REGSC_REGONS_MASK\fP   (0x4U)"
.br
.ti -1c
.RI "#define \fBPMC_REGSC_REGONS_SHIFT\fP   (2U)"
.br
.ti -1c
.RI "#define \fBPMC_REGSC_REGONS\fP(x)   (((uint8_t)(((uint8_t)(x)) << \fBPMC_REGSC_REGONS_SHIFT\fP)) & \fBPMC_REGSC_REGONS_MASK\fP)"
.br
.ti -1c
.RI "#define \fBPMC_REGSC_ACKISO_MASK\fP   (0x8U)"
.br
.ti -1c
.RI "#define \fBPMC_REGSC_ACKISO_SHIFT\fP   (3U)"
.br
.ti -1c
.RI "#define \fBPMC_REGSC_ACKISO\fP(x)   (((uint8_t)(((uint8_t)(x)) << \fBPMC_REGSC_ACKISO_SHIFT\fP)) & \fBPMC_REGSC_ACKISO_MASK\fP)"
.br
.ti -1c
.RI "#define \fBPMC_REGSC_BGEN_MASK\fP   (0x10U)"
.br
.ti -1c
.RI "#define \fBPMC_REGSC_BGEN_SHIFT\fP   (4U)"
.br
.ti -1c
.RI "#define \fBPMC_REGSC_BGEN\fP(x)   (((uint8_t)(((uint8_t)(x)) << \fBPMC_REGSC_BGEN_SHIFT\fP)) & \fBPMC_REGSC_BGEN_MASK\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define PMC   ((\fBPMC_Type\fP *)\fBPMC_BASE\fP)"
Peripheral PMC base pointer 
.SS "#define PMC_BASE   (0x4007D000u)"
Peripheral PMC base address 
.SS "#define PMC_BASE_ADDRS   { \fBPMC_BASE\fP }"
Array initializer of PMC peripheral base addresses 
.SS "#define PMC_BASE_PTRS   { \fBPMC\fP }"
Array initializer of PMC peripheral base pointers 
.SS "#define PMC_IRQS   { \fBLVD_LVW_IRQn\fP }"
Interrupt vectors for the PMC peripheral type 
.SS "#define PMC_LVDSC1_LVDACK(x)   (((uint8_t)(((uint8_t)(x)) << \fBPMC_LVDSC1_LVDACK_SHIFT\fP)) & \fBPMC_LVDSC1_LVDACK_MASK\fP)"

.SS "#define PMC_LVDSC1_LVDACK_MASK   (0x40U)"

.SS "#define PMC_LVDSC1_LVDACK_SHIFT   (6U)"

.SS "#define PMC_LVDSC1_LVDF(x)   (((uint8_t)(((uint8_t)(x)) << \fBPMC_LVDSC1_LVDF_SHIFT\fP)) & \fBPMC_LVDSC1_LVDF_MASK\fP)"

.SS "#define PMC_LVDSC1_LVDF_MASK   (0x80U)"

.SS "#define PMC_LVDSC1_LVDF_SHIFT   (7U)"

.SS "#define PMC_LVDSC1_LVDIE(x)   (((uint8_t)(((uint8_t)(x)) << \fBPMC_LVDSC1_LVDIE_SHIFT\fP)) & \fBPMC_LVDSC1_LVDIE_MASK\fP)"

.SS "#define PMC_LVDSC1_LVDIE_MASK   (0x20U)"

.SS "#define PMC_LVDSC1_LVDIE_SHIFT   (5U)"

.SS "#define PMC_LVDSC1_LVDRE(x)   (((uint8_t)(((uint8_t)(x)) << \fBPMC_LVDSC1_LVDRE_SHIFT\fP)) & \fBPMC_LVDSC1_LVDRE_MASK\fP)"

.SS "#define PMC_LVDSC1_LVDRE_MASK   (0x10U)"

.SS "#define PMC_LVDSC1_LVDRE_SHIFT   (4U)"

.SS "#define PMC_LVDSC1_LVDV(x)   (((uint8_t)(((uint8_t)(x)) << \fBPMC_LVDSC1_LVDV_SHIFT\fP)) & \fBPMC_LVDSC1_LVDV_MASK\fP)"

.SS "#define PMC_LVDSC1_LVDV_MASK   (0x3U)"

.SS "#define PMC_LVDSC1_LVDV_SHIFT   (0U)"

.SS "#define PMC_LVDSC2_LVWACK(x)   (((uint8_t)(((uint8_t)(x)) << \fBPMC_LVDSC2_LVWACK_SHIFT\fP)) & \fBPMC_LVDSC2_LVWACK_MASK\fP)"

.SS "#define PMC_LVDSC2_LVWACK_MASK   (0x40U)"

.SS "#define PMC_LVDSC2_LVWACK_SHIFT   (6U)"

.SS "#define PMC_LVDSC2_LVWF(x)   (((uint8_t)(((uint8_t)(x)) << \fBPMC_LVDSC2_LVWF_SHIFT\fP)) & \fBPMC_LVDSC2_LVWF_MASK\fP)"

.SS "#define PMC_LVDSC2_LVWF_MASK   (0x80U)"

.SS "#define PMC_LVDSC2_LVWF_SHIFT   (7U)"

.SS "#define PMC_LVDSC2_LVWIE(x)   (((uint8_t)(((uint8_t)(x)) << \fBPMC_LVDSC2_LVWIE_SHIFT\fP)) & \fBPMC_LVDSC2_LVWIE_MASK\fP)"

.SS "#define PMC_LVDSC2_LVWIE_MASK   (0x20U)"

.SS "#define PMC_LVDSC2_LVWIE_SHIFT   (5U)"

.SS "#define PMC_LVDSC2_LVWV(x)   (((uint8_t)(((uint8_t)(x)) << \fBPMC_LVDSC2_LVWV_SHIFT\fP)) & \fBPMC_LVDSC2_LVWV_MASK\fP)"

.SS "#define PMC_LVDSC2_LVWV_MASK   (0x3U)"

.SS "#define PMC_LVDSC2_LVWV_SHIFT   (0U)"

.SS "#define PMC_REGSC_ACKISO(x)   (((uint8_t)(((uint8_t)(x)) << \fBPMC_REGSC_ACKISO_SHIFT\fP)) & \fBPMC_REGSC_ACKISO_MASK\fP)"

.SS "#define PMC_REGSC_ACKISO_MASK   (0x8U)"

.SS "#define PMC_REGSC_ACKISO_SHIFT   (3U)"

.SS "#define PMC_REGSC_BGBE(x)   (((uint8_t)(((uint8_t)(x)) << \fBPMC_REGSC_BGBE_SHIFT\fP)) & \fBPMC_REGSC_BGBE_MASK\fP)"

.SS "#define PMC_REGSC_BGBE_MASK   (0x1U)"

.SS "#define PMC_REGSC_BGBE_SHIFT   (0U)"

.SS "#define PMC_REGSC_BGEN(x)   (((uint8_t)(((uint8_t)(x)) << \fBPMC_REGSC_BGEN_SHIFT\fP)) & \fBPMC_REGSC_BGEN_MASK\fP)"

.SS "#define PMC_REGSC_BGEN_MASK   (0x10U)"

.SS "#define PMC_REGSC_BGEN_SHIFT   (4U)"

.SS "#define PMC_REGSC_REGONS(x)   (((uint8_t)(((uint8_t)(x)) << \fBPMC_REGSC_REGONS_SHIFT\fP)) & \fBPMC_REGSC_REGONS_MASK\fP)"

.SS "#define PMC_REGSC_REGONS_MASK   (0x4U)"

.SS "#define PMC_REGSC_REGONS_SHIFT   (2U)"

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
