.TH "RCM_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCM_Type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MK64F12\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__I\fP uint8_t \fBSRS0\fP"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBSRS1\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_0\fP [2]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBRPFC\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBRPFW\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_1\fP [1]"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBMR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
RCM - Register Layout Typedef 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
