.TH "RTC_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTC_Type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MK64F12\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTPR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTAR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBLR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBIER\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_0\fP [2016]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBWAR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRAR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
RTC - Register Layout Typedef 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
