.TH "SCnSCB_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SCnSCB_Type \- Structure type to access the System Control and ID Register not in the SCB\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <core_armv8mml\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBRESERVED0\fP [1U]"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBICTR\fP"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBACTLR\fP"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBCPPWR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure type to access the System Control and ID Register not in the SCB\&. 
.SH "Field Documentation"
.PP 
.SS "\fB__IOM\fP uint32_t ACTLR"
Offset: 0x008 (R/W) Auxiliary Control Register 
.SS "\fB__IOM\fP uint32_t CPPWR"
Offset: 0x00C (R/W) Coprocessor Power Control Register 
.SS "\fB__IM\fP uint32_t ICTR"
Offset: 0x004 (R/ ) Interrupt Controller Type Register 
.SS "uint32_t RESERVED0"


.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
