.TH "SDHC_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDHC_Type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MK64F12\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDSADDR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBLKATTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCMDARG\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBXFERTYP\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBCMDRSP\fP [4]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDATPORT\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBPRSSTAT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPROCTL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSYSCTL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBIRQSTAT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBIRQSTATEN\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBIRQSIGEN\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBAC12ERR\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBHTCAPBLT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBWML\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_0\fP [8]"
.br
.ti -1c
.RI "\fB__O\fP uint32_t \fBFEVT\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBADMAES\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBADSADDR\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_1\fP [100]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBVENDOR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMMCBOOT\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_2\fP [52]"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBHOSTVER\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
SDHC - Register Layout Typedef 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
