.TH "SDK/startup/semihost_hardfault.c" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDK/startup/semihost_hardfault.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__attribute__\fP ((naked))"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "__attribute__ ((naked))"

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
