.TH "SIM_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SIM_Type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MK64F12\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSOPT1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSOPT1CFG\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_0\fP [4092]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSOPT2\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_1\fP [4]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSOPT4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSOPT5\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_2\fP [4]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSOPT7\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_3\fP [8]"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBSDID\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSCGC1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSCGC2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSCGC3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSCGC4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSCGC5\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSCGC6\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSCGC7\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCLKDIV1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCLKDIV2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFCFG1\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBFCFG2\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBUIDH\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBUIDMH\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBUIDML\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBUIDL\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
SIM - Register Layout Typedef 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
