.TH "SMC_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SMC_Type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MK64F12\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint8_t \fBPMPROT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBPMCTRL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBVLLSCTRL\fP"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBPMSTAT\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
SMC - Register Layout Typedef 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
