.TH "TPI_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TPI_Type \- Structure type to access the Trace Port Interface Register (TPI)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <core_armv8mbl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBSSPSR\fP"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBCSPSR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED0\fP [2U]"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBACPR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED1\fP [55U]"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBSPPR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED2\fP [131U]"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBFFSR\fP"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBFFCR\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBFSCR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED3\fP [759U]"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBTRIGGER\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBFIFO0\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBITATBCTR2\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED4\fP [1U]"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBITATBCTR0\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBFIFO1\fP"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBITCTRL\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED5\fP [39U]"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBCLAIMSET\fP"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBCLAIMCLR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED7\fP [8U]"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBDEVID\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBDEVTYPE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure type to access the Trace Port Interface Register (TPI)\&. 
.SH "Field Documentation"
.PP 
.SS "\fB__IOM\fP uint32_t ACPR"
Offset: 0x010 (R/W) Asynchronous Clock Prescaler Register 
.SS "\fB__IOM\fP uint32_t CLAIMCLR"
Offset: 0xFA4 (R/W) Claim tag clear 
.SS "\fB__IOM\fP uint32_t CLAIMSET"
Offset: 0xFA0 (R/W) Claim tag set 
.SS "\fB__IOM\fP uint32_t CSPSR"
Offset: 0x004 (R/W) Current Parallel Port Size Register 
.SS "\fB__IM\fP uint32_t DEVID"
Offset: 0xFC8 (R/ ) TPIU_DEVID 
.SS "\fB__IM\fP uint32_t DEVTYPE"
Offset: 0xFCC (R/ ) TPIU_DEVTYPE 
.SS "\fB__IOM\fP uint32_t FFCR"
Offset: 0x304 (R/W) Formatter and Flush Control Register 
.SS "\fB__IM\fP uint32_t FFSR"
Offset: 0x300 (R/ ) Formatter and Flush Status Register 
.SS "\fB__IM\fP uint32_t FIFO0"
Offset: 0xEEC (R/ ) Integration ETM Data 
.SS "\fB__IM\fP uint32_t FIFO1"
Offset: 0xEFC (R/ ) Integration ITM Data 
.SS "\fB__IM\fP uint32_t FSCR"
Offset: 0x308 (R/ ) Formatter Synchronization Counter Register 
.SS "\fB__IM\fP uint32_t ITATBCTR0"
Offset: 0xEF8 (R/ ) ITATBCTR0 
.SS "\fB__IM\fP uint32_t ITATBCTR2"
Offset: 0xEF0 (R/ ) ITATBCTR2 
.SS "\fB__IOM\fP uint32_t ITCTRL"
Offset: 0xF00 (R/W) Integration Mode Control 
.SS "uint32_t RESERVED0"

.SS "uint32_t RESERVED1"

.SS "uint32_t RESERVED2"

.SS "uint32_t RESERVED3"

.SS "uint32_t RESERVED4"

.SS "uint32_t RESERVED5"

.SS "uint32_t RESERVED7"

.SS "\fB__IOM\fP uint32_t SPPR"
Offset: 0x0F0 (R/W) Selected Pin Protocol Register 
.SS "\fB__IOM\fP uint32_t SSPSR"
Offset: 0x000 (R/ ) Supported Parallel Port Size Register 
.SS "\fB__IM\fP uint32_t TRIGGER"
Offset: 0xEE8 (R/ ) TRIGGER 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
