.TH "UART_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_Type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MK64F12\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint8_t \fBBDH\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBBDL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBC1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBC2\fP"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBS1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBS2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBC3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBD\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBMA1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBMA2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBC4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBC5\fP"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBED\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBMODEM\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBIR\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_0\fP [1]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBPFIFO\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBCFIFO\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBSFIFO\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBTWFIFO\fP"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBTCFIFO\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBRWFIFO\fP"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBRCFIFO\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_1\fP [1]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBC7816\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBIE7816\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBIS7816\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBWP7816T0\fP"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBWP7816T1\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBWN7816\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBWF7816\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBET7816\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBTL7816\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
UART - Register Layout Typedef 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
