.TH "USB_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USB_Type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MK64F12\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__I\fP uint8_t \fBPERID\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_0\fP [3]"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBIDCOMP\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_1\fP [3]"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBREV\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_2\fP [3]"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBADDINFO\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_3\fP [3]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBOTGISTAT\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_4\fP [3]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBOTGICR\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_5\fP [3]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBOTGSTAT\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_6\fP [3]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBOTGCTL\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_7\fP [99]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBISTAT\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_8\fP [3]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBINTEN\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_9\fP [3]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBERRSTAT\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_10\fP [3]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBERREN\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_11\fP [3]"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBSTAT\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_12\fP [3]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBCTL\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_13\fP [3]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBADDR\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_14\fP [3]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBBDTPAGE1\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_15\fP [3]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBFRMNUML\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_16\fP [3]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBFRMNUMH\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_17\fP [3]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBTOKEN\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_18\fP [3]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBSOFTHLD\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_19\fP [3]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBBDTPAGE2\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_20\fP [3]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBBDTPAGE3\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_21\fP [11]"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBENDPT\fP"
.br
.ti -1c
.RI "   uint8_t \fBRESERVED_0\fP [3]"
.br
.ti -1c
.RI "} \fBENDPOINT\fP [16]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBUSBCTRL\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_22\fP [3]"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBOBSERVE\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_23\fP [3]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBCONTROL\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_24\fP [3]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBUSBTRC0\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_25\fP [7]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBUSBFRMADJUST\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_26\fP [43]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBCLK_RECOVER_CTRL\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_27\fP [3]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBCLK_RECOVER_IRC_EN\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED_28\fP [23]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBCLK_RECOVER_INT_STATUS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
USB - Register Layout Typedef 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
