.TH "Users" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Users
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AccountManager\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBID\fP"
.br
.ti -1c
.RI "uint32_t \fBPIN\fP"
.br
.ti -1c
.RI "bool \fBadmin\fP"
.br
.ti -1c
.RI "uint8_t \fBerror_counter\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "bool admin"

.SS "uint8_t error_counter"

.SS "uint32_t ID"

.SS "uint32_t PIN"


.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
