.TH "WDOG_Type" 3 "Mon Sep 13 2021" "TP2_G1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WDOG_Type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MK64F12\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint16_t \fBSTCTRLH\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBSTCTRLL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBTOVALH\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBTOVALL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBWINH\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBWINL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBREFRESH\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBUNLOCK\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBTMROUTH\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBTMROUTL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBRSTCNT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBPRESC\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
WDOG - Register Layout Typedef 

.SH "Author"
.PP 
Generated automatically by Doxygen for TP2_G1 from the source code\&.
